"""Nomes de eventos do domínio expostos para compatibilidade do frontend."""

INSURANCE_UPDATED = "INSURANCE_UPDATED"
LAB_RESULT_READY = "LAB_RESULT_READY"
PAYMENT_RECEIVED = "PAYMENT_RECEIVED"

__all__ = ["INSURANCE_UPDATED", "LAB_RESULT_READY", "PAYMENT_RECEIVED"]
