# Generated by Django 5.2.12 on 2026-03-28 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        ("school", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="competency",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="school.grade",
                verbose_name="Classe",
            ),
        ),
        migrations.AddField(
            model_name="competency",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="basecurriculum",
            name="competencies",
            field=models.ManyToManyField(
                to="curriculum.competency", verbose_name="Competências"
            ),
        ),
        migrations.AddField(
            model_name="competencyoutcome",
            name="competency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculum.competency",
                verbose_name="Competência",
            ),
        ),
        migrations.AddField(
            model_name="competencyoutcome",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="curriculumarea",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="learningoutcome",
            name="competencies",
            field=models.ManyToManyField(
                related_name="learning_outcomes",
                through="curriculum.CompetencyOutcome",
                to="curriculum.competency",
                verbose_name="Competências",
            ),
        ),
        migrations.AddField(
            model_name="learningoutcome",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="school.grade",
                verbose_name="Classe",
            ),
        ),
        migrations.AddField(
            model_name="learningoutcome",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="competencyoutcome",
            name="outcome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculum.learningoutcome",
                verbose_name="Resultado de aprendizagem",
            ),
        ),
        migrations.AddField(
            model_name="localcurriculum",
            name="additional_competencies",
            field=models.ManyToManyField(
                blank=True,
                to="curriculum.competency",
                verbose_name="Competências adicionais",
            ),
        ),
        migrations.AddField(
            model_name="localcurriculum",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculum.curriculumarea",
                verbose_name="Área",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="learningoutcome",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculum.subject",
                verbose_name="Disciplina",
            ),
        ),
        migrations.AddField(
            model_name="competency",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculum.subject",
                verbose_name="Disciplina",
            ),
        ),
        migrations.AddField(
            model_name="subjectcurriculumplan",
            name="grade_subject",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curriculum_plan",
                to="school.gradesubject",
                verbose_name="Disciplina da classe",
            ),
        ),
        migrations.AddField(
            model_name="subjectcurriculumplan",
            name="planned_competencies",
            field=models.ManyToManyField(
                blank=True,
                related_name="curriculum_plans",
                to="curriculum.competency",
                verbose_name="Competências previstas",
            ),
        ),
        migrations.AddField(
            model_name="subjectcurriculumplan",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="subjectspecialty",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialties",
                to="curriculum.subject",
                verbose_name="Disciplina",
            ),
        ),
        migrations.AddField(
            model_name="subjectspecialty",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumarea",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name",),
                name="unique_curriculumarea_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="competencyoutcome",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant_id", "competency", "outcome"),
                name="unique_competency_outcome_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningoutcome",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant_id", "code", "subject", "grade"),
                name="unique_learning_outcome_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectspecialty",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("subject", "name"),
                name="unique_subject_specialty_active",
            ),
        ),
    ]
