# Generated by Django 5.2.12 on 2026-03-28 04:22

import django.db.models.deletion
from django.db import migrations, models


def forwards_populate_competency_area(apps, schema_editor):
    Competency = apps.get_model("curriculum", "Competency")
    Subject = apps.get_model("curriculum", "Subject")
    CurriculumArea = apps.get_model("curriculum", "CurriculumArea")

    legacy_key_map = {
        "linguagem_comunicacao": "language_communication",
        "saber_cientifico_tecnologico": "scientific_technological_knowledge",
        "raciocinio_resolucao_problemas": "reasoning_problem_solving",
        "desenvolvimento_pessoal_autonomia": "personal_development_autonomy",
        "relacionamento_interpessoal": "interpersonal_relationship",
        "bem_estar_saude_ambiente": "wellbeing_health_environment",
        "sensibilidade_estetica_artistica": "aesthetic_artistic_sensitivity",
    }

    label_map = {
        "language_communication": "Linguagem e comunicação",
        "scientific_technological_knowledge": "Saber científico e tecnológico",
        "reasoning_problem_solving": "Raciocínio e resolução de problemas",
        "personal_development_autonomy": "Desenvolvimento pessoal e autonomia",
        "interpersonal_relationship": "Relacionamento interpessoal",
        "wellbeing_health_environment": "Bem-estar, saúde e ambiente",
        "aesthetic_artistic_sensitivity": "Sensibilidade estética e artística",
    }

    subject_area_cache = {}

    for competency in Competency.objects.all().iterator():
        tenant_id = (getattr(competency, "tenant_id", "") or "").strip()

        area_obj = None
        subject_id = getattr(competency, "subject_id", None)
        if subject_id:
            area_obj = subject_area_cache.get(subject_id)
            if area_obj is None:
                subject = Subject.objects.select_related("area").filter(pk=subject_id).first()
                area_obj = getattr(subject, "area", None)
                subject_area_cache[subject_id] = area_obj

        if area_obj is None:
            legacy_value = (getattr(competency, "area", "") or "").strip()
            if not legacy_value:
                continue
            normalized_key = legacy_key_map.get(legacy_value, legacy_value)
            area_name = label_map.get(normalized_key, legacy_value)
            area_obj, _ = CurriculumArea.objects.get_or_create(
                tenant_id=tenant_id,
                name=area_name,
            )

        competency.area_model_id = getattr(area_obj, "pk", None)
        competency.save(update_fields=["area_model"])


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0003_alter_basecurriculum_usuario_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="curriculumarea",
            name="unique_curriculumarea_name",
        ),
        migrations.AddField(
            model_name="competency",
            name="area_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="curriculum.curriculumarea",
                verbose_name="Área",
            ),
        ),
        migrations.RunPython(forwards_populate_competency_area, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="competency",
            name="area",
        ),
        migrations.RenameField(
            model_name="competency",
            old_name="area_model",
            new_name="area",
        ),
        migrations.AddConstraint(
            model_name="curriculumarea",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant_id", "name"),
                name="unique_curriculumarea_name_per_tenant",
            ),
        ),
    ]

