# Generated by Django 6.0.1 on 2026-03-05 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farmacia", "0001_initial"),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="itemvenda",
            name="atualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemvenda",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemvenda",
            name="deletado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deletado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemvenda",
            name="inquilino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.inquilino",
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="atualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="deletado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deletado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="inquilino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.inquilino",
            ),
        ),
        migrations.AddField(
            model_name="movimentoestoque",
            name="atualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movimentoestoque",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movimentoestoque",
            name="deletado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deletado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movimentoestoque",
            name="inquilino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.inquilino",
            ),
        ),
        migrations.AddField(
            model_name="movimentoestoque",
            name="lote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimentos",
                to="farmacia.lote",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="atualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="deletado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deletado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="inquilino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.inquilino",
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lotes",
                to="farmacia.produto",
            ),
        ),
        migrations.AddField(
            model_name="itemvenda",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="farmacia.produto"
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="atualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="deletado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deletado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="inquilino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.inquilino",
            ),
        ),
        migrations.AddField(
            model_name="itemvenda",
            name="venda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="farmacia.venda",
            ),
        ),
        migrations.AddIndex(
            model_name="movimentoestoque",
            index=models.Index(
                fields=["lote", "criado_em"], name="farmacia_mo_lote_id_6838f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(fields=["tipo"], name="farmacia_pr_tipo_209e5c_idx"),
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(
                fields=["inquilino"], name="farmacia_pr_inquili_17f82a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="produto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deletado", False)),
                fields=("inquilino", "id_custom"),
                name="unique_codigo_produto_por_inquilino",
            ),
        ),
        migrations.AddIndex(
            model_name="lote",
            index=models.Index(
                fields=["produto", "validade"], name="farmacia_lo_produto_27c6df_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deletado", False)),
                fields=("produto", "numero_lote"),
                name="unique_lote_produto",
            ),
        ),
        migrations.AddIndex(
            model_name="venda",
            index=models.Index(
                fields=["criado_em"], name="farmacia_ve_criado__e11138_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venda",
            index=models.Index(
                fields=["deletado"], name="farmacia_ve_deletad_e71957_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venda",
            index=models.Index(fields=["numero"], name="farmacia_ve_numero_d32d24_idx"),
        ),
        migrations.AddIndex(
            model_name="venda",
            index=models.Index(
                fields=["inquilino", "criado_em"], name="farmacia_ve_inquili_68bcc5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="venda",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deletado", False)),
                fields=("inquilino", "numero"),
                name="unique_numero_venda_por_inquilino",
            ),
        ),
        migrations.AddIndex(
            model_name="itemvenda",
            index=models.Index(fields=["venda"], name="farmacia_it_venda_i_b24902_idx"),
        ),
        migrations.AddIndex(
            model_name="itemvenda",
            index=models.Index(
                fields=["produto"], name="farmacia_it_produto_d21906_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemvenda",
            index=models.Index(
                fields=["venda", "produto"], name="farmacia_it_venda_i_695ec2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemvenda",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deletado", False)),
                fields=("venda", "produto"),
                name="unique_produto_por_venda",
            ),
        ),
    ]
