# Generated by Django 4.2.16 on 2026-03-15 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinico', '0002_initial'),
        ('inquilinos', '0001_initial'),
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venda',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venda',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venda',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='venda',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_farmacia', to='clinico.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='produto',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='farmacia.categoriaproduto', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produto',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produto',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='item_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='farmacia.itemvenda'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='farmacia.lote'),
        ),
        migrations.AddField(
            model_name='lote',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lote',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lote',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lote',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='lote',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='farmacia.produto'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.produto'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='farmacia.venda'),
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='categoria_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='farmacia.categoriaproduto'),
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['inquilino', 'numero'], name='farmacia_ve_inquili_085d53_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['inquilino', 'paciente'], name='farmacia_ve_inquili_ec7db1_idx'),
        ),
        migrations.AddConstraint(
            model_name='venda',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False)), fields=('inquilino', 'numero'), name='unique_numero_venda_por_inquilino'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['inquilino', 'nome'], name='farmacia_pr_inquili_6d03c4_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria'], name='farmacia_pr_categor_ee4970_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['tipo'], name='farmacia_pr_tipo_209e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['lote', 'criado_em'], name='farmacia_mo_lote_id_6838f4_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['tipo'], name='farmacia_mo_tipo_bfdde8_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['origem'], name='farmacia_mo_origem_9d52b9_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['produto', 'validade'], name='farmacia_lo_produto_27c6df_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['validade'], name='farmacia_lo_validad_262eac_idx'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False)), fields=('produto', 'numero_lote'), name='unique_lote_produto'),
        ),
        migrations.AddIndex(
            model_name='itemvenda',
            index=models.Index(fields=['venda'], name='farmacia_it_venda_i_b24902_idx'),
        ),
        migrations.AddIndex(
            model_name='itemvenda',
            index=models.Index(fields=['produto'], name='farmacia_it_produto_d21906_idx'),
        ),
        migrations.AddIndex(
            model_name='itemvenda',
            index=models.Index(fields=['venda', 'produto'], name='farmacia_it_venda_i_695ec2_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemvenda',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False)), fields=('venda', 'produto'), name='unique_produto_por_venda'),
        ),
        migrations.AddIndex(
            model_name='categoriaproduto',
            index=models.Index(fields=['inquilino', 'nome'], name='farmacia_ca_inquili_c8f550_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriaproduto',
            index=models.Index(fields=['categoria_pai'], name='farmacia_ca_categor_64e38f_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoriaproduto',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False)), fields=('inquilino', 'nome'), name='unique_categoria_produto_por_inquilino'),
        ),
    ]
