# Generated by Django 6.0.1 on 2026-03-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemvenda",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="lote",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="movimentoestoque",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
    ]
