# Generated by Django 4.2.16 on 2026-03-14 21:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0007_exame_iva_percentual_examemedico_iva_percentual_and_more'),
        ('farmacia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='iva_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Taxa de IVA aplicada ao produto (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_farmacia', to='clinico.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='farmacia.categoriaproduto', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço de venda'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('MED', 'Medicamento'), ('MAT', 'Material'), ('OUT', 'Outro')], db_index=True, default='OUT', max_length=3, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='numero',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['inquilino', 'paciente'], name='farmacia_ve_inquili_ec7db1_idx'),
        ),
    ]
