# Generated by Django 4.2.16 on 2026-03-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='aplica_iva_por_padrao',
            field=models.BooleanField(default=True, help_text='Desmarque se este produto normalmente não deve ter IVA.', verbose_name='Aplicar IVA por padrão'),
        ),
    ]
