# Generated by Django 6.0.1 on 2026-03-10 10:16

from django.conf import settings
from django.db import migrations, models


def preencher_origem_venda(apps, schema_editor):
    MovimentoEstoque = apps.get_model("farmacia", "MovimentoEstoque")
    MovimentoEstoque.objects.filter(item_venda__isnull=False).update(origem="VEND")


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_initial'),
        ('inquilinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoestoque',
            name='origem',
            field=models.CharField(choices=[('VEND', 'Venda'), ('PROC', 'Procedimento'), ('AJUS', 'Ajuste')], db_index=True, default='AJUS', max_length=4),
        ),
        migrations.RunPython(preencher_origem_venda, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['origem'], name='farmacia_mo_origem_9d52b9_idx'),
        ),
    ]
