# Generated by Django 4.2.13 on 2026-03-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identidade', '0001_initial'),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='perfilprofissional',
            index=models.Index(fields=['usuario'], name='identidade__usuario_bba900_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilprofissional',
            index=models.Index(fields=['ativo'], name='identidade__ativo_6ecc2c_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'criado_em'], name='identidade__user_id_f784de_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['usado'], name='identidade__usado_f7c8a6_idx'),
        ),
    ]
