# Generated by Django 4.2.16 on 2026-03-14 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def vincular_funcionario_do_usuario_no_perfil(apps, schema_editor):
    """
    Migra o vínculo antigo Funcionario.usuario -> PerfilProfissional.funcionario.

    - Antes: recursos_humanos.Funcionario tinha OneToOne 'usuario'
    - Agora: identidade.PerfilProfissional tem OneToOne opcional 'funcionario'
    """
    PerfilProfissional = apps.get_model("identidade", "PerfilProfissional")
    Funcionario = apps.get_model("recursos_humanos", "Funcionario")

    for func in Funcionario.objects.exclude(usuario_id__isnull=True).only("id", "usuario_id"):
        try:
            perfil = PerfilProfissional.objects.filter(usuario_id=func.usuario_id).first()
        except Exception:
            perfil = None

        if not perfil:
            continue

        if getattr(perfil, "funcionario_id", None):
            continue

        try:
            perfil.funcionario_id = func.id
            perfil.save(update_fields=["funcionario"])
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_cargo_eh_medico'),
        ('identidade', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofissional',
            name='funcionario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_profissional_rh', to='recursos_humanos.funcionario', verbose_name='Funcionário (RH)'),
        ),
        migrations.RunPython(vincular_funcionario_do_usuario_no_perfil, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='perfilprofissional',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='perfilprofissional',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='perfilprofissional',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='perfilprofissional',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='perfilprofissional',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='perfilprofissional',
            name='registro_profissional',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Registro profissional'),
        ),
        migrations.AlterField(
            model_name='perfilprofissional',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profissional', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='perfilprofissional',
            index=models.Index(fields=['funcionario'], name='identidade__funcion_71e18c_idx'),
        ),
    ]
