# Generated by Django 4.2.29 on 2026-06-16 22:12

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

from configuration.utils.django_compat import check_constraint


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0020_seed_sample_rejection_reasons'),
        ('faturamento', '0007_invoice_verification_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0004_tenantconfiguration_fiscal_address_and_more'),
        ('entidades', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('quotation_number', models.CharField(blank=True, db_index=True, default='', help_text='Sequência por tenant/ano (COT-AAAA-NNNNNN); atribuída ao enviar.', max_length=30, verbose_name='Número da cotação')),
                ('fiscal_client_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Cliente (nome)')),
                ('fiscal_client_nuit', models.CharField(blank=True, default='', max_length=30, verbose_name='Cliente (NUIT)')),
                ('fiscal_client_address', models.TextField(blank=True, default='', verbose_name='Cliente (morada)')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SENT', 'Enviada'), ('ACCEPTED', 'Aceite'), ('REJECTED', 'Rejeitada'), ('EXPIRED', 'Expirada'), ('CONVERTED', 'Convertida'), ('CANCELLED', 'Cancelada')], db_index=True, default='DRAFT', max_length=12, verbose_name='Estado')),
                ('issue_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de emissão')),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de validade')),
                ('currency', models.CharField(default='MZN', max_length=3, verbose_name='Moeda')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxa de câmbio')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total de descontos')),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total de impostos')),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total geral')),
                ('deposit_type', models.CharField(choices=[('NONE', 'Sem sinal'), ('PERCENTAGE', 'Percentagem'), ('FIXED', 'Valor fixo')], default='NONE', max_length=12, verbose_name='Tipo de sinal')),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Sinal (%)')),
                ('deposit_fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Valor de sinal pretendido quando o tipo é 'Valor fixo'.", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sinal (valor fixo definido)')),
                ('deposit_required', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor do sinal')),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo previsto')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('terms_and_conditions', models.TextField(blank=True, default='', verbose_name='Termos e condições')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada em')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceite em')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejeitada em')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Convertida em')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Motivo da rejeição')),
                ('converted_invoice', models.ForeignKey(blank=True, db_column='converted_invoice_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotations', to='faturamento.invoice', verbose_name='Fatura gerada')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('fiscal_client', models.ForeignKey(blank=True, db_column='fiscal_client_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='entidades.company', verbose_name='Cliente (entidade)')),
                ('patient', models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='clinical.patient', verbose_name='Paciente')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotação',
                'verbose_name_plural': 'Cotações',
                'db_table': 'cotacoes_cotacao',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('item_type', models.CharField(choices=[('SERVICE', 'Serviço'), ('PRODUCT', 'Produto'), ('OTHER', 'Outro')], db_index=True, default='SERVICE', max_length=12, verbose_name='Tipo de item')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço unitário')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Desconto (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor do desconto')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Imposto (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor do imposto')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total da linha')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(db_column='quotation_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotacoes.quotation', verbose_name='Cotação')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de Cotação',
                'verbose_name_plural': 'Itens de Cotação',
                'db_table': 'cotacoes_item',
                'ordering': ['quotation', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('from_status', models.CharField(blank=True, default='', max_length=12, verbose_name='De')),
                ('to_status', models.CharField(blank=True, default='', max_length=12, verbose_name='Para')),
                ('event_type', models.CharField(db_index=True, max_length=40, verbose_name='Evento')),
                ('actor_name', models.CharField(blank=True, default='', max_length=160, verbose_name='Autor')),
                ('summary', models.CharField(blank=True, default='', max_length=255, verbose_name='Resumo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('event_at', models.DateTimeField(db_index=True, verbose_name='Ocorrido em')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(db_column='quotation_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cotacoes.quotation', verbose_name='Cotação')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Cotação',
                'verbose_name_plural': 'Históricos de Cotação',
                'db_table': 'cotacoes_historico_estado',
                'ordering': ['-event_at', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'quotation', 'event_at'], name='cotacoes_hi_tenant__40b8de_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['tenant', 'status'], name='cotacoes_co_tenant__89806e_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['tenant', 'fiscal_client', 'status'], name='cotacoes_co_tenant__3fbcd6_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['tenant', 'expiry_date'], name='cotacoes_co_tenant__075ca7_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), models.Q(('quotation_number', ''), _negated=True)), fields=('tenant', 'quotation_number'), name='unique_quotation_number_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=check_constraint(condition=models.Q(('deposit_percentage__gte', 0), ('deposit_percentage__lte', 100)), name='cotacao_deposit_percentage_0_100'),
        ),
    ]
