"""Facade module for surgery viewsets."""

from .viewsets_impl import (
    VIEWSET_MAP,
    AnesthesiaRecordViewSet,
    BaseSurgeryViewSet,
    LargeSurgeryViewSet,
    OperatingRoomViewSet,
    OperativeReportViewSet,
    PreoperativeAssessmentViewSet,
    RecoveryRecordViewSet,
    SmallSurgeryViewSet,
    SurgeryOperationsViewSet,
    SurgeryProcedureItemViewSet,
    SurgeryViewSet,
    SurgicalAuditEventViewSet,
    SurgicalAuthorizationViewSet,
    SurgicalBillingItemViewSet,
    SurgicalConsumptionViewSet,
    SurgicalDocumentViewSet,
    SurgicalMaterialViewSet,
    SurgicalProcedureViewSet,
    SurgicalRequestViewSet,
    SurgicalSafetyChecklistViewSet,
    SurgicalScheduleViewSet,
    SurgicalSpecimenViewSet,
    SurgicalTeamMemberViewSet,
)

__all__ = [
    "VIEWSET_MAP",
    "AnesthesiaRecordViewSet",
    "BaseSurgeryViewSet",
    "LargeSurgeryViewSet",
    "OperatingRoomViewSet",
    "OperativeReportViewSet",
    "PreoperativeAssessmentViewSet",
    "RecoveryRecordViewSet",
    "SmallSurgeryViewSet",
    "SurgeryOperationsViewSet",
    "SurgeryProcedureItemViewSet",
    "SurgeryViewSet",
    "SurgicalAuditEventViewSet",
    "SurgicalAuthorizationViewSet",
    "SurgicalBillingItemViewSet",
    "SurgicalConsumptionViewSet",
    "SurgicalDocumentViewSet",
    "SurgicalMaterialViewSet",
    "SurgicalProcedureViewSet",
    "SurgicalRequestViewSet",
    "SurgicalSafetyChecklistViewSet",
    "SurgicalScheduleViewSet",
    "SurgicalSpecimenViewSet",
    "SurgicalTeamMemberViewSet",
]
