# Generated by Django 4.2.16 on 2026-03-28 04:22

from decimal import Decimal

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacia', '0002_initial'),
        ('recursos_humanos', '0001_initial'),
        ('consultas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical', '0002_initial'),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('care_start_at', models.DateTimeField(db_column='care_start_at', db_index=True, default=django.utils.timezone.now, verbose_name='Início do atendimento')),
                ('care_end_at', models.DateTimeField(blank=True, db_column='care_end_at', db_index=True, null=True, verbose_name='Fim do atendimento')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], db_column='status', db_index=True, default='RASCUNHO', max_length=20, verbose_name='Estado')),
                ('symptoms', models.TextField(blank=True, db_column='symptoms', default='', verbose_name='Sintomas')),
                ('diagnosis', models.TextField(blank=True, db_column='diagnosis', default='', verbose_name='Diagnóstico')),
                ('prescription', models.TextField(blank=True, db_column='prescription', default='', help_text='Texto livre opcional. A prescrição estruturada fica nos itens de prescrição.', verbose_name='Observações da prescrição')),
                ('medical_report', models.TextField(blank=True, db_column='medical_report', default='', verbose_name='Relatório médico')),
                ('consultations', models.ManyToManyField(blank=True, db_table='prontuario_registroprontuario_consultas', related_name='cardex_registros', to='consultas.medicalconsultation', verbose_name='Consultas')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, db_column='doctor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_prontuario', to='recursos_humanos.employee', verbose_name='Médico')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, related_name='registros_prontuario', to='clinical.patient', verbose_name='Paciente')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cardex',
                'verbose_name_plural': 'Cardex',
                'db_table': 'prontuario_registroprontuario',
                'ordering': ['-care_start_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('dosage_value', models.DecimalField(db_column='dosage_value', decimal_places=2, default=Decimal('0.00'), help_text='Quantidade da dose (ex.: 500).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Dosagem')),
                ('dosage_unit', models.CharField(choices=[('MG', 'mg'), ('ML', 'ml'), ('G', 'g'), ('L', 'L'), ('KG', 'kg')], db_column='dosage_unit', db_index=True, default='MG', max_length=3, verbose_name='Unidade da dosagem')),
                ('interval_hours', models.PositiveSmallIntegerField(blank=True, db_column='interval_hours', help_text='Intervalo entre doses. Obrigatório quando houver mais de uma dose.', null=True, verbose_name='Intervalo (hours)')),
                ('dose_count', models.PositiveSmallIntegerField(db_column='dose_count', default=1, help_text='Quantidade total de doses. Para dose única, informe 1.', verbose_name='Número de doses')),
                ('notes', models.TextField(blank=True, db_column='notes', default='', verbose_name='Observações')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(db_column='medication_id', on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes_prontuario', to='farmacia.product', verbose_name='Medicação')),
                ('record', models.ForeignKey(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, related_name='itens_prescription', to='prontuario.medicalrecordentry', verbose_name='Cardex')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de Prescrição',
                'verbose_name_plural': 'Itens de Prescrição',
                'db_table': 'prontuario_prescricaoitem',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'record'], name='prontuario__tenant__ad7b32_idx'), models.Index(fields=['tenant', 'medication'], name='prontuario__tenant__a200b3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='medicalrecordentry',
            index=models.Index(fields=['tenant', 'patient', 'care_start_at'], name='prontuario__tenant__5d5205_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecordentry',
            index=models.Index(fields=['tenant', 'doctor', 'care_start_at'], name='prontuario__tenant__4af6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecordentry',
            index=models.Index(fields=['tenant', 'status', 'care_start_at'], name='prontuario__tenant__593b43_idx'),
        ),
    ]
