# Generated by Django 4.2.29 on 2026-04-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescriptionitem',
            options={'ordering': ['record', 'position', 'id'], 'verbose_name': 'Item de Prescrição', 'verbose_name_plural': 'Itens de Prescrição'},
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
