# Generated by Django 5.1 on 2026-03-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prontuario", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="medicalrecordentry",
            new_name="prontuario__tenant__5d5205_idx",
            old_name="prontuario__inquili_cf84a0_idx",
        ),
        migrations.RenameIndex(
            model_name="medicalrecordentry",
            new_name="prontuario__tenant__4af6a4_idx",
            old_name="prontuario__inquili_54a657_idx",
        ),
        migrations.RenameIndex(
            model_name="medicalrecordentry",
            new_name="prontuario__tenant__593b43_idx",
            old_name="prontuario__inquili_ed10e1_idx",
        ),
        migrations.RenameIndex(
            model_name="prescriptionitem",
            new_name="prontuario__tenant__ad7b32_idx",
            old_name="prontuario__inquili_3c46f7_idx",
        ),
        migrations.RenameIndex(
            model_name="prescriptionitem",
            new_name="prontuario__tenant__a200b3_idx",
            old_name="prontuario__inquili_8f8671_idx",
        ),
    ]
