# Generated by Django 5.1 on 2026-03-26 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinical", "0004_clinicalhistory_clinicalevent"),
        ("farmacia", "0002_initial"),
        (
            "inquilinos",
            "0002_rename_inquilinos__tipo_856ce4_idx_inquilinos__type_fdb81e_idx_and_more",
        ),
        ("prontuario", "0001_initial"),
        ("recursos_humanos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecordentry",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                db_column="doctor_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registros_prontuario",
                to="recursos_humanos.employee",
                verbose_name="Médico",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecordentry",
            name="patient",
            field=models.ForeignKey(
                db_column="patient_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registros_prontuario",
                to="clinical.patient",
                verbose_name="Paciente",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecordentry",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.tenant",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecordentry",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="created_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                db_column="deleted_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="medication",
            field=models.ForeignKey(
                db_column="medication_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prescricoes_prontuario",
                to="farmacia.product",
                verbose_name="Medicação",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="record",
            field=models.ForeignKey(
                db_column="record_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens_prescription",
                to="prontuario.medicalrecordentry",
                verbose_name="Cardex",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.tenant",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecordentry",
            index=models.Index(
                fields=["tenant", "patient", "care_start_at"],
                name="prontuario__tenant__5d5205_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecordentry",
            index=models.Index(
                fields=["tenant", "doctor", "care_start_at"],
                name="prontuario__tenant__4af6a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecordentry",
            index=models.Index(
                fields=["tenant", "status", "care_start_at"],
                name="prontuario__tenant__593b43_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prescriptionitem",
            index=models.Index(
                fields=["tenant", "record"], name="prontuario__tenant__ad7b32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescriptionitem",
            index=models.Index(
                fields=["tenant", "medication"], name="prontuario__tenant__a200b3_idx"
            ),
        ),
    ]
