# Generated by Django 4.2.29 on 2026-05-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='interval_hours',
            field=models.PositiveSmallIntegerField(blank=True, db_column='interval_hours', help_text='Intervalo entre doses. Obrigatório quando houver mais de uma dose.', null=True, verbose_name='Intervalo (horas)'),
        ),
    ]
