# Generated by Django 5.1 on 2026-03-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "method",
                    models.CharField(
                        db_column="metodo",
                        db_index=True,
                        max_length=10,
                        verbose_name="Método HTTP",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        db_column="caminho",
                        db_index=True,
                        max_length=255,
                        verbose_name="Rota curta",
                    ),
                ),
                (
                    "full_path",
                    models.TextField(
                        blank=True,
                        db_column="path_completo",
                        default="",
                        verbose_name="URL completa",
                    ),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Status HTTP"
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        db_column="duracao_ms",
                        null=True,
                        verbose_name="Duração (ms)",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP de origin"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="User-Agent",
                    ),
                ),
                (
                    "view_basename",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=120,
                        verbose_name="View",
                    ),
                ),
                (
                    "view_action",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=120,
                        verbose_name="Ação da view",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        db_column="objeto_id",
                        db_index=True,
                        default="",
                        max_length=80,
                        verbose_name="Objeto (ID)",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        db_column="mensagem",
                        default="",
                        max_length=255,
                        verbose_name="Mensagem",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadados"
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividade do Utilizador",
                "verbose_name_plural": "Actividades do Utilizador",
                "db_table": "auditoria_atividades_atividadeusuario",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
