# Generated by Django 5.1 on 2026-03-25 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auditoria_atividades", "0001_initial"),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="criado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                db_column="deletado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="tenant",
            field=models.ForeignKey(
                db_column="inquilino_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.tenant",
            ),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="atualizado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="usuario_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="auditoria_atividades",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilizador",
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["tenant", "created_at"], name="auditoria_a_inquili_efc74c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["tenant", "user", "created_at"],
                name="auditoria_a_inquili_0aaacc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["tenant", "status_code"], name="auditoria_a_inquili_2a1772_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["tenant", "view_basename", "created_at"],
                name="auditoria_a_inquili_dc3d1a_idx",
            ),
        ),
    ]
