# Generated by Django 4.2.29 on 2026-05-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria_atividades', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem'),
        ),
    ]
