# Generated by Django 5.1 on 2026-03-25 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria_atividades", "0002_initial"),
        (
            "inquilinos",
            "0002_rename_inquilinos__tipo_856ce4_idx_inquilinos__type_fdb81e_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="useractivity",
            new_name="auditoria_a_tenant__4bf27a_idx",
            old_name="auditoria_a_inquili_efc74c_idx",
        ),
        migrations.RenameIndex(
            model_name="useractivity",
            new_name="auditoria_a_tenant__ca28f9_idx",
            old_name="auditoria_a_inquili_0aaacc_idx",
        ),
        migrations.RenameIndex(
            model_name="useractivity",
            new_name="auditoria_a_tenant__919002_idx",
            old_name="auditoria_a_inquili_2a1772_idx",
        ),
        migrations.RenameIndex(
            model_name="useractivity",
            new_name="auditoria_a_tenant__79de9a_idx",
            old_name="auditoria_a_inquili_dc3d1a_idx",
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="created_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                db_column="deleted_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="auditoria_atividades",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilizador",
            ),
        ),
    ]
