"""Facade module for human resources viewsets."""

from .viewsets_impl import (
    VIEWSET_MAP,
    AbsenceViewSet,
    EmployeeViewSet,
    FamilyDependentViewSet,
    JobTitleViewSet,
    OvertimeViewSet,
    PayrollViewSet,
    TerminationViewSet,
    VacationViewSet,
    WorkScheduleViewSet,
    AgregadoFamiliarViewSet,
    CargoViewSet,
    DispensaViewSet,
    FaltaViewSet,
    FeriasViewSet,
    FolhaPagamentoViewSet,
    FuncionarioViewSet,
    HoraExtraViewSet,
    HorarioTrabalhoViewSet,
)

__all__ = [
    "VIEWSET_MAP",
    "AbsenceViewSet",
    "EmployeeViewSet",
    "FamilyDependentViewSet",
    "JobTitleViewSet",
    "OvertimeViewSet",
    "PayrollViewSet",
    "TerminationViewSet",
    "VacationViewSet",
    "WorkScheduleViewSet",
    "AgregadoFamiliarViewSet",
    "CargoViewSet",
    "DispensaViewSet",
    "FaltaViewSet",
    "FeriasViewSet",
    "FolhaPagamentoViewSet",
    "FuncionarioViewSet",
    "HoraExtraViewSet",
    "HorarioTrabalhoViewSet",
]
