# Generated by Django 6.0.1 on 2026-03-10 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinico', '0002_initial'),
        ('inquilinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEnfermagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], db_index=True, default='NORMAL', max_length=10)),
                ('observacao', models.TextField(blank=True, default='')),
                ('data_registro', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_enfermagem', to='clinico.paciente')),
            ],
            options={
                'ordering': ['-data_registro', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SinalVitalEnfermagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('frequencia_cardiaca', models.PositiveIntegerField(blank=True, null=True)),
                ('frequencia_respiratoria', models.PositiveIntegerField(blank=True, null=True)),
                ('saturacao_oxigenio', models.PositiveIntegerField(blank=True, null=True)),
                ('pressao_arterial', models.CharField(blank=True, default='', max_length=20)),
                ('coletado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinais_vitais', to='enfermagem.registroenfermagem')),
            ],
            options={
                'ordering': ['-coletado_em', '-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='registroenfermagem',
            index=models.Index(fields=['inquilino', 'paciente'], name='enfermagem__inquili_c884f6_idx'),
        ),
        migrations.AddIndex(
            model_name='registroenfermagem',
            index=models.Index(fields=['prioridade'], name='enfermagem__priorid_d5db32_idx'),
        ),
        migrations.AddIndex(
            model_name='registroenfermagem',
            index=models.Index(fields=['data_registro'], name='enfermagem__data_re_84b912_idx'),
        ),
        migrations.AddIndex(
            model_name='sinalvitalenfermagem',
            index=models.Index(fields=['inquilino', 'registro'], name='enfermagem__inquili_18fe2d_idx'),
        ),
        migrations.AddIndex(
            model_name='sinalvitalenfermagem',
            index=models.Index(fields=['coletado_em'], name='enfermagem__coletad_4dade6_idx'),
        ),
    ]
