# Generated by Django 4.2.16 on 2026-03-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_initial'),
        ('enfermagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimentomaterial',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumos_procedimento', to='farmacia.lote'),
        ),
    ]
