# Generated by Django 6.0.1 on 2026-03-10 09:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0002_initial'),
        ('enfermagem', '0001_initial'),
        ('inquilinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('data_realizacao', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimentos_enfermagem', to='clinico.paciente')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimentos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
                'ordering': ['-data_realizacao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('descricao', models.CharField(db_index=True, max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('realizado', models.BooleanField(db_index=True, default=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='enfermagem.procedimento')),
            ],
            options={
                'verbose_name': 'Item de Procedimento',
                'verbose_name_plural': 'Itens de Procedimento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='procedimento',
            index=models.Index(fields=['inquilino', 'paciente'], name='enfermagem__inquili_1c9e86_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimento',
            index=models.Index(fields=['data_realizacao'], name='enfermagem__data_re_8b4dac_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimentoitem',
            index=models.Index(fields=['inquilino', 'procedimento'], name='enfermagem__inquili_db8a55_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimentoitem',
            index=models.Index(fields=['descricao'], name='enfermagem__descric_73baec_idx'),
        ),
    ]
