# Generated by Django 4.2.16 on 2026-03-14 21:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0002_alter_procedimentomaterial_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentocatalogo',
            name='iva_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Taxa de IVA aplicada ao procedimento (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)'),
        ),
        migrations.AlterField(
            model_name='procedimentocatalogo',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
    ]
