# Generated by Django 4.2.16 on 2026-03-17 11:47

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinico', '0006_exame_aplica_iva_por_padrao_and_more'),
        ('enfermagem', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentocatalogo',
            name='aplica_iva_por_padrao',
            field=models.BooleanField(default=True, help_text='Desmarque se este procedimento normalmente não deve ter IVA.', verbose_name='Aplicar IVA por padrão'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='data_realizacao',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data de realização'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimentos_enfermagem', to='clinico.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimentos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Profissional'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='subtotal_materiais',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal (materiais)'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='subtotal_servicos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal (serviços)'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total'),
        ),
    ]
