# Generated by Django 6.0.1 on 2026-03-10 10:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0003_procedimento_subtotal_materiais_and_more'),
        ('farmacia', '0003_movimentoestoque_origem_and_more'),
        ('inquilinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('descricao', models.TextField(blank=True, default='')),
                ('preco_padrao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Procedimento de Catálogo',
                'verbose_name_plural': 'Procedimentos de Catálogo',
                'ordering': ['nome', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoCatalogoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('quantidade_padrao', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('custo_unitario_padrao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observacao', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Material Padrão do Procedimento',
                'verbose_name_plural': 'Materiais Padrão do Procedimento',
                'ordering': ['catalogo', 'produto'],
            },
        ),
        migrations.AddField(
            model_name='procedimentomaterial',
            name='procedimento_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_gerados', to='enfermagem.procedimentoitem'),
        ),
        migrations.AlterField(
            model_name='procedimentoitem',
            name='descricao',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='procedimentomaterial',
            index=models.Index(fields=['procedimento_item'], name='enfermagem__procedi_fd692c_idx'),
        ),
        migrations.AddField(
            model_name='procedimentocatalogo',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentocatalogo',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentocatalogo',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentocatalogo',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='procedimentoitem',
            name='catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_lancados', to='enfermagem.procedimentocatalogo'),
        ),
        migrations.AddIndex(
            model_name='procedimentoitem',
            index=models.Index(fields=['catalogo'], name='enfermagem__catalog_4e19ce_idx'),
        ),
        migrations.AddField(
            model_name='procedimentocatalogomaterial',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentocatalogomaterial',
            name='catalogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_padrao', to='enfermagem.procedimentocatalogo'),
        ),
        migrations.AddField(
            model_name='procedimentocatalogomaterial',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentocatalogomaterial',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentocatalogomaterial',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='procedimentocatalogomaterial',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiais_padrao_procedimento', to='farmacia.produto'),
        ),
        migrations.AddIndex(
            model_name='procedimentocatalogo',
            index=models.Index(fields=['inquilino', 'nome'], name='enfermagem__inquili_b5e9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimentocatalogomaterial',
            index=models.Index(fields=['inquilino', 'catalogo'], name='enfermagem__inquili_b7c041_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimentocatalogomaterial',
            index=models.Index(fields=['produto'], name='enfermagem__produto_0ff2db_idx'),
        ),
        migrations.AddConstraint(
            model_name='procedimentocatalogomaterial',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False)), fields=('catalogo', 'produto'), name='unique_produto_por_catalogo_procedimento'),
        ),
    ]
