# Generated by Django 4.2.29 on 2026-03-18 19:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('origem', models.CharField(choices=[('CLI', 'Clínico'), ('FAR', 'Farmácia'), ('ENF', 'Enfermagem'), ('CON', 'Consulta'), ('CIR', 'Cirurgia')], db_index=True, default='CLI', max_length=3, verbose_name='Origem')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total sem IVA')),
                ('iva_valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total com IVA')),
                ('valor_seguro', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do seguro')),
                ('valor_paciente', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do paciente')),
                ('estado', models.CharField(choices=[('RASC', 'Rascunho'), ('EMIT', 'Emitida'), ('PAGA', 'Paga'), ('CANC', 'Cancelada')], db_index=True, default='RASC', max_length=5, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FaturaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('tipo_item', models.CharField(choices=[('EXA', 'Exame'), ('EXM', 'Exame médico'), ('FAR', 'Item de farmácia'), ('PRC', 'Serviço de enfermagem'), ('MAT', 'Material de enfermagem'), ('AJU', 'Ajuste manual')], db_index=True, default='EXA', max_length=3, verbose_name='Tipo de item')),
                ('descricao', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Preço unitário')),
                ('aplica_iva', models.BooleanField(default=True, help_text='Desmarque para não aplicar IVA neste item.', verbose_name='Aplicar IVA?')),
                ('iva_percentual', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Deixe em branco para herdar do item (exame/produto/procedimento).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)')),
            ],
            options={
                'verbose_name': 'Item de Fatura',
                'verbose_name_plural': 'Itens de Fatura',
            },
        ),
        migrations.CreateModel(
            name='HistoricoFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('tipo_evento', models.CharField(db_index=True, max_length=40, verbose_name='Tipo de evento')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Histórico de Fatura',
                'verbose_name_plural': 'Históricos de Fatura',
                'ordering': ['-criado_em'],
            },
        ),
    ]
