# Generated by Django 5.1 on 2026-03-26 04:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "name",
                    models.CharField(db_column="name", db_index=True, max_length=120),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_column="event_type",
                        db_index=True,
                        max_length=40,
                        verbose_name="Tipo de evento",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_column="description",
                        default="",
                        verbose_name="Descrição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Fatura",
                "verbose_name_plural": "Históricos de Fatura",
                "db_table": "faturamento_historicofatura",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("EXA", "Exame"),
                            ("EXM", "Exame médico"),
                            ("FAR", "Item de farmácia"),
                            ("PRC", "Serviço de enfermagem"),
                            ("MAT", "Material de enfermagem"),
                            ("AJU", "Ajuste manual"),
                        ],
                        db_column="item_type",
                        db_index=True,
                        default="EXA",
                        max_length=3,
                        verbose_name="Tipo de item",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_column="description",
                        default="",
                        max_length=255,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        db_column="quantity",
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        db_column="unit_price",
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Preço unitário",
                    ),
                ),
                (
                    "applies_vat",
                    models.BooleanField(
                        db_column="applies_vat",
                        default=True,
                        help_text="Desmarque para não aplicar IVA neste item.",
                        verbose_name="Aplicar IVA?",
                    ),
                ),
                (
                    "vat_percentage",
                    models.DecimalField(
                        blank=True,
                        db_column="vat_percentage",
                        decimal_places=2,
                        default=None,
                        help_text="Deixe em branco para herdar do item (exam/product/procedure).",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="IVA (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Fatura",
                "verbose_name_plural": "Invoice Items",
                "db_table": "faturamento_faturaitem",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("CLI", "Clínico"),
                            ("FAR", "Farmácia"),
                            ("ENF", "Enfermagem"),
                            ("CON", "Consulta"),
                            ("CIR", "Cirurgia"),
                            ("MIX", "Mista"),
                        ],
                        db_column="origin",
                        db_index=True,
                        default="CLI",
                        max_length=3,
                        verbose_name="Origem",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total sem IVA",
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        db_column="vat_amount",
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total de IVA",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total com IVA",
                    ),
                ),
                (
                    "insurance_amount",
                    models.DecimalField(
                        db_column="insurance_amount",
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor do seguro",
                    ),
                ),
                (
                    "patient_amount",
                    models.DecimalField(
                        db_column="patient_amount",
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor do patient",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASC", "Rascunho"),
                            ("EMIT", "Emitida"),
                            ("PAGA", "Paga"),
                            ("CANC", "Cancelada"),
                        ],
                        db_column="status",
                        db_index=True,
                        default="RASC",
                        max_length=5,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "consultation",
                    models.OneToOneField(
                        blank=True,
                        db_column="consultation_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="consultas.medicalconsultation",
                        verbose_name="Consulta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura",
                "verbose_name_plural": "Faturas",
                "db_table": "faturamento_fatura",
                "ordering": ["-created_at"],
            },
        ),
    ]
