# Generated by Django 4.2.16 on 2026-03-26 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmacia', '0002_initial'),
        ('clinical', '0002_initial'),
        ('cirurgia', '0001_initial'),
        ('faturamento', '0001_initial'),
        ('inquilinos', '0001_initial'),
        ('enfermagem', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='exam',
            field=models.ForeignKey(blank=True, db_column='exam_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='clinical.labexam', verbose_name='Exame'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='faturamento.invoice', verbose_name='Fatura'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='medical_exam',
            field=models.ForeignKey(blank=True, db_column='medical_exam_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='clinical.medicalexam', verbose_name='Exame médico'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='procedure_item',
            field=models.ForeignKey(blank=True, db_column='procedure_item_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermagem.procedureitem', verbose_name='Item de procedure'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='procedure_material',
            field=models.ForeignKey(blank=True, db_column='procedure_material_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermagem.procedurematerial', verbose_name='Material de procedure'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='sale_item',
            field=models.ForeignKey(blank=True, db_column='sale_item_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='farmacia.saleitem', verbose_name='Item de sale'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='invoice',
            field=models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='faturamento.invoice', verbose_name='Fatura'),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='consultation',
            field=models.OneToOneField(blank=True, db_column='consultation_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='consultas.medicalconsultation', verbose_name='Consulta'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='procedure',
            field=models.OneToOneField(blank=True, db_column='procedure_id', help_text="Legado: prefira usar o campo 'procedures' (múltiplos).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='enfermagem.procedure', verbose_name='Procedimento (legado)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='procedures',
            field=models.ManyToManyField(blank=True, db_table='faturamento_fatura_procedimentos', help_text='Pode associar múltiplos procedures de enfermagem à mesma invoice.', related_name='invoices', to='enfermagem.procedure', verbose_name='Procedimentos (Enfermagem)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='request',
            field=models.OneToOneField(blank=True, db_column='request_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='clinical.labrequest', verbose_name='Requisição'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sale',
            field=models.OneToOneField(blank=True, db_column='sale_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='farmacia.sale', verbose_name='Venda'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='surgery',
            field=models.OneToOneField(blank=True, db_column='surgery_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='cirurgia.surgery', verbose_name='Cirurgia'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('exam__isnull', False)), fields=('invoice', 'exam'), name='unique_exam_por_invoice'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('medical_exam__isnull', False)), fields=('invoice', 'medical_exam'), name='unique_medical_exam_por_invoice'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('sale_item__isnull', False)), fields=('invoice', 'sale_item'), name='unique_sale_item_por_invoice'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('procedure_item__isnull', False)), fields=('invoice', 'procedure_item'), name='unique_proc_item_por_invoice'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('procedure_material__isnull', False)), fields=('invoice', 'procedure_material'), name='unique_proc_material_por_invoice'),
        ),
        migrations.AddIndex(
            model_name='invoicehistory',
            index=models.Index(fields=['invoice', 'created_at'], name='faturamento_invoice_6bfdd6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicehistory',
            index=models.Index(fields=['event_type'], name='faturamento_event_t_09c3f8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'origin', 'status', 'created_at'], name='faturamento_tenant__9c1601_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'patient', 'created_at'], name='faturamento_tenant__fb23c2_idx'),
        ),
    ]
