# Generated by Django 4.2.29 on 2026-04-20 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("faturamento", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="procedure",
            field=models.ForeignKey(
                blank=True,
                db_column="procedure_id",
                help_text="Legado: prefira usar o campo 'procedures' (múltiplos).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices_legacy",
                to="enfermagem.procedure",
                verbose_name="Procedimento (legado)",
            ),
        ),
    ]
