# Generated by Django 4.2.29 on 2026-05-25 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_alter_clinicalhistory_patient_and_more'),
        ('faturamento', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='request',
            field=models.OneToOneField(blank=True, db_column='request_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='clinical.labrequest', verbose_name='Requisição'),
        ),
    ]
