# Generated by Django 5.1 on 2026-03-27 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0004_alter_resultitem_clinical_status_and_more"),
        ("consultas", "0002_initial"),
        ("enfermagem", "0002_initial"),
        ("farmacia", "0006_lot_sale_price"),
        ("faturamento", "0002_initial"),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="consultation",
            field=models.ForeignKey(
                blank=True,
                db_column="consultation_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="consultas.medicalconsultation",
                verbose_name="Consulta médica",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("EXA", "Exame"),
                    ("EXM", "Exame médico"),
                    ("FAR", "Item de farmácia"),
                    ("PRC", "Serviço de enfermagem"),
                    ("MAT", "Material de enfermagem"),
                    ("CON", "Consulta médica"),
                    ("AJU", "Ajuste manual"),
                ],
                db_column="item_type",
                db_index=True,
                default="EXA",
                max_length=3,
                verbose_name="Tipo de item",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("consultation__isnull", False), ("deleted", False)),
                fields=("invoice", "consultation"),
                name="unique_consulta_por_invoice",
            ),
        ),
    ]
