# Generated by Django 5.1 on 2026-03-27 02:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0002_initial"),
        (
            "faturamento",
            "0003_invoiceitem_consultation_alter_invoiceitem_item_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="consultations",
            field=models.ManyToManyField(
                blank=True,
                db_table="faturamento_fatura_consultas",
                help_text="Associa várias consultas (ex.: clínica geral e especialidade) a esta fatura.",
                related_name="invoices",
                to="consultas.medicalconsultation",
                verbose_name="Consultas médicas",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="quantity",
            field=models.DecimalField(
                db_column="quantity",
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Informe a quantidade do itens. Para itens de venda, a quantidade será preenchida automaticamente a partir do item de venda selecionado.",
                max_digits=10,
                verbose_name="Quantidade",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit_price",
            field=models.DecimalField(
                db_column="unit_price",
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Informe o preço unitário do item. Para exames, o preço será preenchido automaticamente a partir do cadastro do exame, podendo ser ajustado para casos específicos.",
                max_digits=12,
                verbose_name="Preço unitário",
            ),
        ),
    ]
