# Generated by Django 4.2.29 on 2026-04-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0004_remove_unique_product_pharmacy_por_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['invoice', 'position', 'id'], 'verbose_name': 'Item de Fatura', 'verbose_name_plural': 'Invoice Items'},
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
