# Generated by Django 5.1 on 2026-03-27 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0004_alter_resultitem_clinical_status_and_more"),
        ("consultas", "0002_initial"),
        ("enfermagem", "0002_initial"),
        ("farmacia", "0006_lot_sale_price"),
        (
            "faturamento",
            "0004_invoice_consultations_alter_invoiceitem_quantity_and_more",
        ),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_column="product_id",
                help_text="Produto vendido (quando não há referência direta ao item da venda).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="farmacia.product",
                verbose_name="Produto",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                db_column="exam_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="clinical.labexam",
                verbose_name="Exame laboratorial",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                db_column="invoice_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="faturamento.invoice",
                verbose_name="Fatura relacionada",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("EXA", "Exame"),
                    ("EXM", "Exame médico"),
                    ("FAR", "Item de farmácia"),
                    ("PRC", "Serviço de enfermagem"),
                    ("MAT", "Material de enfermagem"),
                    ("CON", "Consulta médica"),
                    ("AJU", "Ajuste manual"),
                ],
                db_column="item_type",
                db_index=True,
                default="EXA",
                max_length=3,
                verbose_name="Tipo de item de fatura",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="procedure_item",
            field=models.ForeignKey(
                blank=True,
                db_column="procedure_item_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="enfermagem.procedureitem",
                verbose_name="Procedimento de enfermagem",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="procedure_material",
            field=models.ForeignKey(
                blank=True,
                db_column="procedure_material_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="enfermagem.procedurematerial",
                verbose_name="Material de procedimento de enfermagem",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="sale_item",
            field=models.ForeignKey(
                blank=True,
                db_column="sale_item_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="farmacia.saleitem",
                verbose_name="Item de venda",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted", False),
                    ("product__isnull", False),
                    ("sale_item__isnull", True),
                ),
                fields=("invoice", "product"),
                name="unique_product_pharmacy_por_invoice",
            ),
        ),
    ]
