# Generated by Django 4.2.29 on 2026-06-16 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_initial'),
        ('faturamento', '0005_creditnoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='fiscal_client',
            field=models.ForeignKey(blank=True, db_column='fiscal_client_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_as_fiscal_client', to='entidades.company', verbose_name='Cliente fiscal (entidade)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fiscal_client_address',
            field=models.TextField(blank=True, db_column='fiscal_client_address', default='', verbose_name='Cliente fiscal (morada)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fiscal_client_name',
            field=models.CharField(blank=True, db_column='fiscal_client_name', default='', max_length=200, verbose_name='Cliente fiscal (nome)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fiscal_client_nuit',
            field=models.CharField(blank=True, db_column='fiscal_client_nuit', default='', max_length=30, verbose_name='Cliente fiscal (NUIT)'),
        ),
    ]
