# Generated by Django 4.2.29 on 2026-06-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0006_invoice_fiscal_client_invoice_fiscal_client_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='verification_hash',
            field=models.CharField(blank=True, db_column='verification_hash', db_index=True, default='', max_length=64, verbose_name='Hash de verificação'),
        ),
    ]
