# Generated by Django 4.2.29 on 2026-06-16 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0002_proformainvoice_remove_quotation_converted_invoice_and_more'),
        ('faturamento', '0007_invoice_verification_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='source_proforma',
            field=models.ForeignKey(blank=True, db_column='source_proforma_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='cotacoes.proformainvoice', verbose_name='Proforma de origem'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_quotation',
            field=models.ForeignKey(blank=True, db_column='source_quotation_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='cotacoes.quotation', verbose_name='Cotação de origem'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='origin',
            field=models.CharField(choices=[('CLI', 'Clínico'), ('FAR', 'Farmácia'), ('ENF', 'Enfermagem'), ('CON', 'Consulta'), ('CIR', 'Cirurgia'), ('MIX', 'Mista'), ('PRO', 'Proforma')], db_column='origin', db_index=True, default='CLI', max_length=3, verbose_name='Origem'),
        ),
    ]
