# Generated by Django 4.2.29 on 2026-07-21 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0006_default_vat_5_percent'),
        ('faturamento', '0008_invoice_source_proforma_invoice_source_quotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnoterequest',
            name='sale_item',
            field=models.ForeignKey(blank=True, db_column='sale_item_id', help_text='Item específico da venda a estornar; nulo quando o pedido é sobre a fatura inteira.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_requests', to='farmacia.saleitem', verbose_name='Item de venda'),
        ),
    ]
