# Generated by Django 5.1 on 2026-03-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maternidade", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pregnancy",
            new_name="maternidade_tenant__d3eeb6_idx",
            old_name="maternidade_inquili_d42c57_idx",
        ),
        migrations.RenameIndex(
            model_name="pregnancy",
            new_name="maternidade_tenant__a6c665_idx",
            old_name="maternidade_inquili_78a2a3_idx",
        ),
    ]
