# Generated by Django 5.1 on 2026-03-26 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "inquilinos",
            "0002_rename_inquilinos__tipo_856ce4_idx_inquilinos__type_fdb81e_idx_and_more",
        ),
        ("maternidade", "0001_initial"),
        ("recursos_humanos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pregnancy",
            name="responsible_doctor",
            field=models.ForeignKey(
                blank=True,
                db_column="responsible_doctor_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gestacoes_responsible",
                to="recursos_humanos.employee",
                verbose_name="Médico/Ginecologista responsável",
            ),
        ),
        migrations.AddField(
            model_name="pregnancy",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.tenant",
            ),
        ),
        migrations.AddField(
            model_name="pregnancy",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="pregnancy",
            index=models.Index(
                fields=["tenant", "patient", "created_at"],
                name="maternidade_tenant__d3eeb6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pregnancy",
            index=models.Index(
                fields=["tenant", "status", "created_at"],
                name="maternidade_tenant__a6c665_idx",
            ),
        ),
    ]
