# Generated by Django 4.2.29 on 2026-05-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancy',
            name='maternity_bed',
            field=models.CharField(blank=True, db_column='maternity_bed', default='', help_text='Número/identificação da cama (quando aplicável).', max_length=40, verbose_name='Cama na maternidade'),
        ),
    ]
