# Generated by Django 5.2.12 on 2026-03-28 00:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Identificador do tenant",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Removido em"
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=60, verbose_name="Código"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("acs", "ACS"),
                            ("acp", "ACP"),
                            ("individual_work", "Trabalho individual"),
                            ("group_work", "Trabalho em grupo"),
                            ("test", "Teste"),
                            ("exam", "Exame"),
                            ("diagnostic", "Diagnóstica"),
                            ("formative", "Formativa"),
                            ("summative", "Sumativa"),
                            ("other", "Outra"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Nota",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comentário")),
                (
                    "knowledge",
                    models.BooleanField(default=False, verbose_name="Conhecimentos"),
                ),
                (
                    "skills",
                    models.BooleanField(default=False, verbose_name="Habilidades"),
                ),
                (
                    "attitudes",
                    models.BooleanField(default=False, verbose_name="Atitudes"),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Identificador do tenant",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Removido em"
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=60, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("acs", "ACS"),
                            ("acp", "ACP"),
                            ("individual_work", "Trabalho individual"),
                            ("group_work", "Trabalho em grupo"),
                            ("test", "Teste"),
                            ("exam", "Exame"),
                            ("diagnostic", "Diagnóstica"),
                            ("formative", "Formativa"),
                            ("summative", "Sumativa"),
                            ("other", "Outra"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Peso"
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name="Nota máxima",
                    ),
                ),
                (
                    "mandatory",
                    models.BooleanField(default=True, verbose_name="Obrigatória"),
                ),
            ],
            options={
                "verbose_name": "Componente avaliativa",
                "verbose_name_plural": "Componentes avaliativas",
                "ordering": [
                    "period__academic_year__code",
                    "period__order",
                    "grade_subject__subject__name",
                    "name",
                ],
            },
        ),
        migrations.CreateModel(
            name="AssessmentOutcomeMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Identificador do tenant",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Removido em"
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=60, verbose_name="Código"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, default=100, max_digits=5, verbose_name="Peso"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Mapeamento componente-resultado",
                "verbose_name_plural": "Mapeamentos componente-resultado",
                "ordering": ["component__name", "outcome__code"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Identificador do tenant",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Removido em"
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=60, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome")),
                ("order", models.PositiveSmallIntegerField(verbose_name="Ordem")),
                ("start_date", models.DateField(verbose_name="Data de início")),
                ("end_date", models.DateField(verbose_name="Data de fim")),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Período avaliativo",
                "verbose_name_plural": "Períodos avaliativos",
                "ordering": ["academic_year__code", "order"],
            },
        ),
        migrations.CreateModel(
            name="SubjectPeriodResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Identificador do tenant",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Removido em"
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=60, verbose_name="Código"),
                ),
                (
                    "final_average",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Média final",
                    ),
                ),
                (
                    "assessments_counted",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Avaliações consideradas"
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado por período e disciplina",
                "verbose_name_plural": "Resultados por período e disciplina",
                "ordering": [
                    "period__academic_year__code",
                    "period__order",
                    "student__name",
                ],
            },
        ),
    ]
