# Generated by Django 5.2.12 on 2026-03-28 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0002_initial"),
        ("assessment", "0001_initial"),
        ("curriculum", "0001_initial"),
        ("school", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="competency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="curriculum.competency",
                verbose_name="Competência",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.student",
                verbose_name="Aluno",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="teaching_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.teachingassignment",
                verbose_name="Alocação docente",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="assessmentcomponent",
            name="grade_subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="school.gradesubject",
                verbose_name="Disciplina da classe",
            ),
        ),
        migrations.AddField(
            model_name="assessmentcomponent",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assessment.assessmentcomponent",
                verbose_name="Componente",
            ),
        ),
        migrations.AddField(
            model_name="assessmentoutcomemap",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assessment.assessmentcomponent",
                verbose_name="Componente",
            ),
        ),
        migrations.AddField(
            model_name="assessmentoutcomemap",
            name="outcome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculum.learningoutcome",
                verbose_name="Resultado de aprendizagem",
            ),
        ),
        migrations.AddField(
            model_name="assessmentoutcomemap",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="assessmentperiod",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="school.academicyear",
                verbose_name="Ano letivo",
            ),
        ),
        migrations.AddField(
            model_name="assessmentperiod",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="assessmentcomponent",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assessment.assessmentperiod",
                verbose_name="Período",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assessment.assessmentperiod",
                verbose_name="Período",
            ),
        ),
        migrations.AddField(
            model_name="subjectperiodresult",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assessment.assessmentperiod",
                verbose_name="Período",
            ),
        ),
        migrations.AddField(
            model_name="subjectperiodresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.student",
                verbose_name="Aluno",
            ),
        ),
        migrations.AddField(
            model_name="subjectperiodresult",
            name="teaching_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="school.teachingassignment",
                verbose_name="Alocação docente",
            ),
        ),
        migrations.AddField(
            model_name="subjectperiodresult",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentoutcomemap",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant_id", "component", "outcome"),
                name="unique_assessment_outcome_map_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentperiod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("academic_year", "order"),
                name="unique_assessment_period_order_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentcomponent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("period", "grade_subject", "name"),
                name="unique_assessment_component_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectperiodresult",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("student", "teaching_assignment", "period"),
                name="unique_subject_period_result_active",
            ),
        ),
    ]
