# Generated by Django 5.2.12 on 2026-03-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0004_alter_assessment_tenant_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="type",
            field=models.CharField(
                choices=[
                    ("acs", "ACS"),
                    ("acp", "ACP"),
                    ("individual_work", "Trabalho individual"),
                    ("group_work", "Trabalho em grupo"),
                    ("test", "Teste"),
                    ("exam", "Exame"),
                    ("diagnostic", "Diagnóstica"),
                    ("formative", "Formativa"),
                    ("summative", "Summativa"),
                    ("other", "Outra"),
                ],
                max_length=30,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="assessmentcomponent",
            name="type",
            field=models.CharField(
                choices=[
                    ("acs", "ACS"),
                    ("acp", "ACP"),
                    ("individual_work", "Trabalho individual"),
                    ("group_work", "Trabalho em grupo"),
                    ("test", "Teste"),
                    ("exam", "Exame"),
                    ("diagnostic", "Diagnóstica"),
                    ("formative", "Formativa"),
                    ("summative", "Summativa"),
                    ("other", "Outra"),
                ],
                max_length=30,
                verbose_name="Tipo",
            ),
        ),
    ]
