# Generated by Django 5.1 on 2026-03-25 04:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinico", "0001_initial"),
        ("faturamento", "0001_initial"),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceptionCheckin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deleted_at", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="version", default=1)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("URG", "Urgente"),
                            ("PREF", "Preferencial"),
                            ("NOR", "Normal"),
                        ],
                        db_column="priority",
                        db_index=True,
                        default="NOR",
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGUARD", "Aguardando"),
                            ("ATEND", "Em atendimento"),
                            ("REQ", "Requisição criada"),
                            ("FAT", "Fatura vinculada"),
                            ("CONC", "Concluído"),
                            ("CANC", "Cancelado"),
                        ],
                        db_column="status",
                        db_index=True,
                        default="AGUARD",
                        max_length=6,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, db_column="reason", default="", max_length=255
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, db_column="notes", default=""),
                ),
                (
                    "arrived_at",
                    models.DateTimeField(
                        db_column="arrived_at",
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "called_at",
                    models.DateTimeField(blank=True, db_column="called_at", null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, db_column="completed_at", null=True
                    ),
                ),
                (
                    "attendant",
                    models.ForeignKey(
                        blank=True,
                        db_column="attendant_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkins_recepcao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        db_column="invoice_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkin",
                        to="faturamento.invoice",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkins",
                        to="clinico.patient",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        blank=True,
                        db_column="request_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkin",
                        to="clinico.labrequest",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Check-in",
                "verbose_name_plural": "Check-ins",
                "db_table": "recepcao_checkinrecepcao",
                "ordering": ["-arrived_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "arrived_at"],
                        name="recepcao_ch_inquili_282070_idx",
                    ),
                    models.Index(
                        fields=["tenant", "status"],
                        name="recepcao_ch_inquili_6ae330_idx",
                    ),
                    models.Index(
                        fields=["tenant", "priority"],
                        name="recepcao_ch_inquili_7540fe_idx",
                    ),
                ],
            },
        ),
    ]
