# Generated by Django 5.1 on 2026-03-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recepcao", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="receptioncheckin",
            new_name="recepcao_ch_tenant__fb7e71_idx",
            old_name="recepcao_ch_inquili_282070_idx",
        ),
        migrations.RenameIndex(
            model_name="receptioncheckin",
            new_name="recepcao_ch_tenant__9836f2_idx",
            old_name="recepcao_ch_inquili_6ae330_idx",
        ),
        migrations.RenameIndex(
            model_name="receptioncheckin",
            new_name="recepcao_ch_tenant__3882f2_idx",
            old_name="recepcao_ch_inquili_7540fe_idx",
        ),
    ]
