# Generated by Django 6.0.1 on 2026-02-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=255)),
                ('canal', models.CharField(max_length=50)),
                ('mensagem', models.TextField()),
                ('enviada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['canal'], name='notificacoe_canal_a5c8e0_idx'), models.Index(fields=['enviada'], name='notificacoe_enviada_f32028_idx')],
            },
        ),
    ]
