# Generated by Django 6.0.1 on 2026-03-09 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=255)),
                ('canal', models.CharField(max_length=50)),
                ('mensagem', models.TextField()),
                ('enviada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['canal'], name='notificacoe_canal_a5c8e0_idx'), models.Index(fields=['enviada'], name='notificacoe_enviada_f32028_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('resposta', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notificacoes.notificacao')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status'], name='notificacoe_status_8fbd4f_idx'), models.Index(fields=['criado_em'], name='notificacoe_criado__9be6d1_idx')],
            },
        ),
    ]
