# Generated by Django 4.2.16 on 2026-03-17 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=120, unique=True)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Template de Notificação',
                'verbose_name_plural': 'Templates de Notificação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=255)),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=50)),
                ('assunto', models.CharField(blank=True, default='', max_length=160)),
                ('tipo_evento', models.CharField(choices=[('GERAL', 'Geral'), ('RESET_SENHA', 'Reposição de palavra-passe'), ('RESULTADO', 'Resultado disponível'), ('FATURA', 'Fatura emitida'), ('RECIBO', 'Recibo gerado')], default='GERAL', max_length=40)),
                ('referencia_externa', models.CharField(blank=True, max_length=120)),
                ('mensagem', models.TextField()),
                ('enviada', models.BooleanField(default=False)),
                ('erro_envio', models.TextField(blank=True, default='')),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='clinico.paciente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LogEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, max_length=40)),
                ('resposta', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_envio', to='notificacoes.notificacao')),
            ],
            options={
                'verbose_name': 'Log de Envio',
                'verbose_name_plural': 'Logs de Envio',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['canal'], name='notificacoe_canal_a5c8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['tipo_evento'], name='notificacoe_tipo_ev_42172b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['enviada'], name='notificacoe_enviada_f32028_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['referencia_externa'], name='notificacoe_referen_09c562_idx'),
        ),
        migrations.AddIndex(
            model_name='logenvio',
            index=models.Index(fields=['notificacao', 'criado_em'], name='notificacoe_notific_9108da_idx'),
        ),
        migrations.AddIndex(
            model_name='logenvio',
            index=models.Index(fields=['status'], name='notificacoe_status_8fbd4f_idx'),
        ),
    ]
