# Generated by Django 6.0.1 on 2026-03-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0002_initial'),
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='assunto',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='erro_envio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='clinico.paciente'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='referencia_externa',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='tipo_evento',
            field=models.CharField(choices=[('GERAL', 'Geral'), ('RESULTADO', 'Resultado disponível'), ('FATURA', 'Fatura emitida'), ('RECIBO', 'Recibo gerado')], default='GERAL', max_length=40),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='canal',
            field=models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['tipo_evento'], name='notificacoe_tipo_ev_42172b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['referencia_externa'], name='notificacoe_referen_09c562_idx'),
        ),
    ]
