# Generated by Django 6.0.1 on 2026-02-28 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('resposta', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notificacoes.notificacao')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status'], name='notificacoe_status_8fbd4f_idx'), models.Index(fields=['criado_em'], name='notificacoe_criado__9be6d1_idx')],
            },
        ),
    ]
