# Generated by Django 4.2.16 on 2026-03-13 12:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import infrastrutura.orm.fields.dinheiro_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0001_initial'),
        ('clinico', '0004_alter_requisicaoitem_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('tipo', models.CharField(db_index=True, max_length=120)),
                ('descricao', models.TextField(blank=True, default='')),
                ('agendada_para', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('MARCADA', 'Marcada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='MARCADA', max_length=20)),
                ('preco', infrastrutura.orm.fields.dinheiro_field.DinheiroField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_medicas', to='clinico.paciente')),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consultas Médicas',
                'ordering': ['-agendada_para', '-criado_em'],
                'indexes': [models.Index(fields=['inquilino', 'paciente', 'agendada_para'], name='consultas_c_inquili_06ab8d_idx'), models.Index(fields=['inquilino', 'medico', 'agendada_para'], name='consultas_c_inquili_39d00a_idx'), models.Index(fields=['inquilino', 'estado', 'agendada_para'], name='consultas_c_inquili_631e86_idx'), models.Index(fields=['inquilino', 'tipo'], name='consultas_c_inquili_91ac89_idx')],
            },
        ),
    ]
