# Generated by Django 4.2.16 on 2026-03-15 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultas', '0001_initial'),
        ('clinico', '0002_initial'),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriado',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feriado',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feriado',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feriado',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='especialidadeconsulta',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='especialidadeconsulta',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='especialidadeconsulta',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='especialidadeconsulta',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='consultas.especialidadeconsulta'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_medicas', to='clinico.paciente'),
        ),
        migrations.AddIndex(
            model_name='feriado',
            index=models.Index(fields=['inquilino', 'data'], name='consultas_f_inquili_0b009c_idx'),
        ),
        migrations.AddIndex(
            model_name='feriado',
            index=models.Index(fields=['inquilino', 'ativo', 'data'], name='consultas_f_inquili_1e54a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feriado',
            unique_together={('inquilino', 'data')},
        ),
        migrations.AddIndex(
            model_name='especialidadeconsulta',
            index=models.Index(fields=['inquilino', 'ativo', 'nome'], name='consultas_e_inquili_200f90_idx'),
        ),
        migrations.AddIndex(
            model_name='consultamedica',
            index=models.Index(fields=['inquilino', 'paciente', 'agendada_para'], name='consultas_c_inquili_06ab8d_idx'),
        ),
        migrations.AddIndex(
            model_name='consultamedica',
            index=models.Index(fields=['inquilino', 'medico', 'agendada_para'], name='consultas_c_inquili_39d00a_idx'),
        ),
        migrations.AddIndex(
            model_name='consultamedica',
            index=models.Index(fields=['inquilino', 'estado', 'agendada_para'], name='consultas_c_inquili_631e86_idx'),
        ),
        migrations.AddIndex(
            model_name='consultamedica',
            index=models.Index(fields=['inquilino', 'tipo'], name='consultas_c_inquili_91ac89_idx'),
        ),
    ]
