# Generated by Django 4.2.16 on 2026-03-14 21:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import infrastrutura.orm.fields.dinheiro_field


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_especialidadeconsulta_consultamedica_especialidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidadeconsulta',
            name='iva_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Taxa de IVA aplicada ao serviço de consulta (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)'),
        ),
        migrations.AlterField(
            model_name='especialidadeconsulta',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='especialidadeconsulta',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='especialidadeconsulta',
            name='preco_base',
            field=infrastrutura.orm.fields.dinheiro_field.DinheiroField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Preço base'),
        ),
    ]
