# Generated by Django 4.2.16 on 2026-03-17 11:34

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import infrastrutura.orm.fields.dinheiro_field


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinico', '0005_paciente_endereco_pais_countryfield'),
        ('consultas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='feriado_manual',
            field=models.BooleanField(default=False, help_text='Marque se a data for feriado mesmo não sendo fim de semana.', verbose_name='Feriado (manual)'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='multiplicador_preco',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Fator aplicado sobre o preço base conforme horário/feriado.', max_digits=5, verbose_name='Multiplicador de preço'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='tipo_horario',
            field=models.CharField(choices=[('NORMAL', 'Normal (08h-18h)'), ('FORA_EXPEDIENTE', 'Fora de expediente (19h-07h)'), ('FIM_SEMANA', 'Fim de semana'), ('FERIADO_MANUAL', 'Feriado (marcado)')], db_index=True, default='NORMAL', max_length=32, verbose_name='Tipo de horário'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='agendada_para',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Agendada para'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='cancelada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='concluida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluída em'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='consultas.especialidadeconsulta', verbose_name='Especialidade'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='estado',
            field=models.CharField(choices=[('MARCADA', 'Marcada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='MARCADA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_medicas', to='clinico.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='preco',
            field=infrastrutura.orm.fields.dinheiro_field.DinheiroField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='tipo',
            field=models.CharField(db_index=True, max_length=120, verbose_name='Tipo de consulta'),
        ),
    ]
