# Generated by Django 5.2.12 on 2026-03-28 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("curriculum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcompetency",
            name="competency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculum.competency",
                verbose_name="Competência",
            ),
        ),
        migrations.AddField(
            model_name="studentcompetency",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.student",
                verbose_name="Aluno",
            ),
        ),
        migrations.AddField(
            model_name="studentcompetency",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="competencies",
            field=models.ManyToManyField(
                through="academic.StudentCompetency",
                to="curriculum.competency",
                verbose_name="Competências",
            ),
        ),
        migrations.AddField(
            model_name="studentguardian",
            name="guardian",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.guardian",
                verbose_name="Encarregado",
            ),
        ),
        migrations.AddField(
            model_name="studentguardian",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.student",
                verbose_name="Aluno",
            ),
        ),
        migrations.AddField(
            model_name="studentguardian",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="studentoutcome",
            name="outcome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculum.learningoutcome",
                verbose_name="Resultado de aprendizagem",
            ),
        ),
        migrations.AddField(
            model_name="studentoutcome",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.student",
                verbose_name="Aluno",
            ),
        ),
        migrations.AddField(
            model_name="studentoutcome",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentcompetency",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("student", "competency"),
                name="unique_student_competency_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentguardian",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant_id", "student", "guardian"),
                name="unique_student_guardian_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentoutcome",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant_id", "student", "outcome"),
                name="unique_student_outcome_active",
            ),
        ),
    ]
