# Generated by Django 5.2.12 on 2026-03-28 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
    ]
