# Generated by Django 5.2.12 on 2026-03-29 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0007_student_courses"),
        ("learning", "0005_submissionattachment_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="education_path",
            field=models.CharField(
                choices=[
                    ("general", "Ensino geral"),
                    ("technical", "Ensino técnico profissional"),
                ],
                default="general",
                max_length=20,
                verbose_name="Ramo de ensino",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="identification_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="students/identification/",
                verbose_name="Documento de identificação (PDF/Imagem)",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="previous_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="students/certificates/",
                verbose_name="Certificado/declaração da classe anterior",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="technical_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="technical_students",
                to="learning.course",
                verbose_name="Curso técnico",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="technical_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("basic", "Técnico básico"),
                    ("medium", "Técnico médio"),
                    ("superior", "Técnico superior"),
                ],
                max_length=20,
                null=True,
                verbose_name="Nível técnico",
            ),
        ),
    ]
