# Generated by Django 6.0.1 on 2026-03-07 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanoCobertura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                (
                    "percentual_cobertura",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                ("exige_autorizacao", models.BooleanField(default=False)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deletado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquilino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.inquilino",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de Cobertura",
                "verbose_name_plural": "Planos de Cobertura",
            },
        ),
        migrations.CreateModel(
            name="AutorizacaoProcedimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                ("requisicao_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("APROVADA", "Aprovada"),
                            ("NEGADA", "Negada"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                (
                    "codigo_autorizacao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_resposta", models.DateTimeField(blank=True, null=True)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deletado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquilino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.inquilino",
                    ),
                ),
                (
                    "plano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="autorizacoes",
                        to="seguradora.planocobertura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autorização",
                "verbose_name_plural": "Autorizações",
            },
        ),
        migrations.CreateModel(
            name="Seguradora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                (
                    "codigo_externo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deletado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquilino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.inquilino",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguradora",
                "verbose_name_plural": "Seguradoras",
            },
        ),
        migrations.AddField(
            model_name="planocobertura",
            name="seguradora",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planos",
                to="seguradora.seguradora",
            ),
        ),
    ]
