# Generated by Django 4.2.16 on 2026-03-15 19:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('ordem', models.PositiveIntegerField(db_index=True, default=1)),
                ('percentual_cobertura', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de cobertura (0-100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('exige_autorizacao', models.BooleanField(db_index=True, default=False)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
            ],
            options={
                'verbose_name': 'Plano de Cobertura',
                'verbose_name_plural': 'Planos de Cobertura',
            },
        ),
        migrations.CreateModel(
            name='TenantPlanoCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('ordem', models.PositiveIntegerField(db_index=True, default=1)),
                ('percentual_override', models.DecimalField(blank=True, decimal_places=2, help_text='Se vazio, usa o percentual do plano global.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
                ('plano_global', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides_por_tenant', to='seguradora.planocobertura')),
            ],
            options={
                'verbose_name': 'Plano por Tenant',
                'verbose_name_plural': 'Planos por Tenant',
            },
        ),
        migrations.CreateModel(
            name='Seguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('ordem', models.PositiveIntegerField(db_index=True, default=1)),
                ('codigo_externo', models.CharField(blank=True, db_index=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
            ],
            options={
                'verbose_name': 'Seguradora',
                'verbose_name_plural': 'Seguradoras',
            },
        ),
        migrations.AddField(
            model_name='planocobertura',
            name='seguradora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='seguradora.seguradora'),
        ),
        migrations.CreateModel(
            name='AutorizacaoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(db_index=True, default=1)),
                ('requisicao_id', models.CharField(db_index=True, max_length=60)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('NEGADA', 'Negada')], db_index=True, default='PENDENTE', max_length=20)),
                ('codigo_autorizacao', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes', to='seguradora.planocobertura')),
            ],
            options={
                'verbose_name': 'Autorização de Procedimento',
                'verbose_name_plural': 'Autorizações de Procedimento',
            },
        ),
        migrations.AddConstraint(
            model_name='tenantplanocobertura',
            constraint=models.UniqueConstraint(fields=('inquilino', 'plano_global'), name='uniq_tenant_plano_global'),
        ),
    ]
