# Generated by Django 4.2.16 on 2026-03-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='eh_medico',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
