# Generated by Django 6.0.1 on 2026-02-27 09:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_custom', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('ordem', models.PositiveIntegerField(db_index=True, default=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('identificador', models.SlugField(help_text='Identificador único do tenant (usado em URLs e roteamento).', max_length=100, unique=True)),
                ('nome', models.CharField(db_index=True, help_text='Nome comercial do tenant.', max_length=255)),
                ('dominio', models.CharField(blank=True, help_text='Domínio customizado opcional.', max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Domínio inválido.', regex='^[a-z0-9.-]+\\.[a-z]{2,}$')])),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
            ],
            options={
                'verbose_name': 'Inquilino',
                'verbose_name_plural': 'Inquilinos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_custom', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('ordem', models.PositiveIntegerField(db_index=True, default=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('chave', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=False)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='inquilinos.inquilino')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoInquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_custom', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('ordem', models.PositiveIntegerField(db_index=True, default=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fuso_horario', models.CharField(default='Africa/Maputo', help_text='Timezone padrão do tenant.', max_length=50)),
                ('moeda', models.CharField(default='MZN', help_text='Código ISO 4217 da moeda.', max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('idioma', models.CharField(default='pt', help_text='Código ISO 639-1 do idioma.', max_length=5)),
                ('permite_multi_unidade', models.BooleanField(default=False, help_text='Indica se o tenant possui múltiplas unidades operacionais.')),
                ('limite_usuarios', models.PositiveIntegerField(default=10, help_text='Limite máximo de usuários ativos.')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='inquilinos.inquilino')),
            ],
            options={
                'verbose_name': 'Configuração do Inquilino',
                'verbose_name_plural': 'Configurações dos Inquilinos',
            },
        ),
        migrations.CreateModel(
            name='PlanoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_custom', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('ordem', models.PositiveIntegerField(db_index=True, default=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20)),
                ('limite_usuarios', models.PositiveIntegerField(default=5)),
                ('limite_requisicoes_mes', models.PositiveIntegerField(default=100)),
                ('suporte_prioritario', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano', to='inquilinos.inquilino')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsoTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_custom', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('ordem', models.PositiveIntegerField(db_index=True, default=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuarios_ativos', models.PositiveIntegerField(default=0)),
                ('requisicoes_mes_atual', models.PositiveIntegerField(default=0)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uso', to='inquilinos.inquilino')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='inquilino',
            index=models.Index(fields=['identificador'], name='inquilinos__identif_c3e652_idx'),
        ),
        migrations.AddIndex(
            model_name='inquilino',
            index=models.Index(fields=['ativo'], name='inquilinos__ativo_74d41f_idx'),
        ),
        migrations.AddIndex(
            model_name='inquilino',
            index=models.Index(fields=['dominio'], name='inquilinos__dominio_8b793c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featureflagtenant',
            unique_together={('inquilino', 'chave')},
        ),
        migrations.AddIndex(
            model_name='planoassinatura',
            index=models.Index(fields=['ativo'], name='inquilinos__ativo_fa627d_idx'),
        ),
        migrations.AddIndex(
            model_name='planoassinatura',
            index=models.Index(fields=['deletado'], name='inquilinos__deletad_7c0368_idx'),
        ),
        migrations.AddIndex(
            model_name='usotenant',
            index=models.Index(fields=['ativo'], name='inquilinos__ativo_cde76a_idx'),
        ),
        migrations.AddIndex(
            model_name='usotenant',
            index=models.Index(fields=['deletado'], name='inquilinos__deletad_48f006_idx'),
        ),
    ]
