# Generated by Django 4.2.16 on 2026-03-15 14:30

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('identificador', models.SlugField(max_length=80, unique=True)),
                ('dominio', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('status_comercial', models.CharField(choices=[('TRIAL', 'Trial'), ('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso')], db_index=True, default='TRIAL', max_length=10)),
                ('trial_ate', models.DateField(blank=True, null=True)),
                ('bloqueado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inquilino',
                'verbose_name_plural': 'Inquilinos',
            },
        ),
        migrations.CreateModel(
            name='UsoTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('usuarios_ativos', models.PositiveIntegerField(default=0)),
                ('requisicoes_mes_atual', models.PositiveIntegerField(default=0)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uso', to='inquilinos.inquilino')),
            ],
            options={
                'verbose_name': 'Uso do Tenant',
                'verbose_name_plural': 'Uso dos Tenants',
            },
        ),
        migrations.CreateModel(
            name='PlanoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('ordem', models.PositiveIntegerField(db_index=True, default=1)),
                ('tipo', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PRO', 'Pro')], db_index=True, default='FREE', max_length=10)),
                ('limite_usuarios', models.PositiveIntegerField(default=1)),
                ('limite_requisicoes_mes', models.PositiveIntegerField(default=0)),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('preco_excedente_requisicao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('suporte_prioritario', models.BooleanField(default=False)),
                ('permite_multi_unidade', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de Assinatura',
                'verbose_name_plural': 'Planos de Assinatura',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('chave', models.CharField(db_index=True, max_length=120)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
            ],
            options={
                'verbose_name': 'Feature Flag (Tenant)',
                'verbose_name_plural': 'Feature Flags (Tenant)',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoInquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('fuso_horario', models.CharField(default='Africa/Maputo', max_length=80)),
                ('moeda', models.CharField(default='MZN', max_length=10)),
                ('idioma', models.CharField(default='pt', max_length=10)),
                ('permite_multi_unidade', models.BooleanField(default=False)),
                ('limite_usuarios', models.PositiveIntegerField(default=1)),
                ('acrescimo_percentual_consulta_feriado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='inquilinos.inquilino')),
            ],
            options={
                'verbose_name': 'Configuração do Inquilino',
                'verbose_name_plural': 'Configurações do Inquilino',
            },
        ),
        migrations.CreateModel(
            name='AssinaturaTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('data_inicio', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CANCELADA', 'Cancelada')], db_index=True, default='ATIVA', max_length=10)),
                ('ciclo', models.CharField(choices=[('MENSAL', 'Mensal'), ('ANUAL', 'Anual')], db_index=True, default='MENSAL', max_length=10)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='inquilinos.inquilino')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='inquilinos.planoassinatura')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='planoassinatura',
            index=models.Index(fields=['tipo', 'ativo'], name='inquilinos__tipo_856ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='planoassinatura',
            index=models.Index(fields=['ativo'], name='inquilinos__ativo_fa627d_idx'),
        ),
        migrations.AddIndex(
            model_name='inquilino',
            index=models.Index(fields=['identificador'], name='inquilinos__identif_c3e652_idx'),
        ),
        migrations.AddIndex(
            model_name='inquilino',
            index=models.Index(fields=['dominio'], name='inquilinos__dominio_8b793c_idx'),
        ),
        migrations.AddIndex(
            model_name='inquilino',
            index=models.Index(fields=['ativo'], name='inquilinos__ativo_74d41f_idx'),
        ),
        migrations.AddConstraint(
            model_name='featureflagtenant',
            constraint=models.UniqueConstraint(fields=('inquilino', 'chave'), name='unique_featureflag_por_inquilino'),
        ),
        migrations.AddIndex(
            model_name='assinaturatenant',
            index=models.Index(fields=['inquilino', 'status'], name='inquilinos__inquili_863caa_idx'),
        ),
    ]
