# Generated by Django 6.0.1 on 2026-02-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquilino',
            name='inquilino',
        ),
    ]
