# Generated by Django 6.0.1 on 2026-03-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquilinos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquilino",
            name="bloqueado_ate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
