# Generated by Django 4.2.16 on 2026-03-14 17:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoinquilino',
            name='acrescimo_percentual_consulta_feriado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
