# Generated by Django 6.0.1 on 2026-03-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquilinos", "0002_inquilino_bloqueado_ate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaoinquilino",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="featureflagtenant",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="inquilino",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="planoassinatura",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="usotenant",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
    ]
