# Generated by Django 6.0.1 on 2026-02-28 07:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0002_remove_inquilino_inquilino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planoassinatura',
            options={'ordering': ['preco_mensal'], 'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.AlterModelOptions(
            name='usotenant',
            options={'verbose_name': 'Uso do Tenant', 'verbose_name_plural': 'Usos dos Tenants'},
        ),
        migrations.RemoveIndex(
            model_name='planoassinatura',
            name='inquilinos__deletad_7c0368_idx',
        ),
        migrations.RemoveIndex(
            model_name='usotenant',
            name='inquilinos__ativo_cde76a_idx',
        ),
        migrations.RemoveIndex(
            model_name='usotenant',
            name='inquilinos__deletad_48f006_idx',
        ),
        migrations.AddField(
            model_name='inquilino',
            name='bloqueado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquilino',
            name='status_comercial',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ATIVO', 'Ativo'), ('INADIMPLENTE', 'Inadimplente'), ('SUSPENSO', 'Suspenso'), ('CANCELADO', 'Cancelado')], db_index=True, default='TRIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='inquilino',
            name='trial_ate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planoassinatura',
            name='permite_multi_unidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planoassinatura',
            name='preco_excedente_requisicao',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='planoassinatura',
            name='preco_mensal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='featureflagtenant',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='identificador',
            field=models.SlugField(help_text='Identificador único do tenant.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='planoassinatura',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='planoassinatura',
            name='tipo',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], db_index=True, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='configuracaoinquilino',
            index=models.Index(fields=['inquilino'], name='inquilinos__inquili_88928d_idx'),
        ),
        migrations.AddIndex(
            model_name='inquilino',
            index=models.Index(fields=['status_comercial'], name='inquilinos__status__70c75a_idx'),
        ),
        migrations.AddIndex(
            model_name='planoassinatura',
            index=models.Index(fields=['tipo'], name='inquilinos__tipo_7b835d_idx'),
        ),
        migrations.RemoveField(
            model_name='planoassinatura',
            name='inquilino',
        ),
    ]
