# Generated by Django 4.2.16 on 2026-03-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('serial_number', models.CharField(db_column='serial_number', db_index=True, max_length=120, verbose_name='Número de série')),
                ('acquisition_date', models.DateField(blank=True, db_column='acquisition_date', null=True, verbose_name='Data de aquisição')),
                ('acquisition_status', models.CharField(choices=[('NOVO', 'Novo'), ('USADO', 'Usado')], db_column='acquisition_status', db_index=True, default='NOVO', max_length=20, verbose_name='Estado na aquisição')),
                ('initial_operational_status', models.CharField(choices=[('FUNCIONANDO', 'A funcionar'), ('AVARIADO', 'Avariado'), ('DESLIGADO', 'Desligado')], db_column='initial_operational_status', db_index=True, default='FUNCIONANDO', max_length=20, verbose_name='Estado operacional inicial')),
                ('initial_failure_type', models.CharField(blank=True, db_column='initial_failure_type', default='', max_length=120, verbose_name='Tipo de avaria inicial')),
                ('manufacturer', models.CharField(blank=True, db_column='manufacturer', default='', max_length=120, verbose_name='Fabricante')),
                ('model', models.CharField(blank=True, db_column='model', default='', max_length=120, verbose_name='Modelo')),
                ('location', models.CharField(blank=True, db_column='location', default='', max_length=255, verbose_name='Localização')),
                ('responsible', models.CharField(blank=True, db_column='responsible', default='', max_length=120, verbose_name='Responsável')),
                ('active', models.BooleanField(db_column='active', db_index=True, default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'db_table': 'equipamentos_equipamento',
                'ordering': ['name'],
            },
        ),
    ]
