# Generated by Django 5.1 on 2026-03-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "name",
                    models.CharField(db_column="nome", db_index=True, max_length=120),
                ),
                (
                    "serial_number",
                    models.CharField(
                        db_column="numero_serie",
                        db_index=True,
                        max_length=120,
                        verbose_name="Número de série",
                    ),
                ),
                (
                    "acquisition_date",
                    models.DateField(
                        blank=True,
                        db_column="data_aquisicao",
                        null=True,
                        verbose_name="Data de aquisição",
                    ),
                ),
                (
                    "acquisition_status",
                    models.CharField(
                        choices=[("NOVO", "Novo"), ("USADO", "Usado")],
                        db_column="estado_aquisicao",
                        db_index=True,
                        default="NOVO",
                        max_length=20,
                        verbose_name="Estado na aquisição",
                    ),
                ),
                (
                    "initial_operational_status",
                    models.CharField(
                        choices=[
                            ("FUNCIONANDO", "A funcionar"),
                            ("AVARIADO", "Avariado"),
                            ("DESLIGADO", "Desligado"),
                        ],
                        db_column="estado_operacional_inicial",
                        db_index=True,
                        default="FUNCIONANDO",
                        max_length=20,
                        verbose_name="Estado operacional inicial",
                    ),
                ),
                (
                    "initial_failure_type",
                    models.CharField(
                        blank=True,
                        db_column="tipo_avaria_inicial",
                        default="",
                        max_length=120,
                        verbose_name="Tipo de avaria inicial",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, db_column="fabricante", default="", max_length=120
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, db_column="modelo", default="", max_length=120
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        db_column="localizacao",
                        default="",
                        max_length=255,
                        verbose_name="Localização",
                    ),
                ),
                (
                    "responsible",
                    models.CharField(
                        blank=True,
                        db_column="responsavel",
                        default="",
                        max_length=120,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(db_column="ativo", db_index=True, default=True),
                ),
            ],
            options={
                "verbose_name": "Equipamento",
                "verbose_name_plural": "Equipamentos",
                "db_table": "equipamentos_equipamento",
                "ordering": ["name"],
            },
        ),
    ]
