# Generated by Django 5.1 on 2026-03-25 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipamentos", "0001_initial"),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="criado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                db_column="deletado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="tenant",
            field=models.ForeignKey(
                db_column="inquilino_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.tenant",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="atualizado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["tenant", "serial_number"],
                name="equipamento_inquili_a3b6b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["tenant", "active"], name="equipamento_inquili_1b62c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["tenant", "initial_operational_status"],
                name="equipamento_inquili_2b929b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="equipment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "serial_number"),
                name="uq_equipment_serial_number_tenant",
            ),
        ),
    ]
