# Generated by Django 5.1 on 2026-03-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipamentos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="active",
            field=models.BooleanField(
                db_column="active", db_index=True, default=True, verbose_name="Ativo"
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="manufacturer",
            field=models.CharField(
                blank=True,
                db_column="manufacturer",
                default="",
                max_length=120,
                verbose_name="Fabricante",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="model",
            field=models.CharField(
                blank=True,
                db_column="model",
                default="",
                max_length=120,
                verbose_name="Modelo",
            ),
        ),
    ]
