# Generated by Django 5.1 on 2026-03-25 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipamentos", "0002_initial"),
        (
            "inquilinos",
            "0002_rename_inquilinos__tipo_856ce4_idx_inquilinos__type_fdb81e_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="equipment",
            new_name="equipamento_tenant__3693db_idx",
            old_name="equipamento_inquili_a3b6b8_idx",
        ),
        migrations.RenameIndex(
            model_name="equipment",
            new_name="equipamento_tenant__3ff2bd_idx",
            old_name="equipamento_inquili_1b62c4_idx",
        ),
        migrations.RenameIndex(
            model_name="equipment",
            new_name="equipamento_tenant__ae05b0_idx",
            old_name="equipamento_inquili_2b929b_idx",
        ),
        migrations.AlterField(
            model_name="equipment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="created_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                db_column="deleted_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
