# Generated by Django 4.2.29 on 2026-05-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='maintenance_required_since',
            field=models.DateTimeField(blank=True, db_column='maintenance_required_since', db_index=True, null=True, verbose_name='Manutenção requerida desde'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='requires_maintenance',
            field=models.BooleanField(db_column='requires_maintenance', db_index=True, default=False, verbose_name='Requer manutenção'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['tenant', 'requires_maintenance'], name='equipamento_tenant__9fe5cd_idx'),
        ),
    ]
