# Generated by Django 6.0.1 on 2026-02-27 09:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_custom', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('ordem', models.PositiveIntegerField(db_index=True, default=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva_valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_seguro', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_paciente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('RASC', 'Rascunho'), ('EMIT', 'Emitida'), ('PAGA', 'Paga'), ('CANC', 'Cancelada')], default='RASC', max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaturaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_custom', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('ordem', models.PositiveIntegerField(db_index=True, default=1)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('isento_iva', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('tipo_evento', models.CharField(blank=True, max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
