# Generated by Django 4.2.13 on 2026-03-12 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faturamento', '0001_initial'),
        ('enfermagem', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinico', '__first__'),
        ('farmacia', '0002_initial'),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicofatura',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicofatura',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicofatura',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicofatura',
            name='fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='faturamento.fatura'),
        ),
        migrations.AddField(
            model_name='historicofatura',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='exame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.exame'),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='faturamento.fatura'),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='item_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='farmacia.itemvenda'),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='procedimento_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermagem.procedimentoitem'),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='procedimento_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermagem.procedimentomaterial'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fatura',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fatura',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fatura',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='clinico.paciente'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='procedimento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura', to='enfermagem.procedimento'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='requisicao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fatura', to='clinico.requisicaoanalise'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='venda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura', to='farmacia.venda'),
        ),
        migrations.AddIndex(
            model_name='historicofatura',
            index=models.Index(fields=['fatura', 'criado_em'], name='faturamento_fatura__c7ed3e_idx'),
        ),
        migrations.AddIndex(
            model_name='historicofatura',
            index=models.Index(fields=['tipo_evento'], name='faturamento_tipo_ev_bbf502_idx'),
        ),
        migrations.AddConstraint(
            model_name='faturaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False), ('exame__isnull', False)), fields=('fatura', 'exame'), name='unique_exame_por_fatura'),
        ),
        migrations.AddConstraint(
            model_name='faturaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False), ('item_venda__isnull', False)), fields=('fatura', 'item_venda'), name='unique_item_venda_por_fatura'),
        ),
        migrations.AddConstraint(
            model_name='faturaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False), ('procedimento_item__isnull', False)), fields=('fatura', 'procedimento_item'), name='unique_proc_item_por_fatura'),
        ),
        migrations.AddConstraint(
            model_name='faturaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False), ('procedimento_material__isnull', False)), fields=('fatura', 'procedimento_material'), name='unique_proc_material_por_fatura'),
        ),
    ]
