# Generated by Django 4.2.16 on 2026-03-15 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinico', '0002_initial'),
        ('faturamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmacia', '0002_initial'),
        ('consultas', '0002_initial'),
        ('inquilinos', '0001_initial'),
        ('enfermagem', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicofatura',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicofatura',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicofatura',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicofatura',
            name='fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='faturamento.fatura', verbose_name='Fatura'),
        ),
        migrations.AddField(
            model_name='historicofatura',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='exame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.exame', verbose_name='Exame'),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='exame_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.examemedico', verbose_name='Exame médico'),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='faturamento.fatura', verbose_name='Fatura'),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='item_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='farmacia.itemvenda', verbose_name='Item de venda'),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='procedimento_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermagem.procedimentoitem', verbose_name='Item de procedimento'),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='procedimento_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermagem.procedimentomaterial', verbose_name='Material de procedimento'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fatura',
            name='consulta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura', to='consultas.consultamedica', verbose_name='Consulta'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fatura',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fatura',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='clinico.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='procedimento',
            field=models.OneToOneField(blank=True, help_text="Legado: prefira usar o campo 'procedimentos' (múltiplos).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura', to='enfermagem.procedimento', verbose_name='Procedimento (legado)'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='procedimentos',
            field=models.ManyToManyField(blank=True, help_text='Pode associar múltiplos procedimentos de enfermagem à mesma fatura.', related_name='faturas', to='enfermagem.procedimento', verbose_name='Procedimentos (Enfermagem)'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='requisicao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fatura', to='clinico.requisicaoanalise', verbose_name='Requisição'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='venda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura', to='farmacia.venda', verbose_name='Venda'),
        ),
        migrations.AddIndex(
            model_name='historicofatura',
            index=models.Index(fields=['fatura', 'criado_em'], name='faturamento_fatura__c7ed3e_idx'),
        ),
        migrations.AddIndex(
            model_name='historicofatura',
            index=models.Index(fields=['tipo_evento'], name='faturamento_tipo_ev_bbf502_idx'),
        ),
        migrations.AddConstraint(
            model_name='faturaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False), ('exame__isnull', False)), fields=('fatura', 'exame'), name='unique_exame_por_fatura'),
        ),
        migrations.AddConstraint(
            model_name='faturaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False), ('exame_medico__isnull', False)), fields=('fatura', 'exame_medico'), name='unique_exame_medico_por_fatura'),
        ),
        migrations.AddConstraint(
            model_name='faturaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False), ('item_venda__isnull', False)), fields=('fatura', 'item_venda'), name='unique_item_venda_por_fatura'),
        ),
        migrations.AddConstraint(
            model_name='faturaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False), ('procedimento_item__isnull', False)), fields=('fatura', 'procedimento_item'), name='unique_proc_item_por_fatura'),
        ),
        migrations.AddConstraint(
            model_name='faturaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False), ('procedimento_material__isnull', False)), fields=('fatura', 'procedimento_material'), name='unique_proc_material_por_fatura'),
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['inquilino', 'origem', 'estado', 'criado_em'], name='faturamento_inquili_930f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['inquilino', 'paciente', 'criado_em'], name='faturamento_inquili_01c018_idx'),
        ),
    ]
