# Generated by Django 6.0.1 on 2026-03-10 12:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('clinico', '0002_initial'),
        ('enfermagem', '0005_procedimentoitemvalor_procedimentomaterialvalor'),
        ('farmacia', '0003_movimentoestoque_origem_and_more'),
        ('faturamento', '0002_initial'),
        ('inquilinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faturaitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fatura',
            name='origem',
            field=models.CharField(choices=[('CLI', 'Clínico'), ('FAR', 'Farmácia'), ('ENF', 'Enfermagem')], db_index=True, default='CLI', max_length=3),
        ),
        migrations.AddField(
            model_name='fatura',
            name='procedimento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura', to='enfermagem.procedimento'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='venda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura', to='farmacia.venda'),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='item_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='farmacia.itemvenda'),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='procedimento_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermagem.procedimentoitem'),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='procedimento_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermagem.procedimentomaterial'),
        ),
        migrations.AddField(
            model_name='faturaitem',
            name='tipo_item',
            field=models.CharField(choices=[('EXA', 'Exame'), ('FAR', 'Item de farmácia'), ('PRC', 'Serviço de enfermagem'), ('MAT', 'Material de enfermagem'), ('AJU', 'Ajuste manual')], db_index=True, default='EXA', max_length=3),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='clinico.paciente'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='requisicao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fatura', to='clinico.requisicaoanalise'),
        ),
        migrations.AlterField(
            model_name='faturaitem',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='faturaitem',
            name='exame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.exame'),
        ),
        migrations.AlterField(
            model_name='faturaitem',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='faturaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False), ('exame__isnull', False)), fields=('fatura', 'exame'), name='unique_exame_por_fatura'),
        ),
        migrations.AddConstraint(
            model_name='faturaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False), ('item_venda__isnull', False)), fields=('fatura', 'item_venda'), name='unique_item_venda_por_fatura'),
        ),
        migrations.AddConstraint(
            model_name='faturaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False), ('procedimento_item__isnull', False)), fields=('fatura', 'procedimento_item'), name='unique_proc_item_por_fatura'),
        ),
        migrations.AddConstraint(
            model_name='faturaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False), ('procedimento_material__isnull', False)), fields=('fatura', 'procedimento_material'), name='unique_proc_material_por_fatura'),
        ),
    ]
