# Generated by Django 6.0.1 on 2026-02-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faturamento", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatura",
            name="id_custom",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=30,
                unique=True,
                verbose_name="ordem",
            ),
        ),
        migrations.AlterField(
            model_name="faturaitem",
            name="id_custom",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=30,
                unique=True,
                verbose_name="ordem",
            ),
        ),
    ]
