# Generated by Django 4.2.16 on 2026-03-13 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0004_alter_requisicaoitem_unique_together_and_more'),
        ('faturamento', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturaitem',
            name='exame_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.examemedico'),
        ),
        migrations.AlterField(
            model_name='faturaitem',
            name='tipo_item',
            field=models.CharField(choices=[('EXA', 'Exame'), ('EXM', 'Exame médico'), ('FAR', 'Item de farmácia'), ('PRC', 'Serviço de enfermagem'), ('MAT', 'Material de enfermagem'), ('AJU', 'Ajuste manual')], db_index=True, default='EXA', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='faturaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False), ('exame_medico__isnull', False)), fields=('fatura', 'exame_medico'), name='unique_exame_medico_por_fatura'),
        ),
    ]
