# Generated by Django 6.0.1 on 2026-03-01 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faturamento", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fatura",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="faturaitem",
            name="nome",
        ),
    ]
