# Generated by Django 4.2.16 on 2026-03-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturaitem',
            name='aplica_iva',
            field=models.BooleanField(default=True, help_text='Desmarque para não aplicar IVA neste item.', verbose_name='Aplicar IVA?'),
        ),
    ]
