# Generated by Django 4.2.16 on 2026-03-13 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        ('faturamento', '0003_faturaitem_exame_medico_alter_faturaitem_tipo_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='consulta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura', to='consultas.consultamedica'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='origem',
            field=models.CharField(choices=[('CLI', 'Clínico'), ('FAR', 'Farmácia'), ('ENF', 'Enfermagem'), ('CON', 'Consulta')], db_index=True, default='CLI', max_length=3),
        ),
    ]
