# Generated by Django 6.0.1 on 2026-03-02 00:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faturamento", "0003_remove_fatura_nome_remove_faturaitem_nome"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="faturaitem",
            name="faturamento_fatura__582164_idx",
        ),
        migrations.AddField(
            model_name="faturaitem",
            name="nome",
            field=models.CharField(
                db_index=True, default=django.utils.timezone.now, max_length=120
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fatura",
            name="estado",
            field=models.CharField(
                choices=[
                    ("RASC", "Rascunho"),
                    ("EMIT", "Emitida"),
                    ("PAGA", "Paga"),
                    ("CANC", "Cancelada"),
                ],
                db_index=True,
                default="RASC",
                max_length=5,
            ),
        ),
        migrations.RemoveField(
            model_name="faturaitem",
            name="isento_iva",
        ),
    ]
