# Generated by Django 4.2.16 on 2026-03-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirurgia', '0003_cirurgia_aplica_iva_por_padrao_and_more'),
        ('faturamento', '0003_faturaitem_aplica_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='cirurgia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura', to='cirurgia.cirurgia', verbose_name='Cirurgia'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='origem',
            field=models.CharField(choices=[('CLI', 'Clínico'), ('FAR', 'Farmácia'), ('ENF', 'Enfermagem'), ('CON', 'Consulta'), ('CIR', 'Cirurgia')], db_index=True, default='CLI', max_length=3, verbose_name='Origem'),
        ),
    ]
