# Generated by Django 6.0.1 on 2026-03-02 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "faturamento",
            "0004_remove_faturaitem_faturamento_fatura__582164_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faturaitem",
            name="nome",
        ),
    ]
