# Generated by Django 4.2.16 on 2026-03-14 21:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def migrar_procedimento_legado_para_m2m(apps, schema_editor):
    """
    Copia Fatura.procedimento (legado) -> Fatura.procedimentos (M2M), mantendo compatibilidade.
    """
    Fatura = apps.get_model("faturamento", "Fatura")
    Through = apps.get_model("faturamento", "Fatura_procedimentos")

    for fat in Fatura.objects.exclude(procedimento_id__isnull=True).only("id", "procedimento_id"):
        try:
            Through.objects.get_or_create(
                fatura_id=fat.id,
                procedimento_id=fat.procedimento_id,
            )
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0007_exame_iva_percentual_examemedico_iva_percentual_and_more'),
        ('enfermagem', '0003_procedimentocatalogo_iva_percentual_and_more'),
        ('consultas', '0003_especialidadeconsulta_iva_percentual_and_more'),
        ('farmacia', '0003_produto_iva_percentual_venda_paciente_and_more'),
        ('faturamento', '0004_fatura_consulta_alter_fatura_origem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fatura',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Fatura', 'verbose_name_plural': 'Faturas'},
        ),
        migrations.AlterModelOptions(
            name='faturaitem',
            options={'verbose_name': 'Item de Fatura', 'verbose_name_plural': 'Itens de Fatura'},
        ),
        migrations.AddField(
            model_name='fatura',
            name='procedimentos',
            field=models.ManyToManyField(blank=True, help_text='Pode associar múltiplos procedimentos de enfermagem à mesma fatura.', related_name='faturas', to='enfermagem.procedimento', verbose_name='Procedimentos (Enfermagem)'),
        ),
        migrations.RunPython(migrar_procedimento_legado_para_m2m, migrations.RunPython.noop),
        migrations.AddField(
            model_name='faturaitem',
            name='iva_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Deixe em branco para herdar do item (exame/produto/procedimento).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='consulta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura', to='consultas.consultamedica', verbose_name='Consulta'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='estado',
            field=models.CharField(choices=[('RASC', 'Rascunho'), ('EMIT', 'Emitida'), ('PAGA', 'Paga'), ('CANC', 'Cancelada')], db_index=True, default='RASC', max_length=5, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='iva_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de IVA'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='origem',
            field=models.CharField(choices=[('CLI', 'Clínico'), ('FAR', 'Farmácia'), ('ENF', 'Enfermagem'), ('CON', 'Consulta')], db_index=True, default='CLI', max_length=3, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='clinico.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='procedimento',
            field=models.OneToOneField(blank=True, help_text="Legado: prefira usar o campo 'procedimentos' (múltiplos).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura', to='enfermagem.procedimento', verbose_name='Procedimento (legado)'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='requisicao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fatura', to='clinico.requisicaoanalise', verbose_name='Requisição'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total sem IVA'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total com IVA'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_paciente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do paciente'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_seguro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do seguro'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='venda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura', to='farmacia.venda', verbose_name='Venda'),
        ),
        migrations.AlterField(
            model_name='faturaitem',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='faturaitem',
            name='exame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.exame', verbose_name='Exame'),
        ),
        migrations.AlterField(
            model_name='faturaitem',
            name='exame_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.examemedico', verbose_name='Exame médico'),
        ),
        migrations.AlterField(
            model_name='faturaitem',
            name='fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='faturamento.fatura', verbose_name='Fatura'),
        ),
        migrations.AlterField(
            model_name='faturaitem',
            name='item_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='farmacia.itemvenda', verbose_name='Item de venda'),
        ),
        migrations.AlterField(
            model_name='faturaitem',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Preço unitário'),
        ),
        migrations.AlterField(
            model_name='faturaitem',
            name='procedimento_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermagem.procedimentoitem', verbose_name='Item de procedimento'),
        ),
        migrations.AlterField(
            model_name='faturaitem',
            name='procedimento_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermagem.procedimentomaterial', verbose_name='Material de procedimento'),
        ),
        migrations.AlterField(
            model_name='faturaitem',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='faturaitem',
            name='tipo_item',
            field=models.CharField(choices=[('EXA', 'Exame'), ('EXM', 'Exame médico'), ('FAR', 'Item de farmácia'), ('PRC', 'Serviço de enfermagem'), ('MAT', 'Material de enfermagem'), ('AJU', 'Ajuste manual')], db_index=True, default='EXA', max_length=3, verbose_name='Tipo de item'),
        ),
        migrations.AlterField(
            model_name='historicofatura',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='historicofatura',
            name='fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='faturamento.fatura', verbose_name='Fatura'),
        ),
        migrations.AlterField(
            model_name='historicofatura',
            name='tipo_evento',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Tipo de evento'),
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['inquilino', 'origem', 'estado', 'criado_em'], name='faturamento_inquili_930f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['inquilino', 'paciente', 'criado_em'], name='faturamento_inquili_01c018_idx'),
        ),
    ]
