# Generated by Django 4.2.16 on 2026-03-14 21:26

from decimal import Decimal

from django.db import migrations


def preencher_iva_percentual_itens_existentes(apps, schema_editor):
    """
    Backfill de IVA (%) em itens antigos (antes do cálculo por item).
    """
    FaturaItem = apps.get_model("faturamento", "FaturaItem")

    qs = (
        FaturaItem.objects.filter(iva_percentual__isnull=True)
        .select_related(
            "exame",
            "exame_medico",
            "item_venda__produto",
            "procedimento_item__catalogo",
            "procedimento_material__produto",
        )
        .only(
            "id",
            "tipo_item",
            "exame_id",
            "exame_medico_id",
            "item_venda_id",
            "procedimento_item_id",
            "procedimento_material_id",
        )
    )

    for item in qs.iterator():
        perc = Decimal("0.00")

        if item.exame_id:
            perc = getattr(item.exame, "iva_percentual", None) or Decimal("0.00")
        elif item.exame_medico_id:
            perc = getattr(item.exame_medico, "iva_percentual", None) or Decimal("0.00")
        elif item.item_venda_id:
            produto = getattr(item.item_venda, "produto", None)
            perc = getattr(produto, "iva_percentual", None) or Decimal("0.00")
        elif item.procedimento_item_id:
            catalogo = getattr(item.procedimento_item, "catalogo", None)
            if catalogo is not None:
                perc = getattr(catalogo, "iva_percentual", None) or Decimal("0.00")
            else:
                perc = Decimal("16.00")
        elif item.procedimento_material_id:
            produto = getattr(item.procedimento_material, "produto", None)
            perc = getattr(produto, "iva_percentual", None) or Decimal("0.00")
        elif item.tipo_item == "AJU":
            perc = Decimal("16.00")

        try:
            FaturaItem.objects.filter(pk=item.pk).update(iva_percentual=perc)
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0005_alter_fatura_options_alter_faturaitem_options_and_more'),
    ]

    operations = [
        migrations.RunPython(preencher_iva_percentual_itens_existentes, migrations.RunPython.noop),
    ]
