# Generated by Django 6.0.1 on 2026-03-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faturamento", "0005_remove_faturaitem_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faturaitem",
            name="preco_unitario",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
