# Generated by Django 4.2.16 on 2026-03-14 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinico', '0005_requisicaoanalise_tipo'),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirurgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('procedimento', models.CharField(db_index=True, max_length=160)),
                ('descricao', models.TextField(blank=True, default='')),
                ('agendada_para', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='AGENDADA', max_length=20)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('cirurgiao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirurgias_realizadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cirurgias', to='clinico.paciente')),
            ],
            options={
                'verbose_name': 'Cirurgia',
                'verbose_name_plural': 'Cirurgias',
                'ordering': ['-agendada_para', '-criado_em'],
                'indexes': [models.Index(fields=['inquilino', 'paciente', 'agendada_para'], name='cirurgia_ci_inquili_a87732_idx'), models.Index(fields=['inquilino', 'cirurgiao', 'agendada_para'], name='cirurgia_ci_inquili_47131d_idx'), models.Index(fields=['inquilino', 'estado', 'agendada_para'], name='cirurgia_ci_inquili_22d933_idx')],
            },
        ),
    ]
