# Generated by Django 4.2.16 on 2026-03-15 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cirurgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('procedimento', models.CharField(blank=True, db_index=True, default='', help_text='Use apenas quando o procedimento não estiver no catálogo.', max_length=160, verbose_name='Procedimento (texto livre)')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('agendada_para', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Agendada para')),
                ('estado', models.CharField(choices=[('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='AGENDADA', max_length=20, verbose_name='Estado')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('cancelada_em', models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em')),
            ],
            options={
                'verbose_name': 'Cirurgia',
                'verbose_name_plural': 'Cirurgias',
                'ordering': ['-agendada_para', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoCirurgico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Procedimento Cirúrgico',
                'verbose_name_plural': 'Procedimentos Cirúrgicos',
                'ordering': ['nome'],
            },
        ),
    ]
