# Generated by Django 4.2.16 on 2026-03-17 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinico', '0001_initial'),
        ('inquilinos', '0001_initial'),
        ('cirurgia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentocirurgico',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentocirurgico',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentocirurgico',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentocirurgico',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='cirurgia',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cirurgia',
            name='cirurgiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirurgias_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Cirurgião'),
        ),
        migrations.AddField(
            model_name='cirurgia',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cirurgia',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cirurgia',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='cirurgia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cirurgias', to='clinico.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='cirurgia',
            name='procedimentos',
            field=models.ManyToManyField(blank=True, related_name='cirurgias', to='cirurgia.procedimentocirurgico', verbose_name='Procedimentos cirúrgicos'),
        ),
        migrations.AddIndex(
            model_name='procedimentocirurgico',
            index=models.Index(fields=['inquilino', 'ativo', 'nome'], name='cirurgia_pr_inquili_5ffeb7_idx'),
        ),
        migrations.AddIndex(
            model_name='cirurgia',
            index=models.Index(fields=['inquilino', 'paciente', 'agendada_para'], name='cirurgia_ci_inquili_a87732_idx'),
        ),
        migrations.AddIndex(
            model_name='cirurgia',
            index=models.Index(fields=['inquilino', 'cirurgiao', 'agendada_para'], name='cirurgia_ci_inquili_47131d_idx'),
        ),
        migrations.AddIndex(
            model_name='cirurgia',
            index=models.Index(fields=['inquilino', 'estado', 'agendada_para'], name='cirurgia_ci_inquili_22d933_idx'),
        ),
    ]
