# Generated by Django 4.2.16 on 2026-03-14 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0007_exame_iva_percentual_examemedico_iva_percentual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0002_configuracaoinquilino_acrescimo_percentual_consulta_feriado'),
        ('cirurgia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirurgia',
            name='agendada_para',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Agendada para'),
        ),
        migrations.AlterField(
            model_name='cirurgia',
            name='cancelada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em'),
        ),
        migrations.AlterField(
            model_name='cirurgia',
            name='cirurgiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirurgias_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Cirurgião'),
        ),
        migrations.AlterField(
            model_name='cirurgia',
            name='concluida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluída em'),
        ),
        migrations.AlterField(
            model_name='cirurgia',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cirurgia',
            name='estado',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='AGENDADA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cirurgia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cirurgias', to='clinico.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='cirurgia',
            name='procedimento',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Use apenas quando o procedimento não estiver no catálogo.', max_length=160, verbose_name='Procedimento (texto livre)'),
        ),
        migrations.CreateModel(
            name='ProcedimentoCirurgico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
            ],
            options={
                'verbose_name': 'Procedimento Cirúrgico',
                'verbose_name_plural': 'Procedimentos Cirúrgicos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='cirurgia',
            name='procedimentos',
            field=models.ManyToManyField(blank=True, related_name='cirurgias', to='cirurgia.procedimentocirurgico', verbose_name='Procedimentos cirúrgicos'),
        ),
        migrations.AddIndex(
            model_name='procedimentocirurgico',
            index=models.Index(fields=['inquilino', 'ativo', 'nome'], name='cirurgia_pr_inquili_5ffeb7_idx'),
        ),
    ]
