# Generated by Django 4.2.16 on 2026-03-17 11:54

from decimal import Decimal
from django.db import migrations, models
import infrastrutura.orm.fields.dinheiro_field


class Migration(migrations.Migration):

    dependencies = [
        ('cirurgia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirurgia',
            name='aplica_iva_por_padrao',
            field=models.BooleanField(default=True, verbose_name='Aplicar IVA por padrão'),
        ),
        migrations.AddField(
            model_name='cirurgia',
            name='iva_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5, verbose_name='IVA (%)'),
        ),
        migrations.AddField(
            model_name='cirurgia',
            name='preco_estimado',
            field=infrastrutura.orm.fields.dinheiro_field.DinheiroField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Preço estimado'),
        ),
        migrations.AddField(
            model_name='procedimentocirurgico',
            name='aplica_iva_por_padrao',
            field=models.BooleanField(default=True, verbose_name='Aplicar IVA por padrão'),
        ),
        migrations.AddField(
            model_name='procedimentocirurgico',
            name='iva_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5, verbose_name='IVA (%)'),
        ),
        migrations.AddField(
            model_name='procedimentocirurgico',
            name='preco_base',
            field=infrastrutura.orm.fields.dinheiro_field.DinheiroField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Preço base'),
        ),
    ]
