# Generated by Django 5.1 on 2026-03-26 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identidade", "0001_initial"),
        ("recursos_humanos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionalprofile",
            name="employee",
            field=models.OneToOneField(
                blank=True,
                db_column="employee_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perfil_professional_rh",
                to="recursos_humanos.employee",
                verbose_name="Funcionário (RH)",
            ),
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="user",
            field=models.OneToOneField(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil_professional",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["user", "created_at"], name="identidade__user_id_00da43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(fields=["used"], name="identidade__used_811e79_idx"),
        ),
        migrations.AddIndex(
            model_name="professionalprofile",
            index=models.Index(fields=["user"], name="identidade__user_id_56a60b_idx"),
        ),
        migrations.AddIndex(
            model_name="professionalprofile",
            index=models.Index(
                fields=["employee"], name="identidade__employe_4b907a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="professionalprofile",
            index=models.Index(fields=["active"], name="identidade__active_1e8bd4_idx"),
        ),
    ]
