# Generated by Django 5.1 on 2026-03-25 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identidade", "0002_initial"),
        (
            "inquilinos",
            "0002_rename_inquilinos__tipo_856ce4_idx_inquilinos__type_fdb81e_idx_and_more",
        ),
        (
            "recursos_humanos",
            "0002_rename_recursos_hu_inquili_e0a10c_idx_recursos_hu_tenant__23238d_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="passwordresettoken",
            new_name="identidade__user_id_00da43_idx",
            old_name="identidade__user_id_f784de_idx",
        ),
        migrations.RenameIndex(
            model_name="passwordresettoken",
            new_name="identidade__used_811e79_idx",
            old_name="identidade__usado_f7c8a6_idx",
        ),
        migrations.RenameIndex(
            model_name="professionalprofile",
            new_name="identidade__user_id_56a60b_idx",
            old_name="identidade__usuario_bba900_idx",
        ),
        migrations.RenameIndex(
            model_name="professionalprofile",
            new_name="identidade__employe_4b907a_idx",
            old_name="identidade__funcion_71e18c_idx",
        ),
        migrations.RenameIndex(
            model_name="professionalprofile",
            new_name="identidade__active_1e8bd4_idx",
            old_name="identidade__ativo_6ecc2c_idx",
        ),
        migrations.AlterField(
            model_name="professionalprofile",
            name="employee",
            field=models.OneToOneField(
                blank=True,
                db_column="employee_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perfil_professional_rh",
                to="recursos_humanos.employee",
                verbose_name="Funcionário (RH)",
            ),
        ),
        migrations.AlterField(
            model_name="professionalprofile",
            name="user",
            field=models.OneToOneField(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil_professional",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
