# Generated by Django 4.2.29 on 2026-04-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identidade', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='professional_registration',
            field=models.CharField(blank=True, db_column='professional_registration', default='', max_length=120, verbose_name='Registro Profissional'),
        ),
    ]
