# Generated by Django 5.1 on 2026-03-26 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "identidade",
            "0003_rename_identidade__user_id_f784de_idx_identidade__user_id_00da43_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="created_at",
                db_index=True,
                verbose_name="Criado em",
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=128,
                unique=True,
                verbose_name="Token",
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="used",
            field=models.BooleanField(
                db_column="used", db_index=True, default=False, verbose_name="Utilizado"
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_reset_tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
