import { educationResourceKeyFromEndpoint } from "@/lib/education/ui"

type LabelsByField = Record<string, string>

const INTERNAL_FIELDS = new Set([
  "id",
  "created_at",
  "updated_at",
  "custom_id",
  "deleted",
  "deleted_at",
  "version",
  "created_by",
  "updated_by",
  "deleted_by",
  "tenant",
])

const COMMON_LABELS: LabelsByField = {
  first_name: "Nome próprio",
  last_name: "Apelido",
  full_name: "Nome completo",
  display_name: "Nome de apresentação",
  username: "Nome de utilizador",
  password: "Palavra-passe",
  name: "Nome",
  title: "Título",
  description: "Descrição",
  body: "Conteúdo",
  instructions: "Instruções",
  notes: "Observações",
  location: "Localização",
  status: "Estado",
  code: "Código",
  category: "Categoria",
  level: "Nível",
  email: "Email",
  phone: "Telefone",
  phone1: "Telefone 1",
  phone2: "Telefone 2",
  contact: "Contacto",
  contacts: "Contactos",
  address: "Endereço",
  address_street: "Rua",
  address_number: "Número da residência",
  address_complement: "Complemento do endereço",
  address_neighborhood: "Bairro",
  address_city: "Cidade",
  address_province: "Província",
  address_country: "País",
  address_postal_code: "Código postal",
  user: "Utilizador",
  user_name: "Nome do utilizador",
  owner_name: "Nome do proprietário",
  owner_phone: "Telefone do proprietário",
  owner_email: "Email do proprietário",
  tenant: "Instituição",
  patient: "Paciente",
  patient_name: "Nome do paciente",
  patient_code: "Código do paciente",
  medical_record: "Prontuário clínico",
  medical_exam: "Exame médico",
  medical_exam_name: "Nome do exame médico",
  medical_report: "Relatório médico",
  prescription_item: "Item de prescrição",
  prescription: "Prescrição",
  prescription_date: "Data da prescrição",
  prescription_notes: "Observações da prescrição",
  plan: "Plano",
  plan_name: "Nome do plano",
  plan_code: "Código do plano",
  request: "Pedido",
  request_code: "Código do pedido",
  requested_by: "Pedido por",
  requested_at: "Pedido em",
  requested_quantity: "Quantidade pedida",
  lab_request: "Pedido laboratorial",
  lab_notes: "Observações laboratoriais",
  request_item: "Item do pedido",
  lab_request_item: "Item do pedido laboratorial",
  invoice: "Fatura",
  invoice_code: "Código da fatura",
  invoice_status: "Estado da fatura",
  unit: "Unidade",
  unit_number: "Número da unidade",
  unit_price: "Preço unitário",
  unit_cost: "Custo unitário",
  course: "Curso",
  classroom: "Turma",
  student: "Estudante",
  student_name: "Nome do estudante",
  teacher: "Professor",
  teacher_name: "Nome do professor",
  enrollment: "Matrícula",
  author: "Professor autor",
  assignment: "Trabalho",
  assignment_submission: "Submissão de trabalho",
  examination: "Exame",
  examination_attempt: "Tentativa de exame",
  attendance_date: "Data da presença",
  date: "Data",
  start_date: "Data inicial",
  end_date: "Data final",
  start_time: "Hora inicial",
  end_time: "Hora final",
  started_at: "Iniciado em",
  ended_at: "Terminado em",
  finished_at: "Concluído em",
  created_at: "Criado em",
  created_by: "Criado por",
  updated_at: "Atualizado em",
  updated_by: "Atualizado por",
  deleted_at: "Eliminado em",
  deleted_by: "Eliminado por",
  generated_at: "Gerado em",
  issued_at: "Emitido em",
  verified_at: "Verificado em",
  validated_by: "Validado por",
  validation_date: "Data de validação",
  published: "Publicado",
  published_at: "Publicado em",
  file: "Ficheiro",
  filename: "Nome do ficheiro",
  file_type: "Tipo de ficheiro",
  file_size: "Tamanho do ficheiro",
  file_url: "URL do ficheiro",
  external_url: "Link externo",
  attachment_url: "URL do anexo",
  content_type: "Tipo de conteúdo",
  score: "Nota",
  max_score: "Nota máxima",
  weight: "Peso",
  component: "Componente",
  pass_mark: "Nota mínima de aprovação",
  scheduled_for: "Agendado para",
  opens_at: "Abre em",
  closes_at: "Fecha em",
  due_at: "Prazo de entrega",
  submitted_at: "Submetido em",
  graded_at: "Avaliado em",
  graded_by: "Avaliado por",
  teacher_feedback: "Feedback do professor",
  content_text: "Texto da submissão",
  submission_payload: "Conteúdo da resposta",
  attempt_number: "Número da tentativa",
  duration_minutes: "Duração (minutos)",
  max_attempts: "Tentativas máximas",
  max_submissions: "Submissões máximas",
  allow_late_submission: "Permitir submissão fora do prazo",
  allow_multiple_submissions: "Permitir várias submissões",
  work_category: "Categoria do trabalho",
  exam_type: "Tipo de exame",
  test_slot: "Número do teste",
  discipline_final_stage: "Etapa do exame final",
  random_seed: "Semente aleatória",
  question_count: "Número de questões",
  academic_year: "Ano letivo",
  capacity: "Capacidade",
  workload_hours: "Carga horária",
  homeroom_teacher: "Diretor de turma",
  enrolled_on: "Matriculado em",
  closed_on: "Encerrado em",
  student_code: "Código do estudante",
  teacher_code: "Código do professor",
  birth_date: "Data de nascimento",
  guardian_name: "Encarregado de educação",
  specialty: "Especialidade",
  specialty_area: "Área de especialidade",
  professional: "Profissional",
  professional_name: "Nome do profissional",
  profession: "Profissão",
  professional_registration: "Registo profissional",
  doctor: "Médico",
  doctor_name: "Nome do médico",
  clinician_name: "Nome do clínico",
  technician: "Técnico",
  technician_name: "Nome do técnico",
  pharmacist: "Farmacêutico",
  pharmacist_name: "Nome do farmacêutico",
  dentist: "Dentista",
  dentist_name: "Nome do dentista",
  therapist: "Terapeuta",
  therapist_name: "Nome do terapeuta",
  veterinarian: "Veterinário",
  veterinarian_name: "Nome do veterinário",
  radiologist: "Radiologista",
  radiologist_name: "Nome do radiologista",
  surgeon: "Cirurgião",
  surgeon_name: "Nome do cirurgião",
  diagnosis: "Diagnóstico",
  clinical_diagnosis: "Diagnóstico clínico",
  functional_diagnosis: "Diagnóstico funcional",
  anamnesis: "Anamnese",
  allergies: "Alergias",
  chief_complaint: "Queixa principal",
  clinical_notes: "Observações clínicas",
  clinical_summary: "Resumo clínico",
  clinical_indication: "Indicação clínica",
  clinical_question: "Questão clínica",
  result: "Resultado",
  result_value: "Valor do resultado",
  result_summary: "Resumo do resultado",
  reference_range: "Intervalo de referência",
  reference_min: "Referência mínima",
  reference_max: "Referência máxima",
  critical_min: "Mínimo crítico",
  critical_max: "Máximo crítico",
  critical_result: "Resultado crítico",
  sample_type: "Tipo de amostra",
  sample_identifier: "Identificador da amostra",
  collected_by: "Colhido por",
  collected_at: "Colhido em",
  performed_by: "Realizado por",
  performed_at: "Realizado em",
  reported_by: "Reportado por",
  reported_at: "Reportado em",
  released_at: "Libertado em",
  modality: "Modalidade",
  item_type: "Tipo de item",
  scheduled_date: "Data programada",
  requires_attendance: "Requer presença",
  completed_at: "Concluído em",
  linked_examination: "Exame vinculado",
  linked_assignment: "Trabalho vinculado",
  linked_content: "Conteúdo vinculado",
  schedule_item: "Item do cronograma",
  completion_marked: "Marcar como concluído",
  attendance_status_snapshot: "Estado de presença registado",
  time_limit_minutes_snapshot: "Tempo limite registado",
  max_score_snapshot: "Nota máxima registada",
  requires_year_repeat: "Requer repetição de ano",
  maintenance_type: "Tipo de manutenção",
  maintenance_type_display: "Tipo de manutenção",
  incident: "Ocorrência",
  incident_code: "Ocorrência",
  incident_context: "Contexto da ocorrência",
  equipment_name: "Equipamento",
  equipment_serial_number: "Número de série",
  requires_maintenance: "Requer manutenção",
  maintenance_status: "Estado da manutenção",
  maintenance_requested_at: "Pedido de manutenção em",
  maintenance_completed_at: "Manutenção concluída em",
  post_incident_actions: "Ações após ocorrência",
  is_active: "Ativo",
  active: "Ativo",
  protocol: "Protocolo",
  protocol_name: "Nome do protocolo",
  protocol_reference: "Referência do protocolo",
  manufacturer: "Fabricante",
  model: "Modelo",
  serial_number: "Número de série",
  connection_mode: "Modo de comunicação",
  tcp_host: "Host TCP/IP",
  tcp_port: "Porta TCP/IP",
  tcp_timeout_seconds: "Timeout TCP/IP (s)",
  tcp_framing: "Enquadramento TCP/IP",
  encoding: "Codificação",
  auto_consume_results: "Consumir resultados automaticamente",
  supported_exam_types: "Tipos de exame suportados",
  last_seen_at: "Última comunicação",
  config: "Configuração",
  animal: "Animal",
  animal_name: "Nome do animal",
  species: "Espécie",
  breed: "Raça",
  microchip_number: "Número do microchip",
  vaccine: "Vacina",
  vaccine_name: "Nome da vacina",
  vaccination: "Vacinação",
  dose_number: "Número da dose",
  administered_at: "Administrado em",
  administered_by: "Administrado por",
  campaign: "Campanha",
  campaign_name: "Nome da campanha",
  target_region: "Região-alvo",
  target_group: "Grupo-alvo",
  target_population: "População-alvo",
  adverse_event: "Evento adverso",
  adverse_reaction: "Reação adversa",
  severity: "Gravidade",
  investigated_by: "Investigado por",
  investigation_due_at: "Prazo da investigação",
  notification: "Notificação",
  official_code: "Código oficial",
  official_system: "Sistema oficial",
  body_region: "Região do corpo",
  pain_score: "Pontuação da dor",
  pain_before: "Dor antes",
  pain_after: "Dor depois",
  functional_score: "Pontuação funcional",
  mobility_score: "Pontuação de mobilidade",
  motor_score: "Pontuação motora",
  sensory_score: "Pontuação sensorial",
  balance_score: "Pontuação de equilíbrio",
  cognition_score: "Pontuação cognitiva",
  communication_score: "Pontuação de comunicação",
  objectives: "Objetivos",
  goals: "Objetivos",
  treatment_plan: "Plano de tratamento",
  treatment_summary: "Resumo do tratamento",
  intervention_type: "Tipo de intervenção",
  interventions_performed: "Intervenções realizadas",
  session: "Sessão",
  session_count: "Número de sessões",
  planned_sessions: "Sessões planeadas",
  requested_sessions: "Sessões pedidas",
  completed_sessions: "Sessões concluídas",
  frequency_per_week: "Frequência por semana",
  equipment: "Equipamento",
  device: "Dispositivo",
  device_name: "Nome do dispositivo",
  device_type: "Tipo de dispositivo",
  vehicle: "Veículo",
  vehicle_plate: "Matrícula do veículo",
  vehicle_type: "Tipo de veículo",
  license_plate: "Matrícula",
  driver: "Motorista",
  driver_name: "Nome do motorista",
  route: "Rota",
  route_code: "Código da rota",
  trip: "Viagem",
  fuel_type: "Tipo de combustível",
  liters: "Litros",
  odometer_km: "Odómetro (km)",
  current_odometer_km: "Odómetro atual (km)",
  distance_km: "Distância (km)",
  planned_distance_km: "Distância planeada (km)",
  actual_distance_km: "Distância real (km)",
  speed_kmh: "Velocidade (km/h)",
  latitude: "Latitude",
  longitude: "Longitude",
  accuracy_m: "Precisão (m)",
  amount: "Valor",
  total_amount: "Valor total",
  paid_amount: "Valor pago",
  balance_due: "Saldo em dívida",
  payment_method: "Método de pagamento",
  payment_status: "Estado do pagamento",
  coverage_percent: "Percentagem de cobertura",
  annual_interest_rate: "Taxa de juro anual",
  installment_amount: "Valor da parcela",
  installment_count: "Número de parcelas",
  gross_salary: "Salário bruto",
  base_salary: "Salário base",
  nominal_salary: "Salário nominal",
  total_salary: "Salário total",
  blood_pressure: "Pressão arterial",
  blood_pressure_systolic: "Pressão arterial sistólica",
  blood_pressure_diastolic: "Pressão arterial diastólica",
  systolic_bp: "Pressão sistólica",
  diastolic_bp: "Pressão diastólica",
  heart_rate: "Frequência cardíaca",
  heart_rate_bpm: "Frequência cardíaca (bpm)",
  respiratory_rate: "Frequência respiratória",
  respiratory_rate_bpm: "Frequência respiratória (rpm)",
  oxygen_saturation: "Saturação de oxigénio",
  spo2_percent: "SpO2 (%)",
  temperature_c: "Temperatura (°C)",
  glucose_mg_dl: "Glicose (mg/dL)",
  weight_kg: "Peso (kg)",
  volume_ml: "Volume (mL)",
  duration_days: "Duração (dias)",
  duration_ms: "Duração (ms)",
  interval_days: "Intervalo (dias)",
  interval_hours: "Intervalo (horas)",
  turnaround_hours: "Tempo de resposta (horas)",
}

const TOKEN_LABELS: Record<string, string> = {
  abnormal: "anormal",
  absence: "ausência",
  academic: "académico",
  access: "acesso",
  accession: "acesso",
  account: "conta",
  accounting: "contabilístico",
  accuracy: "precisão",
  acknowledged: "reconhecido",
  acquired: "adquirido",
  acquisition: "aquisição",
  action: "ação",
  actions: "ações",
  active: "ativo",
  actual: "real",
  administered: "administrado",
  administrative: "administrativo",
  admission: "admissão",
  adverse: "adverso",
  age: "idade",
  alert: "alerta",
  allocated: "alocado",
  allowed: "permitidos",
  analyst: "analista",
  animal: "animal",
  annual: "anual",
  antibiotic: "antibiótico",
  anticoagulant: "anticoagulante",
  appeal: "recurso",
  application: "candidatura",
  appointment: "consulta",
  approval: "aprovação",
  approved: "aprovado",
  arrival: "chegada",
  assessed: "avaliado",
  assessment: "avaliação",
  assistive: "assistiva",
  attachment: "anexo",
  attempt: "tentativa",
  attendance: "presença",
  attendant: "atendente",
  author: "autor",
  authorization: "autorização",
  available: "disponível",
  balance: "saldo",
  base: "base",
  baseline: "linha de base",
  battery: "bateria",
  billed: "faturado",
  billing: "faturação",
  birth: "nascimento",
  blocked: "bloqueado",
  blood: "sanguíneo",
  body: "corpo",
  booster: "reforço",
  brand: "marca",
  breed: "raça",
  calculated: "calculado",
  call: "chamada",
  campaign: "campanha",
  canceled: "cancelado",
  care: "cuidados",
  cargo: "carga",
  carrier: "transportadora",
  catalog: "catálogo",
  category: "categoria",
  causality: "causalidade",
  chain: "cadeia",
  check: "verificação",
  checklist: "lista de verificação",
  chief: "principal",
  claim: "pedido",
  classroom: "turma",
  cleaning: "limpeza",
  clinical: "clínico",
  clinician: "clínico",
  closed: "encerrado",
  collected: "colhido",
  collection: "colheita",
  color: "cor",
  commercial: "comercial",
  communication: "comunicação",
  compatibility: "compatibilidade",
  completed: "concluído",
  component: "componente",
  concentration: "concentração",
  condition: "condição",
  config: "configuração",
  confirmation: "confirmação",
  confirmed: "confirmado",
  consent: "consentimento",
  consortium: "consórcio",
  consultation: "consulta",
  consumed: "consumido",
  contact: "contacto",
  container: "recipiente",
  content: "conteúdo",
  contract: "contrato",
  contraindication: "contraindicação",
  contrast: "contraste",
  contribution: "contribuição",
  controlled: "controlado",
  coordination: "coordenação",
  cost: "custo",
  counted: "contado",
  course: "curso",
  coverage: "cobertura",
  created: "criado",
  credit: "crédito",
  critical: "crítico",
  culture: "cultura",
  current: "atual",
  customer: "cliente",
  daily: "diário",
  date: "data",
  decision: "decisão",
  default: "predefinido",
  delivery: "entrega",
  destination: "destino",
  device: "dispositivo",
  diagnosis: "diagnóstico",
  diastolic: "diastólica",
  direction: "direção",
  discharge: "alta",
  discharged: "alta",
  disease: "doença",
  dispatch: "expedição",
  dispensed: "dispensado",
  distance: "distância",
  district: "distrito",
  doctor: "médico",
  document: "documento",
  donation: "doação",
  donor: "doador",
  dosage: "dose",
  dose: "dose",
  doses: "doses",
  driver: "motorista",
  due: "prazo",
  duration: "duração",
  employee: "funcionário",
  end: "fim",
  ended: "terminado",
  enrolled: "matriculado",
  enrollment: "matrícula",
  entry: "entrada",
  equipment: "equipamento",
  error: "erro",
  escalation: "escalonamento",
  estimated: "estimado",
  evaluated: "avaliado",
  event: "evento",
  evolution: "evolução",
  exam: "exame",
  examination: "exame",
  expected: "previsto",
  expiration: "validade",
  expired: "expirado",
  external: "externo",
  family: "família",
  fasting: "jejum",
  fee: "taxa",
  file: "ficheiro",
  final: "final",
  financed: "financiado",
  financier: "financiador",
  findings: "achados",
  finished: "concluído",
  first: "primeiro",
  fleet: "frota",
  forwarded: "encaminhado",
  frequency: "frequência",
  fuel: "combustível",
  fulfilled: "cumprido",
  functional: "funcional",
  funding: "financiamento",
  gender: "género",
  generated: "gerado",
  glosa: "glosa",
  glucose: "glicose",
  goals: "objetivos",
  graded: "avaliado",
  gross: "bruto",
  group: "grupo",
  guardian: "encarregado",
  hazardous: "perigoso",
  heart: "cardíaca",
  hire: "contratação",
  holiday: "feriado",
  home: "domicílio",
  hourly: "horário",
  hours: "horas",
  image: "imagem",
  imaging: "imagiologia",
  immunization: "imunização",
  incident: "ocorrência",
  indication: "indicação",
  infection: "infeção",
  infusion: "infusão",
  ingredient: "ingrediente",
  initial: "inicial",
  installment: "parcela",
  insurance: "seguro",
  insurer: "seguradora",
  integration: "integração",
  intensity: "intensidade",
  interacting: "interagente",
  interest: "juros",
  interpretation: "interpretação",
  interval: "intervalo",
  intervention: "intervenção",
  inventory: "inventário",
  investigated: "investigado",
  investigation: "investigação",
  invoice: "fatura",
  issued: "emitido",
  item: "item",
  justified: "justificado",
  lab: "laboratório",
  language: "idioma",
  last: "último",
  license: "licença",
  limitations: "limitações",
  linked: "vinculado",
  location: "localização",
  lot: "lote",
  maintenance: "manutenção",
  manager: "gestor",
  manual: "manual",
  manufacturer: "fabricante",
  material: "material",
  maximum: "máximo",
  max: "máximo",
  measured: "medido",
  measurement: "medição",
  medical: "médico",
  medication: "medicação",
  message: "mensagem",
  metadata: "metadados",
  method: "método",
  minimum: "mínimo",
  min: "mínimo",
  mobility: "mobilidade",
  modality: "modalidade",
  model: "modelo",
  month: "mês",
  monthly: "mensal",
  motor: "motor",
  moved: "movido",
  movement: "movimento",
  multiplier: "multiplicador",
  name: "nome",
  next: "próximo",
  nominal: "nominal",
  notification: "notificação",
  number: "número",
  numeric: "numérico",
  objective: "objetivo",
  objectives: "objetivos",
  observation: "observação",
  odometer: "odómetro",
  official: "oficial",
  opened: "aberto",
  operation: "operação",
  optimization: "otimização",
  order: "pedido",
  ordered: "pedido",
  organism: "organismo",
  origin: "origem",
  outcome: "resultado",
  owner: "proprietário",
  oxygen: "oxigénio",
  paid: "pago",
  pain: "dor",
  parent: "superior",
  passenger: "passageiro",
  patient: "paciente",
  payer: "pagador",
  payment: "pagamento",
  pending: "pendente",
  performed: "realizado",
  pharmacist: "farmacêutico",
  pharmacy: "farmácia",
  phone: "telefone",
  photo: "foto",
  planned: "planeado",
  position: "posição",
  posted: "lançado",
  precautions: "precauções",
  preferred: "preferencial",
  pregnant: "grávida",
  preliminary: "preliminar",
  preparation: "preparação",
  prepared: "preparado",
  prescription: "prescrição",
  pressure: "pressão",
  price: "preço",
  primary: "principal",
  priority: "prioridade",
  procedure: "procedimento",
  processed: "processado",
  product: "produto",
  profession: "profissão",
  professional: "profissional",
  program: "programa",
  progress: "progresso",
  prosthesis: "prótese",
  protocol: "protocolo",
  provider: "prestador",
  published: "publicado",
  pulse: "pulso",
  purchase: "compra",
  purpose: "finalidade",
  quantity: "quantidade",
  question: "questão",
  queue: "fila",
  quota: "quota",
  radiologist: "radiologista",
  range: "intervalo",
  reaction: "reação",
  reading: "leitura",
  reason: "motivo",
  receipt: "recebimento",
  received: "recebido",
  recipient: "destinatário",
  recommendation: "recomendação",
  recommendations: "recomendações",
  record: "registo",
  recorded: "registado",
  reference: "referência",
  referral: "encaminhamento",
  registered: "registado",
  reimbursed: "reembolsado",
  rejection: "rejeição",
  relationship: "relação",
  released: "libertado",
  replacement: "substituição",
  report: "relatório",
  reported: "reportado",
  request: "pedido",
  requested: "pedido",
  requesting: "solicitante",
  requires: "requer",
  reservation: "reserva",
  reserved: "reservado",
  resolved: "resolvido",
  resource: "recurso",
  response: "resposta",
  responsible: "responsável",
  result: "resultado",
  review: "revisão",
  reviewed: "revisto",
  reviewer: "revisor",
  risk: "risco",
  role: "função",
  room: "sala",
  route: "rota",
  salary: "salário",
  sale: "venda",
  sample: "amostra",
  schedule: "cronograma",
  scheduled: "agendado",
  score: "pontuação",
  screening: "triagem",
  sector: "sector",
  selected: "selecionado",
  sensory: "sensorial",
  sent: "enviado",
  serial: "série",
  series: "série",
  serious: "grave",
  service: "serviço",
  session: "sessão",
  settings: "definições",
  severity: "gravidade",
  sex: "sexo",
  shipment: "expedição",
  shipped: "expedido",
  signed: "assinado",
  source: "origem",
  specialist: "especialista",
  specialty: "especialidade",
  species: "espécie",
  speed: "velocidade",
  sponsor: "patrocinador",
  stability: "estabilidade",
  start: "início",
  started: "iniciado",
  station: "estação",
  status: "estado",
  stop: "paragem",
  storage: "armazenamento",
  student: "estudante",
  study: "estudo",
  submitted: "submetido",
  supplier: "fornecedor",
  support: "suporte",
  surgeon: "cirurgião",
  symptoms: "sintomas",
  system: "sistema",
  target: "meta",
  teacher: "professor",
  technician: "técnico",
  technique: "técnica",
  temperature: "temperatura",
  template: "modelo",
  therapist: "terapeuta",
  therapy: "terapia",
  time: "tempo",
  title: "título",
  tooth: "dente",
  total: "total",
  tracking: "rastreio",
  transaction: "transação",
  transfer: "transferência",
  treatment: "tratamento",
  triage: "triagem",
  trip: "viagem",
  tuition: "propina",
  type: "tipo",
  unit: "unidade",
  updated: "atualizado",
  user: "utilizador",
  vaccine: "vacina",
  validated: "validado",
  validation: "validação",
  value: "valor",
  vehicle: "veículo",
  verified: "verificado",
  version: "versão",
  veterinarian: "veterinário",
  volume: "volume",
  ward: "enfermaria",
  warehouse: "armazém",
  weight: "peso",
  witness: "testemunha",
  workload: "carga horária",
  year: "ano",
}

const ENTITY_CONTEXT_LABELS: Record<string, string> = {
  account: "da conta",
  animal: "do animal",
  appointment: "da consulta",
  campaign: "da campanha",
  category: "da categoria",
  classroom: "da turma",
  clinician: "do clínico",
  consultation: "da consulta",
  course: "do curso",
  customer: "do cliente",
  device: "do dispositivo",
  doctor: "do médico",
  driver: "do motorista",
  employee: "do funcionário",
  equipment: "do equipamento",
  exam: "do exame",
  invoice: "da fatura",
  item: "do item",
  lab_request: "do pedido laboratorial",
  lot: "do lote",
  medical_exam: "do exame médico",
  medical_record: "do prontuário clínico",
  owner: "do proprietário",
  patient: "do paciente",
  plan: "do plano",
  prescription: "da prescrição",
  prescription_item: "do item de prescrição",
  procedure: "do procedimento",
  professional: "do profissional",
  program: "do programa",
  request: "do pedido",
  result: "do resultado",
  route: "da rota",
  sector: "do sector",
  session: "da sessão",
  student: "do estudante",
  teacher: "do professor",
  therapist: "do terapeuta",
  unit: "da unidade",
  user: "do utilizador",
  vaccine: "da vacina",
  vehicle: "do veículo",
  veterinarian: "do veterinário",
  warehouse: "do armazém",
}

const DESCRIPTIVE_SUFFIX_LABELS: Record<string, string> = {
  name: "Nome",
  code: "Código",
  label: "Rótulo",
  status: "Estado",
  type: "Tipo",
  number: "Número",
  amount: "Valor",
  percent: "Percentagem",
  percentage: "Percentagem",
  quantity: "Quantidade",
  count: "Número",
  price: "Preço",
  cost: "Custo",
  value: "Valor",
  score: "Pontuação",
  date: "Data",
  reason: "Motivo",
  notes: "Observações",
  summary: "Resumo",
  description: "Descrição",
  reference: "Referência",
  document: "Documento",
  response: "Resposta",
  outcome: "Resultado",
  result: "Resultado",
  method: "Método",
  priority: "Prioridade",
  frequency: "Frequência",
  duration: "Duração",
}

const UNIT_SUFFIX_LABELS: Record<string, string> = {
  bpm: "bpm",
  c: "°C",
  cm: "cm",
  days: "dias",
  degrees: "graus",
  hours: "horas",
  kg: "kg",
  km: "km",
  kmh: "km/h",
  l: "L",
  min: "min",
  minutes: "minutos",
  ml: "mL",
  ms: "ms",
  percent: "%",
  percentage: "%",
  week: "semana",
  weeks: "semanas",
}

const ACRONYM_LABELS: Record<string, string> = {
  aefi: "AEFI",
  bp: "PA",
  ct: "CT",
  dicom: "DICOM",
  ecg: "ECG",
  eeg: "EEG",
  hiv: "HIV",
  id: "ID",
  ip: "IP",
  iva: "IVA",
  json: "JSON",
  mapa: "MAPA",
  mri: "RM",
  nib: "NIB",
  nuit: "NUIT",
  pacs: "PACS",
  pdf: "PDF",
  pk: "PK",
  rm: "RM",
  rx: "RX",
  sku: "SKU",
  spo2: "SpO2",
  tpn: "TPN",
  uri: "URI",
  url: "URL",
  vat: "IVA",
  vin: "VIN",
}

const GENERIC_FIELD_NAMES = new Set([
  "name",
  "title",
  "code",
  "status",
  "type",
  "number",
  "date",
  "description",
  "notes",
  "value",
])

const EDUCATION_LABELS: Record<string, LabelsByField> = {
  student: {
    status: "Estado do estudante",
    notes: "Observações do estudante",
  },
  teacher: {
    status: "Estado do professor",
  },
  course: {
    name: "Nome do curso",
    code: "Código do curso",
    description: "Descrição do curso",
    workload_hours: "Carga horária",
    status: "Estado do curso",
  },
  classroom: {
    name: "Nome da turma",
    course: "Curso",
    capacity: "Capacidade da turma",
  },
  enrollment: {
    status: "Estado da matrícula",
  },
  attendance: {
    status: "Estado da presença",
  },
  grade: {
    component: "Componente de avaliação",
    score: "Nota obtida",
  },
  examination: {
    title: "Título do exame",
    status: "Estado do exame",
  },
  random_test: {
    title: "Título do teste",
    status: "Estado do teste",
  },
  assignment: {
    title: "Título do trabalho",
    status: "Estado do trabalho",
  },
  submission: {
    status: "Estado da submissão",
  },
  exam_attempt: {
    status: "Estado da tentativa",
  },
  content: {
    title: "Título do conteúdo",
    body: "Conteúdo de aprendizagem",
  },
  bibliography: {
    title: "Título da referência",
    body: "Resumo e orientação de estudo",
  },
  thematic_map: {
    title: "Título do mapa temático",
    body: "Estrutura temática",
  },
  discipline_schedule: {
    title: "Título do item",
    status: "Estado do item",
  },
  schedule_progress: {
    status: "Estado do progresso",
  },
  skill: {
    name: "Nome da competência",
    code: "Código da competência",
    description: "Descrição da competência",
    status: "Estado da competência",
  },
}

const BLOODBANK_LABELS: Record<string, LabelsByField> = {
  storage: {
    name: "Nome",
    location: "Localização",
    capacity_units: "Capacidade (unidades)",
    temperature_min_c: "Temperatura mínima (°C)",
    temperature_max_c: "Temperatura máxima (°C)",
    is_active: "Ativo",
    last_validation_at: "Última validação",
    notes: "Observações",
  },
  storage_maintenance: {
    storage: "Armazenamento",
    maintenance_type: "Tipo de manutenção",
    status: "Estado",
    scheduled_at: "Agendada para",
    performed_at: "Executada em",
    next_due_at: "Próxima manutenção",
    technician_name: "Técnico responsável",
    findings: "Achados",
    actions_taken: "Ações executadas",
    notes: "Observações",
  },
  donation: {
    bag_identifier: "Bolsa (identificador)",
    donor: "Doador",
    donor_role: "Tipo de doador",
    donation_type: "Tipo de doação",
    blood_type: "Tipo sanguíneo",
    status: "Estado",
    screening_status: "Triagem",
    collected_at: "Coleta",
    processed_at: "Processamento",
    volume_ml: "Volume (mL)",
    notes: "Observações",
  },
  unit: {
    unit_number: "Número da unidade",
    component_type: "Componente",
    status: "Estado",
    donation: "Doação",
    storage: "Armazenamento",
    reserved_for: "Reservada para",
    collected_at: "Coleta",
    expires_at: "Validade",
    notes: "Observações",
  },
  transfusion: {
    recipient: "Paciente",
    blood_unit: "Unidade",
    status: "Estado",
    requested_at: "Solicitada em",
    started_at: "Iniciada em",
    finished_at: "Concluída em",
    indication: "Indicação",
    notes: "Observações",
  },
  stock_movement: {
    movement_type: "Tipo de movimento",
    unit: "Unidade",
    source_storage: "Origem",
    destination_storage: "Destino",
    moved_at: "Movimentado em",
    reason: "Motivo",
    notes: "Observações",
  },
}

const WAREHOUSE_COMMON_LABELS: LabelsByField = {
  name: "Nome",
  code: "Código",
  status: "Estado",
  notes: "Observações",
  address: "Endereço",
  warehouse: "Armazém",
  warehouse_type: "Tipo de armazém",
  warehouse_label: "Armazém",
  parent: "Localização superior",
  location: "Localização",
  location_type: "Tipo de localização",
  location_code: "Código da localização",
  source_location: "Localização de origem",
  destination_location: "Localização de destino",
  default_location: "Localização padrão",
  preferred_location: "Localização preferencial",
  barcode: "Código de barras",
  category: "Categoria",
  category_label: "Categoria",
  pharmacy_product: "Produto de farmácia",
  item: "Item",
  item_type: "Tipo de item",
  item_sku: "SKU do item",
  sku: "SKU",
  unit_of_measure: "Unidade de medida",
  reorder_point: "Ponto de reposição",
  reorder_quantity: "Quantidade de reposição",
  external_reference: "Referência externa",
  current_stock: "Estoque atual",
  lot: "Lote",
  lot_number: "Número do lote",
  expiration_date: "Data de validade",
  received_at: "Recebido em",
  unit_cost: "Custo unitário",
  quantity: "Quantidade",
  reserved_quantity: "Quantidade reservada",
  available_quantity: "Quantidade disponível",
  ordered_quantity: "Quantidade pedida",
  received_quantity: "Quantidade recebida",
  pending_quantity: "Quantidade pendente",
  pending_reservation_quantity: "Quantidade pendente de reserva",
  pending_shipment_quantity: "Quantidade pendente de expedição",
  shipped_quantity: "Quantidade expedida",
  recommended_quantity: "Quantidade recomendada",
  estimated_unit_cost: "Custo unitário estimado",
  counted_quantity: "Quantidade contada",
  system_quantity: "Quantidade no sistema",
  variance: "Diferença",
  movement_type: "Tipo de movimento",
  reference_document: "Documento de referência",
  reason: "Motivo",
  posted_at: "Lançado em",
  order_number: "Número do pedido",
  supplier_name: "Fornecedor",
  supplier_document: "Documento do fornecedor",
  ordered_at: "Pedido em",
  expected_at: "Previsão de recebimento",
  purchase_order: "Pedido de compra",
  purchase_order_line: "Linha do pedido de compra",
  receipt: "Recebimento",
  receipt_number: "Número do recebimento",
  plan: "Plano de reposição",
  plan_number: "Número do plano",
  generated_at: "Gerado em",
  purchase_order_number: "Número do pedido de compra",
  customer_name: "Cliente",
  customer_document: "Documento do cliente",
  customer_reference: "Referência do cliente",
  requested_ship_date: "Data solicitada de expedição",
  priority: "Prioridade",
  sales_order: "Pedido de venda",
  sales_order_line: "Linha do pedido de venda",
  reservation: "Reserva",
  pick_list: "Lista de separação",
  pick_number: "Número da separação",
  quantity_to_pick: "Quantidade a separar",
  quantity_picked: "Quantidade separada",
  shipment: "Expedição",
  shipment_number: "Número da expedição",
  carrier_name: "Transportadora",
  tracking_number: "Código de rastreio",
  transfer: "Transferência",
  transfer_number: "Número da transferência",
  cycle_count: "Inventário cíclico",
  count_number: "Número do inventário",
  counted_at: "Contado em",
}

const WAREHOUSE_LABELS: Record<string, LabelsByField> = {
  warehouse: {
    name: "Nome do armazém",
    code: "Código do armazém",
    status: "Estado do armazém",
  },
  storage_location: {
    name: "Nome da localização",
    code: "Código da localização",
    status: "Estado da localização",
  },
  item_category: {
    name: "Nome da categoria",
    code: "Código da categoria",
    status: "Estado da categoria",
  },
  item: {
    name: "Nome do item",
    status: "Estado do item",
  },
  lot: {
    status: "Estado do lote",
  },
  stock_movement: {
    name: "Descrição do movimento",
    status: "Estado do movimento",
  },
  purchase_order: {
    name: "Nome do pedido de compra",
    status: "Estado do pedido",
  },
  goods_receipt: {
    name: "Nome do recebimento",
  },
  replenishment_plan: {
    name: "Nome do plano de reposição",
  },
  sales_order: {
    name: "Nome do pedido de venda",
    status: "Estado do pedido",
  },
  stock_reservation: {
    status: "Estado da reserva",
  },
  pick_list: {
    name: "Nome da lista de separação",
  },
  shipment: {
    name: "Nome da expedição",
  },
  stock_transfer: {
    name: "Nome da transferência",
  },
  cycle_count: {
    name: "Nome do inventário",
  },
}

function normalizeEndpoint(endpoint?: string): string {
  const raw = String(endpoint || "")
  return raw.split("?")[0].split("#")[0]
}

export function bloodbankResourceKeyFromEndpoint(endpoint?: string): string | null {
  const e = normalizeEndpoint(endpoint)
  // Matches both collection and detail endpoints:
  // - /bloodbank/storage/
  // - /bloodbank/storage/123/
  const m = e.match(/\/bloodbank\/([^/]+)(?:\/|$)/)
  return m?.[1] || null
}

export function warehouseResourceKeyFromEndpoint(endpoint?: string): string | null {
  const e = normalizeEndpoint(endpoint)
  const m = e.match(/\/warehouse\/([^/]+)(?:\/|$)/)
  return m?.[1] || null
}

export function isInternalField(name: string): boolean {
  return INTERNAL_FIELDS.has(String(name || ""))
}

function humanizeSnakeCase(name: string): string {
  const s = String(name || "").trim()
  if (!s) return ""
  return translateFieldName(s) || titleCaseLabel(s.replace(/_/g, " "))
}

function normalizeFieldKey(value: string): string {
  return String(value || "")
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^A-Za-z0-9À-ÿ]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase()
}

function titleCaseLabel(value: string): string {
  const text = String(value || "").trim().replace(/\s+/g, " ")
  if (!text) return ""
  return text.charAt(0).toLocaleUpperCase("pt") + text.slice(1)
}

function lowerContext(value: string): string {
  const text = String(value || "").trim()
  if (!text) return ""
  return text.charAt(0).toLocaleLowerCase("pt") + text.slice(1)
}

function tokenLabel(token: string): string {
  const key = normalizeFieldKey(token)
  if (!key) return ""
  if (ACRONYM_LABELS[key]) return ACRONYM_LABELS[key]
  if (TOKEN_LABELS[key]) return TOKEN_LABELS[key]
  return key
}

function plainTranslatedLabel(key: string): string {
  const normalized = normalizeFieldKey(key)
  if (!normalized) return ""
  if (COMMON_LABELS[normalized]) return COMMON_LABELS[normalized]
  const tokens = normalized.split("_").filter(Boolean)
  return titleCaseLabel(tokens.map(tokenLabel).filter(Boolean).join(" "))
}

function entityContextLabel(key: string): string {
  const normalized = normalizeFieldKey(key)
  if (!normalized) return ""
  if (ENTITY_CONTEXT_LABELS[normalized]) return ENTITY_CONTEXT_LABELS[normalized]
  const plain = plainTranslatedLabel(normalized)
  return plain ? `de ${lowerContext(plain)}` : ""
}

function translateTimestampField(key: string, suffix: "at" | "on"): string {
  const base = key.replace(new RegExp(`_${suffix}$`), "")
  const directActionLabels: Record<string, string> = {
    acknowledged: "Reconhecido",
    administered: "Administrado",
    admitted: "Admitido",
    allocated: "Alocado",
    arrived: "Chegado",
    assessed: "Avaliado",
    awarded: "Atribuído",
    billed: "Faturado",
    blocked: "Bloqueado",
    called: "Chamado",
    canceled: "Cancelado",
    checked: "Verificado",
    closed: "Encerrado",
    collected: "Colhido",
    completed: "Concluído",
    confirmed: "Confirmado",
    consumed: "Consumido",
    counted: "Contado",
    created: "Criado",
    deleted: "Eliminado",
    delivered: "Entregue",
    discharged: "Alta dada",
    dispensed: "Dispensado",
    ended: "Terminado",
    evaluated: "Avaliado",
    executed: "Executado",
    finished: "Concluído",
    fulfilled: "Cumprido",
    generated: "Gerado",
    graded: "Avaliado",
    issued: "Emitido",
    measured: "Medido",
    moved: "Movido",
    opened: "Aberto",
    optimized: "Otimizado",
    ordered: "Pedido",
    paid: "Pago",
    paired: "Emparelhado",
    performed: "Realizado",
    posted: "Lançado",
    prepared: "Preparado",
    processed: "Processado",
    published: "Publicado",
    received: "Recebido",
    recorded: "Registado",
    released: "Libertado",
    reported: "Reportado",
    requested: "Pedido",
    reserved: "Reservado",
    resolved: "Resolvido",
    reviewed: "Revisto",
    revoked: "Revogado",
    scheduled: "Agendado",
    sent: "Enviado",
    shipped: "Expedido",
    signed: "Assinado",
    started: "Iniciado",
    submitted: "Submetido",
    triggered: "Disparado",
    updated: "Atualizado",
    validated: "Validado",
    verified: "Verificado",
  }
  if (directActionLabels[base]) return `${directActionLabels[base]} em`
  return `Data/hora ${entityContextLabel(base)}`
}

function translateFieldName(rawName: string): string {
  const name = normalizeFieldKey(rawName)
  if (!name) return ""

  if (COMMON_LABELS[name]) return COMMON_LABELS[name]

  const relationLabelMatch = name.match(/^(.+)__(name|code|label|status)$/)
  if (relationLabelMatch) {
    const [, base, suffix] = relationLabelMatch
    const suffixLabel = DESCRIPTIVE_SUFFIX_LABELS[suffix] || plainTranslatedLabel(suffix)
    return titleCaseLabel(`${suffixLabel} ${entityContextLabel(base)}`)
  }

  if (name.endsWith("_id")) {
    return translateFieldName(name.slice(0, -3))
  }

  if (name.endsWith("_at")) {
    return translateTimestampField(name, "at")
  }

  if (name.endsWith("_on")) {
    return translateTimestampField(name, "on")
  }

  if (name.endsWith("_by")) {
    const base = name.slice(0, -3)
    return `${plainTranslatedLabel(base)} por`
  }

  const tokens = name.split("_").filter(Boolean)
  const lastToken = tokens[tokens.length - 1]
  if (tokens.length > 1 && UNIT_SUFFIX_LABELS[lastToken]) {
    const base = tokens.slice(0, -1).join("_")
    return `${plainTranslatedLabel(base)} (${UNIT_SUFFIX_LABELS[lastToken]})`
  }

  if (tokens.length > 1 && DESCRIPTIVE_SUFFIX_LABELS[lastToken]) {
    const base = tokens.slice(0, -1).join("_")
    return titleCaseLabel(`${DESCRIPTIVE_SUFFIX_LABELS[lastToken]} ${entityContextLabel(base)}`)
  }

  if (tokens.length > 1 && tokens[0] === "is") {
    return `${plainTranslatedLabel(tokens.slice(1).join("_"))}?`
  }

  if (tokens.length > 1 && tokens[0] === "has") {
    return `Tem ${lowerContext(plainTranslatedLabel(tokens.slice(1).join("_")))}?`
  }

  return plainTranslatedLabel(name)
}

function translateTitle(title: string): string {
  const clean = String(title || "").trim()
  if (!clean) return ""
  if (/[áàãâéêíóôõúç]/i.test(clean)) return clean
  const key = normalizeFieldKey(clean)
  if (!key) return clean
  return translateFieldName(key)
}

export function fieldLabel(opts: {
  endpoint?: string
  name: string
  title?: string
}): string {
  const name = String(opts.name || "")
  const title = typeof opts.title === "string" ? opts.title.trim() : ""
  const normalizedName = normalizeFieldKey(name)

  const resourceKey = bloodbankResourceKeyFromEndpoint(opts.endpoint)
  if (resourceKey && BLOODBANK_LABELS[resourceKey]?.[name]) {
    return BLOODBANK_LABELS[resourceKey][name]
  }

  const warehouseKey = warehouseResourceKeyFromEndpoint(opts.endpoint)
  if (warehouseKey) {
    const specific = WAREHOUSE_LABELS[warehouseKey]?.[name]
    if (specific) return specific
    if (WAREHOUSE_COMMON_LABELS[name]) return WAREHOUSE_COMMON_LABELS[name]
  }

  const educationKey = educationResourceKeyFromEndpoint(opts.endpoint)
  if (educationKey && EDUCATION_LABELS[educationKey]?.[name]) {
    return EDUCATION_LABELS[educationKey][name]
  }

  const translatedTitle = translateTitle(title)
  if (translatedTitle && GENERIC_FIELD_NAMES.has(normalizedName)) {
    return translatedTitle
  }

  if (COMMON_LABELS[normalizedName]) return COMMON_LABELS[normalizedName]

  const translatedName = translateFieldName(name)
  if (translatedName) return translatedName

  if (translatedTitle && title.toLowerCase() !== name.toLowerCase()) return translatedTitle

  return humanizeSnakeCase(name)
}
