# Generated by Django 6.0.1 on 2026-03-01 20:33

import django.db.models.deletion
import infrastrutura.orm.fields.dinheiro_field
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faturamento", "0001_initial"),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referencia_externa", models.CharField(max_length=120, unique=True)),
                ("gateway", models.CharField(max_length=50)),
                ("status", models.CharField(default="pendente", max_length=30)),
                ("resposta_gateway", models.JSONField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_custom",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="ordem",
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                ("ordem", models.PositiveIntegerField(db_index=True, default=1)),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "valor",
                    infrastrutura.orm.fields.dinheiro_field.DinheiroField(
                        decimal_places=2, max_digits=12
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("DIN", "Dinheiro"),
                            ("CAR", "Cartão"),
                            ("TRF", "Transferência"),
                            ("MOB", "Mobile Money"),
                            ("POS", "POS"),
                            ("CHQ", "Cheque"),
                            ("OUT", "Outro"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendente"),
                            ("CON", "Confirmado"),
                            ("FAL", "Falhou"),
                            ("EST", "Estornado"),
                            ("CAN", "Cancelado"),
                        ],
                        db_index=True,
                        default="PEN",
                        max_length=3,
                    ),
                ),
                (
                    "referencia_externa",
                    models.CharField(
                        blank=True,
                        help_text="Referência externa (transação, autorização, etc).",
                        max_length=120,
                    ),
                ),
                ("pago_em", models.DateTimeField(blank=True, null=True)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deletado_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagamentos",
                        to="faturamento.fatura",
                    ),
                ),
                (
                    "inquilino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.inquilino",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Recibo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50, unique=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "fatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recibos",
                        to="faturamento.fatura",
                    ),
                ),
                (
                    "pagamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recibos",
                        to="pagamentos.pagamento",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Reconciliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirmado", models.BooleanField(default=False)),
                ("data_confirmacao", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "transacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliacoes",
                        to="pagamentos.transacao",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="pagamento",
            index=models.Index(
                fields=["fatura"], name="pagamentos__fatura__72b132_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pagamento",
            index=models.Index(fields=["status"], name="pagamentos__status_fe65ad_idx"),
        ),
        migrations.AddIndex(
            model_name="pagamento",
            index=models.Index(
                fields=["criado_em"], name="pagamentos__criado__c0be10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recibo",
            index=models.Index(fields=["numero"], name="pagamentos__numero_ce4052_idx"),
        ),
    ]
