# Generated by Django 4.2.16 on 2026-03-15 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import infrastrutura.orm.fields.dinheiro_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faturamento', '0001_initial'),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('valor', infrastrutura.orm.fields.dinheiro_field.DinheiroField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('DIN', 'Dinheiro'), ('CAR', 'Cartão'), ('TRF', 'Transferência'), ('MOB', 'Mobile Money'), ('POS', 'POS'), ('CHQ', 'Cheque'), ('OUT', 'Outro')], max_length=4)),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('CON', 'Confirmado'), ('FAL', 'Falhou'), ('EST', 'Estornado'), ('CAN', 'Cancelado')], db_index=True, default='PEN', max_length=3)),
                ('referencia_externa', models.CharField(blank=True, help_text='Referência externa (transação, autorização, etc).', max_length=120)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='faturamento.fatura')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_externa', models.CharField(db_index=True, max_length=120)),
                ('gateway', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(db_index=True, max_length=40)),
                ('resposta_gateway', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['referencia_externa'], name='pagamentos__referen_ace7b7_idx'), models.Index(fields=['gateway', 'status'], name='pagamentos__gateway_f9701c_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('tipo_evento', models.CharField(choices=[('CRIADO', 'Criado'), ('CONFIRMADO', 'Confirmado'), ('FALHA', 'Falha'), ('ESTORNADO', 'Estornado'), ('CANCELADO', 'Cancelado')], db_index=True, max_length=15)),
                ('valor', infrastrutura.orm.fields.dinheiro_field.DinheiroField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('referencia_externa', models.CharField(blank=True, max_length=120)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='pagamentos.pagamento')),
            ],
            options={
                'verbose_name': 'Histórico de Pagamento',
                'verbose_name_plural': 'Histórico de Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(db_index=True, default=False)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliacao', to='pagamentos.transacao')),
            ],
            options={
                'verbose_name': 'Reconciliação',
                'verbose_name_plural': 'Reconciliações',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['confirmado'], name='pagamentos__confirm_162048_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=60)),
                ('valor', infrastrutura.orm.fields.dinheiro_field.DinheiroField(decimal_places=2, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='faturamento.fatura')),
                ('pagamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recibo', to='pagamentos.pagamento')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['fatura', 'criado_em'], name='pagamentos__fatura__848b6f_idx'), models.Index(fields=['numero'], name='pagamentos__numero_ce4052_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['fatura'], name='pagamentos__fatura__72b132_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['status'], name='pagamentos__status_fe65ad_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['criado_em'], name='pagamentos__criado__c0be10_idx'),
        ),
        migrations.AddIndex(
            model_name='historicopagamento',
            index=models.Index(fields=['pagamento'], name='pagamentos__pagamen_20ed69_idx'),
        ),
        migrations.AddIndex(
            model_name='historicopagamento',
            index=models.Index(fields=['tipo_evento'], name='pagamentos__tipo_ev_e0511e_idx'),
        ),
        migrations.AddIndex(
            model_name='historicopagamento',
            index=models.Index(fields=['criado_em'], name='pagamentos__criado__a317e2_idx'),
        ),
    ]
