# Generated by Django 6.0.1 on 2026-02-28 20:58

import django.db.models.deletion
import django.utils.timezone
import infrastrutura.orm.fields.dinheiro_field
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faturamento", "0002_initial"),
        ("inquilinos", "0003_alter_planoassinatura_options_and_more"),
        ("pagamentos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pagamento",
            name="pagamentos__confirm_a1430b_idx",
        ),
        migrations.AddField(
            model_name="pagamento",
            name="ativo",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="atualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado_por",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado_por",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="deletado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="deletado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="id_custom",
            field=models.CharField(
                db_index=True, default=0, editable=False, max_length=30, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pagamento",
            name="inquilino",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.inquilino",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pagamento",
            name="nome",
            field=models.CharField(
                db_index=True, default=django.utils.timezone.now, max_length=120
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pagamento",
            name="ordem",
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="pago_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="referencia_externa",
            field=models.CharField(
                blank=True,
                help_text="Referência externa (transação, autorização, etc).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("PEN", "Pendente"),
                    ("CON", "Confirmado"),
                    ("FAL", "Falhou"),
                    ("EST", "Estornado"),
                    ("CAN", "Cancelado"),
                ],
                db_index=True,
                default="PEN",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="metodo",
            field=models.CharField(
                choices=[
                    ("DIN", "Dinheiro"),
                    ("CAR", "Cartão"),
                    ("TRF", "Transferência"),
                    ("MOB", "Mobile Money"),
                    ("POS", "POS"),
                    ("CHQ", "Cheque"),
                    ("OUT", "Outro"),
                ],
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="valor",
            field=infrastrutura.orm.fields.dinheiro_field.DinheiroField(
                decimal_places=2, max_digits=12
            ),
        ),
        migrations.AddIndex(
            model_name="pagamento",
            index=models.Index(
                fields=["fatura"], name="pagamentos__fatura__72b132_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pagamento",
            index=models.Index(fields=["status"], name="pagamentos__status_fe65ad_idx"),
        ),
        migrations.AddIndex(
            model_name="pagamento",
            index=models.Index(
                fields=["criado_em"], name="pagamentos__criado__c0be10_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="pagamento",
            name="confirmado",
        ),
    ]
