# Generated by Django 6.0.1 on 2026-02-28 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamentos", "0002_remove_pagamento_pagamentos__confirm_a1430b_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="deletado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deletado_por",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="id_custom",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=30,
                unique=True,
                verbose_name="ordem",
            ),
        ),
    ]
