# Generated by Django 4.2.16 on 2026-03-28 04:22

from decimal import Decimal

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('type', models.CharField(choices=[('ATI', 'Ativo'), ('PAS', 'Passivo'), ('REC', 'Receita'), ('DES', 'Despesa'), ('PAT', 'Patrimônio')], db_column='type', db_index=True, default='DES', max_length=3, verbose_name='Tipo de account')),
            ],
            options={
                'verbose_name': 'Conta contábil',
                'verbose_name_plural': 'Contas contábeis',
                'db_table': 'contabilidade_conta',
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(db_column='current_balance', decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Saldo atual')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_index=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Saldo de Conta',
                'verbose_name_plural': 'Saldos de Conta',
                'db_table': 'contabilidade_saldoconta',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('external_reference', models.CharField(blank=True, db_column='external_reference', db_index=True, default='', max_length=120, verbose_name='Referência externa')),
                ('accounting_value', models.DecimalField(db_column='accounting_value', decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor contábil')),
                ('received_amount', models.DecimalField(db_column='received_amount', decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor recebido')),
                ('discrepancy', models.DecimalField(db_column='discrepancy', decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Diferença')),
                ('reconciled', models.BooleanField(db_column='reconciled', db_index=True, default=False, verbose_name='Conciliado')),
            ],
            options={
                'verbose_name': 'Conciliação financeira',
                'verbose_name_plural': 'Conciliações financeiras',
                'db_table': 'contabilidade_conciliacaofinanceira',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('external_reference', models.CharField(db_column='external_reference', db_index=True, max_length=120, verbose_name='Referência externa')),
                ('idempotency_key', models.CharField(blank=True, max_length=150, null=True, verbose_name='Chave de idempotência')),
                ('accounting_date', models.DateField(db_column='accounting_date', db_index=True, verbose_name='Data contábil')),
                ('description', models.CharField(db_column='description', max_length=255, verbose_name='Descrição')),
                ('reversed', models.BooleanField(db_column='reversed', db_index=True, default=False, verbose_name='Revertido')),
                ('reversal_reason', models.TextField(blank=True, db_column='reversal_reason', null=True, verbose_name='Motivo da reversão')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='Criado em')),
                ('previous_hash', models.CharField(blank=True, db_column='previous_hash', db_index=True, max_length=64, null=True, verbose_name='Hash anterior')),
                ('current_hash', models.CharField(blank=True, db_column='current_hash', max_length=64, null=True, unique=True, verbose_name='Hash atual')),
            ],
            options={
                'verbose_name': 'Lançamento contábil',
                'verbose_name_plural': 'Lançamentos contábeis',
                'db_table': 'contabilidade_ledgerentry',
            },
        ),
        migrations.CreateModel(
            name='LedgerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('value', models.DecimalField(db_column='value', decimal_places=2, max_digits=18, verbose_name='Valor')),
                ('nature', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], db_column='nature', max_length=1, verbose_name='Natureza')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Linha contábil',
                'verbose_name_plural': 'Linhas contábeis',
                'db_table': 'contabilidade_ledgerline',
            },
        ),
        migrations.CreateModel(
            name='LegacyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('description', models.TextField(blank=True, db_column='description', default='', verbose_name='Descrição')),
                ('date', models.DateField(db_column='date', db_index=True, default=django.utils.timezone.localdate, verbose_name='Data')),
                ('external_reference', models.CharField(blank=True, db_column='external_reference', db_index=True, default='', max_length=120, verbose_name='Referência externa')),
                ('confirmed', models.BooleanField(db_column='confirmed', db_index=True, default=False, verbose_name='Confirmado')),
            ],
            options={
                'verbose_name': 'Lançamento legado',
                'verbose_name_plural': 'Lançamentos legados',
                'db_table': 'contabilidade_lancamento',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegacyMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('debit', models.DecimalField(db_column='debit', decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Débito')),
                ('credit', models.DecimalField(db_column='credit', decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Crédito')),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='contabilidade.account', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Movimento legado',
                'verbose_name_plural': 'Movimentos legados',
                'db_table': 'contabilidade_movimento',
                'ordering': ['-created_at'],
            },
        ),
    ]
