# Generated by Django 4.2.29 on 2026-04-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerline',
            options={'ordering': ['entry', 'position', 'id'], 'verbose_name': 'Linha contábil', 'verbose_name_plural': 'Linhas contábeis'},
        ),
        migrations.AddField(
            model_name='ledgerline',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
