# Generated by Django 5.1 on 2026-03-26 05:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidade", "0002_initial"),
        ("faturamento", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "verbose_name": "Conta contábil",
                "verbose_name_plural": "Contas contábeis",
            },
        ),
        migrations.AlterModelOptions(
            name="financialreconciliation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Conciliação financeira",
                "verbose_name_plural": "Conciliações financeiras",
            },
        ),
        migrations.AlterModelOptions(
            name="ledgerentry",
            options={
                "verbose_name": "Lançamento contábil",
                "verbose_name_plural": "Lançamentos contábeis",
            },
        ),
        migrations.AlterModelOptions(
            name="ledgerline",
            options={
                "verbose_name": "Linha contábil",
                "verbose_name_plural": "Linhas contábeis",
            },
        ),
        migrations.AlterModelOptions(
            name="legacyentry",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Lançamento legado",
                "verbose_name_plural": "Lançamentos legados",
            },
        ),
        migrations.AlterModelOptions(
            name="legacymovement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Movimento legado",
                "verbose_name_plural": "Movimentos legados",
            },
        ),
        migrations.AlterField(
            model_name="accountbalance",
            name="account",
            field=models.OneToOneField(
                db_column="account_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saldo",
                to="contabilidade.account",
                verbose_name="Conta",
            ),
        ),
        migrations.AlterField(
            model_name="accountbalance",
            name="current_balance",
            field=models.DecimalField(
                db_column="current_balance",
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Saldo atual",
            ),
        ),
        migrations.AlterField(
            model_name="accountbalance",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_column="updated_at",
                db_index=True,
                verbose_name="Atualizado em",
            ),
        ),
        migrations.AlterField(
            model_name="financialreconciliation",
            name="accounting_value",
            field=models.DecimalField(
                db_column="accounting_value",
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Valor contábil",
            ),
        ),
        migrations.AlterField(
            model_name="financialreconciliation",
            name="discrepancy",
            field=models.DecimalField(
                db_column="discrepancy",
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=18,
                verbose_name="Diferença",
            ),
        ),
        migrations.AlterField(
            model_name="financialreconciliation",
            name="external_reference",
            field=models.CharField(
                blank=True,
                db_column="external_reference",
                db_index=True,
                default="",
                max_length=120,
                verbose_name="Referência externa",
            ),
        ),
        migrations.AlterField(
            model_name="financialreconciliation",
            name="invoice",
            field=models.ForeignKey(
                db_column="invoice_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conciliacoes",
                to="faturamento.invoice",
                verbose_name="Fatura",
            ),
        ),
        migrations.AlterField(
            model_name="financialreconciliation",
            name="received_amount",
            field=models.DecimalField(
                db_column="received_amount",
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Valor recebido",
            ),
        ),
        migrations.AlterField(
            model_name="financialreconciliation",
            name="reconciled",
            field=models.BooleanField(
                db_column="reconciled",
                db_index=True,
                default=False,
                verbose_name="Conciliado",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="accounting_date",
            field=models.DateField(
                db_column="accounting_date", db_index=True, verbose_name="Data contábil"
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="created_at",
                db_index=True,
                verbose_name="Criado em",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="current_hash",
            field=models.CharField(
                blank=True,
                db_column="current_hash",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Hash atual",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="description",
            field=models.CharField(
                db_column="description", max_length=255, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="external_reference",
            field=models.CharField(
                db_column="external_reference",
                db_index=True,
                max_length=120,
                verbose_name="Referência externa",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Chave de idempotência",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="previous_hash",
            field=models.CharField(
                blank=True,
                db_column="previous_hash",
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="Hash anterior",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="reversal_of",
            field=models.OneToOneField(
                blank=True,
                db_column="reversal_of_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversao",
                to="contabilidade.ledgerentry",
                verbose_name="Reversão de",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="reversal_reason",
            field=models.TextField(
                blank=True,
                db_column="reversal_reason",
                null=True,
                verbose_name="Motivo da reversão",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="reversed",
            field=models.BooleanField(
                db_column="reversed",
                db_index=True,
                default=False,
                verbose_name="Revertido",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerline",
            name="account",
            field=models.ForeignKey(
                db_column="account_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="contabilidade.account",
                verbose_name="Conta",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerline",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="created_at",
                db_index=True,
                verbose_name="Criado em",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerline",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="linhas",
                to="contabilidade.ledgerentry",
                verbose_name="Lançamento",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerline",
            name="nature",
            field=models.CharField(
                choices=[("D", "Débito"), ("C", "Crédito")],
                db_column="nature",
                max_length=1,
                verbose_name="Natureza",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerline",
            name="value",
            field=models.DecimalField(
                db_column="value", decimal_places=2, max_digits=18, verbose_name="Valor"
            ),
        ),
    ]
