# Generated by Django 4.2.29 on 2026-05-29 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('ATI', 'Ativo'), ('PAS', 'Passivo'), ('REC', 'Receita'), ('DES', 'Despesa'), ('PAT', 'Patrimônio')], db_column='type', db_index=True, default='DES', max_length=3),
        ),
        migrations.AlterField(
            model_name='legacyentry',
            name='date',
            field=models.DateField(db_column='date', db_index=True, default=django.utils.timezone.localdate, verbose_name='Data da transação'),
        ),
    ]
