# Generated by Django 5.1 on 2026-03-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inquilinos", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="subscriptionplan",
            new_name="inquilinos__type_fdb81e_idx",
            old_name="inquilinos__tipo_856ce4_idx",
        ),
        migrations.RenameIndex(
            model_name="subscriptionplan",
            new_name="inquilinos__active_9b045a_idx",
            old_name="inquilinos__ativo_fa627d_idx",
        ),
        migrations.RenameIndex(
            model_name="tenant",
            new_name="inquilinos__identif_2fffee_idx",
            old_name="inquilinos__identif_c3e652_idx",
        ),
        migrations.RenameIndex(
            model_name="tenant",
            new_name="inquilinos__domain_54e3f7_idx",
            old_name="inquilinos__dominio_8b793c_idx",
        ),
        migrations.RenameIndex(
            model_name="tenant",
            new_name="inquilinos__active_f041a9_idx",
            old_name="inquilinos__ativo_74d41f_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantsubscription",
            new_name="inquilinos__tenant__63c6fd_idx",
            old_name="inquilinos__inquili_863caa_idx",
        ),
    ]
