# Generated by Django 4.2.29 on 2026-05-26 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='tenantconfiguration',
            options={'verbose_name': 'Configuração do Cliente', 'verbose_name_plural': 'Configurações do Cliente'},
        ),
        migrations.AlterModelOptions(
            name='tenantfeatureflag',
            options={'verbose_name': 'Funcionalidade do Cliente', 'verbose_name_plural': 'Funcionalidades do Cliente'},
        ),
        migrations.AlterModelOptions(
            name='tenantusage',
            options={'verbose_name': 'Uso do Cliente', 'verbose_name_plural': 'Uso dos Clientes'},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='commercial_status',
            field=models.CharField(choices=[('TRIAL', 'Experimental'), ('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso')], db_column='commercial_status', db_index=True, default='TRIAL', max_length=10, verbose_name='Estado comercial'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='trial_until',
            field=models.DateField(blank=True, db_column='trial_until', null=True, verbose_name='Teste até'),
        ),
        migrations.AlterField(
            model_name='tenantconfiguration',
            name='tenant',
            field=models.OneToOneField(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='inquilinos.tenant', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='tenantusage',
            name='tenant',
            field=models.OneToOneField(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='uso', to='inquilinos.tenant', verbose_name='Cliente'),
        ),
    ]
