# Generated by Django 5.1 on 2026-03-26 05:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inquilinos",
            "0002_rename_inquilinos__tipo_856ce4_idx_inquilinos__type_fdb81e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="active",
            field=models.BooleanField(
                db_column="active", db_index=True, default=True, verbose_name="Ativo"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="allows_multi_unit",
            field=models.BooleanField(
                db_column="allows_multi_unit",
                default=False,
                verbose_name="Permite multiunidade",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="monthly_price",
            field=models.DecimalField(
                db_column="monthly_price",
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Preço mensal",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="monthly_request_limit",
            field=models.PositiveIntegerField(
                db_column="monthly_request_limit",
                default=0,
                verbose_name="Limite de requisições mensais",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="priority_support",
            field=models.BooleanField(
                db_column="priority_support",
                default=False,
                verbose_name="Suporte prioritário",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="request_overage_price",
            field=models.DecimalField(
                db_column="request_overage_price",
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Preço por excesso",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="type",
            field=models.CharField(
                choices=[("FREE", "Free"), ("BASIC", "Basic"), ("PRO", "Pro")],
                db_column="type",
                db_index=True,
                default="FREE",
                max_length=10,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="user_limit",
            field=models.PositiveIntegerField(
                db_column="user_limit", default=1, verbose_name="Limite de usuários"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="active",
            field=models.BooleanField(
                db_column="active", db_index=True, default=True, verbose_name="Ativo"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="blocked_at",
            field=models.DateTimeField(
                blank=True,
                db_column="blocked_at",
                null=True,
                verbose_name="Bloqueado em",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="commercial_status",
            field=models.CharField(
                choices=[
                    ("TRIAL", "Trial"),
                    ("ATIVO", "Ativo"),
                    ("SUSPENSO", "Suspenso"),
                ],
                db_column="commercial_status",
                db_index=True,
                default="TRIAL",
                max_length=10,
                verbose_name="Status comercial",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="domain",
            field=models.CharField(
                blank=True,
                db_column="domain",
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Domínio",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="identifier",
            field=models.SlugField(
                db_column="identifier",
                max_length=80,
                unique=True,
                verbose_name="Identificador",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="trial_until",
            field=models.DateField(
                blank=True, db_column="trial_until", null=True, verbose_name="Trial até"
            ),
        ),
    ]
