# Generated by Django 4.2.29 on 2026-06-07 19:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import infrastructure.orm.fields.money_field


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0002_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('gateway', models.CharField(db_index=True, max_length=40, verbose_name='Gateway')),
                ('idempotency_key', models.CharField(db_column='idempotency_key', db_index=True, max_length=120, unique=True, verbose_name='Chave de idempotência')),
                ('external_reference', models.CharField(blank=True, db_column='external_reference', db_index=True, default='', max_length=120, verbose_name='Referência externa (gateway)')),
                ('amount', infrastructure.orm.fields.money_field.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor')),
                ('currency', models.CharField(db_column='currency', default='MZN', max_length=3, verbose_name='Moeda')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SUCESSO', 'Sucesso'), ('FALHOU', 'Falhou'), ('ESTORNADA', 'Estornada')], db_index=True, default='PENDENTE', max_length=10)),
                ('gateway_response', models.JSONField(blank=True, db_column='gateway_response', default=dict, verbose_name='Resposta do gateway')),
                ('processed_at', models.DateTimeField(blank=True, db_column='processed_at', null=True, verbose_name='Processada em')),
            ],
            options={
                'verbose_name': 'Cobrança de Assinatura',
                'verbose_name_plural': 'Cobranças de Assinatura',
                'db_table': 'inquilinos_cobranca_assinatura',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('period_start', models.DateField(db_column='period_start', db_index=True, verbose_name='Início do período')),
                ('period_end', models.DateField(db_column='period_end', verbose_name='Fim do período')),
                ('amount', infrastructure.orm.fields.money_field.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor')),
                ('currency', models.CharField(db_column='currency', default='MZN', max_length=3, verbose_name='Moeda')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PAGA', 'Paga'), ('ANULADA', 'Anulada'), ('INCOBRAVEL', 'Incobrável')], db_index=True, default='ABERTA', max_length=12)),
                ('due_date', models.DateField(blank=True, db_column='due_date', db_index=True, null=True, verbose_name='Vencimento')),
                ('issued_at', models.DateTimeField(db_column='issued_at', default=django.utils.timezone.now, verbose_name='Emitida em')),
                ('paid_at', models.DateTimeField(blank=True, db_column='paid_at', null=True, verbose_name='Paga em')),
            ],
            options={
                'verbose_name': 'Fatura de Assinatura',
                'verbose_name_plural': 'Faturas de Assinatura',
                'db_table': 'inquilinos_fatura_assinatura',
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, db_column='canceled_at', null=True, verbose_name='Cancelada em'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='current_period_end',
            field=models.DateField(blank=True, db_column='current_period_end', db_index=True, null=True, verbose_name='Fim do período atual'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='current_period_start',
            field=models.DateField(blank=True, db_column='current_period_start', null=True, verbose_name='Início do período atual'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='failed_charges',
            field=models.PositiveIntegerField(db_column='failed_charges', default=0, verbose_name='Cobranças falhadas seguidas'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='next_billing_at',
            field=models.DateField(blank=True, db_column='next_billing_at', db_index=True, null=True, verbose_name='Próxima cobrança'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='status',
            field=models.CharField(choices=[('TRIAL', 'Em teste'), ('ATIVA', 'Ativa'), ('INADIMPLENTE', 'Inadimplente'), ('SUSPENSA', 'Suspensa'), ('CANCELADA', 'Cancelada')], db_index=True, default='ATIVA', max_length=12),
        ),
        migrations.AddIndex(
            model_name='tenantsubscription',
            index=models.Index(fields=['status', 'next_billing_at'], name='inquilinos__status_4930c8_idx'),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='subscription',
            field=models.ForeignKey(db_column='subscription_id', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inquilinos.tenantsubscription', verbose_name='Assinatura'),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptioncharge',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptioncharge',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptioncharge',
            name='invoice',
            field=models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='inquilinos.subscriptioninvoice', verbose_name='Fatura'),
        ),
        migrations.AddField(
            model_name='subscriptioncharge',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='subscriptioncharge',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['tenant', 'status'], name='inquilinos__tenant__cdc9ad_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['subscription', 'status'], name='inquilinos__subscri_ff72e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('subscription', 'period_start'), name='uniq_subinvoice_subscription_period'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncharge',
            index=models.Index(fields=['gateway', 'status'], name='inquilinos__gateway_86a47e_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncharge',
            index=models.Index(fields=['external_reference'], name='inquilinos__externa_6de789_idx'),
        ),
    ]
