# Generated by Django 4.2.29 on 2026-06-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0003_subscriptioncharge_subscriptioninvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfiguration',
            name='fiscal_address',
            field=models.TextField(blank=True, db_column='fiscal_address', default='', verbose_name='Morada fiscal completa'),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='fiscal_email',
            field=models.CharField(blank=True, db_column='fiscal_email', default='', max_length=120, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='fiscal_phone',
            field=models.CharField(blank=True, db_column='fiscal_phone', default='', max_length=40, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='health_unit_registration',
            field=models.CharField(blank=True, db_column='health_unit_registration', default='', max_length=80, verbose_name='Registo da unidade sanitária/laboratório'),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='legal_name',
            field=models.CharField(blank=True, db_column='legal_name', default='', help_text='Nome legal da entidade tal como registado.', max_length=200, verbose_name='Designação legal'),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='license_number',
            field=models.CharField(blank=True, db_column='license_number', default='', max_length=80, verbose_name='Alvará / Licença'),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='nuit',
            field=models.CharField(blank=True, db_column='nuit', default='', max_length=30, verbose_name='NUIT'),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='technical_manager',
            field=models.CharField(blank=True, db_column='technical_manager', default='', max_length=160, verbose_name='Responsável técnico'),
        ),
    ]
