# Generated by Django 4.2.16 on 2026-03-20 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquilinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('numero_serie', models.CharField(db_index=True, max_length=120, verbose_name='Número de série')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de aquisição')),
                ('estado_aquisicao', models.CharField(choices=[('NOVO', 'Novo'), ('USADO', 'Usado')], db_index=True, default='NOVO', max_length=20, verbose_name='Estado na aquisição')),
                ('estado_operacional_inicial', models.CharField(choices=[('FUNCIONANDO', 'A funcionar'), ('AVARIADO', 'Avariado'), ('DESLIGADO', 'Desligado')], db_index=True, default='FUNCIONANDO', max_length=20, verbose_name='Estado operacional inicial')),
                ('tipo_avaria_inicial', models.CharField(blank=True, default='', max_length=120, verbose_name='Tipo de avaria inicial')),
                ('fabricante', models.CharField(blank=True, default='', max_length=120)),
                ('modelo', models.CharField(blank=True, default='', max_length=120)),
                ('localizacao', models.CharField(blank=True, default='', max_length=255, verbose_name='Localização')),
                ('responsavel', models.CharField(blank=True, default='', max_length=120, verbose_name='Responsável')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['inquilino', 'numero_serie'], name='equipamento_inquili_a3b6b8_idx'), models.Index(fields=['inquilino', 'ativo'], name='equipamento_inquili_1b62c4_idx'), models.Index(fields=['inquilino', 'estado_operacional_inicial'], name='equipamento_inquili_2b929b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='equipamento',
            constraint=models.UniqueConstraint(fields=('inquilino', 'numero_serie'), name='uq_equipamento_numero_serie_inquilino'),
        ),
    ]
