# Generated by Django 4.2.16 on 2026-03-28 04:22

from decimal import Decimal

import django.core.validators
from django.db import migrations, models
import django_countries.fields

import apps.clinical.models.medical_result_file
import core.mixins.tenant_propagation
import infrastructure.orm.fields.email_field
import infrastructure.orm.fields.medical_exam_method_field
import infrastructure.orm.fields.medical_exam_sector_field
import infrastructure.orm.fields.method_field
import infrastructure.orm.fields.money_field
import infrastructure.orm.fields.phone_field
import infrastructure.orm.fields.sector_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('event_type', models.CharField(choices=[('result_criado', 'Resultado Criado'), ('result_interpretado', 'Resultado Interpretado'), ('result_validado', 'Resultado Validado'), ('result_critico', 'Resultado Crítico'), ('request_criada', 'Requisição Criada'), ('request_processamento', 'Requisição em Processamento'), ('request_validada', 'Requisição Validada'), ('request_cancelada', 'Requisição Cancelada'), ('medication_prescrita', 'Medicação Prescrita'), ('medication_administrada', 'Medicação Administrada'), ('observation_clinica', 'Observação Clínica'), ('diagnóstico', 'Diagnóstico')], db_column='event_type', db_index=True, max_length=50, verbose_name='Tipo de evento')),
                ('description', models.TextField(db_column='description', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Evento clínico',
                'verbose_name_plural': 'Eventos clínicos',
                'db_table': 'clinico_eventoclinico',
                'ordering': ['-created_at'],
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClinicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_column='description', verbose_name='Descrição')),
                ('event_date', models.DateTimeField(auto_now_add=True, db_column='event_date', verbose_name='Data do evento')),
            ],
            options={
                'verbose_name': 'Histórico clínico',
                'verbose_name_plural': 'Históricos clínicos',
                'db_table': 'clinico_historicoclinico',
            },
        ),
        migrations.CreateModel(
            name='ClinicalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('sex', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], db_column='sex', help_text='Se vazio, aplica-se a ambos os sexos.', max_length=10, null=True, verbose_name='Sexo')),
                ('minimum_age_days', models.PositiveIntegerField(blank=True, db_column='minimum_age_days', help_text='Idade mínima em dias.', null=True, verbose_name='Idade mínima (dias)')),
                ('maximum_age_days', models.PositiveIntegerField(blank=True, db_column='maximum_age_days', help_text='Idade máxima em dias.', null=True, verbose_name='Idade máxima (dias)')),
                ('minimum_value', models.DecimalField(blank=True, db_column='minimum_value', decimal_places=2, max_digits=10, null=True, verbose_name='Valor mínimo')),
                ('maximum_value', models.DecimalField(blank=True, db_column='maximum_value', decimal_places=2, max_digits=10, null=True, verbose_name='Valor máximo')),
                ('critical_low', models.DecimalField(blank=True, db_column='critical_low', decimal_places=2, max_digits=10, null=True, verbose_name='Limite crítico baixo')),
                ('critical_high', models.DecimalField(blank=True, db_column='critical_high', decimal_places=2, max_digits=10, null=True, verbose_name='Limite crítico alto')),
            ],
            options={
                'verbose_name': 'Referência clínica',
                'verbose_name_plural': 'Referências clínicas',
                'db_table': 'clinico_referenciaclinica',
                'ordering': ['exam_field', 'sex', 'minimum_age_days'],
            },
        ),
        migrations.CreateModel(
            name='LabExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('turnaround_hours', models.PositiveIntegerField(db_column='turnaround_hours', default=24, help_text='Tempo de response em hours.', verbose_name='Tempo de response (em hours)')),
                ('price', infrastructure.orm.fields.money_field.MoneyField(db_column='price', decimal_places=2, default=Decimal('0.00'), help_text='Preço do exam.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço do exam')),
                ('vat_percentage', models.DecimalField(db_column='vat_percentage', decimal_places=2, default=Decimal('16.00'), help_text='Taxa de IVA aplicada ao exam (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)')),
                ('applies_vat_by_default', models.BooleanField(db_column='applies_vat_by_default', default=True, help_text='Desmarque se este exam normalmente não deve ter IVA.', verbose_name='Aplicar IVA por padrão')),
                ('method', infrastructure.orm.fields.method_field.MethodField(choices=[('Enzimatico', 'Enzimático'), ('Colorimetrico', 'Colorimétrico'), ('Espectrofotometrico', 'Espectrofotométrico'), ('Turbidimetrico', 'Turbidimétrico'), ('Nefelometrico', 'Nefelométrico'), ('Potenciometrico', 'Potenciométrico'), ('Eletroquimico', 'Eletroquímico'), ('ELISA', 'ELISA'), ('Quimioluminescencia', 'Quimioluminescência'), ('Eletroquimioluminescencia', 'Eletroquimioluminescência'), ('Imunofluorescencia', 'Imunofluorescência'), ('Imunoturbidimetria', 'Imunoturbidimetria'), ('Aglutinacao', 'Aglutinação'), ('Cultura', 'Cultura'), ('Antibiograma', 'Antibiograma'), ('Microscopico', 'Microscópico'), ('ColoracaoGram', 'Coloração de Gram'), ('ColoracaoZiehl', 'Ziehl-Neelsen'), ('IsolamentoMicrobiano', 'Isolamento Microbiano'), ('CitometriaFluxo', 'Citometria de Fluxo'), ('HematologiaAutomatizada', 'Hematologia Automatizada'), ('MicroscopiaOptica', 'Microscopia Óptica'), ('PCR', 'PCR'), ('RT_PCR', 'RT-PCR'), ('PCRTempoReal', 'PCR em Tempo Real'), ('Sequenciamento', 'Sequenciamento Genético'), ('HibridizacaoMolecular', 'Hibridização Molecular'), ('Genotipagem', 'Genotipagem'), ('Cromatografia', 'Cromatografia'), ('CromatografiaGasosa', 'Cromatografia Gasosa'), ('CromatografiaLiquida', 'Cromatografia Líquida'), ('HPLC', 'Cromatografia Líquida de Alta Eficiência'), ('Eletroforese', 'Eletroforese'), ('Isoeletrofoque', 'Isoeletrofocalização'), ('Sedimentacao', 'Sedimentação'), ('Flutuacao', 'Flutuação'), ('KatoKatz', 'Kato-Katz'), ('TiraReagente', 'Tira Reagente'), ('AnaliseMicroscopica', 'Análise Microscópica'), ('EspectrometriaMassa', 'Espectrometria de Massa'), ('MALDI_TOF', 'MALDI-TOF'), ('RessonanciaMagneticaNuclear', 'Ressonância Magnética Nuclear')], db_index=True, max_length=50, verbose_name='Método do exam')),
                ('sector', infrastructure.orm.fields.sector_field.SectorField(blank=True, choices=[('Hematologia', 'Hematologia'), ('Bioquimica', 'Bioquímica'), ('Microbiologia', 'Microbiologia'), ('Imunologia', 'Imunologia'), ('Serologia', 'Serologia'), ('Parasitologia', 'Parasitologia'), ('BiologiaMolecular', 'Biologia Molecular'), ('Toxicologia', 'Toxicologia'), ('Hormonios', 'Hormônios e Endocrinologia'), ('MarcadoresTumorais', 'Marcadores Tumorais'), ('Coagulacao', 'Coagulação'), ('Urinalise', 'Urinálise'), ('LiquidosCorporais', 'Líquidos Corporais'), ('Gasometria', 'Gasometria'), ('NutricaoClinica', 'Nutrição Clínica'), ('Micologia', 'Micologia'), ('Virologia', 'Virologia'), ('Bacteriologia', 'Bacteriologia'), ('BancoSangue', 'Banco de Sangue'), ('ImunoHematologia', 'Imuno-hematologia'), ('Triagem', 'Triagem Laboratorial'), ('RecepcaoAmostras', 'Recepção de Amostras'), ('ControleQualidade', 'Controle de Qualidade'), ('Pesquisa', 'Pesquisa Laboratorial'), ('Outro', 'Outro')], db_index=True, max_length=40, null=True, verbose_name='Setor do exam')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
                'db_table': 'clinico_exame',
                'ordering': ['name', 'created_at'],
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LabExamField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('type', models.CharField(choices=[('NUMERICO', 'Numérico'), ('QUALITATIVO', 'Qualitativo'), ('SEMIQUANTITATIVO', 'Semi-quantitativo'), ('TEXTO', 'Texto Livre')], db_column='type', max_length=20, verbose_name='Tipo de parâmetro')),
                ('unit', models.CharField(choices=[('g/dl', 'g/dl'), ('mg/dl', 'mg/dl'), ('mmol/l', 'mmol/l'), ('µmol/l', 'µmol/l'), ('cel/mm3', 'cel/mm3'), ('x10³/µl', 'x10³/µl'), ('x10⁶/µL', 'x10⁶/µL'), ('%', '%'), ('u/l', 'u/l'), ('p/µL', 'p/µL'), ('ph', 'ph'), ('fl', 'fl')], db_column='unit', default='p/µL', max_length=30, verbose_name='Unidade de medida')),
                ('reference_min', models.DecimalField(blank=True, db_column='reference_min', decimal_places=2, max_digits=10, null=True, verbose_name='Referência mínima')),
                ('reference_max', models.DecimalField(blank=True, db_column='reference_max', decimal_places=2, max_digits=10, null=True, verbose_name='Referência máxima')),
                ('critical_min', models.DecimalField(blank=True, db_column='critical_min', decimal_places=2, max_digits=10, null=True, verbose_name='Valor crítico mínimo')),
                ('critical_max', models.DecimalField(blank=True, db_column='critical_max', decimal_places=2, max_digits=10, null=True, verbose_name='Valor crítico máximo')),
                ('max_delta', models.DecimalField(blank=True, db_column='max_delta', decimal_places=2, max_digits=10, null=True, verbose_name='Delta máximo permitido')),
            ],
            options={
                'verbose_name': 'parâmetro',
                'verbose_name_plural': 'parâmetros do exam',
                'db_table': 'clinico_examecampo',
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('type', models.CharField(choices=[('LAB', 'Laboratório'), ('MED', 'Exame médico')], db_column='type', db_index=True, default='LAB', max_length=3)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aguardando_validacao', 'Aguardando Validação'), ('validado', 'Validado'), ('rejeitado', 'Rejeitado')], db_column='status', db_index=True, default='pendente', max_length=30)),
                ('clinical_status', models.CharField(choices=[('NAO_URGENTE', 'Não urgente'), ('NORMAL', 'Normal'), ('ROTINA', 'Rotina'), ('POUCO_URGENTE', 'Pouco urgente'), ('PRIORITARIO', 'Prioritário'), ('URGENTE', 'Urgente'), ('MUITO_URGENTE', 'Muito urgente'), ('URGENTISSIMO', 'Urgentíssimo'), ('EMERGENCIA', 'Emergência')], db_column='clinical_status', db_index=True, default='NAO_URGENTE', max_length=50)),
                ('has_critical_result', models.BooleanField(db_column='has_critical_result', db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Requisição de exam',
                'verbose_name_plural': 'Requisições de exams',
                'db_table': 'clinico_requisicaoanalise',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
            ],
            options={
                'db_table': 'clinico_requisicaoitem',
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MedicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('turnaround_hours', models.PositiveIntegerField(db_column='turnaround_hours', default=24, help_text='Tempo de response em hours.', verbose_name='Tempo de response (em hours)')),
                ('price', infrastructure.orm.fields.money_field.MoneyField(db_column='price', decimal_places=2, default=Decimal('0.00'), help_text='Preço do exam médico.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço do exam médico')),
                ('vat_percentage', models.DecimalField(db_column='vat_percentage', decimal_places=2, default=Decimal('16.00'), help_text='Taxa de IVA aplicada ao exam médico (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)')),
                ('applies_vat_by_default', models.BooleanField(db_column='applies_vat_by_default', default=True, help_text='Desmarque se este exam normalmente não deve ter IVA.', verbose_name='Aplicar IVA por padrão')),
                ('method', infrastructure.orm.fields.medical_exam_method_field.MedicalExamMethodField(choices=[('USG', 'Ultrassonografia / Ecografia'), ('RX', 'Raio-X Convencional'), ('CT', 'Tomografia Computorizada (CT)'), ('RM', 'Ressonância Magnética (RM)'), ('MG', 'Mamografia'), ('DXA', 'Densitometria Óssea (DXA)'), ('ECO', 'Ecocardiograma'), ('ECG', 'Eletrocardiograma (ECG)'), ('HOLTER', 'Holter'), ('MAPA', 'MAPA (PA 24h)'), ('EEG', 'Eletroencefalograma (EEG)'), ('ENDO', 'Endoscopia'), ('COLONO', 'Colonoscopia'), ('ANGIO', 'Angiografia'), ('MN', 'Medicina Nuclear / Cintilografia'), ('OUT', 'Outro')], db_index=True, max_length=30, verbose_name='Método do exam (imagem/diagnóstico)')),
                ('sector', infrastructure.orm.fields.medical_exam_sector_field.MedicalExamSectorField(blank=True, choices=[('Radiologia', 'Radiologia'), ('DiagnosticoImagem', 'Diagnóstico por Imagem'), ('Cardiologia', 'Cardiologia'), ('GinecoObstetricia', 'Ginecologia/Obstetrícia'), ('Ortopedia', 'Ortopedia/Traumato'), ('Neurologia', 'Neurologia'), ('Otorrino', 'Otorrinolaringologia'), ('Oftalmologia', 'Oftalmologia'), ('MedicinaNuclear', 'Medicina Nuclear'), ('Endoscopia', 'Endoscopia'), ('Outro', 'Outro')], db_index=True, max_length=40, null=True, verbose_name='Setor do exam (imagem/diagnóstico)')),
            ],
            options={
                'verbose_name': 'Exame médico',
                'verbose_name_plural': 'Exames médicos',
                'db_table': 'clinico_examemedico',
                'ordering': ['name', 'created_at'],
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MedicalExamField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('type', models.CharField(choices=[('PDF', 'Laudo/Relatório (PDF)'), ('IMAGEM', 'Imagem (JPEG/PNG)'), ('DICOM', 'DICOM'), ('VIDEO', 'Vídeo/loop'), ('TEXTO', 'Texto livre'), ('NUMERICO', 'Valor numérico')], db_column='type', max_length=20, verbose_name='Tipo de parâmetro/file')),
            ],
            options={
                'verbose_name': 'parâmetro de exam médico',
                'verbose_name_plural': 'parâmetros de exam médico',
                'db_table': 'clinico_examemedicocampo',
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MedicalResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('type', models.CharField(choices=[('PDF', 'Laudo/Relatório (PDF)'), ('IMAGEM', 'Imagem (JPEG/PNG)'), ('DICOM', 'DICOM'), ('VIDEO', 'Vídeo/loop'), ('TEXTO', 'Texto livre'), ('NUMERICO', 'Valor numérico')], db_column='type', default='IMAGEM', max_length=20, verbose_name='Tipo de file')),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, verbose_name='Descrição/legenda')),
                ('file', models.FileField(db_column='file', upload_to=apps.clinical.models.medical_result_file._medical_result_upload_to, verbose_name='Arquivo (PDF/Imagem/DICOM)')),
            ],
            options={
                'verbose_name': 'Arquivo de result médico',
                'verbose_name_plural': 'Arquivos de result médico',
                'db_table': 'clinico_resultadomedicoarquivo',
                'ordering': ['-created_at'],
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('pregnant', models.BooleanField(db_column='pregnant', default=False, verbose_name='Gestante')),
                ('gestational_age_weeks', models.PositiveIntegerField(blank=True, db_column='gestational_age_weeks', help_text='Preencher se a patient estiver pregnant.', null=True, verbose_name='Idade gestacional (semanas)')),
                ('birth_date', models.DateField(blank=True, db_column='birth_date', null=True, verbose_name='Data de nascimento')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], db_column='gender', db_index=True, default='Femenino', max_length=10, verbose_name='Gênero')),
                ('race_origin', models.CharField(choices=[('Branca', 'Branca'), ('Negra', 'Negra'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Indígena', 'Indígena'), ('Outro', 'Outro')], db_column='race_origin', default='Negra', max_length=20, verbose_name='Raça / Origem')),
                ('document_type', models.CharField(choices=[('BI', 'Bilhete de Identidade'), ('PASS', 'Passaporte'), ('DIRE', 'Documento de Identificação de Residente Estrangeiro'), ('CC', 'Carta de Condução'), ('NUIT', 'Número Único de Identificação Tributária'), ('CE', 'Cartão de Eleitor'), ('CN', 'Certidão de Nascimento'), ('OUT', 'Outro')], db_column='document_type', default='BI', max_length=50, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(blank=True, db_column='document_number', max_length=50, null=True, unique=True, verbose_name='Número do documento')),
                ('address_street', models.CharField(blank=True, db_column='address_street', default='', max_length=120, verbose_name='Rua')),
                ('address_number', models.CharField(blank=True, db_column='address_number', default='', max_length=30, verbose_name='Número')),
                ('address_neighborhood', models.CharField(blank=True, db_column='address_neighborhood', default='', max_length=120, verbose_name='Bairro')),
                ('address_city', models.CharField(blank=True, db_column='address_city', default='', max_length=120, verbose_name='Cidade')),
                ('address_province', models.CharField(blank=True, db_column='address_province', default='', max_length=120, verbose_name='Província')),
                ('address_postal_code', models.CharField(blank=True, db_column='address_postal_code', default='', max_length=30, verbose_name='Código postal')),
                ('address_country', django_countries.fields.CountryField(blank=True, db_column='address_country', default='MZ', max_length=2, verbose_name='País')),
                ('address_complement', models.CharField(blank=True, db_column='address_complement', default='', max_length=255, verbose_name='Complemento')),
                ('address', models.CharField(blank=True, db_column='address', default='', help_text='Texto livre ou resumo (auto) da address.', max_length=255, verbose_name='Morada')),
                ('contact', infrastructure.orm.fields.phone_field.PhoneField(blank=True, db_column='contact', max_length=9, null=True, verbose_name='Contacto')),
                ('email', infrastructure.orm.fields.email_field.NormalizedEmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('provenance', models.CharField(blank=True, choices=[('Ambulatório', 'Ambulatório'), ('Clínica Externa', 'Clínica Externa'), ('Medicina Ocupacional', 'Medicina Ocupacional'), ('Maternidade', 'Maternidade'), ('Ginecologia', 'Ginecologia'), ('Pediatria', 'Pediatria'), ('Banco de Socorros', 'Banco de Socorros'), ('Consulta Externa', 'Consulta Externa'), ('Urologia', 'Urologia'), ('Cirurgia', 'Cirurgia'), ('Dentária', 'Dentária'), ('Oftalmologia', 'Oftalmologia'), ('Outro', 'Outro')], db_column='provenance', default='Clínica Externa', max_length=50, verbose_name='Proveniência')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'db_table': 'clinico_paciente',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('finalized', models.BooleanField(db_column='finalized', default=False)),
            ],
            options={
                'db_table': 'clinico_resultado',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('result_value', models.DecimalField(blank=True, db_column='result_value', decimal_places=2, max_digits=12, null=True, verbose_name='Valor do resultado')),
                ('clinical_status', models.CharField(blank=True, db_column='clinical_status', max_length=20, verbose_name='Status clínico')),
                ('report_color', models.CharField(blank=True, db_column='report_color', max_length=20, null=True, verbose_name='Cor para relatório')),
                ('critical_alert', models.BooleanField(db_column='critical_alert', default=False, verbose_name='Alerta crítico')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aguardando_validacao', 'Aguardando Validação'), ('validado', 'Validado'), ('rejeitado', 'Rejeitado')], db_column='status', db_index=True, default='pendente', max_length=30, verbose_name='Status do resultado')),
                ('validation_date', models.DateTimeField(blank=True, db_column='validation_date', null=True, verbose_name='Data de validação')),
            ],
            options={
                'db_table': 'clinico_resultadoitem',
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
    ]
