# Generated by Django 5.1 on 2026-03-25 04:18

import apps.clinical.models.medical_result_file
import core.mixins.tenant_propagation
import django.core.validators
import django_countries.fields
import infrastructure.orm.fields.email_field
import infrastructure.orm.fields.medical_exam_method_field
import infrastructure.orm.fields.medical_exam_sector_field
import infrastructure.orm.fields.method_field
import infrastructure.orm.fields.money_field
import infrastructure.orm.fields.phone_field
import infrastructure.orm.fields.sector_field
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicalReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "name",
                    models.CharField(db_column="nome", db_index=True, max_length=120),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("Masculino", "Masculino"), ("Femenino", "Femenino")],
                        db_column="sexo",
                        help_text="Se vazio, aplica-se a ambos os sexos.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "minimum_age_days",
                    models.PositiveIntegerField(
                        blank=True,
                        db_column="idade_minima_dias",
                        help_text="Idade mínima em dias.",
                        null=True,
                    ),
                ),
                (
                    "maximum_age_days",
                    models.PositiveIntegerField(
                        blank=True,
                        db_column="idade_maxima_dias",
                        help_text="Idade máxima em dias.",
                        null=True,
                    ),
                ),
                (
                    "minimum_value",
                    models.DecimalField(
                        blank=True,
                        db_column="valor_minimo",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "maximum_value",
                    models.DecimalField(
                        blank=True,
                        db_column="valor_maximo",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "critical_low",
                    models.DecimalField(
                        blank=True,
                        db_column="critico_baixo",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "critical_high",
                    models.DecimalField(
                        blank=True,
                        db_column="critico_alto",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "clinico_referenciaclinica",
                "ordering": ["exam_field", "sex", "minimum_age_days"],
            },
        ),
        migrations.CreateModel(
            name="LabExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "name",
                    models.CharField(db_column="nome", db_index=True, max_length=120),
                ),
                (
                    "turnaround_hours",
                    models.PositiveIntegerField(
                        db_column="trl_horas",
                        default=24,
                        help_text="Tempo de response em hours.",
                        verbose_name="Tempo de response (em hours)",
                    ),
                ),
                (
                    "price",
                    infrastructure.orm.fields.money_field.MoneyField(
                        db_column="preco",
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Preço do exam.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Preço do exam",
                    ),
                ),
                (
                    "vat_percentage",
                    models.DecimalField(
                        db_column="iva_percentual",
                        decimal_places=2,
                        default=Decimal("16.00"),
                        help_text="Taxa de IVA aplicada ao exam (0 a 100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="IVA (%)",
                    ),
                ),
                (
                    "applies_vat_by_default",
                    models.BooleanField(
                        db_column="aplica_iva_por_padrao",
                        default=True,
                        help_text="Desmarque se este exam normalmente não deve ter IVA.",
                        verbose_name="Aplicar IVA por padrão",
                    ),
                ),
                (
                    "method",
                    infrastructure.orm.fields.method_field.MethodField(
                        choices=[
                            ("Enzimatico", "Enzimático"),
                            ("Colorimetrico", "Colorimétrico"),
                            ("Espectrofotometrico", "Espectrofotométrico"),
                            ("Turbidimetrico", "Turbidimétrico"),
                            ("Nefelometrico", "Nefelométrico"),
                            ("Potenciometrico", "Potenciométrico"),
                            ("Eletroquimico", "Eletroquímico"),
                            ("ELISA", "ELISA"),
                            ("Quimioluminescencia", "Quimioluminescência"),
                            ("Eletroquimioluminescencia", "Eletroquimioluminescência"),
                            ("Imunofluorescencia", "Imunofluorescência"),
                            ("Imunoturbidimetria", "Imunoturbidimetria"),
                            ("Aglutinacao", "Aglutinação"),
                            ("Cultura", "Cultura"),
                            ("Antibiograma", "Antibiograma"),
                            ("Microscopico", "Microscópico"),
                            ("ColoracaoGram", "Coloração de Gram"),
                            ("ColoracaoZiehl", "Ziehl-Neelsen"),
                            ("IsolamentoMicrobiano", "Isolamento Microbiano"),
                            ("CitometriaFluxo", "Citometria de Fluxo"),
                            ("HematologiaAutomatizada", "Hematologia Automatizada"),
                            ("MicroscopiaOptica", "Microscopia Óptica"),
                            ("PCR", "PCR"),
                            ("RT_PCR", "RT-PCR"),
                            ("PCRTempoReal", "PCR em Tempo Real"),
                            ("Sequenciamento", "Sequenciamento Genético"),
                            ("HibridizacaoMolecular", "Hibridização Molecular"),
                            ("Genotipagem", "Genotipagem"),
                            ("Cromatografia", "Cromatografia"),
                            ("CromatografiaGasosa", "Cromatografia Gasosa"),
                            ("CromatografiaLiquida", "Cromatografia Líquida"),
                            ("HPLC", "Cromatografia Líquida de Alta Eficiência"),
                            ("Eletroforese", "Eletroforese"),
                            ("Isoeletrofoque", "Isoeletrofocalização"),
                            ("Sedimentacao", "Sedimentação"),
                            ("Flutuacao", "Flutuação"),
                            ("KatoKatz", "Kato-Katz"),
                            ("TiraReagente", "Tira Reagente"),
                            ("AnaliseMicroscopica", "Análise Microscópica"),
                            ("EspectrometriaMassa", "Espectrometria de Massa"),
                            ("MALDI_TOF", "MALDI-TOF"),
                            (
                                "RessonanciaMagneticaNuclear",
                                "Ressonância Magnética Nuclear",
                            ),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Método do exam",
                    ),
                ),
                (
                    "sector",
                    infrastructure.orm.fields.sector_field.SectorField(
                        blank=True,
                        choices=[
                            ("Hematologia", "Hematologia"),
                            ("Bioquimica", "Bioquímica"),
                            ("Microbiologia", "Microbiologia"),
                            ("Imunologia", "Imunologia"),
                            ("Serologia", "Serologia"),
                            ("Parasitologia", "Parasitologia"),
                            ("BiologiaMolecular", "Biologia Molecular"),
                            ("Toxicologia", "Toxicologia"),
                            ("Hormonios", "Hormônios e Endocrinologia"),
                            ("MarcadoresTumorais", "Marcadores Tumorais"),
                            ("Coagulacao", "Coagulação"),
                            ("Urinalise", "Urinálise"),
                            ("LiquidosCorporais", "Líquidos Corporais"),
                            ("Gasometria", "Gasometria"),
                            ("NutricaoClinica", "Nutrição Clínica"),
                            ("Micologia", "Micologia"),
                            ("Virologia", "Virologia"),
                            ("Bacteriologia", "Bacteriologia"),
                            ("BancoSangue", "Banco de Sangue"),
                            ("ImunoHematologia", "Imuno-hematologia"),
                            ("Triagem", "Triagem Laboratorial"),
                            ("RecepcaoAmostras", "Recepção de Amostras"),
                            ("ControleQualidade", "Controle de Qualidade"),
                            ("Pesquisa", "Pesquisa Laboratorial"),
                            ("Outro", "Outro"),
                        ],
                        db_index=True,
                        max_length=40,
                        null=True,
                        verbose_name="Setor do exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exame",
                "verbose_name_plural": "Exames",
                "db_table": "clinico_exame",
                "ordering": ["name", "created_at"],
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LabExamField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "name",
                    models.CharField(db_column="nome", db_index=True, max_length=120),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NUMERICO", "Numérico"),
                            ("QUALITATIVO", "Qualitativo"),
                            ("SEMIQUANTITATIVO", "Semi-quantitativo"),
                            ("TEXTO", "Texto Livre"),
                        ],
                        db_column="tipo",
                        max_length=20,
                        verbose_name="Tipo de parâmetro",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g/dl", "g/dl"),
                            ("mg/dl", "mg/dl"),
                            ("mmol/l", "mmol/l"),
                            ("µmol/l", "µmol/l"),
                            ("cel/mm3", "cel/mm3"),
                            ("x10³/µl", "x10³/µl"),
                            ("x10⁶/µL", "x10⁶/µL"),
                            ("%", "%"),
                            ("u/l", "u/l"),
                            ("p/µL", "p/µL"),
                            ("ph", "ph"),
                            ("fl", "fl"),
                        ],
                        db_column="unidade",
                        default="p/µL",
                        max_length=30,
                        verbose_name="Unidade de medida",
                    ),
                ),
                (
                    "reference_min",
                    models.DecimalField(
                        blank=True,
                        db_column="referencia_min",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Referência mínima",
                    ),
                ),
                (
                    "reference_max",
                    models.DecimalField(
                        blank=True,
                        db_column="referencia_max",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Referência máxima",
                    ),
                ),
                (
                    "critical_min",
                    models.DecimalField(
                        blank=True,
                        db_column="critico_min",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor crítico mínimo",
                    ),
                ),
                (
                    "critical_max",
                    models.DecimalField(
                        blank=True,
                        db_column="critico_max",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor crítico máximo",
                    ),
                ),
                (
                    "max_delta",
                    models.DecimalField(
                        blank=True,
                        db_column="delta_max",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Delta máximo permitido",
                    ),
                ),
            ],
            options={
                "verbose_name": "parâmetro",
                "verbose_name_plural": "parâmetros do exam",
                "db_table": "clinico_examecampo",
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LabRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "type",
                    models.CharField(
                        choices=[("LAB", "Laboratório"), ("MED", "Exame médico")],
                        db_column="tipo",
                        db_index=True,
                        default="LAB",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_analise", "Em Análise"),
                            ("aguardando_validacao", "Aguardando Validação"),
                            ("validado", "Validado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        db_column="estado",
                        db_index=True,
                        default="pendente",
                        max_length=30,
                    ),
                ),
                (
                    "clinical_status",
                    models.CharField(
                        choices=[
                            ("NAO_URGENTE", "Não urgente"),
                            ("NORMAL", "Normal"),
                            ("ROTINA", "Rotina"),
                            ("POUCO_URGENTE", "Pouco urgente"),
                            ("PRIORITARIO", "Prioritário"),
                            ("URGENTE", "Urgente"),
                            ("MUITO_URGENTE", "Muito urgente"),
                            ("URGENTISSIMO", "Urgentíssimo"),
                            ("EMERGENCIA", "Emergência"),
                        ],
                        db_column="status_clinico",
                        db_index=True,
                        default="NAO_URGENTE",
                        max_length=50,
                    ),
                ),
                (
                    "has_critical_result",
                    models.BooleanField(
                        db_column="possui_resultado_critico",
                        db_index=True,
                        default=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisição de exam",
                "verbose_name_plural": "Requisições de exams",
                "db_table": "clinico_requisicaoanalise",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
            ],
            options={
                "db_table": "clinico_requisicaoitem",
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MedicalExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "name",
                    models.CharField(db_column="nome", db_index=True, max_length=120),
                ),
                (
                    "turnaround_hours",
                    models.PositiveIntegerField(
                        db_column="trl_horas",
                        default=24,
                        help_text="Tempo de response em hours.",
                        verbose_name="Tempo de response (em hours)",
                    ),
                ),
                (
                    "price",
                    infrastructure.orm.fields.money_field.MoneyField(
                        db_column="preco",
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Preço do exam médico.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Preço do exam médico",
                    ),
                ),
                (
                    "vat_percentage",
                    models.DecimalField(
                        db_column="iva_percentual",
                        decimal_places=2,
                        default=Decimal("16.00"),
                        help_text="Taxa de IVA aplicada ao exam médico (0 a 100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="IVA (%)",
                    ),
                ),
                (
                    "applies_vat_by_default",
                    models.BooleanField(
                        db_column="aplica_iva_por_padrao",
                        default=True,
                        help_text="Desmarque se este exam normalmente não deve ter IVA.",
                        verbose_name="Aplicar IVA por padrão",
                    ),
                ),
                (
                    "method",
                    infrastructure.orm.fields.medical_exam_method_field.MedicalExamMethodField(
                        choices=[
                            ("USG", "Ultrassonografia / Ecografia"),
                            ("RX", "Raio-X Convencional"),
                            ("CT", "Tomografia Computorizada (CT)"),
                            ("RM", "Ressonância Magnética (RM)"),
                            ("MG", "Mamografia"),
                            ("DXA", "Densitometria Óssea (DXA)"),
                            ("ECO", "Ecocardiograma"),
                            ("ECG", "Eletrocardiograma (ECG)"),
                            ("HOLTER", "Holter"),
                            ("MAPA", "MAPA (PA 24h)"),
                            ("EEG", "Eletroencefalograma (EEG)"),
                            ("ENDO", "Endoscopia"),
                            ("COLONO", "Colonoscopia"),
                            ("ANGIO", "Angiografia"),
                            ("MN", "Medicina Nuclear / Cintilografia"),
                            ("OUT", "Outro"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Método do exam (imagem/diagnóstico)",
                    ),
                ),
                (
                    "sector",
                    infrastructure.orm.fields.medical_exam_sector_field.MedicalExamSectorField(
                        blank=True,
                        choices=[
                            ("Radiologia", "Radiologia"),
                            ("DiagnosticoImagem", "Diagnóstico por Imagem"),
                            ("Cardiologia", "Cardiologia"),
                            ("GinecoObstetricia", "Ginecologia/Obstetrícia"),
                            ("Ortopedia", "Ortopedia/Traumato"),
                            ("Neurologia", "Neurologia"),
                            ("Otorrino", "Otorrinolaringologia"),
                            ("Oftalmologia", "Oftalmologia"),
                            ("MedicinaNuclear", "Medicina Nuclear"),
                            ("Endoscopia", "Endoscopia"),
                            ("Outro", "Outro"),
                        ],
                        db_index=True,
                        max_length=40,
                        null=True,
                        verbose_name="Setor do exam (imagem/diagnóstico)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exame médico",
                "verbose_name_plural": "Exames médicos",
                "db_table": "clinico_examemedico",
                "ordering": ["name", "created_at"],
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MedicalExamField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "name",
                    models.CharField(db_column="nome", db_index=True, max_length=120),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PDF", "Laudo/Relatório (PDF)"),
                            ("IMAGEM", "Imagem (JPEG/PNG)"),
                            ("DICOM", "DICOM"),
                            ("VIDEO", "Vídeo/loop"),
                            ("TEXTO", "Texto livre"),
                            ("NUMERICO", "Valor numérico"),
                        ],
                        db_column="tipo",
                        max_length=20,
                        verbose_name="Tipo de parâmetro/file",
                    ),
                ),
            ],
            options={
                "verbose_name": "parâmetro de exam médico",
                "verbose_name_plural": "parâmetros de exam médico",
                "db_table": "clinico_examemedicocampo",
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MedicalResultFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PDF", "Laudo/Relatório (PDF)"),
                            ("IMAGEM", "Imagem (JPEG/PNG)"),
                            ("DICOM", "DICOM"),
                            ("VIDEO", "Vídeo/loop"),
                            ("TEXTO", "Texto livre"),
                            ("NUMERICO", "Valor numérico"),
                        ],
                        db_column="tipo",
                        default="IMAGEM",
                        max_length=20,
                        verbose_name="Tipo de file",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_column="descricao",
                        max_length=255,
                        verbose_name="Descrição/legenda",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        db_column="arquivo",
                        upload_to=apps.clinical.models.medical_result_file._medical_result_upload_to,
                        verbose_name="Arquivo (PDF/Imagem/DICOM)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo de result médico",
                "verbose_name_plural": "Arquivos de result médico",
                "db_table": "clinico_resultadomedicoarquivo",
                "ordering": ["-created_at"],
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "name",
                    models.CharField(db_column="nome", db_index=True, max_length=120),
                ),
                (
                    "pregnant",
                    models.BooleanField(
                        db_column="gestante", default=False, verbose_name="Gestante"
                    ),
                ),
                (
                    "gestational_age_weeks",
                    models.PositiveIntegerField(
                        blank=True,
                        db_column="idade_gestacional_semanas",
                        help_text="Preencher se a patient estiver pregnant.",
                        null=True,
                        verbose_name="Idade gestacional (semanas)",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True,
                        db_column="data_nascimento",
                        null=True,
                        verbose_name="Data de nascimento",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Masculino", "Masculino"), ("Femenino", "Femenino")],
                        db_column="genero",
                        db_index=True,
                        default="Femenino",
                        max_length=10,
                        verbose_name="Gênero",
                    ),
                ),
                (
                    "race_origin",
                    models.CharField(
                        choices=[
                            ("Branca", "Branca"),
                            ("Negra", "Negra"),
                            ("Parda", "Parda"),
                            ("Amarela", "Amarela"),
                            ("Indígena", "Indígena"),
                            ("Outro", "Outro"),
                        ],
                        db_column="raca_origem",
                        default="Negra",
                        max_length=20,
                        verbose_name="Raça / Origem",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("BI", "Bilhete de Identidade"),
                            ("PASS", "Passaporte"),
                            (
                                "DIRE",
                                "Documento de Identificação de Residente Estrangeiro",
                            ),
                            ("CC", "Carta de Condução"),
                            ("NUIT", "Número Único de Identificação Tributária"),
                            ("CE", "Cartão de Eleitor"),
                            ("CN", "Certidão de Nascimento"),
                            ("OUT", "Outro"),
                        ],
                        db_column="tipo_documento",
                        default="BI",
                        max_length=50,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        db_column="numero_id",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Número do documento",
                    ),
                ),
                (
                    "address_street",
                    models.CharField(
                        blank=True,
                        db_column="endereco_rua",
                        default="",
                        max_length=120,
                        verbose_name="Rua",
                    ),
                ),
                (
                    "address_number",
                    models.CharField(
                        blank=True,
                        db_column="endereco_numero",
                        default="",
                        max_length=30,
                        verbose_name="Número",
                    ),
                ),
                (
                    "address_neighborhood",
                    models.CharField(
                        blank=True,
                        db_column="endereco_bairro",
                        default="",
                        max_length=120,
                        verbose_name="Bairro",
                    ),
                ),
                (
                    "address_city",
                    models.CharField(
                        blank=True,
                        db_column="endereco_cidade",
                        default="",
                        max_length=120,
                        verbose_name="Cidade",
                    ),
                ),
                (
                    "address_province",
                    models.CharField(
                        blank=True,
                        db_column="endereco_provincia",
                        default="",
                        max_length=120,
                        verbose_name="Província",
                    ),
                ),
                (
                    "address_postal_code",
                    models.CharField(
                        blank=True,
                        db_column="endereco_codigo_postal",
                        default="",
                        max_length=30,
                        verbose_name="Código postal",
                    ),
                ),
                (
                    "address_country",
                    django_countries.fields.CountryField(
                        blank=True,
                        db_column="endereco_pais",
                        default="MZ",
                        max_length=2,
                        verbose_name="País",
                    ),
                ),
                (
                    "address_complement",
                    models.CharField(
                        blank=True,
                        db_column="endereco_complemento",
                        default="",
                        max_length=255,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_column="morada",
                        default="",
                        help_text="Texto livre ou resumo (auto) da address.",
                        max_length=255,
                        verbose_name="Morada",
                    ),
                ),
                (
                    "contact",
                    infrastructure.orm.fields.phone_field.PhoneField(
                        blank=True,
                        db_column="contacto",
                        max_length=9,
                        null=True,
                        verbose_name="Contacto",
                    ),
                ),
                (
                    "email",
                    infrastructure.orm.fields.email_field.NormalizedEmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Ambulatório", "Ambulatório"),
                            ("Clínica Externa", "Clínica Externa"),
                            ("Medicina Ocupacional", "Medicina Ocupacional"),
                            ("Maternidade", "Maternidade"),
                            ("Ginecologia", "Ginecologia"),
                            ("Pediatria", "Pediatria"),
                            ("Banco de Socorros", "Banco de Socorros"),
                            ("Consulta Externa", "Consulta Externa"),
                            ("Urologia", "Urologia"),
                            ("Cirurgia", "Cirurgia"),
                            ("Dentária", "Dentária"),
                            ("Oftalmologia", "Oftalmologia"),
                            ("Outro", "Outro"),
                        ],
                        db_column="proveniencia",
                        default="Clínica Externa",
                        max_length=50,
                        verbose_name="Proveniência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada",
                "verbose_name_plural": "Entradas",
                "db_table": "clinico_paciente",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "finalized",
                    models.BooleanField(db_column="finalizado", default=False),
                ),
            ],
            options={
                "db_table": "clinico_resultado",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResultItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "result_value",
                    models.DecimalField(
                        blank=True,
                        db_column="resultado_valor",
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "clinical_status",
                    models.CharField(
                        blank=True, db_column="status_clinico", max_length=20
                    ),
                ),
                (
                    "report_color",
                    models.CharField(
                        blank=True, db_column="cor_laudo", max_length=20, null=True
                    ),
                ),
                (
                    "critical_alert",
                    models.BooleanField(db_column="alerta_critico", default=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_analise", "Em Análise"),
                            ("aguardando_validacao", "Aguardando Validação"),
                            ("validado", "Validado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        db_column="estado",
                        db_index=True,
                        default="pendente",
                        max_length=30,
                    ),
                ),
                (
                    "validation_date",
                    models.DateTimeField(
                        blank=True, db_column="data_validacao", null=True
                    ),
                ),
            ],
            options={
                "db_table": "clinico_resultadoitem",
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
    ]
