# Generated by Django 4.2.29 on 2026-05-22 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from configuration.utils.django_compat import check_constraint


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('inquilinos', '0001_initial'),
        ('entidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='sample',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultitem',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultitem',
            name='exam_field',
            field=models.ForeignKey(db_column='exam_field_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='clinical.labexamfield', verbose_name='Campo do exame'),
        ),
        migrations.AddField(
            model_name='resultitem',
            name='result',
            field=models.ForeignKey(db_column='result_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.result', verbose_name='Resultado'),
        ),
        migrations.AddField(
            model_name='resultitem',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='resultitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultitem',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_items', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='resultitem',
            name='validated_by',
            field=models.ForeignKey(blank=True, db_column='validated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_results', to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
        migrations.AddField(
            model_name='result',
            name='analyst',
            field=models.ForeignKey(blank=True, db_column='analyst_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_analyst', to=settings.AUTH_USER_MODEL, verbose_name='analista'),
        ),
        migrations.AddField(
            model_name='result',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='request',
            field=models.OneToOneField(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='clinical.labrequest', verbose_name='requisição'),
        ),
        migrations.AddField(
            model_name='result',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='result',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='origin_company',
            field=models.ForeignKey(blank=True, db_column='origin_company_id', help_text='Para medicina ocupacional, indique a empresa de origin do patient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='entidades.company', verbose_name='Empresa (origin)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalresultfile',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalresultfile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalresultfile',
            name='medical_exam',
            field=models.ForeignKey(db_column='medical_exam_id', on_delete=django.db.models.deletion.PROTECT, related_name='arquivos', to='clinical.medicalexam'),
        ),
        migrations.AddField(
            model_name='medicalresultfile',
            name='request_item',
            field=models.ForeignKey(blank=True, db_column='request_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_medicos', to='clinical.labrequestitem'),
        ),
        migrations.AddField(
            model_name='medicalresultfile',
            name='result',
            field=models.ForeignKey(db_column='result_id', on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_medicos', to='clinical.result'),
        ),
        migrations.AddField(
            model_name='medicalresultfile',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='medicalresultfile',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalexamfield',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalexamfield',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalexamfield',
            name='exam',
            field=models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='clinical.medicalexam', verbose_name='Exame médico'),
        ),
        migrations.AddField(
            model_name='medicalexamfield',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='medicalexamfield',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalexam',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalexam',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalexam',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='medicalexam',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labrequestitem',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labrequestitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labrequestitem',
            name='exam',
            field=models.ForeignKey(blank=True, db_column='exam_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_request_items', to='clinical.labexam', verbose_name='Exame laboratorial'),
        ),
        migrations.AddField(
            model_name='labrequestitem',
            name='medical_exam',
            field=models.ForeignKey(blank=True, db_column='medical_exam_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_request_items', to='clinical.medicalexam', verbose_name='Exame médico'),
        ),
        migrations.AddField(
            model_name='labrequestitem',
            name='request',
            field=models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.labrequest', verbose_name='Requisição'),
        ),
        migrations.AddField(
            model_name='labrequestitem',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='labrequestitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='analyst',
            field=models.ForeignKey(blank=True, db_column='analyst_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_lab_requests', to=settings.AUTH_USER_MODEL, verbose_name='O Usuario'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='lab_requests', through='clinical.LabRequestItem', to='clinical.labexam', verbose_name='Exames'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='external_executing_company',
            field=models.ForeignKey(blank=True, db_column='external_executing_company_id', help_text='Quando a clínica terceiriza a execução para outra empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outsourced_lab_requests', to='entidades.company', verbose_name='Empresa executora externa'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='requesting_company',
            field=models.ForeignKey(blank=True, db_column='requesting_company_id', help_text='Empresa que subcontrata os serviços (ex.: medicina ocupacional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_lab_requests', to='entidades.company', verbose_name='Empresa solicitante'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='samples',
            field=models.ManyToManyField(blank=True, db_table='clinico_requisicaoanalise_amostras', related_name='lab_requests', to='clinical.sample', verbose_name='Amostras agregadas'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labexamfield',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labexamfield',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labexamfield',
            name='exam',
            field=models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='clinical.labexam', verbose_name='Exame laboratorial'),
        ),
        migrations.AddField(
            model_name='labexamfield',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='labexamfield',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labexam',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labexam',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labexam',
            name='sample_options',
            field=models.ManyToManyField(blank=True, db_table='clinico_exame_opcoes_amostras', help_text='Amostras alternativas aceites pelo exame. O tipo de amostra principal também é considerado automaticamente.', related_name='exam_sample_options', to='clinical.sample', verbose_name='Opções de amostra'),
        ),
        migrations.AddField(
            model_name='labexam',
            name='sample_type',
            field=models.ForeignKey(db_column='sample_id', on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='clinical.sample', verbose_name='Tipo de amostra'),
        ),
        migrations.AddField(
            model_name='labexam',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='labexam',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalreference',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalreference',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalreference',
            name='exam_field',
            field=models.ForeignKey(db_column='exam_field_id', on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='clinical.labexamfield', verbose_name='Campo de exame'),
        ),
        migrations.AddField(
            model_name='clinicalreference',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='clinicalreference',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='clinicalevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalevent',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalevent',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='eventos_clinicos', to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='clinicalevent',
            name='request',
            field=models.ForeignKey(blank=True, db_column='request_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_clinicos', to='clinical.labrequest', verbose_name='Requisição'),
        ),
        migrations.AddField(
            model_name='clinicalevent',
            name='result',
            field=models.ForeignKey(blank=True, db_column='result_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_clinicos', to='clinical.resultitem', verbose_name='Resultado'),
        ),
        migrations.AddField(
            model_name='clinicalevent',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='clinicalevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['tenant', 'name'], name='clinico_amo_tenant__303d68_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['bottle_type'], name='clinico_amo_bottle__174c94_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['fasting_required'], name='clinico_amo_fasting_f09229_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resultitem',
            unique_together={('result', 'exam_field')},
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant'], name='clinico_pac_tenant__1280a2_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name'], name='clinico_pac_name_6cfb6e_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['document_number'], name='clinico_pac_documen_b4f97c_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['gender'], name='clinico_pac_gender_b05b54_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['blood_type'], name='clinico_pac_blood_t_d80c17_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_replacement_donor_inapt'], name='clinico_pac_is_repl_f0a41b_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['birth_date'], name='clinico_pac_birth_d_dedb9f_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['origin_company'], name='clinico_pac_origin__868aae_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalexam',
            index=models.Index(fields=['sector', 'deleted'], name='clinico_exa_sector_e0b457_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalexam',
            index=models.Index(fields=['method'], name='clinico_exa_method_590699_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicalexam',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('sector', 'name'), name='unique_name_medical_exam_por_sector_nao_deleted'),
        ),
        migrations.AddConstraint(
            model_name='medicalexam',
            constraint=check_constraint(condition=models.Q(('turnaround_hours__gt', 0)), name='exm_turnaround_hours_positivo'),
        ),
        migrations.AddConstraint(
            model_name='medicalexam',
            constraint=check_constraint(condition=models.Q(('price__gte', 0)), name='exm_price_nao_negativo'),
        ),
        migrations.AddIndex(
            model_name='labrequestitem',
            index=models.Index(fields=['request', 'exam'], name='clinico_req_request_f19e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequestitem',
            index=models.Index(fields=['request', 'medical_exam'], name='clinico_req_request_1f7c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='labexam',
            index=models.Index(fields=['sector', 'deleted'], name='clinico_exa_sector_cc56ca_idx'),
        ),
        migrations.AddIndex(
            model_name='labexam',
            index=models.Index(fields=['method'], name='clinico_exa_method_92e5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='labexam',
            index=models.Index(fields=['sample_type'], name='clinico_exa_sample__665cd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='labexam',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('sector', 'name'), name='unique_name_exam_por_sector_nao_deleted'),
        ),
        migrations.AddConstraint(
            model_name='labexam',
            constraint=check_constraint(condition=models.Q(('turnaround_hours__gt', 0)), name='turnaround_hours_positivo'),
        ),
        migrations.AddConstraint(
            model_name='labexam',
            constraint=check_constraint(condition=models.Q(('price__gte', 0)), name='price_nao_negativo'),
        ),
        migrations.AddIndex(
            model_name='clinicalreference',
            index=models.Index(fields=['exam_field'], name='clinico_ref_exam_fi_51dfe2_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalreference',
            index=models.Index(fields=['sex'], name='clinico_ref_sex_df69f8_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalreference',
            index=models.Index(fields=['minimum_age_days', 'maximum_age_days'], name='clinico_ref_minimum_04c3ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicalreference',
            constraint=check_constraint(condition=models.Q(('maximum_age_days__gte', models.F('minimum_age_days')), ('minimum_age_days__isnull', True), ('maximum_age_days__isnull', True), _connector='OR'), name='ref_idade_intervalo_valido'),
        ),
        migrations.AddConstraint(
            model_name='clinicalreference',
            constraint=check_constraint(condition=models.Q(('maximum_value__gte', models.F('minimum_value')), ('minimum_value__isnull', True), ('maximum_value__isnull', True), _connector='OR'), name='ref_value_intervalo_valido'),
        ),
        migrations.AddConstraint(
            model_name='clinicalreference',
            constraint=check_constraint(condition=models.Q(('critical_high__gte', models.F('critical_low')), ('critical_low__isnull', True), ('critical_high__isnull', True), _connector='OR'), name='ref_critico_intervalo_valido'),
        ),
        migrations.AddIndex(
            model_name='clinicalevent',
            index=models.Index(fields=['patient'], name='clinico_eve_patient_190731_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalevent',
            index=models.Index(fields=['event_type'], name='clinico_eve_event_t_b57a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalevent',
            index=models.Index(fields=['created_at'], name='clinico_eve_created_c1cbb9_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalevent',
            index=models.Index(fields=['request'], name='clinico_eve_request_398b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalevent',
            index=models.Index(fields=['result'], name='clinico_eve_result__61e0cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicalevent',
            constraint=check_constraint(condition=models.Q(('request__isnull', False), ('result__isnull', False), _connector='OR'), name='evento_clinico_deve_ter_contexto'),
        ),
    ]
