# Generated by Django 4.2.29 on 2026-03-18 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquilinos', '0001_initial'),
        ('entidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoitem',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultadoitem',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultadoitem',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultadoitem',
            name='exame_campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='clinico.examecampo'),
        ),
        migrations.AddField(
            model_name='resultadoitem',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='resultadoitem',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='clinico.resultado'),
        ),
        migrations.AddField(
            model_name='resultadoitem',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_validados', to=settings.AUTH_USER_MODEL, verbose_name='Resultado'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='analista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultado',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultado',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultado',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultado',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='requisicao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='clinico.requisicaoanalise'),
        ),
        migrations.AddField(
            model_name='requisicaoitem',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisicaoitem',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisicaoitem',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisicaoitem',
            name='exame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='clinico.exame'),
        ),
        migrations.AddField(
            model_name='requisicaoitem',
            name='exame_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='clinico.examemedico'),
        ),
        migrations.AddField(
            model_name='requisicaoitem',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='requisicaoitem',
            name='requisicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='clinico.requisicaoanalise'),
        ),
        migrations.AddField(
            model_name='requisicaoanalise',
            name='analista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_processadas', to=settings.AUTH_USER_MODEL, verbose_name='O Usuario'),
        ),
        migrations.AddField(
            model_name='requisicaoanalise',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisicaoanalise',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisicaoanalise',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisicaoanalise',
            name='empresa_executora_externa',
            field=models.ForeignKey(blank=True, help_text='Quando a clínica terceiriza a execução para outra empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_terceirizadas', to='entidades.empresa', verbose_name='Empresa executora externa'),
        ),
        migrations.AddField(
            model_name='requisicaoanalise',
            name='empresa_solicitante',
            field=models.ForeignKey(blank=True, help_text='Empresa que subcontrata os serviços (ex.: medicina ocupacional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_solicitadas', to='entidades.empresa', verbose_name='Empresa solicitante'),
        ),
        migrations.AddField(
            model_name='requisicaoanalise',
            name='exames',
            field=models.ManyToManyField(through='clinico.RequisicaoItem', to='clinico.exame'),
        ),
        migrations.AddField(
            model_name='requisicaoanalise',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='requisicaoanalise',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to='clinico.paciente'),
        ),
        migrations.AddField(
            model_name='referenciaclinica',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referenciaclinica',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referenciaclinica',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referenciaclinica',
            name='exame_campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='clinico.examecampo'),
        ),
        migrations.AddField(
            model_name='referenciaclinica',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='empresa_origem',
            field=models.ForeignKey(blank=True, help_text='Para medicina ocupacional, indique a empresa de origem do paciente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='entidades.empresa', verbose_name='Empresa (origem)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='historicoclinico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinico.paciente'),
        ),
        migrations.AddField(
            model_name='examemedicocampo',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examemedicocampo',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examemedicocampo',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examemedicocampo',
            name='exame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='clinico.examemedico', verbose_name='Exame médico'),
        ),
        migrations.AddField(
            model_name='examemedicocampo',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='examemedico',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examemedico',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examemedico',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examemedico',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='examecampo',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examecampo',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examecampo',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examecampo',
            name='exame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='clinico.exame', verbose_name='Exame'),
        ),
        migrations.AddField(
            model_name='examecampo',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='exame',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exame',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exame',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exame',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='eventoclinico',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoclinico',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoclinico',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoclinico',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='eventoclinico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_clinicos', to='clinico.paciente'),
        ),
        migrations.AddField(
            model_name='eventoclinico',
            name='requisicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_clinicos', to='clinico.requisicaoanalise'),
        ),
        migrations.AddField(
            model_name='eventoclinico',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_clinicos', to='clinico.resultadoitem'),
        ),
        migrations.AlterUniqueTogether(
            name='resultadoitem',
            unique_together={('resultado', 'exame_campo')},
        ),
        migrations.AddIndex(
            model_name='requisicaoitem',
            index=models.Index(fields=['requisicao', 'exame'], name='clinico_req_requisi_9607c6_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaoitem',
            index=models.Index(fields=['requisicao', 'exame_medico'], name='clinico_req_requisi_d795ac_idx'),
        ),
        migrations.AddIndex(
            model_name='referenciaclinica',
            index=models.Index(fields=['exame_campo'], name='clinico_ref_exame_c_4f26c7_idx'),
        ),
        migrations.AddIndex(
            model_name='referenciaclinica',
            index=models.Index(fields=['sexo'], name='clinico_ref_sexo_5e6d41_idx'),
        ),
        migrations.AddIndex(
            model_name='referenciaclinica',
            index=models.Index(fields=['idade_minima_dias', 'idade_maxima_dias'], name='clinico_ref_idade_m_b6ce91_idx'),
        ),
        migrations.AddConstraint(
            model_name='referenciaclinica',
            constraint=models.CheckConstraint(check=models.Q(('idade_maxima_dias__gte', models.F('idade_minima_dias')), ('idade_minima_dias__isnull', True), ('idade_maxima_dias__isnull', True), _connector='OR'), name='ref_idade_intervalo_valido'),
        ),
        migrations.AddConstraint(
            model_name='referenciaclinica',
            constraint=models.CheckConstraint(check=models.Q(('valor_maximo__gte', models.F('valor_minimo')), ('valor_minimo__isnull', True), ('valor_maximo__isnull', True), _connector='OR'), name='ref_valor_intervalo_valido'),
        ),
        migrations.AddConstraint(
            model_name='referenciaclinica',
            constraint=models.CheckConstraint(check=models.Q(('critico_alto__gte', models.F('critico_baixo')), ('critico_baixo__isnull', True), ('critico_alto__isnull', True), _connector='OR'), name='ref_critico_intervalo_valido'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['inquilino'], name='clinico_pac_inquili_f10385_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['nome'], name='clinico_pac_nome_359cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['numero_id'], name='clinico_pac_numero__9173c8_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['genero'], name='clinico_pac_genero_c82f15_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['data_nascimento'], name='clinico_pac_data_na_620600_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['empresa_origem'], name='clinico_pac_empresa_1c6414_idx'),
        ),
        migrations.AddIndex(
            model_name='examemedico',
            index=models.Index(fields=['setor', 'deletado'], name='clinico_exa_setor_b6fcd0_idx'),
        ),
        migrations.AddIndex(
            model_name='examemedico',
            index=models.Index(fields=['metodo'], name='clinico_exa_metodo_726154_idx'),
        ),
        migrations.AddConstraint(
            model_name='examemedico',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False)), fields=('setor', 'nome'), name='unique_nome_exame_medico_por_setor_nao_deletado'),
        ),
        migrations.AddConstraint(
            model_name='examemedico',
            constraint=models.CheckConstraint(check=models.Q(('trl_horas__gt', 0)), name='exm_trl_horas_positivo'),
        ),
        migrations.AddConstraint(
            model_name='examemedico',
            constraint=models.CheckConstraint(check=models.Q(('preco__gte', 0)), name='exm_preco_nao_negativo'),
        ),
        migrations.AddIndex(
            model_name='exame',
            index=models.Index(fields=['setor', 'deletado'], name='clinico_exa_setor_acff4d_idx'),
        ),
        migrations.AddIndex(
            model_name='exame',
            index=models.Index(fields=['metodo'], name='clinico_exa_metodo_77d177_idx'),
        ),
        migrations.AddConstraint(
            model_name='exame',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False)), fields=('setor', 'nome'), name='unique_nome_exame_por_setor_nao_deletado'),
        ),
        migrations.AddConstraint(
            model_name='exame',
            constraint=models.CheckConstraint(check=models.Q(('trl_horas__gt', 0)), name='trl_horas_positivo'),
        ),
        migrations.AddConstraint(
            model_name='exame',
            constraint=models.CheckConstraint(check=models.Q(('preco__gte', 0)), name='preco_nao_negativo'),
        ),
        migrations.AddIndex(
            model_name='eventoclinico',
            index=models.Index(fields=['paciente'], name='clinico_eve_pacient_6880f6_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoclinico',
            index=models.Index(fields=['tipo_evento'], name='clinico_eve_tipo_ev_980b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoclinico',
            index=models.Index(fields=['criado_em'], name='clinico_eve_criado__db5346_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoclinico',
            index=models.Index(fields=['requisicao'], name='clinico_eve_requisi_d73773_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoclinico',
            index=models.Index(fields=['resultado'], name='clinico_eve_resulta_5d0c9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventoclinico',
            constraint=models.CheckConstraint(check=models.Q(('requisicao__isnull', False), ('resultado__isnull', False), _connector='OR'), name='evento_clinico_deve_ter_contexto'),
        ),
    ]
