# Generated by Django 4.2.16 on 2026-03-18 20:33

import apps.clinical.models.medical_result_file
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import infrastructure.orm.fields.medical_exam_method_field
import infrastructure.orm.fields.medical_exam_sector_field
import core.mixins.tenant_propagation


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinico', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examemedico',
            name='metodo',
            field=infrastructure.orm.fields.medical_exam_method_field.MedicalExamMethodField(choices=[('USG', 'Ultrassonografia / Ecografia'), ('RX', 'Raio-X Convencional'), ('CT', 'Tomografia Computorizada (CT)'), ('RM', 'Ressonância Magnética (RM)'), ('MG', 'Mamografia'), ('DXA', 'Densitometria Óssea (DXA)'), ('ECO', 'Ecocardiograma'), ('ECG', 'Eletrocardiograma (ECG)'), ('HOLTER', 'Holter'), ('MAPA', 'MAPA (PA 24h)'), ('EEG', 'Eletroencefalograma (EEG)'), ('ENDO', 'Endoscopia'), ('COLONO', 'Colonoscopia'), ('ANGIO', 'Angiografia'), ('MN', 'Medicina Nuclear / Cintilografia'), ('OUT', 'Outro')], db_index=True, max_length=30, verbose_name='Método do exame (imagem/diagnóstico)'),
        ),
        migrations.AlterField(
            model_name='examemedico',
            name='setor',
            field=infrastructure.orm.fields.medical_exam_sector_field.MedicalExamSectorField(blank=True, choices=[('Radiologia', 'Radiologia'), ('DiagnosticoImagem', 'Diagnóstico por Imagem'), ('Cardiologia', 'Cardiologia'), ('GinecoObstetricia', 'Ginecologia/Obstetrícia'), ('Ortopedia', 'Ortopedia/Traumato'), ('Neurologia', 'Neurologia'), ('Otorrino', 'Otorrinolaringologia'), ('Oftalmologia', 'Oftalmologia'), ('MedicinaNuclear', 'Medicina Nuclear'), ('Endoscopia', 'Endoscopia'), ('Outro', 'Outro')], db_index=True, max_length=40, null=True, verbose_name='Setor do exame (imagem/diagnóstico)'),
        ),
        migrations.AlterField(
            model_name='examemedicocampo',
            name='tipo',
            field=models.CharField(choices=[('PDF', 'Laudo/Relatório (PDF)'), ('IMAGEM', 'Imagem (JPEG/PNG)'), ('DICOM', 'DICOM'), ('VIDEO', 'Vídeo/loop'), ('TEXTO', 'Texto livre'), ('NUMERICO', 'Valor numérico')], max_length=20, verbose_name='Tipo de parâmetro/arquivo'),
        ),
        migrations.CreateModel(
            name='ResultadoMedicoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('tipo', models.CharField(choices=[('PDF', 'Laudo/Relatório (PDF)'), ('IMAGEM', 'Imagem (JPEG/PNG)'), ('DICOM', 'DICOM'), ('VIDEO', 'Vídeo/loop'), ('TEXTO', 'Texto livre'), ('NUMERICO', 'Valor numérico')], default='IMAGEM', max_length=20, verbose_name='Tipo de arquivo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição/legenda')),
                ('arquivo', models.FileField(upload_to=apps.clinical.models.resultado_medico_arquivo._resultado_medico_upload_to, verbose_name='Arquivo (PDF/Imagem/DICOM)')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('exame_medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos', to='clinico.examemedico')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
                ('requisicao_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_medicos', to='clinico.requisicaoitem')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_medicos', to='clinico.resultado')),
            ],
            options={
                'verbose_name': 'Arquivo de resultado médico',
                'verbose_name_plural': 'Arquivos de resultado médico',
                'ordering': ['-criado_em'],
            },
            bases=(core.mixins.tenant_propagation.PropagarInquilinoMixin, models.Model),
        ),
    ]

