# Generated by Django 4.2.29 on 2026-05-25 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalhistory',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, related_name='lab_requests', to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='result',
            name='request',
            field=models.OneToOneField(db_column='request_id', on_delete=django.db.models.deletion.PROTECT, related_name='result', to='clinical.labrequest', verbose_name='requisição'),
        ),
    ]
