# Generated by Django 4.2.16 on 2026-03-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0003_alter_examemedico_metodo_alter_examemedico_setor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examemedicocampo',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='examemedicocampo',
            name='referencia_min',
        ),
        migrations.RemoveField(
            model_name='examemedicocampo',
            name='referencia_max',
        ),
        migrations.RemoveField(
            model_name='examemedicocampo',
            name='critico_min',
        ),
        migrations.RemoveField(
            model_name='examemedicocampo',
            name='critico_max',
        ),
        migrations.RemoveField(
            model_name='examemedicocampo',
            name='delta_max',
        ),
    ]
