# Generated by Django 4.2.29 on 2026-05-26 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_initial'),
        ('clinical', '0003_alter_clinicalhistory_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labexam',
            name='turnaround_hours',
            field=models.PositiveIntegerField(db_column='turnaround_hours', default=24, help_text='Tempo de resposta em horas.', verbose_name='Tempo de resposta (em horas)'),
        ),
        migrations.AlterField(
            model_name='medicalexam',
            name='turnaround_hours',
            field=models.PositiveIntegerField(db_column='turnaround_hours', default=24, help_text='Tempo de resposta em horas.', verbose_name='Tempo de resposta (em horas)'),
        ),
        migrations.AlterField(
            model_name='medicalexamfield',
            name='type',
            field=models.CharField(choices=[('PDF', 'Laudo/Relatório (PDF)'), ('IMAGEM', 'Imagem (JPEG/PNG)'), ('DICOM', 'DICOM'), ('VIDEO', 'Vídeo/loop'), ('TEXTO', 'Texto livre'), ('NUMERICO', 'Valor numérico')], db_column='type', max_length=20, verbose_name='Tipo de parâmetro/arquivo'),
        ),
        migrations.AlterField(
            model_name='medicalresultfile',
            name='type',
            field=models.CharField(choices=[('PDF', 'Laudo/Relatório (PDF)'), ('IMAGEM', 'Imagem (JPEG/PNG)'), ('DICOM', 'DICOM'), ('VIDEO', 'Vídeo/loop'), ('TEXTO', 'Texto livre'), ('NUMERICO', 'Valor numérico')], db_column='type', default='IMAGEM', max_length=20, verbose_name='Tipo de arquivo'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gestational_age_weeks',
            field=models.PositiveIntegerField(blank=True, db_column='gestational_age_weeks', help_text='Preencher se a paciente estiver grávida.', null=True, verbose_name='Idade gestacional (semanas)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='origin_company',
            field=models.ForeignKey(blank=True, db_column='origin_company_id', help_text='Para medicina ocupacional, indique a empresa de origem do paciente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='entidades.company', verbose_name='Empresa de origem'),
        ),
    ]
