# Generated by Django 5.1 on 2026-03-26 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0003_resultitem_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultitem",
            name="clinical_status",
            field=models.CharField(
                blank=True,
                db_column="clinical_status",
                max_length=20,
                verbose_name="Status clínico",
            ),
        ),
        migrations.AlterField(
            model_name="resultitem",
            name="critical_alert",
            field=models.BooleanField(
                db_column="critical_alert", default=False, verbose_name="Alerta crítico"
            ),
        ),
        migrations.AlterField(
            model_name="resultitem",
            name="exam_field",
            field=models.ForeignKey(
                db_column="exam_field_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="clinical.labexamfield",
                verbose_name="Campo do exame",
            ),
        ),
        migrations.AlterField(
            model_name="resultitem",
            name="report_color",
            field=models.CharField(
                blank=True,
                db_column="report_color",
                max_length=20,
                null=True,
                verbose_name="Cor para relatório",
            ),
        ),
        migrations.AlterField(
            model_name="resultitem",
            name="result",
            field=models.ForeignKey(
                db_column="result_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="clinical.result",
                verbose_name="Resultado",
            ),
        ),
        migrations.AlterField(
            model_name="resultitem",
            name="result_value",
            field=models.DecimalField(
                blank=True,
                db_column="result_value",
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valor do resultado",
            ),
        ),
        migrations.AlterField(
            model_name="resultitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em_analise", "Em Análise"),
                    ("aguardando_validacao", "Aguardando Validação"),
                    ("validado", "Validado"),
                    ("rejeitado", "Rejeitado"),
                ],
                db_column="status",
                db_index=True,
                default="pendente",
                max_length=30,
                verbose_name="Status do resultado",
            ),
        ),
        migrations.AlterField(
            model_name="resultitem",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="validated_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_results",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validado por",
            ),
        ),
        migrations.AlterField(
            model_name="resultitem",
            name="validation_date",
            field=models.DateTimeField(
                blank=True,
                db_column="validation_date",
                null=True,
                verbose_name="Data de validação",
            ),
        ),
    ]
