# Generated by Django 5.1 on 2026-03-25 23:02

import core.mixins.tenant_propagation
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clinico",
            "0003_rename_clinico_ref_exame_c_4f26c7_idx_clinico_ref_exam_fi_51dfe2_idx_and_more",
        ),
        (
            "inquilinos",
            "0002_rename_inquilinos__tipo_856ce4_idx_inquilinos__type_fdb81e_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(db_column="description")),
                (
                    "event_date",
                    models.DateTimeField(auto_now_add=True, db_column="event_date"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinico.patient",
                    ),
                ),
            ],
            options={
                "db_table": "clinico_historicoclinico",
            },
        ),
        migrations.CreateModel(
            name="ClinicalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "name",
                    models.CharField(db_column="name", db_index=True, max_length=120),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("result_criado", "Resultado Criado"),
                            ("result_interpretado", "Resultado Interpretado"),
                            ("result_validado", "Resultado Validado"),
                            ("result_critico", "Resultado Crítico"),
                            ("request_criada", "Requisição Criada"),
                            ("request_processamento", "Requisição em Processamento"),
                            ("request_validada", "Requisição Validada"),
                            ("request_cancelada", "Requisição Cancelada"),
                            ("medication_prescrita", "Medicação Prescrita"),
                            ("medication_administrada", "Medicação Administrada"),
                            ("observation_clinica", "Observação Clínica"),
                            ("diagnóstico", "Diagnóstico"),
                        ],
                        db_column="event_type",
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(db_column="description")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_clinicos",
                        to="clinico.patient",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        db_column="request_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_clinicos",
                        to="clinico.labrequest",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        db_column="result_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_clinicos",
                        to="clinico.resultitem",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "clinico_eventoclinico",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient"], name="clinico_eve_patient_190731_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="clinico_eve_event_t_b57a2b_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="clinico_eve_created_c1cbb9_idx"
                    ),
                    models.Index(
                        fields=["request"], name="clinico_eve_request_398b0f_idx"
                    ),
                    models.Index(
                        fields=["result"], name="clinico_eve_result__61e0cc_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("request__isnull", False),
                            ("result__isnull", False),
                            _connector="OR",
                        ),
                        name="evento_clinico_deve_ter_contexto",
                    )
                ],
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
    ]
