# Generated by Django 5.1 on 2026-03-26 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0004_clinicalhistory_clinicalevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clinicalevent",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Evento clínico",
                "verbose_name_plural": "Eventos clínicos",
            },
        ),
        migrations.AlterModelOptions(
            name="clinicalhistory",
            options={
                "verbose_name": "Histórico clínico",
                "verbose_name_plural": "Históricos clínicos",
            },
        ),
        migrations.AlterModelOptions(
            name="clinicalreference",
            options={
                "ordering": ["exam_field", "sex", "minimum_age_days"],
                "verbose_name": "Referência clínica",
                "verbose_name_plural": "Referências clínicas",
            },
        ),
        migrations.AlterField(
            model_name="clinicalevent",
            name="description",
            field=models.TextField(db_column="description", verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="clinicalevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("result_criado", "Resultado Criado"),
                    ("result_interpretado", "Resultado Interpretado"),
                    ("result_validado", "Resultado Validado"),
                    ("result_critico", "Resultado Crítico"),
                    ("request_criada", "Requisição Criada"),
                    ("request_processamento", "Requisição em Processamento"),
                    ("request_validada", "Requisição Validada"),
                    ("request_cancelada", "Requisição Cancelada"),
                    ("medication_prescrita", "Medicação Prescrita"),
                    ("medication_administrada", "Medicação Administrada"),
                    ("observation_clinica", "Observação Clínica"),
                    ("diagnóstico", "Diagnóstico"),
                ],
                db_column="event_type",
                db_index=True,
                max_length=50,
                verbose_name="Tipo de evento",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalevent",
            name="patient",
            field=models.ForeignKey(
                db_column="patient_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_clinicos",
                to="clinical.patient",
                verbose_name="Paciente",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalevent",
            name="request",
            field=models.ForeignKey(
                blank=True,
                db_column="request_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_clinicos",
                to="clinical.labrequest",
                verbose_name="Requisição",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalevent",
            name="result",
            field=models.ForeignKey(
                blank=True,
                db_column="result_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_clinicos",
                to="clinical.resultitem",
                verbose_name="Resultado",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalhistory",
            name="description",
            field=models.TextField(db_column="description", verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="clinicalhistory",
            name="event_date",
            field=models.DateTimeField(
                auto_now_add=True, db_column="event_date", verbose_name="Data do evento"
            ),
        ),
        migrations.AlterField(
            model_name="clinicalhistory",
            name="patient",
            field=models.ForeignKey(
                db_column="patient_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="clinical.patient",
                verbose_name="Paciente",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreference",
            name="critical_high",
            field=models.DecimalField(
                blank=True,
                db_column="critical_high",
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Limite crítico alto",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreference",
            name="critical_low",
            field=models.DecimalField(
                blank=True,
                db_column="critical_low",
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Limite crítico baixo",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreference",
            name="exam_field",
            field=models.ForeignKey(
                db_column="exam_field_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referencias",
                to="clinical.labexamfield",
                verbose_name="Campo de exame",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreference",
            name="maximum_age_days",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="maximum_age_days",
                help_text="Idade máxima em dias.",
                null=True,
                verbose_name="Idade máxima (dias)",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreference",
            name="maximum_value",
            field=models.DecimalField(
                blank=True,
                db_column="maximum_value",
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor máximo",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreference",
            name="minimum_age_days",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="minimum_age_days",
                help_text="Idade mínima em dias.",
                null=True,
                verbose_name="Idade mínima (dias)",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreference",
            name="minimum_value",
            field=models.DecimalField(
                blank=True,
                db_column="minimum_value",
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor mínimo",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreference",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("Masculino", "Masculino"), ("Femenino", "Femenino")],
                db_column="sex",
                help_text="Se vazio, aplica-se a ambos os sexos.",
                max_length=10,
                null=True,
                verbose_name="Sexo",
            ),
        ),
    ]
