# Generated by Django 5.2.12 on 2026-04-20 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0006_patient_blood_type_and_more"),
        ("entidades", "0003_alter_company_contacts"),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_replacement_donor_inapt",
            field=models.BooleanField(
                db_column="is_replacement_donor_inapt",
                db_index=True,
                default=False,
                verbose_name="Repositor inapto",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="replacement_donor_inapt_at",
            field=models.DateTimeField(
                blank=True,
                db_column="replacement_donor_inapt_at",
                null=True,
                verbose_name="Repositor inapto em",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="replacement_donor_inapt_reason",
            field=models.TextField(
                blank=True,
                db_column="replacement_donor_inapt_reason",
                default="",
                verbose_name="Motivo de inapto (reposicao)",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["is_replacement_donor_inapt"],
                name="clinico_pac_is_repl_f0a41b_idx",
            ),
        ),
    ]
