# Generated by Django 4.2.29 on 2026-04-28 22:10

from decimal import Decimal

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0001_initial'),
        ('clinical', '0007_patient_is_replacement_donor_inapt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('bottle_type', models.CharField(choices=[('TUBO_SECO', 'Tubo seco (soro)'), ('TUBO_EDTA', 'Tubo EDTA'), ('TUBO_CITRATO', 'Tubo citrato'), ('TUBO_FLUORETO', 'Tubo fluoreto'), ('FRASCO_URINA', 'Frasco de urina'), ('FRASCO_FEZES', 'Frasco de fezes'), ('FRASCO_ESTERIL', 'Frasco estéril'), ('HEMOCULTURA', 'Frasco de hemocultura'), ('OUTRO', 'Outro')], db_column='bottle_type', db_index=True, default='TUBO_SECO', max_length=30, verbose_name='Tipo de frasco')),
                ('cap_color', models.CharField(blank=True, db_column='cap_color', default='', help_text='Ex.: roxa, vermelha, azul, amarela.', max_length=80, verbose_name='Cor da tampa')),
                ('minimum_volume_ml', models.DecimalField(db_column='minimum_volume_ml', decimal_places=2, default=Decimal('1.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Volume mínimo (ml)')),
                ('fasting_required', models.BooleanField(db_column='fasting_required', db_index=True, default=False, verbose_name='Requer jejum')),
                ('fasting_hours', models.PositiveIntegerField(db_column='fasting_hours', default=0, verbose_name='Horas de jejum')),
                ('storage_temperature', models.CharField(blank=True, db_column='storage_temperature', default='2-8°C', help_text='Ex.: ambiente, refrigerado (2-8°C), congelado (-20°C).', max_length=120, verbose_name='Conservação')),
                ('stability_hours', models.PositiveIntegerField(db_column='stability_hours', default=24, verbose_name='Estabilidade (horas)')),
                ('anticoagulant', models.CharField(blank=True, db_column='anticoagulant', default='', max_length=120, verbose_name='Anticoagulante/reagente')),
                ('collection_instructions', models.TextField(blank=True, db_column='collection_instructions', default='', verbose_name='Instruções de coleta')),
            ],
            options={
                'verbose_name': 'Amostra',
                'verbose_name_plural': 'Amostras',
                'db_table': 'clinico_amostra',
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='sample',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labexam',
            name='sample_type',
            field=models.ForeignKey(blank=True, db_column='sample_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='clinical.sample', verbose_name='Tipo de amostra'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='samples',
            field=models.ManyToManyField(blank=True, db_table='clinico_requisicaoanalise_amostras', related_name='lab_requests', to='clinical.sample', verbose_name='Amostras agregadas'),
        ),
        migrations.AddIndex(
            model_name='labexam',
            index=models.Index(fields=['sample_type'], name='clinico_exa_sample__665cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['tenant', 'name'], name='clinico_amo_tenant__303d68_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['bottle_type'], name='clinico_amo_bottle__174c94_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['fasting_required'], name='clinico_amo_fasting_f09229_idx'),
        ),
    ]
