# Generated by Django 4.2.29 on 2026-04-28 22:10

from django.db import migrations, models
import django.db.models.deletion


def _backfill_sample_requirements(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Sample = apps.get_model("clinical", "Sample")
    LabExam = apps.get_model("clinical", "LabExam")
    LabRequest = apps.get_model("clinical", "LabRequest")
    LabRequestItem = apps.get_model("clinical", "LabRequestItem")

    default_sample_ids: dict[int, int] = {}
    tenant_ids = (
        LabExam.objects.using(db_alias)
        .filter(sample_type__isnull=True, tenant_id__isnull=False)
        .values_list("tenant_id", flat=True)
        .distinct()
    )

    for tenant_id in tenant_ids:
        sample = (
            Sample.objects.using(db_alias)
            .filter(tenant_id=tenant_id, name="Sangue total", deleted=False)
            .order_by("id")
            .first()
        )
        if sample is None:
            sample = Sample.objects.using(db_alias).create(
                tenant_id=tenant_id,
                name="Sangue total",
                bottle_type="TUBO_EDTA",
                minimum_volume_ml="1.00",
                fasting_required=False,
                fasting_hours=0,
                storage_temperature="2-8°C",
                stability_hours=24,
                anticoagulant="",
                collection_instructions="",
            )
        default_sample_ids[tenant_id] = sample.id

    for tenant_id, sample_id in default_sample_ids.items():
        (
            LabExam.objects.using(db_alias)
            .filter(sample_type__isnull=True, tenant_id=tenant_id)
            .update(sample_type_id=sample_id)
        )

    through_model = LabRequest.samples.through
    request_field_name = next(
        field.name
        for field in through_model._meta.fields
        if getattr(field, "is_relation", False) and getattr(getattr(field, "related_model", None), "_meta", None)
        and field.related_model._meta.model_name == "labrequest"
    )
    sample_field_name = next(
        field.name
        for field in through_model._meta.fields
        if getattr(field, "is_relation", False) and getattr(getattr(field, "related_model", None), "_meta", None)
        and field.related_model._meta.model_name == "sample"
    )

    pairs = (
        LabRequestItem.objects.using(db_alias)
        .filter(
            deleted=False,
            request__deleted=False,
            exam__isnull=False,
            exam__deleted=False,
            exam__sample_type__isnull=False,
        )
        .values_list("request_id", "exam__sample_type_id")
        .distinct()
    )

    for request_id, sample_id in pairs:
        through_model.objects.using(db_alias).get_or_create(
            **{
                f"{request_field_name}_id": request_id,
                f"{sample_field_name}_id": sample_id,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0008_add_samples_model_and_links'),
    ]

    operations = [
        migrations.RunPython(
            _backfill_sample_requirements,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='labexam',
            name='sample_type',
            field=models.ForeignKey(db_column='sample_id', on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='clinical.sample', verbose_name='Tipo de amostra'),
        ),
    ]
