# Generated by Django 4.2.29 on 2026-04-28 22:31

from django.db import migrations, models


def _backfill_request_fasting_fields(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    LabRequest = apps.get_model("clinical", "LabRequest")
    LabRequestItem = apps.get_model("clinical", "LabRequestItem")

    items_qs = LabRequestItem.objects.using(db_alias).filter(
        deleted=False,
        request__deleted=False,
        exam__isnull=False,
        exam__deleted=False,
        exam__sample_type__isnull=False,
        exam__sample_type__deleted=False,
    )

    # Não usar BoolOr aqui: ele gera BOOL_OR no SQLite e quebra testes locais.
    # exists() por request mantém a migração portável entre SQLite e PostgreSQL.
    stats = items_qs.values("request_id").annotate(
        max_fasting_hours=models.Max("exam__sample_type__fasting_hours")
    )

    for row in stats:
        requires_fasting = items_qs.filter(
            request_id=row["request_id"],
            exam__sample_type__fasting_required=True,
        ).exists()
        fasting_hours = int(row.get("max_fasting_hours") or 0) if requires_fasting else 0
        (
            LabRequest._base_manager.using(db_alias)
            .filter(id=row["request_id"])
            .update(requires_fasting=requires_fasting, fasting_hours=fasting_hours)
        )

class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0009_require_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='fasting_hours',
            field=models.PositiveIntegerField(db_column='fasting_hours', default=0, verbose_name='Horas de jejum'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='requires_fasting',
            field=models.BooleanField(db_column='requires_fasting', db_index=True, default=False, verbose_name='Requer jejum'),
        ),
        migrations.RunPython(
            _backfill_request_fasting_fields,
            migrations.RunPython.noop,
        ),
    ]
