# Generated by Django 4.2.16 on 2026-06-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0010_alter_labexamfield_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labexamfield',
            name='unit',
            field=models.CharField(choices=[('g/dl', 'g/dl'), ('g/L', 'g/L'), ('mg/dl', 'mg/dl'), ('mg/L', 'mg/L'), ('mg/24h', 'mg/24h'), ('µg/dL', 'µg/dL'), ('µg/L', 'µg/L'), ('µg/mL', 'µg/mL'), ('ng/mL', 'ng/mL'), ('ng/dL', 'ng/dL'), ('pg/mL', 'pg/mL'), ('mmol/l', 'mmol/l'), ('mmol/mol', 'mmol/mol'), ('µmol/l', 'µmol/l'), ('nmol/L', 'nmol/L'), ('pmol/L', 'pmol/L'), ('mEq/L', 'mEq/L'), ('cel/mm3', 'cel/mm3'), ('x10³/µl', 'x10³/µl'), ('x10⁶/µL', 'x10⁶/µL'), ('%', '%'), ('u/l', 'u/l'), ('U/mL', 'U/mL'), ('UI/L', 'UI/L'), ('UI/mL', 'UI/mL'), ('mUI/L', 'mUI/L'), ('kU/L', 'kU/L'), ('p/µL', 'p/µL'), ('ph', 'ph'), ('fl', 'fl'), ('mm/h', 'mm/h'), ('ovos/g', 'ovos/g'), ('ovos/10mL', 'ovos/10mL'), ('parasitas/µL', 'parasitas/µL'), ('parasitas/campo', 'parasitas/campo'), ('cistos/campo', 'cistos/campo'), ('larvas/campo', 'larvas/campo'), ('Ct', 'Ct'), ('cópias/mL', 'cópias/mL'), ('cópias/reação', 'cópias/reação'), ('log10', 'log10'), ('% alelo', '% alelo'), ('% IS', '% IS'), ('genótipo', 'genótipo'), ('traços/detectado', 'traços/detectado'), ('S/CO', 'S/CO'), ('mUI/mL', 'mUI/mL'), ('título', 'título'), ('index', 'index'), ('UFC/mL', 'UFC/mL'), ('UFC/g', 'UFC/g'), ('UFC/placa', 'UFC/placa'), ('horas', 'horas'), ('S/I/R', 'S/I/R'), ('mm', 'mm'), ('cruzes', 'cruzes'), ('campo', 'campo'), ('mmHg', 'mmHg'), ('mOsm/kg', 'mOsm/kg'), ('s', 's'), ('INR', 'INR'), ('razão/índice', 'razão/índice'), ('sem unidade', 'sem unidade')], db_column='unit', default='p/µL', max_length=30, verbose_name='Unidade de medida'),
        ),
    ]
