# Generated by Django 4.2.29 on 2026-04-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0010_add_request_fasting_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labexamfield',
            options={'ordering': ['exam', 'position', 'id'], 'verbose_name': 'parâmetro', 'verbose_name_plural': 'parâmetros do exam'},
        ),
        migrations.AlterModelOptions(
            name='labrequestitem',
            options={'ordering': ['request', 'position', 'id']},
        ),
        migrations.AlterModelOptions(
            name='medicalexamfield',
            options={'ordering': ['exam', 'position', 'id'], 'verbose_name': 'parâmetro de exam médico', 'verbose_name_plural': 'parâmetros de exam médico'},
        ),
        migrations.AlterModelOptions(
            name='resultitem',
            options={'ordering': ['result', 'position', 'id']},
        ),
        migrations.AddField(
            model_name='labexamfield',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='labrequestitem',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='medicalexamfield',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='resultitem',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
