# Generated by Django 4.2.29 on 2026-06-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_contract_employeedocument_leavepermission_and_more'),
        ('clinical', '0016_labrequest_is_occupational_occupationalexamprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='requesting_physician',
            field=models.ForeignKey(blank=True, db_column='requesting_physician_id', help_text='Médico que solicitou os exames.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_lab_requests', to='recursos_humanos.employee', verbose_name='Médico solicitante'),
        ),
    ]
