# Generated by Django 4.2.29 on 2026-06-12 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0003_subscriptioncharge_subscriptioninvoice_and_more'),
        ('clinical', '0018_labrequest_collected_at_labrequest_collected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequestitem',
            name='rejection_note',
            field=models.TextField(blank=True, db_column='rejection_note', default='', verbose_name='Observação da rejeição'),
        ),
        migrations.AddField(
            model_name='labrequestitem',
            name='sample_received_at',
            field=models.DateTimeField(blank=True, db_column='sample_received_at', null=True, verbose_name='Amostra recebida em'),
        ),
        migrations.AddField(
            model_name='labrequestitem',
            name='sample_status',
            field=models.CharField(choices=[('aguardando', 'Aguardando receção'), ('recebida', 'Amostra recebida'), ('rejeitada', 'Amostra rejeitada')], db_column='sample_status', db_index=True, default='aguardando', max_length=20, verbose_name='Estado da amostra'),
        ),
        migrations.CreateModel(
            name='SampleRejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('code', models.CharField(choices=[('VOLUME_INSUFICIENTE', 'Volume insuficiente'), ('HEMOLISE', 'Amostra hemolisada'), ('COAGULADA', 'Amostra coagulada'), ('TUBO_ERRADO', 'Tubo/frasco incorreto'), ('SEM_IDENTIFICACAO', 'Identificação ausente ou incorreta'), ('CONTAMINADA', 'Amostra contaminada/derramada'), ('TRANSPORTE_TARDIO', 'Tempo de transporte excedido'), ('CONSERVACAO_INADEQUADA', 'Conservação/temperatura inadequada'), ('OUTRO', 'Outro motivo')], db_column='code', db_index=True, max_length=40, verbose_name='Código do motivo')),
                ('active', models.BooleanField(db_column='active', db_index=True, default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motivo de rejeição de amostra',
                'verbose_name_plural': 'Motivos de rejeição de amostra',
                'db_table': 'clinico_motivo_rejeicao_amostra',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='labrequestitem',
            name='rejection_reasons',
            field=models.ManyToManyField(blank=True, related_name='rejected_items', to='clinical.samplerejectionreason', verbose_name='Motivos de rejeição'),
        ),
        migrations.AddConstraint(
            model_name='samplerejectionreason',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_sample_rejection_reason_tenant_code'),
        ),
    ]
