# Generated by Django 4.2.29 on 2026-06-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0022_patient_is_organ_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='is_organ_donor',
            field=models.BooleanField(default=False, help_text='Indica se o paciente é doador de órgãos.', verbose_name='Doador de órgãos'),
        ),
    ]
