# Generated by Django 4.2.29 on 2026-06-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0023_align_patient_organ_donor_help_text'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='labexam',
            name='unique_name_exam_por_sector_nao_deleted',
        ),
        migrations.RemoveConstraint(
            model_name='medicalexam',
            name='unique_name_medical_exam_por_sector_nao_deleted',
        ),
        migrations.AddConstraint(
            model_name='labexam',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('tenant', 'sector', 'name'), name='unique_name_exam_por_tenant_sector_nao_deleted'),
        ),
        migrations.AddConstraint(
            model_name='medicalexam',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('tenant', 'sector', 'name'), name='unique_name_medical_exam_por_tenant_sector_nao_deleted'),
        ),
    ]
