# Generated by Django 4.2.29 on 2026-06-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0025_labrequestitem_collected_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrequest',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aguardando_validacao', 'Aguardando Validação'), ('validado', 'Validado'), ('rejeitado', 'Rejeitado'), ('desconsiderado', 'Desconsiderado'), ('cancelado', 'Cancelado')], db_column='status', db_index=True, default='pendente', max_length=30, verbose_name='Status da requisição'),
        ),
        migrations.AlterField(
            model_name='resultitem',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aguardando_validacao', 'Aguardando Validação'), ('validado', 'Validado'), ('rejeitado', 'Rejeitado'), ('desconsiderado', 'Desconsiderado'), ('cancelado', 'Cancelado')], db_column='status', db_index=True, default='pendente', max_length=30, verbose_name='Status do resultado'),
        ),
    ]
