# Generated by Django 4.2.29 on 2026-06-22 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0004_tenantconfiguration_fiscal_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical', '0026_alter_labrequest_status_alter_resultitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleRejectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('reasons_text', models.CharField(blank=True, default='', max_length=500, verbose_name='Motivos')),
                ('note', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('resolvida', 'Resolvida')], db_index=True, default='pendente', max_length=12, verbose_name='Estado')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvida em')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_rejections', to='clinical.labrequest', verbose_name='Requisição')),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='clinical.labrequestitem', verbose_name='Item da requisição')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Resolvida por')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rejeição de amostra',
                'verbose_name_plural': 'Rejeições de amostra',
                'db_table': 'clinico_rejeicao_amostra',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status'], name='clinico_rej_status_b5a846_idx'), models.Index(fields=['request'], name='clinico_rej_request_1e1035_idx')],
            },
        ),
    ]
