# Generated by Django 4.2.29 on 2026-06-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0028_backfill_pending_sample_rejections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='provenance',
            field=models.CharField(blank=True, choices=[('Ambulatório', 'Ambulatório'), ('Clínica Externa', 'Clínica Externa'), ('Medicina Ocupacional', 'Medicina Ocupacional'), ('Maternidade', 'Maternidade'), ('Ginecologia', 'Ginecologia'), ('Pediatria', 'Pediatria'), ('Banco de Socorros', 'Banco de Socorros'), ('Consulta Externa', 'Consulta Externa'), ('Urologia', 'Urologia'), ('Cirurgia', 'Cirurgia'), ('Dentária', 'Dentária'), ('Oftalmologia', 'Oftalmologia'), ('Doação de Sangue', 'Doação de Sangue'), ('Outro', 'Outro')], db_column='provenance', default='Clínica Externa', max_length=50, verbose_name='Proveniência'),
        ),
    ]
