# Generated by Django 4.2.29 on 2026-06-24 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0011_labtestfield_result_choices_labtestfield_result_type'),
        ('clinical', '0029_add_doacao_sangue_provenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrequest',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='lab_requests', through='clinical.LabRequestItem', to='laboratorio.labtest', verbose_name='Exames'),
        ),
        migrations.AlterField(
            model_name='labrequestitem',
            name='exam',
            field=models.ForeignKey(blank=True, db_column='exam_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_request_items', to='laboratorio.labtest', verbose_name='Exame laboratorial'),
        ),
        migrations.AlterField(
            model_name='occupationalexamprofile',
            name='exams',
            field=models.ManyToManyField(blank=True, help_text='Conjunto de exames laboratoriais da bandeja deste perfil.', related_name='occupational_profiles', to='laboratorio.labtest', verbose_name='Exames do perfil'),
        ),
        migrations.AlterField(
            model_name='resultitem',
            name='exam_field',
            field=models.ForeignKey(db_column='exam_field_id', on_delete=django.db.models.deletion.CASCADE, related_name='result_items', to='laboratorio.labtestfield', verbose_name='Campo do exame'),
        ),
    ]
