# Generated by Django 4.2.29 on 2026-07-14 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0025_alter_labtest_method'),
        ('clinical', '0031_add_result_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequestitem',
            name='sector_order_item',
            field=models.ForeignKey(blank=True, db_column='sector_order_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='laboratorio.laborderitem', verbose_name='Item do sector (LIS)'),
        ),
    ]
