# Generated by Django 4.2.16 on 2026-03-28 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import core.mixins.tenant_propagation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipamentos', '0001_initial'),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('date', models.DateField(db_column='date', db_index=True, default=django.utils.timezone.localdate)),
                ('operation_status', models.CharField(choices=[('FUNCIONANDO', 'A funcionar'), ('AVARIADO', 'Avariado'), ('DESLIGADO', 'Desligado')], db_column='operation_status', db_index=True, default='FUNCIONANDO', max_length=20)),
                ('cleaning_performed', models.BooleanField(db_column='cleaning_performed', default=False)),
                ('assessment', models.TextField(blank=True, db_column='assessment', default='')),
                ('notes', models.TextField(blank=True, db_column='notes', default='')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='inspecoes_diarias', to='equipamentos.equipment')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspeção Diária',
                'verbose_name_plural': 'Inspeções Diárias',
                'db_table': 'inspecoes_inspecaodiaria',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'equipment', 'date'], name='inspecoes_i_tenant__5119b3_idx'), models.Index(fields=['tenant', 'operation_status', 'date'], name='inspecoes_i_tenant__d5a81b_idx')],
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='dailyinspection',
            constraint=models.UniqueConstraint(fields=('tenant', 'equipment', 'date'), name='uq_inspecao_diaria_equipment_date'),
        ),
    ]
