# Generated by Django 4.2.16 on 2026-03-20 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import core.mixins.tenant_propagation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0001_initial'),
        ('inquilinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspecaoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('data', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('funcionamento', models.CharField(choices=[('FUNCIONANDO', 'A funcionar'), ('AVARIADO', 'Avariado'), ('DESLIGADO', 'Desligado')], db_index=True, default='FUNCIONANDO', max_length=20)),
                ('limpeza_realizada', models.BooleanField(default=False)),
                ('avaliacao', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecoes_diarias', to='equipamentos.equipamento')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
            ],
            options={
                'verbose_name': 'Inspeção Diária',
                'verbose_name_plural': 'Inspeções Diárias',
                'ordering': ['-data', '-criado_em'],
                'indexes': [models.Index(fields=['inquilino', 'equipamento', 'data'], name='inspecoes_i_inquili_1fed5b_idx'), models.Index(fields=['inquilino', 'funcionamento', 'data'], name='inspecoes_i_inquili_d45ab8_idx')],
            },
            bases=(core.mixins.tenant_propagation.PropagarInquilinoMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='inspecaodiaria',
            constraint=models.UniqueConstraint(fields=('inquilino', 'equipamento', 'data'), name='uq_inspecao_diaria_equipamento_data'),
        ),
    ]
