# Generated by Django 5.1 on 2026-03-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inspecoes", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dailyinspection",
            new_name="inspecoes_i_tenant__5119b3_idx",
            old_name="inspecoes_i_inquili_1fed5b_idx",
        ),
        migrations.RenameIndex(
            model_name="dailyinspection",
            new_name="inspecoes_i_tenant__d5a81b_idx",
            old_name="inspecoes_i_inquili_d45ab8_idx",
        ),
    ]
