# Generated by Django 5.1 on 2026-03-25 04:18

import django.db.models.deletion
import django.utils.timezone
import infrastructure.orm.fields.money_field
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinico", "0001_initial"),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurgicalProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "name",
                    models.CharField(db_column="nome", db_index=True, max_length=120),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_column="descricao",
                        default="",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "base_price",
                    infrastructure.orm.fields.money_field.MoneyField(
                        db_column="preco_base",
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Preço base",
                    ),
                ),
                (
                    "vat_percentage",
                    models.DecimalField(
                        db_column="iva_percentual",
                        decimal_places=2,
                        default=Decimal("16.00"),
                        max_digits=5,
                        verbose_name="IVA (%)",
                    ),
                ),
                (
                    "applies_vat_by_default",
                    models.BooleanField(
                        db_column="aplica_iva_por_padrao",
                        default=True,
                        verbose_name="Aplicar IVA por padrão",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_column="ativo",
                        db_index=True,
                        default=True,
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="criado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deletado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="inquilino_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="atualizado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedimento Cirúrgico",
                "verbose_name_plural": "Procedimentos Cirúrgicos",
                "db_table": "cirurgia_procedimentocirurgico",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Surgery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "procedure",
                    models.CharField(
                        blank=True,
                        db_column="procedimento",
                        db_index=True,
                        default="",
                        help_text="Use quando o procedure não estiver no catálogo.",
                        max_length=160,
                        verbose_name="Procedimento (texto livre)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_column="descricao",
                        default="",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "estimated_price",
                    infrastructure.orm.fields.money_field.MoneyField(
                        db_column="preco_estimado",
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Preço estimado",
                    ),
                ),
                (
                    "vat_percentage",
                    models.DecimalField(
                        db_column="iva_percentual",
                        decimal_places=2,
                        default=Decimal("16.00"),
                        max_digits=5,
                        verbose_name="IVA (%)",
                    ),
                ),
                (
                    "applies_vat_by_default",
                    models.BooleanField(
                        db_column="aplica_iva_por_padrao",
                        default=True,
                        verbose_name="Aplicar IVA por padrão",
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        db_column="agendada_para",
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Agendada para",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGENDADA", "Agendada"),
                            ("EM_ANDAMENTO", "Em andamento"),
                            ("CONCLUIDA", "Concluída"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        db_column="estado",
                        db_index=True,
                        default="AGENDADA",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="concluida_em",
                        null=True,
                        verbose_name="Concluída em",
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="cancelada_em",
                        null=True,
                        verbose_name="Cancelada em",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="criado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deletado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="paciente_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cirurgias",
                        to="clinico.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "surgeon",
                    models.ForeignKey(
                        blank=True,
                        db_column="cirurgiao_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cirurgias_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cirurgião",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="inquilino_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="atualizado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "procedures",
                    models.ManyToManyField(
                        blank=True,
                        db_table="cirurgia_cirurgia_procedimentos",
                        related_name="cirurgias",
                        to="cirurgia.surgicalprocedure",
                        verbose_name="Procedimentos cirúrgicos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cirurgia",
                "verbose_name_plural": "Cirurgias",
                "db_table": "cirurgia_cirurgia",
                "ordering": ["-scheduled_for", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="surgicalprocedure",
            index=models.Index(
                fields=["tenant", "active", "name"],
                name="cirurgia_pr_inquili_5ffeb7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="surgery",
            index=models.Index(
                fields=["tenant", "patient", "scheduled_for"],
                name="cirurgia_ci_inquili_a87732_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="surgery",
            index=models.Index(
                fields=["tenant", "surgeon", "scheduled_for"],
                name="cirurgia_ci_inquili_47131d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="surgery",
            index=models.Index(
                fields=["tenant", "status", "scheduled_for"],
                name="cirurgia_ci_inquili_22d933_idx",
            ),
        ),
    ]
