# Generated by Django 4.2.16 on 2026-03-28 04:22

from decimal import Decimal

from django.db import migrations, models
import django.utils.timezone

import infrastructure.orm.fields.money_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('procedure', models.CharField(blank=True, db_column='procedure', db_index=True, default='', help_text='Use quando o procedure não estiver no catálogo.', max_length=160, verbose_name='Procedimento (texto livre)')),
                ('description', models.TextField(blank=True, db_column='description', default='', verbose_name='Descrição')),
                ('estimated_price', infrastructure.orm.fields.money_field.MoneyField(db_column='estimated_price', decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Preço estimado')),
                ('vat_percentage', models.DecimalField(db_column='vat_percentage', decimal_places=2, default=Decimal('16.00'), max_digits=5, verbose_name='IVA (%)')),
                ('applies_vat_by_default', models.BooleanField(db_column='applies_vat_by_default', default=True, verbose_name='Aplicar IVA por padrão')),
                ('scheduled_for', models.DateTimeField(db_column='scheduled_for', db_index=True, default=django.utils.timezone.now, verbose_name='Agendada para')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_column='status', db_index=True, default='AGENDADA', max_length=20, verbose_name='Estado')),
                ('completed_at', models.DateTimeField(blank=True, db_column='completed_at', null=True, verbose_name='Concluída em')),
                ('canceled_at', models.DateTimeField(blank=True, db_column='canceled_at', null=True, verbose_name='Cancelada em')),
            ],
            options={
                'verbose_name': 'Cirurgia',
                'verbose_name_plural': 'Cirurgias',
                'db_table': 'cirurgia_cirurgia',
                'ordering': ['-scheduled_for', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurgicalProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('description', models.TextField(blank=True, db_column='description', default='', verbose_name='Descrição')),
                ('base_price', infrastructure.orm.fields.money_field.MoneyField(db_column='base_price', decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Preço base')),
                ('vat_percentage', models.DecimalField(db_column='vat_percentage', decimal_places=2, default=Decimal('16.00'), max_digits=5, verbose_name='IVA (%)')),
                ('applies_vat_by_default', models.BooleanField(db_column='applies_vat_by_default', default=True, verbose_name='Aplicar IVA por padrão')),
                ('active', models.BooleanField(db_column='active', db_index=True, default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Procedimento Cirúrgico',
                'verbose_name_plural': 'Procedimentos Cirúrgicos',
                'db_table': 'cirurgia_procedimentocirurgico',
                'ordering': ['name'],
            },
        ),
    ]
