# Generated by Django 5.1 on 2026-03-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cirurgia", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="surgery",
            new_name="cirurgia_ci_tenant__b2ca1a_idx",
            old_name="cirurgia_ci_inquili_a87732_idx",
        ),
        migrations.RenameIndex(
            model_name="surgery",
            new_name="cirurgia_ci_tenant__083350_idx",
            old_name="cirurgia_ci_inquili_47131d_idx",
        ),
        migrations.RenameIndex(
            model_name="surgery",
            new_name="cirurgia_ci_tenant__969041_idx",
            old_name="cirurgia_ci_inquili_22d933_idx",
        ),
        migrations.RenameIndex(
            model_name="surgicalprocedure",
            new_name="cirurgia_pr_tenant__7dc930_idx",
            old_name="cirurgia_pr_inquili_5ffeb7_idx",
        ),
    ]
