# Generated by Django 4.2.29 on 2026-05-22 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('inquilinos', '0001_initial'),
        ('cirurgia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicalprocedure',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgery',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgery',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgery',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, related_name='cirurgias', to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='procedures',
            field=models.ManyToManyField(blank=True, db_table='cirurgia_cirurgia_procedimentos', related_name='cirurgias', to='cirurgia.surgicalprocedure', verbose_name='Procedimentos cirúrgicos'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='surgeon',
            field=models.ForeignKey(blank=True, db_column='surgeon_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirurgias_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Cirurgião'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LargeSurgery',
            fields=[
            ],
            options={
                'verbose_name': 'Grande cirurgia',
                'verbose_name_plural': 'Grandes cirurgias',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cirurgia.surgery',),
        ),
        migrations.CreateModel(
            name='SmallSurgery',
            fields=[
            ],
            options={
                'verbose_name': 'Pequena cirurgia',
                'verbose_name_plural': 'Pequenas cirurgias',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cirurgia.surgery',),
        ),
        migrations.AddIndex(
            model_name='surgicalprocedure',
            index=models.Index(fields=['tenant', 'active', 'name'], name='cirurgia_pr_tenant__7dc930_idx'),
        ),
        migrations.AddIndex(
            model_name='surgery',
            index=models.Index(fields=['tenant', 'patient', 'scheduled_for'], name='cirurgia_ci_tenant__b2ca1a_idx'),
        ),
        migrations.AddIndex(
            model_name='surgery',
            index=models.Index(fields=['tenant', 'surgeon', 'scheduled_for'], name='cirurgia_ci_tenant__083350_idx'),
        ),
        migrations.AddIndex(
            model_name='surgery',
            index=models.Index(fields=['tenant', 'status', 'scheduled_for'], name='cirurgia_ci_tenant__969041_idx'),
        ),
        migrations.AddIndex(
            model_name='surgery',
            index=models.Index(fields=['tenant', 'surgery_size', 'scheduled_for'], name='cirurgia_ci_tenant__a75e8d_idx'),
        ),
    ]
