# Generated by Django 4.2.29 on 2026-04-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirurgia', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeSurgery',
            fields=[
            ],
            options={
                'verbose_name': 'Grande cirurgia',
                'verbose_name_plural': 'Grandes cirurgias',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cirurgia.surgery',),
        ),
        migrations.CreateModel(
            name='SmallSurgery',
            fields=[
            ],
            options={
                'verbose_name': 'Pequena cirurgia',
                'verbose_name_plural': 'Pequenas cirurgias',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cirurgia.surgery',),
        ),
        migrations.AddField(
            model_name='surgery',
            name='surgery_size',
            field=models.CharField(choices=[('PEQUENA', 'Pequena'), ('GRANDE', 'Grande')], db_column='surgery_size', db_index=True, default='PEQUENA', max_length=10, verbose_name='Porte da cirurgia'),
        ),
        migrations.AddIndex(
            model_name='surgery',
            index=models.Index(fields=['tenant', 'surgery_size', 'scheduled_for'], name='cirurgia_ci_tenant__a75e8d_idx'),
        ),
    ]
