# Generated by Django 4.2.29 on 2026-07-01 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cirurgia', '0004_preoperativeassessment_surgeryprocedureitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='surgeons',
            field=models.ManyToManyField(blank=True, related_name='cirurgias_como_cirurgiao', to=settings.AUTH_USER_MODEL, verbose_name='Cirurgiões'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='surgeon',
            field=models.ForeignKey(blank=True, db_column='surgeon_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirurgias_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Cirurgião principal (legado)'),
        ),
    ]
