# Generated by Django 4.2.29 on 2026-07-01 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0006_repair_nursing_record_lab_intake_schema'),
        ('cirurgia', '0005_surgery_surgeons_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='ward',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='enfermagem.ward', verbose_name='Bloco / enfermaria'),
        ),
    ]
