# Generated by Django 4.2.29 on 2026-07-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_contract_employeedocument_leavepermission_and_more'),
        ('cirurgia', '0006_surgery_ward_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='surgeons',
            field=models.ManyToManyField(blank=True, related_name='cirurgias_como_cirurgiao', to='recursos_humanos.employee', verbose_name='Cirurgiões'),
        ),
    ]
