# Generated by Django 4.2.29 on 2026-07-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipamentos", "0003_equipment_maintenance_required_since_and_more"),
        ("cirurgia", "0013_alter_operatingroom_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operatingroom",
            name="equipment_notes",
        ),
        migrations.AddField(
            model_name="operatingroom",
            name="equipment",
            field=models.ManyToManyField(
                blank=True,
                related_name="operating_rooms",
                to="equipamentos.equipment",
                verbose_name="Equipamentos disponíveis",
            ),
        ),
    ]
