# Generated by Django 4.2.29 on 2026-07-18 11:22

from django.db import migrations


def seed_surgical_procedure_materials(apps, schema_editor):
    Product = apps.get_model("farmacia", "Product")
    SurgicalProcedure = apps.get_model("cirurgia", "SurgicalProcedure")
    SurgicalProcedureMaterial = apps.get_model("cirurgia", "SurgicalProcedureMaterial")

    def product_id(*needles):
        qs = Product.objects.filter(deleted=False)
        for needle in needles:
            found = qs.filter(name__icontains=needle).order_by("name").values_list("id", flat=True).first()
            if found:
                return found
        return None

    kit = {
        "gaze": product_id("Gaze Esterilizada", "Compressa De Gaze", "Gaze"),
        "luvas": product_id("Luvas M", "Luvas"),
        "campo": product_id("Campo Cirúrgico", "Campo"),
        "mascara": product_id("Máscara Cirúrgica", "Mascara Cirurgica", "Máscara"),
        "touca": product_id("Touca Descartável", "Touca"),
        "lamina": product_id("Lâmina Bisturi 15", "Lamina Bisturi 15", "Lâmina Bisturi"),
        "fio_nylon": product_id("Fio Nylon 3-0", "Fio Nylon"),
        "fio_vicryl": product_id("Fio Vicryl 2-0", "Fio Vicryl"),
        "seringa": product_id("Seringa 10 Ml", "Seringa 5 Ml", "Seringa"),
        "atadura": product_id("Atadura 10 Cm", "Atadura"),
        "coletor": product_id("Coletor Perfurocortante", "Coletor"),
    }

    small_defaults = [
        ("gaze", 4),
        ("luvas", 2),
        ("campo", 1),
        ("mascara", 2),
        ("lamina", 1),
        ("fio_nylon", 1),
        ("seringa", 1),
        ("atadura", 1),
    ]
    large_defaults = [
        ("gaze", 8),
        ("luvas", 4),
        ("campo", 2),
        ("mascara", 3),
        ("touca", 3),
        ("lamina", 2),
        ("fio_vicryl", 2),
        ("seringa", 2),
        ("coletor", 1),
    ]

    for procedure in SurgicalProcedure.objects.filter(active=True):
        if SurgicalProcedureMaterial.objects.filter(procedure=procedure).exists():
            continue
        defaults = large_defaults if procedure.surgery_type == "GRANDE" else small_defaults
        for key, quantity in defaults:
            pid = kit.get(key)
            if pid:
                SurgicalProcedureMaterial.objects.get_or_create(
                    procedure=procedure,
                    product_id=pid,
                    defaults={"quantity": quantity},
                )


def unseed_surgical_procedure_materials(apps, schema_editor):
    # Data migration only hydrates missing operational defaults; keep existing
    # materials on reverse to avoid deleting user-adjusted procedure kits.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('cirurgia', '0016_default_vat_5_percent'),
    ]

    operations = [
        migrations.RunPython(seed_surgical_procedure_materials, unseed_surgical_procedure_materials),
    ]
