# Generated by Django 4.2.29 on 2026-03-18 19:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import infrastructure.orm.fields.dinheiro_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('tipo', models.CharField(db_index=True, max_length=120, verbose_name='Tipo de consulta')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('agendada_para', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Agendada para')),
                ('estado', models.CharField(choices=[('MARCADA', 'Marcada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='MARCADA', max_length=20, verbose_name='Estado')),
                ('preco', infrastructure.orm.fields.dinheiro_field.DinheiroField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Preço')),
                ('multiplicador_preco', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Fator aplicado sobre o preço base conforme horário/feriado.', max_digits=5, verbose_name='Multiplicador de preço')),
                ('tipo_horario', models.CharField(choices=[('NORMAL', 'Normal (08h-18h)'), ('FORA_EXPEDIENTE', 'Fora de expediente (19h-07h)'), ('FIM_SEMANA', 'Fim de semana'), ('FERIADO_MANUAL', 'Feriado (marcado)')], db_index=True, default='NORMAL', max_length=32, verbose_name='Tipo de horário')),
                ('feriado_manual', models.BooleanField(default=False, help_text='Marque se a data for feriado mesmo não sendo fim de semana.', verbose_name='Feriado (manual)')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('cancelada_em', models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em')),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consultas Médicas',
                'ordering': ['-agendada_para', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EspecialidadeConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('preco_base', infrastructure.orm.fields.dinheiro_field.DinheiroField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Preço base')),
                ('iva_percentual', models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Taxa de IVA aplicada ao serviço de consulta (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Especialidade (Consulta)',
                'verbose_name_plural': 'Especialidades (Consulta)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('data', models.DateField(db_index=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
