# Generated by Django 4.2.16 on 2026-03-26 05:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import infrastructure.orm.fields.money_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('description', models.TextField(blank=True, db_column='description', default='', verbose_name='Descrição')),
                ('base_price', infrastructure.orm.fields.money_field.MoneyField(db_column='base_price', decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Preço base')),
                ('vat_percentage', models.DecimalField(db_column='vat_percentage', decimal_places=2, default=Decimal('16.00'), help_text='Taxa de IVA aplicada ao serviço de consultation (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)')),
                ('active', models.BooleanField(db_column='active', db_index=True, default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Especialidade (Consulta)',
                'verbose_name_plural': 'Especialidades (Consulta)',
                'db_table': 'consultas_especialidadeconsulta',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('date', models.DateField(db_column='date', db_index=True)),
                ('description', models.CharField(blank=True, db_column='description', default='', max_length=255)),
                ('active', models.BooleanField(db_column='active', db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'db_table': 'consultas_feriado',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('type', models.CharField(db_column='type', db_index=True, max_length=120, verbose_name='Tipo de consultation')),
                ('description', models.TextField(blank=True, db_column='description', default='', verbose_name='Descrição')),
                ('scheduled_for', models.DateTimeField(db_column='scheduled_for', db_index=True, default=django.utils.timezone.now, verbose_name='Agendada para')),
                ('status', models.CharField(choices=[('MARCADA', 'Marcada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_column='status', db_index=True, default='MARCADA', max_length=20, verbose_name='Estado')),
                ('price', infrastructure.orm.fields.money_field.MoneyField(db_column='price', decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Preço')),
                ('price_multiplier', models.DecimalField(db_column='price_multiplier', decimal_places=2, default=Decimal('1.00'), help_text='Fator aplicado sobre o preço base conforme horário/feriado.', max_digits=5, verbose_name='Multiplicador de preço')),
                ('schedule_type', models.CharField(choices=[('NORMAL', 'Normal (08h-18h)'), ('FORA_EXPEDIENTE', 'Fora de expediente (19h-07h)'), ('FIM_SEMANA', 'Fim de semana'), ('FERIADO_MANUAL', 'Feriado (marcado)')], db_column='schedule_type', db_index=True, default='NORMAL', max_length=32, verbose_name='Tipo de horário')),
                ('manual_holiday', models.BooleanField(db_column='manual_holiday', default=False, help_text='Marque se a date for feriado mesmo não sendo fim de semana.', verbose_name='Feriado (manual)')),
                ('completed_at', models.DateTimeField(blank=True, db_column='completed_at', null=True, verbose_name='Concluída em')),
                ('canceled_at', models.DateTimeField(blank=True, db_column='canceled_at', null=True, verbose_name='Cancelada em')),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consultas Médicas',
                'db_table': 'consultas_consultamedica',
                'ordering': ['-scheduled_for', '-created_at'],
            },
        ),
    ]
