# Generated by Django 5.1 on 2026-03-25 04:18

import django.core.validators
import django.utils.timezone
import infrastructure.orm.fields.money_field
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsultationSpecialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "name",
                    models.CharField(db_column="nome", db_index=True, max_length=120),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_column="descricao",
                        default="",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "base_price",
                    infrastructure.orm.fields.money_field.MoneyField(
                        db_column="preco_base",
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Preço base",
                    ),
                ),
                (
                    "vat_percentage",
                    models.DecimalField(
                        db_column="iva_percentual",
                        decimal_places=2,
                        default=Decimal("16.00"),
                        help_text="Taxa de IVA aplicada ao serviço de consultation (0 a 100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="IVA (%)",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_column="ativo",
                        db_index=True,
                        default=True,
                        verbose_name="Ativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Especialidade (Consulta)",
                "verbose_name_plural": "Especialidades (Consulta)",
                "db_table": "consultas_especialidadeconsulta",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                ("date", models.DateField(db_column="data", db_index=True)),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="descricao", default="", max_length=255
                    ),
                ),
                (
                    "active",
                    models.BooleanField(db_column="ativo", db_index=True, default=True),
                ),
            ],
            options={
                "verbose_name": "Feriado",
                "verbose_name_plural": "Feriados",
                "db_table": "consultas_feriado",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalConsultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "type",
                    models.CharField(
                        db_column="tipo",
                        db_index=True,
                        max_length=120,
                        verbose_name="Tipo de consultation",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_column="descricao",
                        default="",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        db_column="agendada_para",
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Agendada para",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MARCADA", "Marcada"),
                            ("CONCLUIDA", "Concluída"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        db_column="estado",
                        db_index=True,
                        default="MARCADA",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "price",
                    infrastructure.orm.fields.money_field.MoneyField(
                        db_column="preco",
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Preço",
                    ),
                ),
                (
                    "price_multiplier",
                    models.DecimalField(
                        db_column="multiplicador_preco",
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Fator aplicado sobre o preço base conforme horário/feriado.",
                        max_digits=5,
                        verbose_name="Multiplicador de preço",
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal (08h-18h)"),
                            ("FORA_EXPEDIENTE", "Fora de expediente (19h-07h)"),
                            ("FIM_SEMANA", "Fim de semana"),
                            ("FERIADO_MANUAL", "Feriado (marcado)"),
                        ],
                        db_column="tipo_horario",
                        db_index=True,
                        default="NORMAL",
                        max_length=32,
                        verbose_name="Tipo de horário",
                    ),
                ),
                (
                    "manual_holiday",
                    models.BooleanField(
                        db_column="feriado_manual",
                        default=False,
                        help_text="Marque se a date for feriado mesmo não sendo fim de semana.",
                        verbose_name="Feriado (manual)",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="concluida_em",
                        null=True,
                        verbose_name="Concluída em",
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="cancelada_em",
                        null=True,
                        verbose_name="Cancelada em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta Médica",
                "verbose_name_plural": "Consultas Médicas",
                "db_table": "consultas_consultamedica",
                "ordering": ["-scheduled_for", "-created_at"],
            },
        ),
    ]
