# Generated by Django 4.2.29 on 2026-05-22 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos_humanos', '0001_initial'),
        ('clinical', '0002_initial'),
        ('consultas', '0001_initial'),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalconsultation',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalconsultation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalconsultation',
            name='doctor',
            field=models.ForeignKey(blank=True, db_column='doctor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_realizadas', to='recursos_humanos.employee', verbose_name='Médico'),
        ),
        migrations.AddField(
            model_name='medicalconsultation',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, related_name='consultations_medicas', to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='medicalconsultation',
            name='specialty',
            field=models.ForeignKey(blank=True, db_column='specialty_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='consultas.consultationspecialty', verbose_name='Especialidade'),
        ),
        migrations.AddField(
            model_name='medicalconsultation',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='medicalconsultation',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationspecialty',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationspecialty',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationspecialty',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='consultationspecialty',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='medicalconsultation',
            index=models.Index(fields=['tenant', 'patient', 'scheduled_for'], name='consultas_c_tenant__958f11_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalconsultation',
            index=models.Index(fields=['tenant', 'doctor', 'scheduled_for'], name='consultas_c_tenant__ddda23_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalconsultation',
            index=models.Index(fields=['tenant', 'status', 'scheduled_for'], name='consultas_c_tenant__b63c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalconsultation',
            index=models.Index(fields=['tenant', 'type'], name='consultas_c_tenant__9a597b_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['tenant', 'date'], name='consultas_f_tenant__58791d_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['tenant', 'active', 'date'], name='consultas_f_tenant__b384e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('tenant', 'date')},
        ),
        migrations.AddIndex(
            model_name='consultationspecialty',
            index=models.Index(fields=['tenant', 'active', 'name'], name='consultas_e_tenant__98e126_idx'),
        ),
    ]
