# Generated by Django 5.1 on 2026-03-25 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinico", "0002_initial"),
        ("consultas", "0001_initial"),
        ("inquilinos", "0001_initial"),
        ("recursos_humanos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationspecialty",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="criado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consultationspecialty",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                db_column="deletado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consultationspecialty",
            name="tenant",
            field=models.ForeignKey(
                db_column="inquilino_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.tenant",
            ),
        ),
        migrations.AddField(
            model_name="consultationspecialty",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="atualizado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="criado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                db_column="deletado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="tenant",
            field=models.ForeignKey(
                db_column="inquilino_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.tenant",
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="atualizado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medicalconsultation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="criado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medicalconsultation",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                db_column="deletado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medicalconsultation",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                db_column="medico_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultations_realizadas",
                to="recursos_humanos.employee",
                verbose_name="Médico",
            ),
        ),
        migrations.AddField(
            model_name="medicalconsultation",
            name="patient",
            field=models.ForeignKey(
                db_column="paciente_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consultations_medicas",
                to="clinico.patient",
                verbose_name="Paciente",
            ),
        ),
        migrations.AddField(
            model_name="medicalconsultation",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                db_column="especialidade_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consultations",
                to="consultas.consultationspecialty",
                verbose_name="Especialidade",
            ),
        ),
        migrations.AddField(
            model_name="medicalconsultation",
            name="tenant",
            field=models.ForeignKey(
                db_column="inquilino_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.tenant",
            ),
        ),
        migrations.AddField(
            model_name="medicalconsultation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="atualizado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="consultationspecialty",
            index=models.Index(
                fields=["tenant", "active", "name"],
                name="consultas_e_inquili_200f90_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(
                fields=["tenant", "date"], name="consultas_f_inquili_0b009c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(
                fields=["tenant", "active", "date"],
                name="consultas_f_inquili_1e54a8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="holiday",
            unique_together={("tenant", "date")},
        ),
        migrations.AddIndex(
            model_name="medicalconsultation",
            index=models.Index(
                fields=["tenant", "patient", "scheduled_for"],
                name="consultas_c_inquili_06ab8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalconsultation",
            index=models.Index(
                fields=["tenant", "doctor", "scheduled_for"],
                name="consultas_c_inquili_39d00a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalconsultation",
            index=models.Index(
                fields=["tenant", "status", "scheduled_for"],
                name="consultas_c_inquili_631e86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalconsultation",
            index=models.Index(
                fields=["tenant", "type"], name="consultas_c_inquili_91ac89_idx"
            ),
        ),
    ]
