# Generated by Django 4.2.16 on 2026-03-18 23:14

from django.db import migrations, models
import django.db.models.deletion


def _map_usuario_para_funcionario(apps):
    ProfessionalProfile = apps.get_model("identidade", "PerfilProfissional")
    return dict(
        ProfessionalProfile.objects.exclude(funcionario_id__isnull=True).values_list("usuario_id", "funcionario_id")
    )


def forward_medico_funcionario(apps, schema_editor):
    MedicalConsultation = apps.get_model("consultas", "ConsultaMedica")
    mapping = _map_usuario_para_funcionario(apps)
    if not mapping:
        return

    qs = MedicalConsultation.objects.exclude(medico_id__isnull=True)
    for consulta in qs.iterator():
        funcionario_id = mapping.get(consulta.medico_id)
        if funcionario_id and consulta.medico_funcionario_id != funcionario_id:
            consulta.medico_funcionario_id = funcionario_id
            consulta.save(update_fields=["medico_funcionario"])


def backward_medico_funcionario(apps, schema_editor):
    MedicalConsultation = apps.get_model("consultas", "ConsultaMedica")
    ProfessionalProfile = apps.get_model("identidade", "PerfilProfissional")
    mapping = dict(
        ProfessionalProfile.objects.exclude(usuario_id__isnull=True).values_list("funcionario_id", "usuario_id")
    )
    if not mapping:
        return

    qs = MedicalConsultation.objects.exclude(medico_funcionario_id__isnull=True)
    for consulta in qs.iterator():
        usuario_id = mapping.get(consulta.medico_funcionario_id)
        if usuario_id and consulta.medico_id != usuario_id:
            consulta.medico_id = usuario_id
            consulta.save(update_fields=["medico"])


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_funcionario_profissao'),
        ('identidade', '0002_initial'),
        ('consultas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name="consultamedica",
            name="medico_funcionario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultas_realizadas",
                to="human_resources.funcionario",
                verbose_name="Médico",
            ),
        ),
        migrations.RunPython(forward_medico_funcionario, backward_medico_funcionario),
        migrations.RemoveField(
            model_name="consultamedica",
            name="medico",
        ),
        migrations.RenameField(
            model_name="consultamedica",
            old_name="medico_funcionario",
            new_name="medico",
        ),
    ]
