# Generated by Django 4.2.29 on 2026-05-26 05:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationspecialty',
            name='vat_percentage',
            field=models.DecimalField(db_column='vat_percentage', decimal_places=2, default=Decimal('16.00'), help_text='Taxa de IVA aplicada ao serviço de consulta (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)'),
        ),
        migrations.AlterField(
            model_name='medicalconsultation',
            name='type',
            field=models.CharField(db_column='type', db_index=True, max_length=120, verbose_name='Tipo de consulta'),
        ),
    ]
