# Generated by Django 4.2.29 on 2026-05-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_consultationspecialty_vat_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalconsultation',
            name='consultation_type',
            field=models.CharField(choices=[('IN_PERSON', 'Presencial'), ('TELEMEDICINE', 'Telemedicina'), ('ASYNC', 'Assíncrona'), ('REMOTE_MONITORING', 'Monitoramento remoto')], db_column='consultation_type', db_index=True, default='IN_PERSON', max_length=24, verbose_name='Modalidade da consulta'),
        ),
        migrations.AddIndex(
            model_name='medicalconsultation',
            index=models.Index(fields=['tenant', 'consultation_type', 'scheduled_for'], name='consultas_c_tenant__fec87e_idx'),
        ),
    ]
