# Generated by Django 4.2.29 on 2026-06-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0004_medicalconsultation_consultation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalconsultation",
            name="reschedule_count",
            field=models.PositiveIntegerField(
                db_column="reschedule_count",
                default=0,
                help_text="Quantas vezes a consulta foi remarcada.",
                verbose_name="Nº de reagendamentos",
            ),
        ),
    ]
