# Generated by Django 4.2.29 on 2026-05-25 20:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0002_outbound_fulfillment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenishmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('plan_number', models.CharField(db_column='plan_number', max_length=64)),
                ('supplier_name', models.CharField(db_column='supplier_name', default='Fornecedor padrão', max_length=180)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('GENERATED', 'Gerado'), ('ORDERED', 'Pedido criado'), ('CANCELLED', 'Cancelado')], db_column='status', default='DRAFT', max_length=16)),
                ('generated_at', models.DateTimeField(blank=True, db_column='generated_at', null=True)),
                ('notes', models.TextField(blank=True, db_column='notes', default='')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, db_column='purchase_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_plans', to='warehouse.purchaseorder')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, db_column='warehouse_id', help_text='Quando vazio, o plano considera todos os armazéns do tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_plans', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Plano de Reposição',
                'verbose_name_plural': 'Planos de Reposição',
                'db_table': 'warehouse_replenishment_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('current_quantity', models.DecimalField(db_column='current_quantity', decimal_places=4, default=Decimal('0.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('reserved_quantity', models.DecimalField(db_column='reserved_quantity', decimal_places=4, default=Decimal('0.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('available_quantity', models.DecimalField(db_column='available_quantity', decimal_places=4, default=Decimal('0.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('reorder_point', models.DecimalField(db_column='reorder_point', decimal_places=4, default=Decimal('0.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('recommended_quantity', models.DecimalField(db_column='recommended_quantity', decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('estimated_unit_cost', models.DecimalField(db_column='estimated_unit_cost', decimal_places=4, default=Decimal('0.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('ORDERED', 'Pedido criado'), ('IGNORED', 'Ignorada')], db_column='status', default='OPEN', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_suggestions', to='warehouse.warehouseitem')),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='warehouse.replenishmentplan')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_suggestions', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Sugestão de Reposição',
                'verbose_name_plural': 'Sugestões de Reposição',
                'db_table': 'warehouse_replenishment_suggestion',
                'ordering': ['plan', 'item__name'],
                'indexes': [models.Index(fields=['tenant', 'plan'], name='warehouse_r_tenant__9b2901_idx'), models.Index(fields=['tenant', 'item'], name='warehouse_r_tenant__4f90a3_idx'), models.Index(fields=['tenant', 'status'], name='warehouse_r_tenant__2e7dbe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='replenishmentplan',
            index=models.Index(fields=['tenant', 'status'], name='warehouse_r_tenant__f161af_idx'),
        ),
        migrations.AddIndex(
            model_name='replenishmentplan',
            index=models.Index(fields=['tenant', 'warehouse'], name='warehouse_r_tenant__9c57fc_idx'),
        ),
        migrations.AddIndex(
            model_name='replenishmentplan',
            index=models.Index(fields=['tenant', 'generated_at'], name='warehouse_r_tenant__a0adb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='replenishmentplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'plan_number'), name='warehouse_replenishment_plan_number_uniq'),
        ),
    ]
