# Generated by Django 5.2.12 on 2026-03-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_alter_assignment_usuario_alter_course_usuario_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonmaterial",
            name="url",
        ),
        migrations.AddField(
            model_name="lessonmaterial",
            name="audio_enabled",
            field=models.BooleanField(default=False, verbose_name="Usar áudio"),
        ),
        migrations.AddField(
            model_name="lessonmaterial",
            name="audio_url",
            field=models.URLField(blank=True, verbose_name="URL do áudio"),
        ),
        migrations.AddField(
            model_name="lessonmaterial",
            name="document_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Usar documento (PDF/Word)"
            ),
        ),
        migrations.AddField(
            model_name="lessonmaterial",
            name="document_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="lesson_materials/docs/",
                verbose_name="Documento",
            ),
        ),
        migrations.AddField(
            model_name="lessonmaterial",
            name="image_enabled",
            field=models.BooleanField(default=False, verbose_name="Usar imagem"),
        ),
        migrations.AddField(
            model_name="lessonmaterial",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lesson_materials/images/",
                verbose_name="Imagem",
            ),
        ),
        migrations.AddField(
            model_name="lessonmaterial",
            name="link_enabled",
            field=models.BooleanField(default=False, verbose_name="Usar link"),
        ),
        migrations.AddField(
            model_name="lessonmaterial",
            name="link_url",
            field=models.URLField(blank=True, verbose_name="Link"),
        ),
        migrations.AddField(
            model_name="lessonmaterial",
            name="video_enabled",
            field=models.BooleanField(default=False, verbose_name="Usar vídeo"),
        ),
        migrations.AddField(
            model_name="lessonmaterial",
            name="video_url",
            field=models.URLField(blank=True, verbose_name="URL do vídeo"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="course",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="courseoffering",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="lessonmaterial",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
    ]
