# Generated by Django 5.2.12 on 2026-03-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_submissionattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionattachment",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
    ]
