# Generated by Django 5.2.12 on 2026-03-29 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0005_alter_basecurriculum_tenant_id_and_more"),
        ("learning", "0006_course_cycle_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.CharField(blank=True, max_length=50, verbose_name="Escola")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Removido em")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=30, unique=True, verbose_name="Código"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=180, verbose_name="Nome do módulo")),
                (
                    "workload_hours",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Carga horária (h)"),
                ),
                ("required", models.BooleanField(default=True, verbose_name="Obrigatório para certificar")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Ordem")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="learning.course",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_modules",
                        to="curriculum.subject",
                        verbose_name="Disciplina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Módulo do curso",
                "verbose_name_plural": "Módulos do curso",
                "ordering": ["course__title", "order", "subject__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="coursemodule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("course", "subject"),
                name="unique_course_subject_module_active",
            ),
        ),
    ]
