# Generated by Django 5.2.12 on 2026-03-28 04:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_alter_academicyear_usuario_and_more"),
    ]

    operations = [
        # Free the `specialty` name so we can use it for the FK field.
        migrations.RenameField(
            model_name="teacher",
            old_name="specialty",
            new_name="specialty_text",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="specialty_subject",
            new_name="specialty",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="specialty_text",
        ),
    ]

