# Generated by Django 5.2.12 on 2026-03-28 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0004_competency_area_fk"),
        ("school", "0003_teacher_specialty_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="curriculum.subjectspecialty",
                verbose_name="Especialidade",
            ),
        ),
    ]
