# Generated by Django 5.2.12 on 2026-03-29 02:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_alter_teacher_specialty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={},
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="auditalert",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="grade",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="gradesubject",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="managementassignment",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="teachingassignment",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.CreateModel(
            name="TeacherSpecialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(blank=True, max_length=50, verbose_name="Escola"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Removido em"
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=60, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome")),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_specialties",
                        to="school.teacher",
                        verbose_name="Professor",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Professor",
                "verbose_name_plural": "Professores",
                "ordering": ["name"],
            },
        ),
    ]
