# Generated by Django 5.2.12 on 2026-03-29 05:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_alter_teacher_options_alter_academicyear_tenant_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(blank=True, max_length=50, verbose_name="Escola"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Removido em"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "code",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Código do ciclo"
                    ),
                ),
                (
                    "track",
                    models.CharField(
                        choices=[
                            ("general", "Ensino geral"),
                            ("technical", "Ensino técnico profissional"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Trilho",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciclo",
                "verbose_name_plural": "Ciclos",
                "ordering": ["track", "order", "code"],
            },
        ),
        migrations.AddField(
            model_name="grade",
            name="cycle_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grades",
                to="school.cycle",
                verbose_name="Ciclo (model)",
            ),
        ),
    ]
