# Generated by Django 5.2.12 on 2026-03-29 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0006_cycle_grade_cycle_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="cycle_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classrooms",
                to="school.cycle",
                verbose_name="Ciclo (model)",
            ),
        ),
    ]
