# Generated by Django 5.2.12 on 2026-03-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0007_classroom_cycle_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "ordering": ["name"],
                "verbose_name": "Professor",
                "verbose_name_plural": "Professores",
            },
        ),
        migrations.AlterModelOptions(
            name="teacherspecialty",
            options={
                "ordering": ["teacher__name", "name"],
                "verbose_name": "Especialidade de professor",
                "verbose_name_plural": "Especialidades de professor",
            },
        ),
        migrations.RemoveField(
            model_name="teacherspecialty",
            name="notes",
        ),
    ]
