# Generated by Django 5.2.12 on 2026-03-29 09:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0010_payment_payment_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentplan",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="code",
            field=models.CharField(blank=True, max_length=60, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Criado em",
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Removido em"
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Atualizado em"
            ),
        ),
    ]
