// Métodos analíticos do catálogo de exames (espelha apps/clinical_laboratory/models.py · LabMethod).
// Pares [valor, rótulo], ordenados por rótulo. Usado nos formulários de exame (criar/editar).
export const LAB_METHOD_OPTIONS: [string, string][] = [
  ['Aglutinacao', 'Aglutinação'],
  ['AglutinacaoLatex', 'Aglutinação em látex'],
  ['Automatizado', 'Automatizado'],
  ['AvaliacaoMacroscopica', 'Avaliação macroscópica'],
  ['Baermann', 'Baermann'],
  ['Biureto', 'Biureto'],
  ['CineticoColorimetrico', 'Cinético colorimétrico'],
  ['CineticoEnzimatico', 'Cinético enzimático'],
  ['CineticoUV', 'Cinético UV'],
  ['Coagulometria', 'Coagulometria'],
  ['ColoracaoGram', 'Coloração de Gram'],
  ['ColoracaoZiehl', 'Coloração de Ziehl-Neelsen'],
  ['Colorimetrico', 'Colorimétrico'],
  ['ConcentracaoFormolEter', 'Concentração formol-éter'],
  ['Cromogenico', 'Cromogénico'],
  ['Cultura', 'Cultura'],
  ['CulturaMicologica', 'Cultura micológica'],
  ['CulturaQuantitativa', 'Cultura quantitativa'],
  ['CulturaSeletiva', 'Cultura seletiva'],
  ['CulturaSemiquantitativa', 'Cultura semiquantitativa'],
  ['Calculo', 'Cálculo'],
  ['DiazoColorimetrico', 'Diazo-colorimétrico'],
  ['dRVVT', 'dRVVT'],
  ['ELISA', 'ELISA'],
  ['EletrodoIonSeletivo', 'Elétrodo íon-seletivo (ISE)'],
  ['Enzimatico', 'Enzimático'],
  ['EnzimaticoColorimetrico', 'Enzimático colorimétrico'],
  ['EnzimaticoDireto', 'Enzimático direto'],
  ['EsfregacoDelgado', 'Esfregaço delgado'],
  ['espectrofotometrico/colorimetrico', 'Espectrofotométrico / Colorimétrico'],
  ['ExameMicologicoDireto', 'Exame micológico direto'],
  ['FitaGomada', 'Fita gomada'],
  ['Floculacao', 'Floculação'],
  ['FisicoQuimicoMicroscopia', 'Físico-químico + microscopia'],
  ['Genotipagem', 'Genotipagem'],
  ['GotaEspessa', 'Gota espessa'],
  ['Hemaglutinacao', 'Hemaglutinação'],
  ['HematologiaAutomatizada', 'Hematologia automatizada'],
  ['HibridizacaoMolecular', 'Hibridização molecular'],
  ['HPLC', 'HPLC'],
  ['Imunocromatografia', 'Imunocromatografia'],
  ['Imunoensaio', 'Imunoensaio'],
  ['Imunoinibicao', 'Imunoinibição'],
  ['Imunoturbidimetria', 'Imunoturbidimetria'],
  ['IvyDuke', 'Ivy / Duke'],
  ['KatoKatz', 'Kato-Katz'],
  ['KirbyBauer', 'Kirby-Bauer'],
  ['MicroscopiaSedimento', 'Microscopia de sedimento'],
  ['MicroscopiaOptica', 'Microscopia óptica'],
  ['Microscopico', 'Microscópico'],
  ['MetodoManual', 'Método manual'],
  ['NAAT', 'NAAT'],
  ['PCR', 'PCR'],
  ['PCRAleloEspecifico', 'PCR alelo-específico'],
  ['PCRTempoReal', 'PCR em tempo real'],
  ['PCRMultiplex', 'PCR multiplex'],
  ['PCRMutacional', 'PCR mutacional'],
  ['PCRQualitativo', 'PCR qualitativo'],
  ['PCRQuantitativo', 'PCR quantitativo'],
  ['Quimioluminescencia', 'Quimioluminescência (CLIA)'],
  ['RTPCRMultiplex', 'RT-PCR multiplex'],
  ['RTPCRQualitativo', 'RT-PCR qualitativo'],
  ['RTPCRQuantitativo', 'RT-PCR quantitativo'],
  ['RTqPCR', 'RT-qPCR'],
  ['Sedimentacao', 'Sedimentação'],
  ['Sequenciamento', 'Sequenciamento'],
  ['TiraReagente', 'Tira reagente'],
  ['VerdeBromocresol', 'Verde de bromocresol'],];
