import type { LucideIcon } from "lucide-react"
import {
  Activity,
  Baby,
  Bell,
  Bot,
  BrainCircuit,
  Briefcase,
  Building2,
  Calculator,
  CalendarClock,
  ClipboardCheck,
  ClipboardList,
  CreditCard,
  Droplet,
  FileText,
  Fuel,
  Gauge,
  FlaskConical,
  GraduationCap,
  HeartPulse,
  Layers,
  Lightbulb,
  MapPin,
  Microscope,
  Navigation,
  PackageSearch,
  PackageCheck,
  Pill,
  Router,
  Scissors,
  Search,
  ShieldCheck,
  ShoppingCart,
  Stethoscope,
  Syringe,
  TerminalSquare,
  Truck,
  Users,
  Wrench,
} from "lucide-react"

const MODULE_ICON_BY_KEY: Record<string, LucideIcon> = {
  administration: Briefcase,
  accounting: Calculator,
  ai_assistant: Bot,
  analytics: Activity,
  audit: Activity,
  billing: FileText,
  bloodbank: Droplet,
  care: HeartPulse,
  clinical: Stethoscope,
  clinical_pharmacy: Pill,
  consultations: ClipboardList,
  credit_financing: CreditCard,
  dashboard: ClipboardList,
  dental: Stethoscope,
  pathology: Microscope,
  education: GraduationCap,
  entities: Building2,
  equipment: Microscope,
  equipment_integrations: TerminalSquare,
  human_resources: Users,
  identity: ShieldCheck,
  insurer: ShieldCheck,
  maternity: Baby,
  medical_records: FileText,
  monitoring: Activity,
  notifications: Bell,
  nursing: HeartPulse,
  payments: CreditCard,
  physiotherapy: Activity,
  platform: ShieldCheck,
  public_health: Syringe,
  radiology: Microscope,
  diagnostics: Microscope,
  hospitalization: HeartPulse,
  operations: PackageSearch,
  specialty_diagnostics: HeartPulse,
  therapy: HeartPulse,
  pharmacy: Pill,
  reception: Briefcase,
  surgery: Scissors,
  tenants: Building2,
  telemedicine: HeartPulse,
  transportation: Truck,
  veterinary: HeartPulse,
  warehouse: PackageSearch,
}

const RESOURCE_ICON_BY_KEY: Record<string, LucideIcon> = {
  "clinical.clinicalevent": Bell,
  "clinical.clinicalhistory": FileText,
  "clinical.clinicalreference": ClipboardCheck,
  "clinical.eventoclinico": Bell,
  "clinical.historicoclinico": FileText,
  "clinical.labrequestitem": ClipboardList,
  "clinical.medicalresultfile": FileText,
  "clinical.referenciaclinica": ClipboardCheck,
  "clinical.requisicaoitem": ClipboardList,
  "clinical.resultadomedicoarquivo": FileText,
  "clinical.resultadoitem": ClipboardCheck,
  "clinical.resultitem": ClipboardCheck,
  "clinical_pharmacy.antibiotic_review": ShieldCheck,
  "clinical_pharmacy.controlled_movement": ShieldCheck,
  "clinical_pharmacy.ingredient": FlaskConical,
  "clinical_pharmacy.interaction_check": ClipboardCheck,
  "clinical_pharmacy.interaction_rule": ClipboardList,
  "clinical_pharmacy.preparation": Pill,
  "credit_financing.consortium": Users,
  "credit_financing.installment": Calculator,
  "credit_financing.procedure_financing": CreditCard,
  "credit_financing.reimbursement_claim": FileText,
  "credit_financing.student_funding": GraduationCap,
  "dental.approval": ShieldCheck,
  "dental.appointment": ClipboardList,
  "dental.audit_event": Activity,
  "dental.billing_item": Calculator,
  "dental.clinical_evolution": HeartPulse,
  "dental.consultation": Stethoscope,
  "dental.diagnosis": ClipboardCheck,
  "dental.document": FileText,
  "dental.followup": CalendarClock,
  "dental.imaging_order": Microscope,
  "dental.material_consumption": PackageSearch,
  "dental.odontogram": ClipboardCheck,
  "dental.odontogram_chart": ClipboardCheck,
  "dental.payment": CreditCard,
  "dental.procedure": Stethoscope,
  "dental.procedure_execution": Stethoscope,
  "dental.prosthesis_lab_order": PackageCheck,
  "dental.quotation": Calculator,
  "dental.record": FileText,
  "dental.patient_treatment_plan": Users,
  "dental.patient_plan_summary": Users,
  "dental.prescription": Pill,
  "dental.treatment_phase": Layers,
  "dental.treatment_item": ClipboardCheck,
  "dental.treatment_plan": ClipboardList,
  "veterinary.admission": HeartPulse,
  "veterinary.animal": HeartPulse,
  "veterinary.appointment": ClipboardList,
  "veterinary.lab_exam": FlaskConical,
  "veterinary.lab_request": FileText,
  "veterinary.lab_request_item": ClipboardCheck,
  "veterinary.prescription": Pill,
  "veterinary.prescription_item": Pill,
  "veterinary.record": FileText,
  "veterinary.vaccination": ShieldCheck,
  "veterinary.vaccine": ShieldCheck,
  "physiotherapy.assessment": ClipboardCheck,
  "physiotherapy.device": Wrench,
  "physiotherapy.device_usage": Gauge,
  "physiotherapy.intervention": Activity,
  "physiotherapy.progress_note": FileText,
  "physiotherapy.session": ClipboardList,
  "physiotherapy.treatment_plan": ClipboardList,
  "pathology.pedidos": ClipboardList,
  "pathology.recepcao_amostras": FlaskConical,
  "pathology.acessionamento": PackageCheck,
  "pathology.macroscopia": Search,
  "pathology.processamento": Gauge,
  "pathology.inclusao": PackageSearch,
  "pathology.microtomia": Scissors,
  "pathology.histologia": Microscope,
  "pathology.coloracoes": FlaskConical,
  "pathology.citologia": Microscope,
  "pathology.imunohistoquimica": FlaskConical,
  "pathology.molecular": BrainCircuit,
  "pathology.diagnosticos": ClipboardCheck,
  "pathology.laudos": FileText,
  "pathology.faturacao": CreditCard,
  "pathology.inventario": PackageCheck,
  "pathology.controlo_qualidade": ShieldCheck,
  "pathology.arquivamento": PackageSearch,
  "radiology.equipment": Wrench,
  "radiology.file": FileText,
  "radiology.pacs_event": TerminalSquare,
  "radiology.protocol": ClipboardList,
  "radiology.report": FileText,
  "radiology.series": Layers,
  "radiology.study": Microscope,
  "specialty_diagnostics.equipment": Wrench,
  "specialty_diagnostics.integration_event": TerminalSquare,
  "specialty_diagnostics.measurement": Activity,
  "specialty_diagnostics.order": HeartPulse,
  "specialty_diagnostics.protocol": ClipboardList,
  "specialty_diagnostics.report": FileText,
  "therapy.evaluation": ClipboardCheck,
  "therapy.goal": ClipboardCheck,
  "therapy.prescription_link": Pill,
  "therapy.progress_note": FileText,
  "therapy.resource": Wrench,
  "therapy.session": ClipboardList,
  "therapy.treatment_plan": ClipboardList,
  "transportation.driver": Users,
  "transportation.fuel_log": Fuel,
  "transportation.maintenance_order": Wrench,
  "transportation.maintenance_plan": ClipboardList,
  "transportation.route": Router,
  "transportation.route_stop": MapPin,
  "transportation.tracking_point": Navigation,
  "transportation.trip": Gauge,
  "transportation.vehicle": Truck,
  "identity.perfilprofissional": Users,
  "identity.professionalprofile": Users,
  "insurer.tenant_coverage_plan": Building2,
  "insurer.tenantcoverageplan": Building2,
  "insurer.tenantplanocobertura": Building2,
  "tenants.assinaturatenant": FileText,
  "tenants.featureflagtenant": ShieldCheck,
  "tenants.planoassinatura": ClipboardList,
  "tenants.subscriptionplan": ClipboardList,
  "tenants.tenantfeatureflag": ShieldCheck,
  "tenants.tenantsubscription": FileText,
  "tenants.tenantusage": Activity,
  "tenants.usotenant": Activity,
  "telemedicine.alert": Bell,
  "telemedicine.async_case": FileText,
  "telemedicine.device": Activity,
  "telemedicine.program": ClipboardCheck,
  "telemedicine.vital_reading": HeartPulse,
  "telemedicine.waiting_room": ClipboardList,
  "public_health.adverse_event": Bell,
  "public_health.campaign": ClipboardList,
  "public_health.immunization": ClipboardCheck,
  "public_health.lot": PackageCheck,
  "public_health.notification": FileText,
  "public_health.target": MapPin,
  "public_health.vaccine": Syringe,
  "surgery.pedido_cirurgico": ClipboardList,
  "surgery.avaliacao_pre_operatoria": Stethoscope,
  "surgery.agenda_cirurgica": ClipboardList,
  "surgery.centro_cirurgico": Scissors,
  "surgery.equipa_cirurgica": Users,
  "surgery.anestesia": HeartPulse,
  "surgery.checklist_seguranca": ClipboardCheck,
  "surgery.materiais": PackageSearch,
  "surgery.consumos": PackageCheck,
  "surgery.recuperacao": HeartPulse,
  "surgery.relatorio_operatorio": FileText,
  "surgery.procedimentos_realizados": ClipboardCheck,
  "surgery.autorizacoes": ShieldCheck,
  "surgery.faturacao": CreditCard,
  "surgery.documentos": FileText,
  "surgery.auditoria": Activity,
  "surgery.amostras": Microscope,
  "ai_assistant.ai_session": Bot,
  "ai_assistant.ai_message": FileText,
  "ai_assistant.ai_tool_call": TerminalSquare,
  "ai_assistant.ai_suggested_action": Lightbulb,
  "ai_assistant.ai_operational_task": ClipboardCheck,
  "ai_assistant.ai_investigation": Search,
  "ai_assistant.ai_knowledge_entry": BrainCircuit,
  "ai_assistant.ai_policy_event": ShieldCheck,
  "ai_assistant.ai_tools": TerminalSquare,
  "warehouse.replenishment_plan": ClipboardList,
  "warehouse.replenishment_suggestion": ClipboardCheck,
  "warehouse.sales_order": ShoppingCart,
  "warehouse.sales_order_line": ClipboardList,
  "warehouse.stock_reservation": ClipboardCheck,
  "warehouse.pick_list": PackageSearch,
  "warehouse.pick_list_line": ClipboardList,
  "warehouse.shipment": Truck,
  "warehouse.shipment_line": PackageCheck,
}

export function getModuleIcon(moduleKey: string): LucideIcon {
  return MODULE_ICON_BY_KEY[moduleKey] || Layers
}

export function getResourceIcon(moduleKey: string, resourceKey: string): LucideIcon {
  return RESOURCE_ICON_BY_KEY[`${moduleKey}.${resourceKey}`] || getModuleIcon(moduleKey)
}
