"use client";
import Link from "next/link";import{useRouter}from"next/navigation";import{useEffect,useMemo,useState}from"react";import{AlertTriangle,ArrowLeft,CalendarClock,ClipboardList,Loader2,MapPin,Stethoscope,User}from"lucide-react";
import AutoForm from "@/components/form/AutoForm";import AppLayout from "@/components/layout/AppLayout";import useAuthGuard from "@/hooks/useAuthGuard";import{apiFetch}from"@/lib/api";import{getResourceFormConfig}from"@/lib/resources/resourceFormConfig";import{GROUPS}from"@/lib/rbac";import type{PathologyRequest}from"./page";
const ENDPOINT="/pathology/pedidos/";const GLASS="rounded-lg border border-white/20 bg-white/35 shadow-sm backdrop-blur-sm dark:border-white/10 dark:bg-white/[0.04]";const COMPACT=["patient","lab_request","requesting_doctor","service","request_type","priority","status","requested_at","icd_code","anatomical_site"];
function Summary({icon:Icon,label,value}:{icon:React.ElementType;label:string;value:React.ReactNode}){return <div className="min-w-0 rounded-md border border-border/60 bg-background/45 px-2 py-1"><div className="flex items-center gap-1 text-[9px] font-bold uppercase tracking-[.1em] text-muted-foreground"><Icon size={11}/>{label}</div><div className="break-words text-sm font-bold">{value||"—"}</div></div>}
export default function RequestFormPage({id}:{id?:string}){useAuthGuard();const router=useRouter();const editing=Boolean(id);const[item,setItem]=useState<PathologyRequest|null>(null);const[loading,setLoading]=useState(editing);const[error,setError]=useState<string|null>(null);
const config=useMemo(()=>{const b=getResourceFormConfig("pathology","pedidos",ENDPOINT)||{};return{...b,ordenarCampos:["patient","lab_request","requesting_doctor","service","request_type","priority","status","requested_at","clinical_diagnosis","icd_code","anatomical_site","notes"],widgets:{...b.widgets,clinical_diagnosis:"textarea" as const,notes:"textarea" as const},etapasEmCartoes:true,etapas:[{titulo:"Paciente e solicitação",descricao:"Paciente, requisição e médico solicitante.",campos:["patient","lab_request","requesting_doctor","service"]},{titulo:"Classificação",descricao:"Tipo, prioridade, estado e data do pedido.",campos:["request_type","priority","status","requested_at"]},{titulo:"Contexto clínico",descricao:"Diagnóstico, CID e procedência anatómica.",campos:["clinical_diagnosis","icd_code","anatomical_site"]},{titulo:"Observações",descricao:"Informação complementar do pedido.",campos:["notes"]}]};},[]);
useEffect(()=>{if(!id)return;let m=true;apiFetch<PathologyRequest>(`${ENDPOINT}${id}/`,{clientCache:false}).then(d=>{if(m)setItem(d)}).catch(e=>{if(m)setError(e?.message||"Falha ao carregar pedido.")}).finally(()=>{if(m)setLoading(false)});return()=>{m=false}},[id]);
return <AppLayout requiredGroups={[GROUPS.ADMIN,GROUPS.RECEPCAO,GROUPS.LABORATORIO,GROUPS.MEDICINA]} fullWidth><div className="w-auto space-y-1.5 px-0.5"><header className={`${GLASS} relative overflow-hidden`}><span className="absolute inset-y-0 left-0 w-1 bg-fuchsia-500"/><div className="space-y-1.5 px-2.5 py-1.5 pl-4"><div className="flex flex-wrap items-center justify-between gap-1.5"><div className="flex min-w-0 items-center gap-1.5"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-fuchsia-500/12 text-fuchsia-600"><ClipboardList size={18}/></span><div className="min-w-0"><p className="text-[9px] font-bold uppercase tracking-[.12em] text-fuchsia-700">Pedido de Patologia</p><h1 className="break-words text-base font-bold">{editing?`Editar ${item?.custom_id||`pedido #${id}`}`:"Novo pedido"}</h1></div></div><Link href={editing?`/pathology/requests/${id}`:"/pathology/requests"} className="inline-flex h-7 items-center gap-1 rounded-md border border-border/70 bg-background/60 px-2 text-xs font-semibold text-muted-foreground"><ArrowLeft size={13}/>Voltar</Link></div>{item?<div className="grid grid-cols-2 gap-1 lg:grid-cols-5"><Summary icon={User} label="Paciente" value={item.patient_name}/><Summary icon={Stethoscope} label="Tipo" value={item.request_type}/><Summary icon={AlertTriangle} label="Prioridade" value={item.priority}/><Summary icon={MapPin} label="Local" value={item.anatomical_site}/><Summary icon={CalendarClock} label="Data" value={item.requested_at}/></div>:null}</div></header>{loading?<div className={`${GLASS} flex min-h-52 items-center justify-center gap-2`}><Loader2 className="animate-spin" size={18}/>A carregar pedido...</div>:error?<div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>:<AutoForm endpoint={editing?`${ENDPOINT}${id}/`:ENDPOINT} method={editing?"put":"post"} initialValues={item?{...item,notes:item.notes?.replace("[SEED-PATHOLOGY]","").trim()}:{}} submitLabel={editing?"Guardar alterações":"Criar pedido"} config={config} compactFields={COMPACT} presentation="radiology" onSuccess={(d)=>router.push(`/pathology/requests/${d?.id||id||""}`)}/>}</div></AppLayout>}
