# Generated by Django 4.2.16 on 2026-03-28 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import infrastructure.orm.fields.money_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seguradora', '0001_initial'),
        ('faturamento', '0002_initial'),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('value', infrastructure.orm.fields.money_field.MoneyField(db_column='value', decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('method', models.CharField(choices=[('DIN', 'Dinheiro'), ('CAR', 'Cartão'), ('TRF', 'Transferência'), ('MOB', 'Mobile Money'), ('POS', 'POS'), ('CHQ', 'Cheque'), ('SEG', 'Seguro de Saúde'), ('OUT', 'Outro')], db_column='method', max_length=4, verbose_name='Método')),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('CON', 'Confirmado'), ('FAL', 'Falhou'), ('EST', 'Estornado'), ('CAN', 'Cancelado')], db_index=True, default='PEN', max_length=3, verbose_name='Estado')),
                ('external_reference', models.CharField(blank=True, db_column='external_reference', help_text='Referência externa (transação, autorização, etc).', max_length=120, verbose_name='Referência externa')),
                ('authorization_number', models.CharField(blank=True, db_column='authorization_number', default='', help_text='Número de autorização do seguro de saúde.', max_length=80, verbose_name='Número de autorização')),
                ('insurance_date', models.JSONField(blank=True, db_column='insurance_date', default=dict, help_text='Dados adicionais do seguro de saúde (ex.: apólice, beneficiário).', verbose_name='Dados do seguro')),
                ('paid_at', models.DateTimeField(blank=True, db_column='paid_at', null=True, verbose_name='Pago em')),
                ('coverage_plan', models.ForeignKey(blank=True, db_column='coverage_plan_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='seguradora.coverageplan', verbose_name='Plano de cobertura')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('insurer', models.ForeignKey(blank=True, db_column='insurer_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='seguradora.insurer', verbose_name='Seguradora')),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='faturamento.invoice', verbose_name='Fatura')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'pagamentos_pagamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.CharField(db_column='external_reference', db_index=True, max_length=120, verbose_name='Referência externa')),
                ('gateway', models.CharField(db_index=True, max_length=80, verbose_name='Gateway')),
                ('status', models.CharField(db_index=True, max_length=40, verbose_name='Status do gateway')),
                ('gateway_response', models.TextField(blank=True, db_column='gateway_response', default='', verbose_name='Resposta do gateway')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'db_table': 'pagamentos_transacao',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['external_reference'], name='pagamentos__externa_0e4039_idx'), models.Index(fields=['gateway', 'status'], name='pagamentos__gateway_f9701c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(db_column='confirmed', db_index=True, default=False, verbose_name='Confirmado')),
                ('confirmation_date', models.DateTimeField(blank=True, db_column='confirmation_date', null=True, verbose_name='Data de confirmação')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='Criado em')),
                ('transaction', models.OneToOneField(db_column='transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='reconciliacao', to='pagamentos.transaction', verbose_name='Transação')),
            ],
            options={
                'verbose_name': 'Reconciliação',
                'verbose_name_plural': 'Reconciliações',
                'db_table': 'pagamentos_reconciliacao',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['confirmed'], name='pagamentos__confirm_c5e691_idx')],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_column='number', db_index=True, max_length=60, verbose_name='Número do recibo')),
                ('value', infrastructure.orm.fields.money_field.MoneyField(db_column='value', decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='Criado em')),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='faturamento.invoice', verbose_name='Fatura')),
                ('payment', models.OneToOneField(db_column='payment_id', on_delete=django.db.models.deletion.PROTECT, related_name='recibo', to='pagamentos.payment', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'db_table': 'pagamentos_recibo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice', 'created_at'], name='pagamentos__invoice_603f3b_idx'), models.Index(fields=['number'], name='pagamentos__number_2689dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('event_type', models.CharField(choices=[('CRIADO', 'Criado'), ('CONFIRMADO', 'Confirmado'), ('FALHA', 'Falha'), ('ESTORNADO', 'Estornado'), ('CANCELADO', 'Cancelado')], db_column='event_type', db_index=True, max_length=15, verbose_name='Tipo de evento')),
                ('value', infrastructure.orm.fields.money_field.MoneyField(blank=True, db_column='value', decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, verbose_name='Descrição')),
                ('external_reference', models.CharField(blank=True, db_column='external_reference', max_length=120, verbose_name='Referência externa')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='pagamentos.payment', verbose_name='Pagamento')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Pagamento',
                'verbose_name_plural': 'Histórico de Pagamentos',
                'db_table': 'pagamentos_historicopagamento',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment'], name='pagamentos__payment_c1e129_idx'), models.Index(fields=['event_type'], name='pagamentos__event_t_5aeccf_idx'), models.Index(fields=['created_at'], name='pagamentos__created_990fce_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='pagamentos__invoice_778b81_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='pagamentos__status_fe65ad_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='pagamentos__created_9e01f9_idx'),
        ),
    ]
