# Generated by Django 4.2.29 on 2026-04-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('DIN', 'Dinheiro'), ('CAR', 'Cartão'), ('TRF', 'Transferência'), ('MOB', 'Mobile Money'), ('POS', 'POS'), ('CHQ', 'Cheque'), ('SEG', 'Seguro de Saúde'), ('OUT', 'Outro')], db_column='method', max_length=4, verbose_name='Forma de Pagamento'),
        ),
    ]
