# Generated by Django 5.1 on 2026-03-26 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faturamento", "0002_initial"),
        (
            "inquilinos",
            "0002_rename_inquilinos__tipo_856ce4_idx_inquilinos__type_fdb81e_idx_and_more",
        ),
        ("pagamentos", "0001_initial"),
        ("seguradora", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="coverage_plan",
            field=models.ForeignKey(
                blank=True,
                db_column="coverage_plan_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagamentos",
                to="seguradora.coverageplan",
                verbose_name="Plano de cobertura",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="created_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                db_column="deleted_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="insurer",
            field=models.ForeignKey(
                blank=True,
                db_column="insurer_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagamentos",
                to="seguradora.insurer",
                verbose_name="Seguradora",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                db_column="invoice_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagamentos",
                to="faturamento.invoice",
                verbose_name="Fatura",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.tenant",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="created_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                db_column="deleted_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="payment",
            field=models.ForeignKey(
                db_column="payment_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historico",
                to="pagamentos.payment",
                verbose_name="Pagamento",
            ),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.tenant",
            ),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="invoice",
            field=models.ForeignKey(
                db_column="invoice_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recibos",
                to="faturamento.invoice",
                verbose_name="Fatura",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="payment",
            field=models.OneToOneField(
                db_column="payment_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recibo",
                to="pagamentos.payment",
                verbose_name="Pagamento",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["external_reference"], name="pagamentos__externa_0e4039_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["gateway", "status"], name="pagamentos__gateway_f9701c_idx"
            ),
        ),
        migrations.AddField(
            model_name="reconciliation",
            name="transaction",
            field=models.OneToOneField(
                db_column="transaction_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reconciliacao",
                to="pagamentos.transaction",
                verbose_name="Transação",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["invoice"], name="pagamentos__invoice_778b81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="pagamentos__status_fe65ad_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created_at"], name="pagamentos__created_9e01f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenthistory",
            index=models.Index(
                fields=["payment"], name="pagamentos__payment_c1e129_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenthistory",
            index=models.Index(
                fields=["event_type"], name="pagamentos__event_t_5aeccf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenthistory",
            index=models.Index(
                fields=["created_at"], name="pagamentos__created_990fce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["invoice", "created_at"], name="pagamentos__invoice_603f3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(fields=["number"], name="pagamentos__number_2689dc_idx"),
        ),
        migrations.AddIndex(
            model_name="reconciliation",
            index=models.Index(
                fields=["confirmed"], name="pagamentos__confirm_c5e691_idx"
            ),
        ),
    ]
