# Generated by Django 4.2.29 on 2026-04-20 11:50

from decimal import Decimal

from django.db import migrations

import infrastructure.orm.fields.money_field


class Migration(migrations.Migration):

    dependencies = [
        ("pagamentos", "0002_alter_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="change_amount",
            field=infrastructure.orm.fields.money_field.MoneyField(
                db_column="change_amount",
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Troco",
            ),
        ),
    ]
