# Generated by Django 5.1 on 2026-03-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagamentos", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
            },
        ),
    ]
