# Generated by Django 4.2.16 on 2026-03-14 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultas', '0001_initial'),
        ('clinico', '0005_requisicaoanalise_tipo'),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProntuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('data_atendimento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], db_index=True, default='RASCUNHO', max_length=20)),
                ('sintomas', models.TextField(blank=True, default='')),
                ('diagnostico', models.TextField(blank=True, default='')),
                ('prescricao', models.TextField(blank=True, default='')),
                ('relatorio_medico', models.TextField(blank=True, default='')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('consulta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prontuario', to='consultas.consultamedica')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_prontuario', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_prontuario', to='clinico.paciente')),
            ],
            options={
                'verbose_name': 'Registro de Prontuário',
                'verbose_name_plural': 'Registros de Prontuário',
                'ordering': ['-data_atendimento', '-criado_em'],
                'indexes': [models.Index(fields=['inquilino', 'paciente', 'data_atendimento'], name='prontuario__inquili_e96b03_idx'), models.Index(fields=['inquilino', 'medico', 'data_atendimento'], name='prontuario__inquili_2af459_idx'), models.Index(fields=['inquilino', 'estado', 'data_atendimento'], name='prontuario__inquili_a30011_idx')],
            },
        ),
    ]
