# Generated by Django 4.2.29 on 2026-06-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_backfill_tests_from_legacy_clinical'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestpanel',
            name='occupation',
            field=models.CharField(blank=True, db_column='occupation', default='', max_length=120, verbose_name='Função / tipo de trabalho'),
        ),
        migrations.AddField(
            model_name='labtestpanel',
            name='profile_type',
            field=models.CharField(choices=[('standard', 'Painel padrão'), ('occupational', 'Perfil ocupacional')], db_column='profile_type', db_index=True, default='standard', max_length=20, verbose_name='Tipo de perfil'),
        ),
    ]
