# Generated by Django 4.2.29 on 2026-06-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_initial'),
        ('laboratorio', '0005_labtestpanel_occupation_labtestpanel_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='requesting_company',
            field=models.ForeignKey(blank=True, db_column='requesting_company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entidades.company', verbose_name='Companhia solicitante'),
        ),
    ]
