# Generated by Django 4.2.29 on 2026-06-23 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0004_tenantconfiguration_fiscal_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratorio', '0008_backfill_laborderitem_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalresultnotification',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='critical_notifications', to='laboratorio.laborder', verbose_name='Requisição'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='critical_high',
            field=models.DecimalField(blank=True, db_column='critical_high', decimal_places=4, max_digits=18, null=True, verbose_name='Limite crítico superior (pânico)'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='critical_low',
            field=models.DecimalField(blank=True, db_column='critical_low', decimal_places=4, max_digits=18, null=True, verbose_name='Limite crítico inferior (pânico)'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='reference_high',
            field=models.DecimalField(blank=True, db_column='reference_high', decimal_places=4, max_digits=18, null=True, verbose_name='Limite superior de referência'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='reference_low',
            field=models.DecimalField(blank=True, db_column='reference_low', decimal_places=4, max_digits=18, null=True, verbose_name='Limite inferior de referência'),
        ),
        migrations.CreateModel(
            name='LabTestField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('code', models.CharField(blank=True, db_column='code', default='', max_length=30, verbose_name='Código')),
                ('unit', models.CharField(blank=True, db_column='unit', default='', max_length=30, verbose_name='Unidade')),
                ('reference_range', models.CharField(blank=True, db_column='reference_range', default='', max_length=160, verbose_name='Intervalo de referência')),
                ('reference_low', models.DecimalField(blank=True, db_column='reference_low', decimal_places=4, max_digits=18, null=True, verbose_name='Limite inferior de referência')),
                ('reference_high', models.DecimalField(blank=True, db_column='reference_high', decimal_places=4, max_digits=18, null=True, verbose_name='Limite superior de referência')),
                ('critical_low', models.DecimalField(blank=True, db_column='critical_low', decimal_places=4, max_digits=18, null=True, verbose_name='Limite crítico inferior (pânico)')),
                ('critical_high', models.DecimalField(blank=True, db_column='critical_high', decimal_places=4, max_digits=18, null=True, verbose_name='Limite crítico superior (pânico)')),
                ('sequence', models.PositiveIntegerField(db_column='sequence', default=0, verbose_name='Ordem')),
                ('active', models.BooleanField(db_column='active', db_index=True, default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('test', models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='laboratorio.labtest', verbose_name='Exame')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campo de exame',
                'verbose_name_plural': 'Campos de exame',
                'db_table': 'laboratorio_exame_campo',
                'ordering': ['test', 'sequence', 'name'],
            },
        ),
        migrations.AddField(
            model_name='labresult',
            name='test_field',
            field=models.ForeignKey(blank=True, db_column='test_field_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='laboratorio.labtestfield', verbose_name='Campo de exame'),
        ),
        migrations.AddIndex(
            model_name='labtestfield',
            index=models.Index(fields=['tenant', 'test', 'active'], name='laboratorio_tenant__1267c6_idx'),
        ),
    ]
