# Generated by Django 4.2.29 on 2026-07-03 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0004_tenantconfiguration_fiscal_address_and_more'),
        ('laboratorio', '0014_labcontainertype_labtest_container_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biologicalhazard',
            name='required_ppe',
        ),
        migrations.RemoveField(
            model_name='biologicalhazard',
            name='transmission_route',
        ),
        migrations.AddField(
            model_name='biologicalhazard',
            name='required_ppe_items',
            field=models.ManyToManyField(blank=True, db_table='laboratorio_bio_perigo_epi', related_name='hazards', to='laboratorio.ppeitem', verbose_name='EPI requerido'),
        ),
        migrations.AlterField(
            model_name='biologicalhazard',
            name='containment_level',
            field=models.CharField(blank=True, choices=[('NB1', 'NB-1 — Nível de biossegurança 1'), ('NB2', 'NB-2 — Nível de biossegurança 2'), ('NB3', 'NB-3 — Nível de biossegurança 3'), ('NB4', 'NB-4 — Nível de biossegurança 4')], db_column='containment_level', default='', max_length=4, verbose_name='Nível de contenção'),
        ),
        migrations.CreateModel(
            name='TransmissionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', max_length=80, verbose_name='Nome')),
                ('description', models.TextField(blank=True, db_column='description', default='', verbose_name='Descrição')),
                ('active', models.BooleanField(db_column='active', db_index=True, default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Via de transmissão',
                'verbose_name_plural': 'Vias de transmissão',
                'db_table': 'laboratorio_bio_via_transmissao',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='biologicalhazard',
            name='transmission_routes',
            field=models.ManyToManyField(blank=True, db_table='laboratorio_bio_perigo_vias', related_name='hazards', to='laboratorio.transmissionroute', verbose_name='Vias de transmissão'),
        ),
    ]
