# Generated by Django 4.2.29 on 2026-07-06 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0004_tenantconfiguration_fiscal_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratorio', '0018_alter_biologicalhazard_hazard_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftrainingrecord',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='stafftrainingrecord',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='training_participations', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.CreateModel(
            name='TrainingReplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('replication_date', models.DateField(blank=True, null=True, verbose_name='Data da réplica')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replications', to='laboratorio.stafftrainingrecord', verbose_name='Formação original')),
                ('participants', models.ManyToManyField(blank=True, related_name='replication_participations', to=settings.AUTH_USER_MODEL, verbose_name='Participantes da réplica')),
                ('replicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Replicante')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réplica de formação',
                'verbose_name_plural': 'Réplicas de formação',
                'db_table': 'laboratorio_qm_formacao_replica',
                'ordering': ['-replication_date'],
            },
        ),
    ]
