# Generated by Django 4.2.29 on 2026-07-06 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0004_tenantconfiguration_fiscal_address_and_more'),
        ('laboratorio', '0019_training_participants_notes_replication'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('file', models.FileField(upload_to='trainings/attachments/%Y/%m/', verbose_name='Ficheiro')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome original')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='laboratorio.stafftrainingrecord', verbose_name='Formação')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo de formação',
                'verbose_name_plural': 'Anexos de formação',
                'db_table': 'laboratorio_qm_formacao_anexo',
                'ordering': ['created_at'],
            },
        ),
    ]
