# Generated by Django 4.2.29 on 2026-07-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0021_training_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalaudit',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='internal_audits', to='laboratorio.labsector', verbose_name='Sectores auditados'),
        ),
        migrations.AlterField(
            model_name='internalaudit',
            name='area',
            field=models.CharField(blank=True, db_column='area', default='', max_length=300, verbose_name='Área auditada'),
        ),
    ]
