# Generated by Django 6.0.5 on 2026-07-07 07:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0004_tenantconfiguration_fiscal_address_and_more'),
        ('laboratorio', '0022_audit_sectors_auto_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryQualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('control_type', models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo'), ('ENSAIO_PROFICIENCIA', 'Ensaio de proficiência'), ('CALIBRACAO', 'Calibração/verificação')], db_column='control_type', db_index=True, default='INTERNO', max_length=20, verbose_name='Tipo de controlo')),
                ('result_mode', models.CharField(choices=[('NUMERICO', 'Numérico'), ('QUALITATIVO', 'Qualitativo')], db_column='result_mode', default='NUMERICO', max_length=12, verbose_name='Modo de resultado')),
                ('material_name', models.CharField(blank=True, db_column='material_name', default='', max_length=160, verbose_name='Material de controlo')),
                ('material_lot', models.CharField(blank=True, db_column='material_lot', default='', max_length=80, verbose_name='Lote do material')),
                ('material_level', models.CharField(choices=[('BAIXO', 'Baixo'), ('NORMAL', 'Normal'), ('ALTO', 'Alto'), ('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo'), ('MULTINIVEL', 'Multinível')], db_column='material_level', default='NORMAL', max_length=12, verbose_name='Nível do controlo')),
                ('manufacturer', models.CharField(blank=True, db_column='manufacturer', default='', max_length=120, verbose_name='Fabricante')),
                ('expiry_date', models.DateField(blank=True, db_column='expiry_date', null=True, verbose_name='Validade do material')),
                ('method', models.CharField(blank=True, db_column='method', default='', max_length=120, verbose_name='Método')),
                ('equipment', models.CharField(blank=True, db_column='equipment', default='', max_length=120, verbose_name='Equipamento')),
                ('sop_reference', models.CharField(blank=True, db_column='sop_reference', default='', max_length=120, verbose_name='POP/Procedimento')),
                ('iso_clause', models.CharField(blank=True, db_column='iso_clause', default='ISO 9001:2015 8.5.1/9.1', max_length=80, verbose_name='Cláusula ISO/SGQ')),
                ('acceptance_criteria', models.TextField(blank=True, db_column='acceptance_criteria', default='', verbose_name='Critério de aceitação')),
                ('expected_result', models.CharField(db_column='expected_result', max_length=255, verbose_name='Resultado esperado')),
                ('observed_result', models.CharField(db_column='observed_result', max_length=255, verbose_name='Resultado obtido')),
                ('expected_numeric', models.DecimalField(blank=True, db_column='expected_numeric', decimal_places=4, max_digits=18, null=True, verbose_name='Valor esperado')),
                ('observed_numeric', models.DecimalField(blank=True, db_column='observed_numeric', decimal_places=4, max_digits=18, null=True, verbose_name='Valor obtido')),
                ('expected_min', models.DecimalField(blank=True, db_column='expected_min', decimal_places=4, max_digits=18, null=True, verbose_name='Mínimo aceitável')),
                ('expected_max', models.DecimalField(blank=True, db_column='expected_max', decimal_places=4, max_digits=18, null=True, verbose_name='Máximo aceitável')),
                ('tolerance', models.DecimalField(blank=True, db_column='tolerance', decimal_places=4, max_digits=18, null=True, verbose_name='Tolerância absoluta')),
                ('deviation', models.DecimalField(blank=True, db_column='deviation', decimal_places=4, max_digits=18, null=True, verbose_name='Desvio')),
                ('unit', models.CharField(blank=True, db_column='unit', default='', max_length=30, verbose_name='Unidade')),
                ('measurement_uncertainty', models.CharField(blank=True, db_column='measurement_uncertainty', default='', max_length=80, verbose_name='Incerteza de medição')),
                ('run_at', models.DateTimeField(db_column='run_at', db_index=True, default=django.utils.timezone.now, verbose_name='Executado em')),
                ('reviewed_at', models.DateTimeField(blank=True, db_column='reviewed_at', null=True, verbose_name='Revisto em')),
                ('decision', models.CharField(choices=[('APROVADO', 'Aprovado para uso'), ('REJEITADO', 'Rejeitado'), ('REVISAO', 'Requer revisão'), ('INCOMPLETO', 'Incompleto')], db_column='decision', db_index=True, default='INCOMPLETO', max_length=12, verbose_name='Conclusão automática')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AVALIADO', 'Avaliado'), ('REVISTO', 'Revisto'), ('BLOQUEADO', 'Bloqueado')], db_column='status', db_index=True, default='RASCUNHO', max_length=10, verbose_name='Estado')),
                ('approved_for_use', models.BooleanField(db_column='approved_for_use', default=False, verbose_name='Pode usar o teste')),
                ('corrective_action_required', models.BooleanField(db_column='corrective_action_required', default=False, verbose_name='Requer ação corretiva')),
                ('root_cause', models.TextField(blank=True, db_column='root_cause', default='', verbose_name='Causa provável')),
                ('corrective_action', models.TextField(blank=True, db_column='corrective_action', default='', verbose_name='Ação corretiva/preventiva')),
                ('traceability_notes', models.TextField(blank=True, db_column='traceability_notes', default='', verbose_name='Rastreabilidade/evidências')),
                ('conclusion_notes', models.TextField(blank=True, db_column='conclusion_notes', default='', verbose_name='Notas de conclusão')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('nonconformity', models.ForeignKey(blank=True, db_column='nonconformity_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_controls', to='laboratorio.nonconformity', verbose_name='Não conformidade')),
                ('performed_by', models.ForeignKey(blank=True, db_column='performed_by_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Executado por')),
                ('result', models.ForeignKey(blank=True, db_column='result_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_controls', to='laboratorio.labresult', verbose_name='Resultado associado')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revisto por')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('test', models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.PROTECT, related_name='quality_controls', to='laboratorio.labtest', verbose_name='Exame')),
                ('test_field', models.ForeignKey(blank=True, db_column='test_field_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_controls', to='laboratorio.labtestfield', verbose_name='Analito/campo')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Controlo de qualidade laboratorial',
                'verbose_name_plural': 'Controlos de qualidade laboratoriais',
                'db_table': 'laboratorio_controle_qualidade',
                'ordering': ['-run_at'],
                'indexes': [models.Index(fields=['tenant', 'test', 'decision'], name='laboratorio_tenant__7c6781_idx'), models.Index(fields=['tenant', 'status', 'run_at'], name='laboratorio_tenant__03ba16_idx')],
            },
        ),
    ]
