# Generated by Django 4.2.29 on 2026-07-07 20:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0023_laboratoryqualitycontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='microbiologyculture',
            name='biochemical_tests',
            field=models.JSONField(blank=True, db_column='biochemical_tests', default=list, verbose_name='Provas bioquímicas'),
        ),
        migrations.AddField(
            model_name='microbiologyculture',
            name='culture_plates',
            field=models.JSONField(blank=True, db_column='culture_plates', default=list, verbose_name='Placas e meios de cultura'),
        ),
        migrations.AddField(
            model_name='microbiologyculture',
            name='gram_exam',
            field=models.JSONField(blank=True, db_column='gram_exam', default=dict, verbose_name='Exame de Gram'),
        ),
        migrations.AddField(
            model_name='microbiologyculture',
            name='growth_observations',
            field=models.JSONField(blank=True, db_column='growth_observations', default=list, verbose_name='Observações de crescimento'),
        ),
        migrations.AddField(
            model_name='microbiologyculture',
            name='incubation_accumulated_hours',
            field=models.DecimalField(db_column='incubation_accumulated_hours', decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Horas acumuladas de incubação'),
        ),
        migrations.AddField(
            model_name='microbiologyculture',
            name='incubation_expected_end_at',
            field=models.DateTimeField(blank=True, db_column='incubation_expected_end_at', null=True, verbose_name='Fim previsto da incubação'),
        ),
        migrations.AddField(
            model_name='microbiologyculture',
            name='incubation_periods',
            field=models.JSONField(blank=True, db_column='incubation_periods', default=list, verbose_name='Períodos de incubação'),
        ),
        migrations.AlterField(
            model_name='microbiologyculture',
            name='status',
            field=models.CharField(choices=[('MONTADA', 'Montada'), ('INCUBACAO', 'Em incubação'), ('AGUARDA_AVALIACAO', 'Aguardando avaliação'), ('REINCUBACAO', 'Reincubada'), ('CRESCIMENTO', 'Crescimento detetado'), ('SEM_CRESCIMENTO', 'Sem crescimento'), ('POSITIVA', 'Positiva'), ('NEGATIVA', 'Negativa'), ('CONCLUIDA', 'Concluída')], db_index=True, default='MONTADA', max_length=20, verbose_name='Estado'),
        ),
    ]
