# Generated by Django 4.2.16 on 2026-03-15 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0001_initial'),
        ('clinico', '0001_initial'),
        ('faturamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinRecepcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('prioridade', models.CharField(choices=[('URG', 'Urgente'), ('PREF', 'Preferencial'), ('NOR', 'Normal')], db_index=True, default='NOR', max_length=5)),
                ('estado', models.CharField(choices=[('AGUARD', 'Aguardando'), ('ATEND', 'Em atendimento'), ('REQ', 'Requisição criada'), ('FAT', 'Fatura vinculada'), ('CONC', 'Concluído'), ('CANC', 'Cancelado')], db_index=True, default='AGUARD', max_length=6)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('chegou_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('chamado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_recepcao', to=settings.AUTH_USER_MODEL)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('fatura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkin', to='faturamento.fatura')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='clinico.paciente')),
                ('requisicao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkin', to='clinico.requisicaoanalise')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['-chegou_em'],
                'indexes': [models.Index(fields=['inquilino', 'chegou_em'], name='recepcao_ch_inquili_282070_idx'), models.Index(fields=['inquilino', 'estado'], name='recepcao_ch_inquili_6ae330_idx'), models.Index(fields=['inquilino', 'prioridade'], name='recepcao_ch_inquili_7540fe_idx')],
            },
        ),
    ]
