# Generated by Django 6.0.1 on 2026-03-10 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0001_initial'),
        ('recepcao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='checkinrecepcao',
            new_name='recepcao_ch_inquili_6ae330_idx',
            old_name='recepcao_inq_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='checkinrecepcao',
            new_name='recepcao_ch_inquili_282070_idx',
            old_name='recepcao_inq_chegou_idx',
        ),
        migrations.RenameIndex(
            model_name='checkinrecepcao',
            new_name='recepcao_ch_priorid_930cf9_idx',
            old_name='recepcao_prioridade_idx',
        ),
        migrations.AlterField(
            model_name='checkinrecepcao',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkinrecepcao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkinrecepcao',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkinrecepcao',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
    ]
