import { apiPath } from "@/lib/api-path";

export type CrudResource = {
  key: string;
  label: string;
  endpoint: string;
  description: string;
  template: Record<string, unknown>;
};

export const crudResources: CrudResource[] = [
  {
    key: "students",
    label: "Alunos",
    endpoint: apiPath("/academic/students/"),
    description: "Registos principais de alunos e respetivo ciclo.",
    template: {
      name: "",
      tenant_id: "",
      birth_date: "2015-01-01",
      grade: 1,
      status: "active",
    },
  },
  {
    key: "guardians",
    label: "Encarregados",
    endpoint: apiPath("/academic/guardians/"),
    description: "Contactos familiares associados aos alunos.",
    template: {
      name: "",
      tenant_id: "",
      phone: "",
      email: "",
      relationship: "Pai",
      active: true,
    },
  },
  {
    key: "student_guardians",
    label: "Relacoes aluno-encarregado",
    endpoint: apiPath("/academic/student-guardians/"),
    description: "Liga alunos e encarregados com permissoes de contacto.",
    template: {
      student: 1,
      guardian: 1,
      primary_contact: true,
      receives_notifications: true,
      tenant_id: "",
    },
  },
  {
    key: "student_outcomes",
    label: "Resultados por aluno",
    endpoint: apiPath("/academic/student-outcomes/"),
    description: "Niveis de dominio por resultado de aprendizagem.",
    template: {
      student: 1,
      outcome: 1,
      mastery_level: "2.0",
      status: "developing",
      evidence_count: 1,
      tenant_id: "",
    },
  },
  {
    key: "academic_years",
    label: "Anos letivos",
    endpoint: apiPath("/school/academic-years/"),
    description: "Calendario oficial de cada ano letivo.",
    template: {
      code: "2026-2027",
      tenant_id: "",
      start_date: "2026-01-01",
      end_date: "2027-01-01",
      active: true,
    },
  },
  {
    key: "grades",
    label: "Classes",
    endpoint: apiPath("/school/grades/"),
    description: "Estrutura de classes e ciclos do ensino.",
    template: {
      number: 1,
      cycle: 1,
      name: "Classe 1",
    },
  },
  {
    key: "schools",
    label: "Escolas",
    endpoint: apiPath("/school/schools/"),
    description: "Unidades escolares e localizacao.",
    template: {
      code: "ESC-001",
      name: "",
      district: "",
      province: "",
      active: true,
    },
  },
  {
    key: "teachers",
    label: "Professores",
    endpoint: apiPath("/school/teachers/"),
    description: "Docentes ligados as escolas.",
    template: {
      user: 1,
      school: 1,
      name: "",
      specialty: "",
    },
  },
  {
    key: "classrooms",
    label: "Turmas",
    endpoint: apiPath("/school/classrooms/"),
    description: "Turmas e respetivos anos letivos.",
    template: {
      name: "1A",
      tenant_id: "",
      school: 1,
      grade: 1,
      cycle: 1,
      academic_year: "2026-2027",
      lead_teacher: 1,
    },
  },
  {
    key: "grade_subjects",
    label: "Disciplinas da classe",
    endpoint: apiPath("/school/grade-subjects/"),
    description: "Carga horaria por disciplina e classe.",
    template: {
      academic_year: "2026-2027",
      grade: 1,
      subject: 1,
      weekly_workload: 3,
      tenant_id: "",
    },
  },
  {
    key: "teaching_assignments",
    label: "Alocacoes docentes",
    endpoint: apiPath("/school/teaching-assignments/"),
    description: "Professor ligado a turma e disciplina.",
    template: {
      teacher: 1,
      classroom: 1,
      grade_subject: 1,
    },
  },
  {
    key: "enrollments",
    label: "Matriculas",
    endpoint: apiPath("/school/enrollments/"),
    description: "Ligacao de alunos a turmas.",
    template: {
      student: 1,
      classroom: 1,
    },
  },
  {
    key: "management_assignments",
    label: "Cargos de gestao",
    endpoint: apiPath("/school/management-assignments/"),
    description: "Direcao e cargos administrativos.",
    template: {
      teacher: 1,
      school: 1,
      academic_year: "2026-2027",
      role: "school_director",
      active: true,
    },
  },
  {
    key: "attendance_records",
    label: "Presencas",
    endpoint: apiPath("/school/attendance-records/"),
    description: "Registos diarios de presenca.",
    template: {
      enrollment: 1,
      lesson_date: "2026-03-01",
      status: "present",
      notes: "",
    },
  },
  {
    key: "announcements",
    label: "Comunicados",
    endpoint: apiPath("/school/announcements/"),
    description: "Mensagens internas para escolas e turmas.",
    template: {
      school: 1,
      classroom: null,
      title: "",
      message: "",
      audience: "school",
      active: true,
    },
  },
  {
    key: "invoices",
    label: "Faturas",
    endpoint: apiPath("/school/invoices/"),
    description: "Cobrancas e faturas escolares.",
    template: {
      student: 1,
      school: 1,
      reference: "INV-001",
      description: "",
      amount: "100.00",
      due_date: "2026-04-01",
      status: "issued",
    },
  },
  {
    key: "payments",
    label: "Pagamentos",
    endpoint: apiPath("/school/payments/"),
    description: "Registo de pagamentos de faturas.",
    template: {
      invoice: 1,
      amount: "100.00",
      payment_date: "2026-04-05",
      method: "cash",
      reference: "",
      notes: "",
    },
  },
  {
    key: "curriculum_areas",
    label: "Areas curriculares",
    endpoint: apiPath("/curriculum/areas/"),
    description: "Areas macro do curriculo.",
    template: {
      name: "",
    },
  },
  {
    key: "subjects",
    label: "Disciplinas",
    endpoint: apiPath("/curriculum/subjects/"),
    description: "Disciplinas e ciclos associados.",
    template: {
      name: "",
      area_id: 1,
      cycle: 1,
    },
  },
  {
    key: "competencies",
    label: "Competencias",
    endpoint: apiPath("/curriculum/competencies/"),
    description: "Competencias curriculares por disciplina.",
    template: {
      name: "",
      area: "language_communication",
      cycle: 1,
      subject_id: 1,
      grade: 1,
    },
  },
  {
    key: "base_curricula",
    label: "Curriculo base",
    endpoint: apiPath("/curriculum/base-curricula/"),
    description: "Curriculo nacional por ciclo.",
    template: {
      cycle: 1,
      competency_ids: [1],
    },
  },
  {
    key: "local_curricula",
    label: "Curriculo local",
    endpoint: apiPath("/curriculum/local-curricula/"),
    description: "Adaptacoes curriculares por tenant.",
    template: {
      tenant_id: "",
      cycle: 1,
      competency_ids: [1],
    },
  },
  {
    key: "learning_outcomes",
    label: "Resultados de aprendizagem",
    endpoint: apiPath("/curriculum/learning-outcomes/"),
    description: "Resultados por disciplina e classe.",
    template: {
      tenant_id: "",
      code: "LO-001",
      description: "",
      subject: 1,
      grade: 1,
      cycle: 1,
      taxonomy_level: "remember",
      knowledge_dimension: "factual",
      active: true,
    },
  },
  {
    key: "competency_outcomes",
    label: "Alinhamentos competencia-resultado",
    endpoint: apiPath("/curriculum/competency-outcomes/"),
    description: "Mapeamento entre competencias e resultados.",
    template: {
      competency: 1,
      outcome: 1,
      weight: "80",
      tenant_id: "",
    },
  },
  {
    key: "subject_plans",
    label: "Planos curriculares",
    endpoint: apiPath("/curriculum/subject-plans/"),
    description: "Planos por disciplina e classe.",
    template: {
      grade_subject: 1,
      objectives: "",
      methodology: "",
      assessment_criteria: "",
      active: true,
      competency_ids: [1],
    },
  },
  {
    key: "assessment_periods",
    label: "Periodos avaliativos",
    endpoint: apiPath("/assessment/periods/"),
    description: "Periodos de avaliacao e calendario.",
    template: {
      academic_year: "2026-2027",
      name: "Periodo 1",
      order: 1,
      start_date: "2026-02-01",
      end_date: "2026-04-30",
      active: true,
    },
  },
  {
    key: "assessment_components",
    label: "Componentes avaliativos",
    endpoint: apiPath("/assessment/components/"),
    description: "Componentes e pesos avaliativos.",
    template: {
      period: 1,
      grade_subject: 1,
      type: "test",
      name: "",
      weight: "50",
      max_score: "20",
      mandatory: true,
    },
  },
  {
    key: "assessment_component_outcomes",
    label: "Mapas componente-resultado",
    endpoint: apiPath("/assessment/component-outcomes/"),
    description: "Peso de resultados por componente.",
    template: {
      component: 1,
      outcome: 1,
      weight: "100",
      tenant_id: "",
    },
  },
  {
    key: "assessments",
    label: "Avaliacoes",
    endpoint: apiPath("/assessment/assessments/"),
    description: "Registos individuais de avaliacao.",
    template: {
      student: 1,
      teaching_assignment: 1,
      period: 1,
      component: 1,
      type: "test",
      date: "2026-03-10",
      score: "15",
    },
  },
  {
    key: "subject_period_results",
    label: "Resultados finais",
    endpoint: apiPath("/assessment/subject-period-results/"),
    description: "Resultados finais por periodo.",
    template: {
      student: 1,
      teaching_assignment: 1,
      period: 1,
      final_average: "14.5",
      assessments_counted: 1,
    },
  },
  {
    key: "courses",
    label: "Cursos",
    endpoint: apiPath("/learning/courses/"),
    description: "Cursos online e presenciais.",
    template: {
      school: 1,
      title: "",
      description: "",
      modality: "online",
      active: true,
    },
  },
  {
    key: "offerings",
    label: "Ofertas de curso",
    endpoint: apiPath("/learning/offerings/"),
    description: "Cursos ligados a turmas e professores.",
    template: {
      course: 1,
      classroom: 1,
      teacher: 1,
      academic_year: "2026-2027",
      start_date: "2026-02-01",
      end_date: "2026-06-01",
      active: true,
    },
  },
  {
    key: "lessons",
    label: "Aulas online",
    endpoint: apiPath("/learning/lessons/"),
    description: "Aulas e encontros virtuais.",
    template: {
      offering: 1,
      title: "",
      description: "",
      scheduled_at: "2026-03-10T09:00:00",
      duration_minutes: 45,
      meeting_url: "",
      published: true,
    },
  },
  {
    key: "lesson_materials",
    label: "Materiais de aula",
    endpoint: apiPath("/learning/lesson-materials/"),
    description: "Recursos e links associados as aulas.",
    template: {
      lesson: 1,
      title: "",
      material_type: "link",
      // Habilita pelo menos um canal para passar na validação do backend.
      link_enabled: true,
      link_url: "https://",
      video_enabled: false,
      audio_enabled: false,
      document_enabled: false,
      image_enabled: false,
      required: true,
    },
  },
  {
    key: "assignments",
    label: "Tarefas",
    endpoint: apiPath("/learning/assignments/"),
    description: "Tarefas online e instrucoes.",
    template: {
      offering: 1,
      title: "",
      instructions: "",
      opens_at: "2026-03-12T08:00:00",
      due_at: "2026-03-20T23:00:00",
      max_score: "20",
      published: true,
    },
  },
  {
    key: "submissions",
    label: "Submissoes",
    endpoint: apiPath("/learning/submissions/"),
    description: "Respostas e entregas dos alunos.",
    template: {
      assignment: 1,
      student: 1,
      submitted_at: "2026-03-14T10:00:00",
      text_response: "",
      status: "submitted",
    },
  },
  {
    key: "progressions",
    label: "Progresso",
    endpoint: apiPath("/progress/progressions/"),
    description: "Decisoes de transicao por ciclo.",
    template: {
      student: 1,
      cycle: 1,
      academic_year: "2026-2027",
      decision_date: "2026-12-10",
      decision: "approved",
      comment: "",
    },
  },
  {
    key: "transfers",
    label: "Transferencias",
    endpoint: apiPath("/transfer/transfers/"),
    description: "Solicitacoes de transferencia de alunos ou professores.",
    template: {
      kind: "student",
      student: null,
      teacher: null,
      from_classroom: null,
      to_classroom: null,
      from_school: null,
      to_school: null,
      move_teaching_assignments: false,
      reason: "",
    },
  },
  {
    key: "certificates",
    label: "Certificados",
    endpoint: apiPath("/certificate/certificates/"),
    description: "Certificados emitidos para alunos.",
    template: {
      student: null,
      course: null,
      status: "draft",
      notes: "",
    },
  },
  {
    key: "events",
    label: "Eventos",
    endpoint: apiPath("/events/events/"),
    description: "Eventos gerados pelo sistema.",
    template: {
      type: "student_registered",
      payload: {
        student_id: 1,
      },
      tenant_id: "",
    },
  },
];
