# Generated by Django 5.1 on 2026-03-25 04:18

import core.mixins.tenant_propagation
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipamentos", "0001_initial"),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deleted_at", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="version", default=1)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DIARIA", "Diária"),
                            ("SEMANAL", "Semanal"),
                            ("MENSAL", "Mensal"),
                            ("SEMESTRAL", "Semestral"),
                            ("ANUAL", "Anual"),
                        ],
                        db_column="type",
                        db_index=True,
                        default="MENSAL",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        db_column="scheduled_date",
                        db_index=True,
                        default=django.utils.timezone.localdate,
                    ),
                ),
                (
                    "performed_date",
                    models.DateField(
                        blank=True, db_column="performed_date", db_index=True, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_column="description", default=""),
                ),
                (
                    "technician",
                    models.CharField(
                        blank=True,
                        db_column="technician",
                        default="",
                        max_length=120,
                        verbose_name="Técnico",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        db_column="equipment_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manutencoes",
                        to="equipamentos.equipment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Manutenção",
                "verbose_name_plural": "Manutenções",
                "db_table": "manutencoes_manutencao",
                "ordering": ["-scheduled_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "equipment", "scheduled_date"],
                        name="manutencoes_inquili_2114e7_idx",
                    ),
                    models.Index(
                        fields=["tenant", "type", "scheduled_date"],
                        name="manutencoes_inquili_eafc65_idx",
                    ),
                    models.Index(
                        fields=["tenant", "performed_date"],
                        name="manutencoes_inquili_4bf83a_idx",
                    ),
                ],
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
    ]
