# Generated by Django 5.1 on 2026-03-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manutencoes", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="maintenance",
            new_name="manutencoes_tenant__2d4cba_idx",
            old_name="manutencoes_inquili_2114e7_idx",
        ),
        migrations.RenameIndex(
            model_name="maintenance",
            new_name="manutencoes_tenant__d3b3ac_idx",
            old_name="manutencoes_inquili_eafc65_idx",
        ),
        migrations.RenameIndex(
            model_name="maintenance",
            new_name="manutencoes_tenant__d0b56f_idx",
            old_name="manutencoes_inquili_4bf83a_idx",
        ),
    ]
