# Generated by Django 4.2.29 on 2026-05-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0003_alter_maintenance_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRECTIVA', 'Correctiva')], db_column='maintenance_type', db_index=True, help_text='Indica se a manutenção é preventiva ou correctiva.', max_length=20, verbose_name='Tipo de manutenção'),
        ),
    ]
