# Generated by Django 4.2.29 on 2026-07-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0004_alter_maintenance_maintenance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='type',
            field=models.CharField(choices=[('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], db_column='type', db_index=True, default='MENSAL', max_length=20),
        ),
    ]
