# Generated by Django 4.2.16 on 2026-03-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='profissao',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Profissão'),
        ),
    ]
