# Generated by Django 5.1 on 2026-03-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recursos_humanos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtitle",
            name="description",
            field=models.TextField(
                blank=True,
                db_column="description",
                default="",
                verbose_name="Descrição",
            ),
        ),
        migrations.AlterField(
            model_name="jobtitle",
            name="is_doctor",
            field=models.BooleanField(
                db_column="is_doctor",
                db_index=True,
                default=False,
                verbose_name="É médico",
            ),
        ),
    ]
