# Generated by Django 4.2.29 on 2026-04-29 19:33

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import infrastructure.orm.fields.money_field


def migrate_employee_profession_to_reference(apps, schema_editor):
    Employee = apps.get_model('recursos_humanos', 'Employee')
    Profession = apps.get_model('recursos_humanos', 'Profession')
    db_alias = schema_editor.connection.alias

    for employee in Employee._base_manager.using(db_alias).all():
        legacy_name = (getattr(employee, 'profession_legacy', '') or '').strip()
        if not legacy_name:
            continue

        base_salary = Decimal(getattr(employee, 'nominal_salary', Decimal('0.00')) or Decimal('0.00'))
        base_hours = int(getattr(employee, 'base_month_hours', 176) or 176)
        ordinary_hour_value = Decimal('0.0000')
        if base_hours > 0:
            ordinary_hour_value = (base_salary / Decimal(base_hours)).quantize(Decimal('0.0001'))
        extraordinary_hour_value = (ordinary_hour_value * Decimal('1.50')).quantize(Decimal('0.0001'))

        profession, _ = Profession._base_manager.using(db_alias).get_or_create(
            tenant_id=employee.tenant_id,
            name=legacy_name,
            defaults={
                'base_salary': base_salary.quantize(Decimal('0.01')),
                'ordinary_hour_value': ordinary_hour_value,
                'extraordinary_hour_value': extraordinary_hour_value,
            },
        )
        Employee._base_manager.using(db_alias).filter(pk=employee.pk).update(profession_id=profession.pk)


def reverse_employee_profession_reference(apps, schema_editor):
    Employee = apps.get_model('recursos_humanos', 'Employee')
    Profession = apps.get_model('recursos_humanos', 'Profession')
    db_alias = schema_editor.connection.alias

    profession_names = {
        row['id']: row['name']
        for row in Profession._base_manager.using(db_alias).values('id', 'name')
    }
    for employee in Employee._base_manager.using(db_alias).all():
        legacy_name = profession_names.get(getattr(employee, 'profession_id', None), '') or ''
        Employee._base_manager.using(db_alias).filter(pk=employee.pk).update(profession_legacy=legacy_name)


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos_humanos', '0002_alter_familydependent_relationship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('incident_date', models.DateField(db_column='incident_date', db_index=True, default=django.utils.timezone.now, verbose_name='Data do incidente')),
                ('incident_type', models.CharField(blank=True, db_column='incident_type', default='', max_length=120, verbose_name='Tipo de incidente')),
                ('severity', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('GRAVE', 'Grave'), ('GRAVISSIMA', 'Gravíssima')], db_column='severity', db_index=True, default='MODERADA', max_length=12, verbose_name='Gravidade')),
                ('description', models.TextField(blank=True, db_column='description', default='', help_text='Incidentes, maus comportamentos e atitudes que prejudicam a empresa ou colaboradores.', verbose_name='Descrição')),
                ('action_taken', models.TextField(blank=True, db_column='action_taken', default='', verbose_name='Ação disciplinar aplicada')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ENCERRADO', 'Encerrado')], db_column='status', db_index=True, default='ABERTO', max_length=10, verbose_name='Estado')),
                ('resolved_at', models.DateField(blank=True, db_column='resolved_at', null=True, verbose_name='Data de encerramento')),
                ('notes', models.TextField(blank=True, db_column='notes', default='', verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Processo Disciplinar',
                'verbose_name_plural': 'Processos Disciplinares',
                'db_table': 'recursos_humanos_processodisciplinar',
                'ordering': ['-incident_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('description', models.TextField(blank=True, db_column='description', default='', verbose_name='Descrição')),
                ('base_salary', infrastructure.orm.fields.money_field.MoneyField(db_column='base_salary', decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Salário Base')),
                ('ordinary_hour_value', models.DecimalField(db_column='ordinary_hour_value', decimal_places=4, default=Decimal('0.0000'), max_digits=12, verbose_name='Valor Hora Ordinária')),
                ('extraordinary_hour_value', models.DecimalField(db_column='extraordinary_hour_value', decimal_places=4, default=Decimal('0.0000'), max_digits=12, verbose_name='Valor Hora Extraordinária')),
                ('minimum_progression_months', models.PositiveSmallIntegerField(db_column='minimum_progression_months', default=12, verbose_name='Período mínimo de progressão (meses)')),
                ('minimum_career_change_months', models.PositiveSmallIntegerField(db_column='minimum_career_change_months', default=24, verbose_name='Período mínimo de mudança de carreira (meses)')),
                ('family_allowance_per_dependent', infrastructure.orm.fields.money_field.MoneyField(db_column='family_allowance_per_dependent', decimal_places=2, default=Decimal('0.00'), help_text='Valor adicional por cada agregado familiar ativo do funcionário.', max_digits=12, verbose_name='Aumento por agregado familiar')),
                ('active', models.BooleanField(db_column='active', db_index=True, default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Profissão',
                'verbose_name_plural': 'Profissões',
                'db_table': 'recursos_humanos_profissao',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='extraordinary_hour_value',
            field=models.DecimalField(db_column='extraordinary_hour_value', decimal_places=4, default=Decimal('0.0000'), max_digits=12, verbose_name='Valor da Hora Extraordinária'),
        ),
        migrations.AddField(
            model_name='employee',
            name='family_allowance_per_dependent',
            field=infrastructure.orm.fields.money_field.MoneyField(db_column='family_allowance_per_dependent', decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Aumento por agregado familiar'),
        ),
        migrations.AddField(
            model_name='employee',
            name='minimum_career_change_months',
            field=models.PositiveSmallIntegerField(db_column='minimum_career_change_months', default=24, verbose_name='Período mínimo de mudança de carreira (meses)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='minimum_progression_months',
            field=models.PositiveSmallIntegerField(db_column='minimum_progression_months', default=12, verbose_name='Período mínimo de progressão (meses)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ordinary_hour_value',
            field=models.DecimalField(db_column='ordinary_hour_value', decimal_places=4, default=Decimal('0.0000'), max_digits=12, verbose_name='Valor da Hora Ordinária'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='kind',
            field=models.CharField(choices=[('ORDINARIA', 'Ordinária'), ('EXTRAORDINARIA', 'Extraordinária')], db_column='kind', db_index=True, default='EXTRAORDINARIA', max_length=20, verbose_name='Tipo de Hora'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='absence_days',
            field=models.PositiveSmallIntegerField(db_column='absence_days', default=0, verbose_name='Faltas no mês'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='absence_discount_value',
            field=infrastructure.orm.fields.money_field.MoneyField(db_column='absence_discount_value', decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Desconto por faltas'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='daily_salary_value',
            field=models.DecimalField(db_column='daily_salary_value', decimal_places=4, default=Decimal('0.0000'), max_digits=12, verbose_name='Valor diário do salário'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='disciplinary_discount_value',
            field=infrastructure.orm.fields.money_field.MoneyField(db_column='disciplinary_discount_value', decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Desconto disciplinar'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='discounted_absence_days',
            field=models.PositiveSmallIntegerField(db_column='discounted_absence_days', default=0, verbose_name='Faltas com desconto'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='extraordinary_hour_value',
            field=models.DecimalField(db_column='extraordinary_hour_value', decimal_places=4, default=Decimal('0.0000'), max_digits=12, verbose_name='Valor hora extraordinária'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='extraordinary_hours',
            field=models.DecimalField(db_column='extraordinary_hours', decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Horas extraordinárias'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='extraordinary_hours_value',
            field=infrastructure.orm.fields.money_field.MoneyField(db_column='extraordinary_hours_value', decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total horas extraordinárias'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='family_allowance_value',
            field=infrastructure.orm.fields.money_field.MoneyField(db_column='family_allowance_value', decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Aumento por agregados familiares'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='family_dependents_count',
            field=models.PositiveSmallIntegerField(db_column='family_dependents_count', default=0, verbose_name='Quantidade de agregados familiares'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='gross_salary',
            field=infrastructure.orm.fields.money_field.MoneyField(db_column='gross_salary', decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Salário bruto'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='ordinary_hour_value',
            field=models.DecimalField(db_column='ordinary_hour_value', decimal_places=4, default=Decimal('0.0000'), max_digits=12, verbose_name='Valor hora ordinária'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='ordinary_hours',
            field=models.DecimalField(db_column='ordinary_hours', decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Horas ordinárias'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='ordinary_hours_value',
            field=infrastructure.orm.fields.money_field.MoneyField(db_column='ordinary_hours_value', decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total horas ordinárias'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='other_discounts_value',
            field=infrastructure.orm.fields.money_field.MoneyField(db_column='other_discounts_value', decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Outros descontos'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='salary_increase_value',
            field=infrastructure.orm.fields.money_field.MoneyField(db_column='salary_increase_value', decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Aumento Salarial no Mês'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='overtime_hour_multiplier',
            field=models.DecimalField(db_column='overtime_hour_multiplier', decimal_places=2, default=Decimal('1.50'), help_text='Usado como fallback quando o valor extraordinário não estiver definido no funcionário.', max_digits=4, verbose_name='Multiplicador da Hora Extra'),
        ),
        migrations.AddIndex(
            model_name='overtime',
            index=models.Index(fields=['tenant', 'kind', 'date'], name='recursos_hu_tenant__b70b21_idx'),
        ),
        migrations.AddField(
            model_name='profession',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profession',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profession',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='profession',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinaryprocess',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinaryprocess',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinaryprocess',
            name='employee',
            field=models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='processos_disciplinares', to='recursos_humanos.employee', verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='disciplinaryprocess',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='disciplinaryprocess',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='profession',
            new_name='profession_legacy',
        ),
        migrations.AddField(
            model_name='employee',
            name='profession',
            field=models.ForeignKey(blank=True, db_column='profession_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='recursos_humanos.profession', verbose_name='Profissão'),
        ),
        migrations.RunPython(migrate_employee_profession_to_reference, reverse_employee_profession_reference),
        migrations.RemoveField(
            model_name='employee',
            name='profession_legacy',
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'profession'], name='recursos_hu_tenant__b7efaf_idx'),
        ),
        migrations.AddIndex(
            model_name='profession',
            index=models.Index(fields=['tenant', 'active'], name='recursos_hu_tenant__1246be_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinaryprocess',
            index=models.Index(fields=['tenant', 'employee', 'incident_date'], name='recursos_hu_tenant__84726d_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinaryprocess',
            index=models.Index(fields=['tenant', 'status', 'incident_date'], name='recursos_hu_tenant__2c774f_idx'),
        ),
    ]
