# Generated by Django 4.2.29 on 2026-07-18 10:56

from django.db import migrations


def hydrate_surgeons_from_surgeries(apps, schema_editor):
    Employee = apps.get_model("recursos_humanos", "Employee")
    Surgery = apps.get_model("cirurgia", "Surgery")

    updates_by_employee: dict[int, dict[str, object]] = {}
    for surgery in Surgery.objects.filter(surgeons__isnull=False).prefetch_related("surgeons").iterator():
        for surgeon in surgery.surgeons.all():
            data = updates_by_employee.setdefault(
                surgeon.id,
                {"is_medical_doctor": True, "is_surgeon": True},
            )
            if surgery.specialty_id and not data.get("medical_specialty_id"):
                data["medical_specialty_id"] = surgery.specialty_id

    for employee_id, updates in updates_by_employee.items():
        Employee.objects.filter(pk=employee_id).update(**updates)


def reverse_hydrate_surgeons_from_surgeries(apps, schema_editor):
    Employee = apps.get_model("recursos_humanos", "Employee")
    Surgery = apps.get_model("cirurgia", "Surgery")
    surgeon_ids = set(
        Surgery.objects.filter(surgeons__isnull=False)
        .values_list("surgeons__id", flat=True)
        .distinct()
    )
    if surgeon_ids:
        Employee.objects.filter(pk__in=surgeon_ids).update(is_surgeon=False)


class Migration(migrations.Migration):

    dependencies = [
        ('cirurgia', '0016_default_vat_5_percent'),
        ('recursos_humanos', '0003_employee_is_medical_doctor_employee_is_surgeon_and_more'),
    ]

    operations = [
        migrations.RunPython(hydrate_surgeons_from_surgeries, reverse_hydrate_surgeons_from_surgeries),
    ]
