# Generated by Django 4.2.29 on 2026-04-30 18:22

from decimal import Decimal

from django.db import migrations

import infrastructure.orm.fields.money_field


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0003_disciplinaryprocess_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='tenure_increase_value',
            field=infrastructure.orm.fields.money_field.MoneyField(db_column='tenure_increase_value', decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Aumento por tempo de serviço'),
        ),
    ]
