# Generated by Django 6.0.1 on 2026-03-05 00:13

import django.core.validators
import infrastrutura.orm.fields.dinheiro_field
import infrastrutura.orm.fields.email_field
import infrastrutura.orm.fields.metodo_field
import infrastrutura.orm.fields.setor_field
import infrastrutura.orm.fields.telefone_field
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="ordem",
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                (
                    "trl_horas",
                    models.PositiveIntegerField(
                        default=24, help_text="Tempo de resposta em horas."
                    ),
                ),
                (
                    "preco",
                    infrastrutura.orm.fields.dinheiro_field.DinheiroField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Preço do exame.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "metodo",
                    infrastrutura.orm.fields.metodo_field.MetodoField(
                        choices=[
                            ("Enzimatico", "Enzimático"),
                            ("Colorimetrico", "Colorimétrico"),
                            ("Espectrofotometrico", "Espectrofotométrico"),
                            ("Turbidimetrico", "Turbidimétrico"),
                            ("Nefelometrico", "Nefelométrico"),
                            ("Potenciometrico", "Potenciométrico"),
                            ("Eletroquimico", "Eletroquímico"),
                            ("ELISA", "ELISA"),
                            ("Quimioluminescencia", "Quimioluminescência"),
                            ("Eletroquimioluminescencia", "Eletroquimioluminescência"),
                            ("Imunofluorescencia", "Imunofluorescência"),
                            ("Imunoturbidimetria", "Imunoturbidimetria"),
                            ("Aglutinacao", "Aglutinação"),
                            ("Cultura", "Cultura"),
                            ("Antibiograma", "Antibiograma"),
                            ("Microscopico", "Microscópico"),
                            ("ColoracaoGram", "Coloração de Gram"),
                            ("ColoracaoZiehl", "Ziehl-Neelsen"),
                            ("IsolamentoMicrobiano", "Isolamento Microbiano"),
                            ("CitometriaFluxo", "Citometria de Fluxo"),
                            ("HematologiaAutomatizada", "Hematologia Automatizada"),
                            ("MicroscopiaOptica", "Microscopia Óptica"),
                            ("PCR", "PCR"),
                            ("RT_PCR", "RT-PCR"),
                            ("PCRTempoReal", "PCR em Tempo Real"),
                            ("Sequenciamento", "Sequenciamento Genético"),
                            ("HibridizacaoMolecular", "Hibridização Molecular"),
                            ("Genotipagem", "Genotipagem"),
                            ("Cromatografia", "Cromatografia"),
                            ("CromatografiaGasosa", "Cromatografia Gasosa"),
                            ("CromatografiaLiquida", "Cromatografia Líquida"),
                            ("HPLC", "Cromatografia Líquida de Alta Eficiência"),
                            ("Eletroforese", "Eletroforese"),
                            ("Isoeletrofoque", "Isoeletrofocalização"),
                            ("Sedimentacao", "Sedimentação"),
                            ("Flutuacao", "Flutuação"),
                            ("KatoKatz", "Kato-Katz"),
                            ("TiraReagente", "Tira Reagente"),
                            ("AnaliseMicroscopica", "Análise Microscópica"),
                            ("EspectrometriaMassa", "Espectrometria de Massa"),
                            ("MALDI_TOF", "MALDI-TOF"),
                            (
                                "RessonanciaMagneticaNuclear",
                                "Ressonância Magnética Nuclear",
                            ),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "setor",
                    infrastrutura.orm.fields.setor_field.SetorField(
                        blank=True,
                        choices=[
                            ("Hematologia", "Hematologia"),
                            ("Bioquimica", "Bioquímica"),
                            ("Microbiologia", "Microbiologia"),
                            ("Imunologia", "Imunologia"),
                            ("Serologia", "Serologia"),
                            ("Parasitologia", "Parasitologia"),
                            ("BiologiaMolecular", "Biologia Molecular"),
                            ("Toxicologia", "Toxicologia"),
                            ("Hormonios", "Hormônios e Endocrinologia"),
                            ("MarcadoresTumorais", "Marcadores Tumorais"),
                            ("Coagulacao", "Coagulação"),
                            ("Urinalise", "Urinálise"),
                            ("LiquidosCorporais", "Líquidos Corporais"),
                            ("Gasometria", "Gasometria"),
                            ("NutricaoClinica", "Nutrição Clínica"),
                            ("Micologia", "Micologia"),
                            ("Virologia", "Virologia"),
                            ("Bacteriologia", "Bacteriologia"),
                            ("BancoSangue", "Banco de Sangue"),
                            ("ImunoHematologia", "Imuno-hematologia"),
                            ("Triagem", "Triagem Laboratorial"),
                            ("RecepcaoAmostras", "Recepção de Amostras"),
                            ("ControleQualidade", "Controle de Qualidade"),
                            ("Pesquisa", "Pesquisa Laboratorial"),
                            ("Outro", "Outro"),
                        ],
                        db_index=True,
                        max_length=40,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exame",
                "verbose_name_plural": "Exames",
                "ordering": ["nome", "criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ExameCampo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="ordem",
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NUMERICO", "Numérico"),
                            ("QUALITATIVO", "Qualitativo"),
                            ("SEMIQUANTITATIVO", "Semi-quantitativo"),
                            ("TEXTO", "Texto Livre"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de resultado",
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        choices=[
                            ("g/dl", "g/dl"),
                            ("mg/dl", "mg/dl"),
                            ("mmol/l", "mmol/l"),
                            ("µmol/l", "µmol/l"),
                            ("cel/mm3", "cel/mm3"),
                            ("x10³/µl", "x10³/µl"),
                            ("×10⁶/µL", "×10⁶/µL"),
                            ("%", "%"),
                            ("u/l", "u/l"),
                            ("p/µL", "p/µL"),
                            ("ph", "ph"),
                        ],
                        default="p/µL",
                        max_length=30,
                        verbose_name="Unidade de medida",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="ordem",
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                (
                    "gestante",
                    models.BooleanField(default=False, verbose_name="Gestante"),
                ),
                (
                    "idade_gestacional_semanas",
                    models.PositiveIntegerField(
                        blank=True, help_text="Preencher apenas se gestante", null=True
                    ),
                ),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                (
                    "genero",
                    models.CharField(
                        choices=[("Masculino", "Masculino"), ("Femenino", "Femenino")],
                        db_index=True,
                        default="Femenino",
                        max_length=10,
                    ),
                ),
                (
                    "raca_origem",
                    models.CharField(
                        choices=[
                            ("Branca", "Branca"),
                            ("Negra", "Negra"),
                            ("Parda", "Parda"),
                            ("Amarela", "Amarela"),
                            ("Indígena", "Indígena"),
                            ("Outro", "Outro"),
                        ],
                        default="Negra",
                        max_length=20,
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("BI", "Bilhete de Identidade"),
                            ("PASS", "Passaporte"),
                            (
                                "DIRE",
                                "Documento de Identificação de Residente Estrangeiro",
                            ),
                            ("CC", "Carta de Condução"),
                            ("NUIT", "Número Único de Identificação Tributária"),
                            ("CE", "Cartão de Eleitor"),
                            ("CN", "Certidão de Nascimento"),
                            ("OUT", "Outro"),
                        ],
                        default="BI",
                        max_length=50,
                    ),
                ),
                (
                    "numero_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Numero do documento",
                    ),
                ),
                ("morada", models.CharField(max_length=150)),
                (
                    "contacto",
                    infrastrutura.orm.fields.telefone_field.TelefoneField(
                        blank=True, max_length=9, null=True, verbose_name="Contacto"
                    ),
                ),
                (
                    "email",
                    infrastrutura.orm.fields.email_field.NormalizedEmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "proveniencia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Ambulatório", "Ambulatório"),
                            ("Clínica Externa", "Clínica Externa"),
                            ("Medicina Ocupacional", "Medicina Ocupacional"),
                            ("Maternidade", "Maternidade"),
                            ("Ginecologia", "Ginecologia"),
                            ("Pediatria", "Pediatria"),
                            ("Banco de Socorros", "Banco de Socorros"),
                            ("Consulta Externa", "Consulta Externa"),
                            ("Urologia", "Urologia"),
                            ("Cirurgia", "Cirurgia"),
                            ("Dentária", "Dentária"),
                            ("Oftalmologia", "Oftalmologia"),
                            ("Outro", "Outro"),
                        ],
                        default="Clínica Externa",
                        max_length=50,
                        verbose_name="Proveniencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ReferenciaClinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="ordem",
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("Masculino", "Masculino"), ("Femenino", "Femenino")],
                        help_text="Se vazio, aplica-se a ambos os sexos.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "idade_minima_dias",
                    models.PositiveIntegerField(
                        blank=True, help_text="Idade mínima em dias.", null=True
                    ),
                ),
                (
                    "idade_maxima_dias",
                    models.PositiveIntegerField(
                        blank=True, help_text="Idade máxima em dias.", null=True
                    ),
                ),
                (
                    "valor_minimo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valor_maximo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "critico_baixo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "critico_alto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["exame_campo", "sexo", "idade_minima_dias"],
            },
        ),
        migrations.CreateModel(
            name="RequisicaoAnalise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="ordem",
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("criada", "Criada"),
                            ("em_processamento", "Em Processamento"),
                            ("aguardando_validacao", "Aguardando Validação"),
                            ("validada", "Validada"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="criada",
                        max_length=30,
                    ),
                ),
                (
                    "status_clinico",
                    models.CharField(
                        choices=[
                            ("N", "Normal"),
                            ("↓", "Baixo"),
                            ("↑", "Alto"),
                            ("↓↓", "Muito baixo"),
                            ("↑↑", "Muito alto"),
                            ("?", "Indeterminado"),
                        ],
                        db_index=True,
                        default="N",
                        max_length=2,
                    ),
                ),
                (
                    "possui_resultado_critico",
                    models.BooleanField(db_index=True, default=False),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="RequisicaoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="ordem",
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Resultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="ordem",
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("finalizado", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ResultadoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="ordem",
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                (
                    "resultado_valor",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("status_clinico", models.CharField(blank=True, max_length=20)),
                ("cor_laudo", models.CharField(blank=True, max_length=20)),
                ("alerta_critico", models.BooleanField(default=False)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_analise", "Em Análise"),
                            ("aguardando_validacao", "Aguardando Validação"),
                            ("validado", "Validado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        db_index=True,
                        default="pendente",
                        max_length=30,
                    ),
                ),
                ("data_validacao", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
