# Generated by Django 4.2.16 on 2026-03-15 19:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import infrastrutura.orm.fields.dinheiro_field
import infrastrutura.orm.fields.email_field
import infrastrutura.orm.fields.endereco_field
import infrastrutura.orm.fields.metodo_field
import infrastrutura.orm.fields.setor_field
import infrastrutura.orm.fields.telefone_field
import nucleo.mixins.tenant_propagation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('tipo_evento', models.CharField(choices=[('resultado_criado', 'Resultado Criado'), ('resultado_interpretado', 'Resultado Interpretado'), ('resultado_validado', 'Resultado Validado'), ('resultado_critico', 'Resultado Crítico'), ('requisicao_criada', 'Requisição Criada'), ('requisicao_processamento', 'Requisição em Processamento'), ('requisicao_validada', 'Requisição Validada'), ('requisicao_cancelada', 'Requisição Cancelada'), ('medicacao_prescrita', 'Medicação Prescrita'), ('medicacao_administrada', 'Medicação Administrada'), ('observacao_clinica', 'Observação Clínica'), ('diagnóstico', 'Diagnóstico')], db_index=True, max_length=50)),
                ('descricao', models.TextField()),
            ],
            options={
                'ordering': ['-criado_em'],
            },
            bases=(nucleo.mixins.tenant_propagation.PropagarInquilinoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('trl_horas', models.PositiveIntegerField(default=24, help_text='Tempo de resposta em horas.', verbose_name='Tempo de resposta (em horas)')),
                ('preco', infrastrutura.orm.fields.dinheiro_field.DinheiroField(decimal_places=2, default=Decimal('0.00'), help_text='Preço do exame.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço do exame')),
                ('iva_percentual', models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Taxa de IVA aplicada ao exame (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)')),
                ('metodo', infrastrutura.orm.fields.metodo_field.MetodoField(choices=[('Enzimatico', 'Enzimático'), ('Colorimetrico', 'Colorimétrico'), ('Espectrofotometrico', 'Espectrofotométrico'), ('Turbidimetrico', 'Turbidimétrico'), ('Nefelometrico', 'Nefelométrico'), ('Potenciometrico', 'Potenciométrico'), ('Eletroquimico', 'Eletroquímico'), ('ELISA', 'ELISA'), ('Quimioluminescencia', 'Quimioluminescência'), ('Eletroquimioluminescencia', 'Eletroquimioluminescência'), ('Imunofluorescencia', 'Imunofluorescência'), ('Imunoturbidimetria', 'Imunoturbidimetria'), ('Aglutinacao', 'Aglutinação'), ('Cultura', 'Cultura'), ('Antibiograma', 'Antibiograma'), ('Microscopico', 'Microscópico'), ('ColoracaoGram', 'Coloração de Gram'), ('ColoracaoZiehl', 'Ziehl-Neelsen'), ('IsolamentoMicrobiano', 'Isolamento Microbiano'), ('CitometriaFluxo', 'Citometria de Fluxo'), ('HematologiaAutomatizada', 'Hematologia Automatizada'), ('MicroscopiaOptica', 'Microscopia Óptica'), ('PCR', 'PCR'), ('RT_PCR', 'RT-PCR'), ('PCRTempoReal', 'PCR em Tempo Real'), ('Sequenciamento', 'Sequenciamento Genético'), ('HibridizacaoMolecular', 'Hibridização Molecular'), ('Genotipagem', 'Genotipagem'), ('Cromatografia', 'Cromatografia'), ('CromatografiaGasosa', 'Cromatografia Gasosa'), ('CromatografiaLiquida', 'Cromatografia Líquida'), ('HPLC', 'Cromatografia Líquida de Alta Eficiência'), ('Eletroforese', 'Eletroforese'), ('Isoeletrofoque', 'Isoeletrofocalização'), ('Sedimentacao', 'Sedimentação'), ('Flutuacao', 'Flutuação'), ('KatoKatz', 'Kato-Katz'), ('TiraReagente', 'Tira Reagente'), ('AnaliseMicroscopica', 'Análise Microscópica'), ('EspectrometriaMassa', 'Espectrometria de Massa'), ('MALDI_TOF', 'MALDI-TOF'), ('RessonanciaMagneticaNuclear', 'Ressonância Magnética Nuclear')], db_index=True, max_length=50, verbose_name='Método do exame')),
                ('setor', infrastrutura.orm.fields.setor_field.SetorField(blank=True, choices=[('Hematologia', 'Hematologia'), ('Bioquimica', 'Bioquímica'), ('Microbiologia', 'Microbiologia'), ('Imunologia', 'Imunologia'), ('Serologia', 'Serologia'), ('Parasitologia', 'Parasitologia'), ('BiologiaMolecular', 'Biologia Molecular'), ('Toxicologia', 'Toxicologia'), ('Hormonios', 'Hormônios e Endocrinologia'), ('MarcadoresTumorais', 'Marcadores Tumorais'), ('Coagulacao', 'Coagulação'), ('Urinalise', 'Urinálise'), ('LiquidosCorporais', 'Líquidos Corporais'), ('Gasometria', 'Gasometria'), ('NutricaoClinica', 'Nutrição Clínica'), ('Micologia', 'Micologia'), ('Virologia', 'Virologia'), ('Bacteriologia', 'Bacteriologia'), ('BancoSangue', 'Banco de Sangue'), ('ImunoHematologia', 'Imuno-hematologia'), ('Triagem', 'Triagem Laboratorial'), ('RecepcaoAmostras', 'Recepção de Amostras'), ('ControleQualidade', 'Controle de Qualidade'), ('Pesquisa', 'Pesquisa Laboratorial'), ('Outro', 'Outro')], db_index=True, max_length=40, null=True, verbose_name='Setor do exame')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
                'ordering': ['nome', 'criado_em'],
            },
            bases=(nucleo.mixins.tenant_propagation.PropagarInquilinoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExameCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('tipo', models.CharField(choices=[('NUMERICO', 'Numérico'), ('QUALITATIVO', 'Qualitativo'), ('SEMIQUANTITATIVO', 'Semi-quantitativo'), ('TEXTO', 'Texto Livre')], max_length=20, verbose_name='Tipo de parâmetro')),
                ('unidade', models.CharField(choices=[('g/dl', 'g/dl'), ('mg/dl', 'mg/dl'), ('mmol/l', 'mmol/l'), ('µmol/l', 'µmol/l'), ('cel/mm3', 'cel/mm3'), ('x10³/µl', 'x10³/µl'), ('×10⁶/µL', '×10⁶/µL'), ('%', '%'), ('u/l', 'u/l'), ('p/µL', 'p/µL'), ('ph', 'ph'), ('fl', 'fl')], default='p/µL', max_length=30, verbose_name='Unidade de medida')),
                ('referencia_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Referência mínima')),
                ('referencia_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Referência máxima')),
                ('critico_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor crítico mínimo')),
                ('critico_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor crítico máximo')),
                ('delta_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Delta máximo permitido')),
            ],
            options={
                'verbose_name': 'parâmetro',
                'verbose_name_plural': 'parâmetros do exame',
            },
            bases=(nucleo.mixins.tenant_propagation.PropagarInquilinoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExameMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('trl_horas', models.PositiveIntegerField(default=24, help_text='Tempo de resposta em horas.', verbose_name='Tempo de resposta (em horas)')),
                ('preco', infrastrutura.orm.fields.dinheiro_field.DinheiroField(decimal_places=2, default=Decimal('0.00'), help_text='Preço do exame médico.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço do exame médico')),
                ('iva_percentual', models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Taxa de IVA aplicada ao exame médico (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)')),
                ('metodo', infrastrutura.orm.fields.metodo_field.MetodoField(choices=[('Enzimatico', 'Enzimático'), ('Colorimetrico', 'Colorimétrico'), ('Espectrofotometrico', 'Espectrofotométrico'), ('Turbidimetrico', 'Turbidimétrico'), ('Nefelometrico', 'Nefelométrico'), ('Potenciometrico', 'Potenciométrico'), ('Eletroquimico', 'Eletroquímico'), ('ELISA', 'ELISA'), ('Quimioluminescencia', 'Quimioluminescência'), ('Eletroquimioluminescencia', 'Eletroquimioluminescência'), ('Imunofluorescencia', 'Imunofluorescência'), ('Imunoturbidimetria', 'Imunoturbidimetria'), ('Aglutinacao', 'Aglutinação'), ('Cultura', 'Cultura'), ('Antibiograma', 'Antibiograma'), ('Microscopico', 'Microscópico'), ('ColoracaoGram', 'Coloração de Gram'), ('ColoracaoZiehl', 'Ziehl-Neelsen'), ('IsolamentoMicrobiano', 'Isolamento Microbiano'), ('CitometriaFluxo', 'Citometria de Fluxo'), ('HematologiaAutomatizada', 'Hematologia Automatizada'), ('MicroscopiaOptica', 'Microscopia Óptica'), ('PCR', 'PCR'), ('RT_PCR', 'RT-PCR'), ('PCRTempoReal', 'PCR em Tempo Real'), ('Sequenciamento', 'Sequenciamento Genético'), ('HibridizacaoMolecular', 'Hibridização Molecular'), ('Genotipagem', 'Genotipagem'), ('Cromatografia', 'Cromatografia'), ('CromatografiaGasosa', 'Cromatografia Gasosa'), ('CromatografiaLiquida', 'Cromatografia Líquida'), ('HPLC', 'Cromatografia Líquida de Alta Eficiência'), ('Eletroforese', 'Eletroforese'), ('Isoeletrofoque', 'Isoeletrofocalização'), ('Sedimentacao', 'Sedimentação'), ('Flutuacao', 'Flutuação'), ('KatoKatz', 'Kato-Katz'), ('TiraReagente', 'Tira Reagente'), ('AnaliseMicroscopica', 'Análise Microscópica'), ('EspectrometriaMassa', 'Espectrometria de Massa'), ('MALDI_TOF', 'MALDI-TOF'), ('RessonanciaMagneticaNuclear', 'Ressonância Magnética Nuclear')], db_index=True, max_length=50, verbose_name='Método do exame')),
                ('setor', infrastrutura.orm.fields.setor_field.SetorField(blank=True, choices=[('Hematologia', 'Hematologia'), ('Bioquimica', 'Bioquímica'), ('Microbiologia', 'Microbiologia'), ('Imunologia', 'Imunologia'), ('Serologia', 'Serologia'), ('Parasitologia', 'Parasitologia'), ('BiologiaMolecular', 'Biologia Molecular'), ('Toxicologia', 'Toxicologia'), ('Hormonios', 'Hormônios e Endocrinologia'), ('MarcadoresTumorais', 'Marcadores Tumorais'), ('Coagulacao', 'Coagulação'), ('Urinalise', 'Urinálise'), ('LiquidosCorporais', 'Líquidos Corporais'), ('Gasometria', 'Gasometria'), ('NutricaoClinica', 'Nutrição Clínica'), ('Micologia', 'Micologia'), ('Virologia', 'Virologia'), ('Bacteriologia', 'Bacteriologia'), ('BancoSangue', 'Banco de Sangue'), ('ImunoHematologia', 'Imuno-hematologia'), ('Triagem', 'Triagem Laboratorial'), ('RecepcaoAmostras', 'Recepção de Amostras'), ('ControleQualidade', 'Controle de Qualidade'), ('Pesquisa', 'Pesquisa Laboratorial'), ('Outro', 'Outro')], db_index=True, max_length=40, null=True, verbose_name='Setor do exame')),
            ],
            options={
                'verbose_name': 'Exame médico',
                'verbose_name_plural': 'Exames médicos',
                'ordering': ['nome', 'criado_em'],
            },
            bases=(nucleo.mixins.tenant_propagation.PropagarInquilinoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExameMedicoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('tipo', models.CharField(choices=[('NUMERICO', 'Numérico'), ('QUALITATIVO', 'Qualitativo'), ('SEMIQUANTITATIVO', 'Semi-quantitativo'), ('TEXTO', 'Texto Livre')], max_length=20, verbose_name='Tipo de parâmetro')),
                ('unidade', models.CharField(choices=[('g/dl', 'g/dl'), ('mg/dl', 'mg/dl'), ('mmol/l', 'mmol/l'), ('µmol/l', 'µmol/l'), ('cel/mm3', 'cel/mm3'), ('x10³/µl', 'x10³/µl'), ('×10⁶/µL', '×10⁶/µL'), ('%', '%'), ('u/l', 'u/l'), ('p/µL', 'p/µL'), ('ph', 'ph'), ('fl', 'fl')], default='p/µL', max_length=30, verbose_name='Unidade de medida')),
                ('referencia_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Referência mínima')),
                ('referencia_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Referência máxima')),
                ('critico_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor crítico mínimo')),
                ('critico_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor crítico máximo')),
                ('delta_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Delta máximo permitido')),
            ],
            options={
                'verbose_name': 'parâmetro de exame médico',
                'verbose_name_plural': 'parâmetros de exame médico',
            },
            bases=(nucleo.mixins.tenant_propagation.PropagarInquilinoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('gestante', models.BooleanField(default=False, verbose_name='Gestante')),
                ('idade_gestacional_semanas', models.PositiveIntegerField(blank=True, help_text='Preencher apenas se a paciente estiver gestante.', null=True, verbose_name='Idade gestacional (semanas)')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], db_index=True, default='Femenino', max_length=10, verbose_name='Gênero')),
                ('raca_origem', models.CharField(choices=[('Branca', 'Branca'), ('Negra', 'Negra'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Indígena', 'Indígena'), ('Outro', 'Outro')], default='Negra', max_length=20, verbose_name='Raça / Origem')),
                ('tipo_documento', models.CharField(choices=[('BI', 'Bilhete de Identidade'), ('PASS', 'Passaporte'), ('DIRE', 'Documento de Identificação de Residente Estrangeiro'), ('CC', 'Carta de Condução'), ('NUIT', 'Número Único de Identificação Tributária'), ('CE', 'Cartão de Eleitor'), ('CN', 'Certidão de Nascimento'), ('OUT', 'Outro')], default='BI', max_length=50, verbose_name='Tipo de documento')),
                ('numero_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número do documento')),
                ('morada', infrastrutura.orm.fields.endereco_field.EnderecoField(default=infrastrutura.orm.fields.endereco_field.EnderecoField.default_endereco, help_text='Endereço estruturado do paciente', verbose_name='Morada')),
                ('contacto', infrastrutura.orm.fields.telefone_field.TelefoneField(blank=True, max_length=9, null=True, verbose_name='Contacto')),
                ('email', infrastrutura.orm.fields.email_field.NormalizedEmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('proveniencia', models.CharField(blank=True, choices=[('Ambulatório', 'Ambulatório'), ('Clínica Externa', 'Clínica Externa'), ('Medicina Ocupacional', 'Medicina Ocupacional'), ('Maternidade', 'Maternidade'), ('Ginecologia', 'Ginecologia'), ('Pediatria', 'Pediatria'), ('Banco de Socorros', 'Banco de Socorros'), ('Consulta Externa', 'Consulta Externa'), ('Urologia', 'Urologia'), ('Cirurgia', 'Cirurgia'), ('Dentária', 'Dentária'), ('Oftalmologia', 'Oftalmologia'), ('Outro', 'Outro')], default='Clínica Externa', max_length=50, verbose_name='Proveniência')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ReferenciaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('sexo', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], help_text='Se vazio, aplica-se a ambos os sexos.', max_length=10, null=True)),
                ('idade_minima_dias', models.PositiveIntegerField(blank=True, help_text='Idade mínima em dias.', null=True)),
                ('idade_maxima_dias', models.PositiveIntegerField(blank=True, help_text='Idade máxima em dias.', null=True)),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('critico_baixo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('critico_alto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['exame_campo', 'sexo', 'idade_minima_dias'],
            },
        ),
        migrations.CreateModel(
            name='RequisicaoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('tipo', models.CharField(choices=[('LAB', 'Laboratório'), ('MED', 'Exame médico')], db_index=True, default='LAB', max_length=3)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aguardando_validacao', 'Aguardando Validação'), ('validado', 'Validado'), ('rejeitado', 'Rejeitado')], db_index=True, default='pendente', max_length=30)),
                ('status_clinico', models.CharField(choices=[('NAO_URGENTE', 'Não urgente'), ('NORMAL', 'Normal'), ('ROTINA', 'Rotina'), ('POUCO_URGENTE', 'Pouco urgente'), ('PRIORITARIO', 'Prioritário'), ('URGENTE', 'Urgente'), ('MUITO_URGENTE', 'Muito urgente'), ('URGENTISSIMO', 'Urgentíssimo'), ('EMERGENCIA', 'Emergência')], db_index=True, default='NAO_URGENTE', max_length=50)),
                ('possui_resultado_critico', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Requisição de exame',
                'verbose_name_plural': 'Requisições de exames',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RequisicaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
            ],
            bases=(nucleo.mixins.tenant_propagation.PropagarInquilinoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('finalizado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('resultado_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status_clinico', models.CharField(blank=True, max_length=20)),
                ('cor_laudo', models.CharField(blank=True, max_length=20, null=True)),
                ('alerta_critico', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aguardando_validacao', 'Aguardando Validação'), ('validado', 'Validado'), ('rejeitado', 'Rejeitado')], db_index=True, default='pendente', max_length=30)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
            ],
            bases=(nucleo.mixins.tenant_propagation.PropagarInquilinoMixin, models.Model),
        ),
    ]
