# Generated by Django 4.2.13 on 2026-03-12 11:05

from django.db import migrations
import infrastrutura.orm.fields.endereco_field


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='morada',
            field=infrastrutura.orm.fields.endereco_field.EnderecoField(default=infrastrutura.orm.fields.endereco_field.EnderecoField.default_endereco, help_text='Endereço estruturado do paciente', verbose_name='Morada'),
        ),
    ]
