# Generated by Django 6.0.1 on 2026-03-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requisicaoanalise",
            name="nome",
        ),
    ]
