# Generated by Django 4.2.16 on 2026-03-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examecampo',
            name='unidade',
            field=models.CharField(choices=[('g/dl', 'g/dl'), ('mg/dl', 'mg/dl'), ('mmol/l', 'mmol/l'), ('µmol/l', 'µmol/l'), ('cel/mm3', 'cel/mm3'), ('x10³/µl', 'x10³/µl'), ('x10⁶/µL', 'x10⁶/µL'), ('%', '%'), ('u/l', 'u/l'), ('p/µL', 'p/µL'), ('ph', 'ph'), ('fl', 'fl')], default='p/µL', max_length=30, verbose_name='Unidade de medida'),
        ),
        migrations.AlterField(
            model_name='examemedicocampo',
            name='unidade',
            field=models.CharField(choices=[('g/dl', 'g/dl'), ('mg/dl', 'mg/dl'), ('mmol/l', 'mmol/l'), ('µmol/l', 'µmol/l'), ('cel/mm3', 'cel/mm3'), ('x10³/µl', 'x10³/µl'), ('x10⁶/µL', 'x10⁶/µL'), ('%', '%'), ('u/l', 'u/l'), ('p/µL', 'p/µL'), ('ph', 'ph'), ('fl', 'fl')], default='p/µL', max_length=30, verbose_name='Unidade de medida'),
        ),
    ]
