# Generated by Django 6.0.1 on 2026-03-05 19:10

import django.core.validators
import django.utils.timezone
import infrastrutura.orm.fields.dinheiro_field
import infrastrutura.orm.fields.metodo_field
import infrastrutura.orm.fields.setor_field
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exame",
            options={
                "ordering": ["nome", "criado_em"],
                "verbose_name": "Exame disponível no sistema",
                "verbose_name_plural": "Exames disponíveis no sistema",
            },
        ),
        migrations.AlterModelOptions(
            name="examecampo",
            options={
                "verbose_name": "parâmetro de cada exame",
                "verbose_name_plural": "parâmetros de cada exame",
            },
        ),
        migrations.RemoveIndex(
            model_name="examecampo",
            name="clinico_exa_deletad_1039a6_idx",
        ),
        migrations.RemoveIndex(
            model_name="examecampo",
            name="clinico_exa_versao_bb3a78_idx",
        ),
        migrations.AddField(
            model_name="examecampo",
            name="referencia",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=50,
                verbose_name="Valor de Referência",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exame",
            name="metodo",
            field=infrastrutura.orm.fields.metodo_field.MetodoField(
                choices=[
                    ("Enzimatico", "Enzimático"),
                    ("Colorimetrico", "Colorimétrico"),
                    ("Espectrofotometrico", "Espectrofotométrico"),
                    ("Turbidimetrico", "Turbidimétrico"),
                    ("Nefelometrico", "Nefelométrico"),
                    ("Potenciometrico", "Potenciométrico"),
                    ("Eletroquimico", "Eletroquímico"),
                    ("ELISA", "ELISA"),
                    ("Quimioluminescencia", "Quimioluminescência"),
                    ("Eletroquimioluminescencia", "Eletroquimioluminescência"),
                    ("Imunofluorescencia", "Imunofluorescência"),
                    ("Imunoturbidimetria", "Imunoturbidimetria"),
                    ("Aglutinacao", "Aglutinação"),
                    ("Cultura", "Cultura"),
                    ("Antibiograma", "Antibiograma"),
                    ("Microscopico", "Microscópico"),
                    ("ColoracaoGram", "Coloração de Gram"),
                    ("ColoracaoZiehl", "Ziehl-Neelsen"),
                    ("IsolamentoMicrobiano", "Isolamento Microbiano"),
                    ("CitometriaFluxo", "Citometria de Fluxo"),
                    ("HematologiaAutomatizada", "Hematologia Automatizada"),
                    ("MicroscopiaOptica", "Microscopia Óptica"),
                    ("PCR", "PCR"),
                    ("RT_PCR", "RT-PCR"),
                    ("PCRTempoReal", "PCR em Tempo Real"),
                    ("Sequenciamento", "Sequenciamento Genético"),
                    ("HibridizacaoMolecular", "Hibridização Molecular"),
                    ("Genotipagem", "Genotipagem"),
                    ("Cromatografia", "Cromatografia"),
                    ("CromatografiaGasosa", "Cromatografia Gasosa"),
                    ("CromatografiaLiquida", "Cromatografia Líquida"),
                    ("HPLC", "Cromatografia Líquida de Alta Eficiência"),
                    ("Eletroforese", "Eletroforese"),
                    ("Isoeletrofoque", "Isoeletrofocalização"),
                    ("Sedimentacao", "Sedimentação"),
                    ("Flutuacao", "Flutuação"),
                    ("KatoKatz", "Kato-Katz"),
                    ("TiraReagente", "Tira Reagente"),
                    ("AnaliseMicroscopica", "Análise Microscópica"),
                    ("EspectrometriaMassa", "Espectrometria de Massa"),
                    ("MALDI_TOF", "MALDI-TOF"),
                    ("RessonanciaMagneticaNuclear", "Ressonância Magnética Nuclear"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="método do exame",
            ),
        ),
        migrations.AlterField(
            model_name="exame",
            name="preco",
            field=infrastrutura.orm.fields.dinheiro_field.DinheiroField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="preço do exame.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="preço do exame",
            ),
        ),
        migrations.AlterField(
            model_name="exame",
            name="setor",
            field=infrastrutura.orm.fields.setor_field.SetorField(
                blank=True,
                choices=[
                    ("Hematologia", "Hematologia"),
                    ("Bioquimica", "Bioquímica"),
                    ("Microbiologia", "Microbiologia"),
                    ("Imunologia", "Imunologia"),
                    ("Serologia", "Serologia"),
                    ("Parasitologia", "Parasitologia"),
                    ("BiologiaMolecular", "Biologia Molecular"),
                    ("Toxicologia", "Toxicologia"),
                    ("Hormonios", "Hormônios e Endocrinologia"),
                    ("MarcadoresTumorais", "Marcadores Tumorais"),
                    ("Coagulacao", "Coagulação"),
                    ("Urinalise", "Urinálise"),
                    ("LiquidosCorporais", "Líquidos Corporais"),
                    ("Gasometria", "Gasometria"),
                    ("NutricaoClinica", "Nutrição Clínica"),
                    ("Micologia", "Micologia"),
                    ("Virologia", "Virologia"),
                    ("Bacteriologia", "Bacteriologia"),
                    ("BancoSangue", "Banco de Sangue"),
                    ("ImunoHematologia", "Imuno-hematologia"),
                    ("Triagem", "Triagem Laboratorial"),
                    ("RecepcaoAmostras", "Recepção de Amostras"),
                    ("ControleQualidade", "Controle de Qualidade"),
                    ("Pesquisa", "Pesquisa Laboratorial"),
                    ("Outro", "Outro"),
                ],
                db_index=True,
                max_length=40,
                null=True,
                verbose_name="sector do exame",
            ),
        ),
        migrations.AlterField(
            model_name="exame",
            name="trl_horas",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Tempo de resposta em horas.",
                verbose_name="Tempo de resposta (em horas)",
            ),
        ),
        migrations.AlterField(
            model_name="examecampo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("NUMERICO", "Numérico"),
                    ("QUALITATIVO", "Qualitativo"),
                    ("SEMIQUANTITATIVO", "Semi-quantitativo"),
                    ("TEXTO", "Texto Livre"),
                ],
                max_length=20,
                verbose_name="Tipo de parâmetro",
            ),
        ),
    ]
