# Generated by Django 4.2.13 on 2026-03-12 19:19

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import infrastrutura.orm.fields.dinheiro_field
import infrastrutura.orm.fields.metodo_field
import infrastrutura.orm.fields.setor_field
import nucleo.mixins.tenant_propagation


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0001_initial'),
        ('clinico', '0002_alter_paciente_morada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('trl_horas', models.PositiveIntegerField(default=24, help_text='Tempo de resposta em horas.', verbose_name='Tempo de resposta (em horas)')),
                ('preco', infrastrutura.orm.fields.dinheiro_field.DinheiroField(decimal_places=2, default=Decimal('0.00'), help_text='preço do exame médico.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='preço do exame médico')),
                ('metodo', infrastrutura.orm.fields.metodo_field.MetodoField(choices=[('Enzimatico', 'Enzimático'), ('Colorimetrico', 'Colorimétrico'), ('Espectrofotometrico', 'Espectrofotométrico'), ('Turbidimetrico', 'Turbidimétrico'), ('Nefelometrico', 'Nefelométrico'), ('Potenciometrico', 'Potenciométrico'), ('Eletroquimico', 'Eletroquímico'), ('ELISA', 'ELISA'), ('Quimioluminescencia', 'Quimioluminescência'), ('Eletroquimioluminescencia', 'Eletroquimioluminescência'), ('Imunofluorescencia', 'Imunofluorescência'), ('Imunoturbidimetria', 'Imunoturbidimetria'), ('Aglutinacao', 'Aglutinação'), ('Cultura', 'Cultura'), ('Antibiograma', 'Antibiograma'), ('Microscopico', 'Microscópico'), ('ColoracaoGram', 'Coloração de Gram'), ('ColoracaoZiehl', 'Ziehl-Neelsen'), ('IsolamentoMicrobiano', 'Isolamento Microbiano'), ('CitometriaFluxo', 'Citometria de Fluxo'), ('HematologiaAutomatizada', 'Hematologia Automatizada'), ('MicroscopiaOptica', 'Microscopia Óptica'), ('PCR', 'PCR'), ('RT_PCR', 'RT-PCR'), ('PCRTempoReal', 'PCR em Tempo Real'), ('Sequenciamento', 'Sequenciamento Genético'), ('HibridizacaoMolecular', 'Hibridização Molecular'), ('Genotipagem', 'Genotipagem'), ('Cromatografia', 'Cromatografia'), ('CromatografiaGasosa', 'Cromatografia Gasosa'), ('CromatografiaLiquida', 'Cromatografia Líquida'), ('HPLC', 'Cromatografia Líquida de Alta Eficiência'), ('Eletroforese', 'Eletroforese'), ('Isoeletrofoque', 'Isoeletrofocalização'), ('Sedimentacao', 'Sedimentação'), ('Flutuacao', 'Flutuação'), ('KatoKatz', 'Kato-Katz'), ('TiraReagente', 'Tira Reagente'), ('AnaliseMicroscopica', 'Análise Microscópica'), ('EspectrometriaMassa', 'Espectrometria de Massa'), ('MALDI_TOF', 'MALDI-TOF'), ('RessonanciaMagneticaNuclear', 'Ressonância Magnética Nuclear')], db_index=True, max_length=50, verbose_name='método do exame')),
                ('setor', infrastrutura.orm.fields.setor_field.SetorField(blank=True, choices=[('Hematologia', 'Hematologia'), ('Bioquimica', 'Bioquímica'), ('Microbiologia', 'Microbiologia'), ('Imunologia', 'Imunologia'), ('Serologia', 'Serologia'), ('Parasitologia', 'Parasitologia'), ('BiologiaMolecular', 'Biologia Molecular'), ('Toxicologia', 'Toxicologia'), ('Hormonios', 'Hormônios e Endocrinologia'), ('MarcadoresTumorais', 'Marcadores Tumorais'), ('Coagulacao', 'Coagulação'), ('Urinalise', 'Urinálise'), ('LiquidosCorporais', 'Líquidos Corporais'), ('Gasometria', 'Gasometria'), ('NutricaoClinica', 'Nutrição Clínica'), ('Micologia', 'Micologia'), ('Virologia', 'Virologia'), ('Bacteriologia', 'Bacteriologia'), ('BancoSangue', 'Banco de Sangue'), ('ImunoHematologia', 'Imuno-hematologia'), ('Triagem', 'Triagem Laboratorial'), ('RecepcaoAmostras', 'Recepção de Amostras'), ('ControleQualidade', 'Controle de Qualidade'), ('Pesquisa', 'Pesquisa Laboratorial'), ('Outro', 'Outro')], db_index=True, max_length=40, null=True, verbose_name='sector do exame')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
            ],
            options={
                'verbose_name': 'Exame médico',
                'verbose_name_plural': 'Exames médicos',
                'ordering': ['nome', 'criado_em'],
            },
            bases=(nucleo.mixins.tenant_propagation.PropagarInquilinoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExameMedicoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('tipo', models.CharField(choices=[('NUMERICO', 'Numérico'), ('QUALITATIVO', 'Qualitativo'), ('SEMIQUANTITATIVO', 'Semi-quantitativo'), ('TEXTO', 'Texto Livre')], max_length=20, verbose_name='Tipo de parâmetro')),
                ('unidade', models.CharField(choices=[('g/dl', 'g/dl'), ('mg/dl', 'mg/dl'), ('mmol/l', 'mmol/l'), ('µmol/l', 'µmol/l'), ('cel/mm3', 'cel/mm3'), ('x10³/µl', 'x10³/µl'), ('×10⁶/µL', '×10⁶/µL'), ('%', '%'), ('u/l', 'u/l'), ('p/µL', 'p/µL'), ('ph', 'ph'), ('fl', 'fl')], default='p/µL', max_length=30, verbose_name='Unidade de medida')),
                ('referencia_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Referência mínima')),
                ('referencia_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Referência máxima')),
                ('critico_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor crítico mínimo')),
                ('critico_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor crítico máximo')),
                ('delta_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Delta máximo permitido')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='clinico.examemedico', verbose_name='Exame médico')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
            ],
            options={
                'verbose_name': 'parâmetro de exame médico',
                'verbose_name_plural': 'parâmetros de exame médico',
            },
            bases=(nucleo.mixins.tenant_propagation.PropagarInquilinoMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='examemedico',
            index=models.Index(fields=['setor', 'deletado'], name='clinico_exa_setor_b6fcd0_idx'),
        ),
        migrations.AddIndex(
            model_name='examemedico',
            index=models.Index(fields=['metodo'], name='clinico_exa_metodo_726154_idx'),
        ),
        migrations.AddConstraint(
            model_name='examemedico',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False)), fields=('setor', 'nome'), name='unique_nome_exame_medico_por_setor_nao_deletado'),
        ),
        migrations.AddConstraint(
            model_name='examemedico',
            constraint=models.CheckConstraint(check=models.Q(('trl_horas__gt', 0)), name='exm_trl_horas_positivo'),
        ),
        migrations.AddConstraint(
            model_name='examemedico',
            constraint=models.CheckConstraint(check=models.Q(('preco__gte', 0)), name='exm_preco_nao_negativo'),
        ),
    ]
