# Generated by Django 6.0.1 on 2026-03-07 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0002_initial"),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenciaClinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("Masculino", "Masculino"), ("Femenino", "Femenino")],
                        help_text="Se vazio, aplica-se a ambos os sexos.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "idade_minima_dias",
                    models.PositiveIntegerField(
                        blank=True, help_text="Idade mínima em dias.", null=True
                    ),
                ),
                (
                    "idade_maxima_dias",
                    models.PositiveIntegerField(
                        blank=True, help_text="Idade máxima em dias.", null=True
                    ),
                ),
                (
                    "valor_minimo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valor_maximo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "critico_baixo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "critico_alto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deletado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exame_campo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referencias",
                        to="clinico.examecampo",
                    ),
                ),
                (
                    "inquilino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.inquilino",
                    ),
                ),
            ],
            options={
                "ordering": ["exame_campo", "sexo", "idade_minima_dias"],
                "indexes": [
                    models.Index(
                        fields=["exame_campo"], name="clinico_ref_exame_c_4f26c7_idx"
                    ),
                    models.Index(fields=["sexo"], name="clinico_ref_sexo_5e6d41_idx"),
                    models.Index(
                        fields=["idade_minima_dias", "idade_maxima_dias"],
                        name="clinico_ref_idade_m_b6ce91_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("idade_maxima_dias__gte", models.F("idade_minima_dias")),
                            ("idade_minima_dias__isnull", True),
                            ("idade_maxima_dias__isnull", True),
                            _connector="OR",
                        ),
                        name="ref_idade_intervalo_valido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valor_maximo__gte", models.F("valor_minimo")),
                            ("valor_minimo__isnull", True),
                            ("valor_maximo__isnull", True),
                            _connector="OR",
                        ),
                        name="ref_valor_intervalo_valido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("critico_alto__gte", models.F("critico_baixo")),
                            ("critico_baixo__isnull", True),
                            ("critico_alto__isnull", True),
                            _connector="OR",
                        ),
                        name="ref_critico_intervalo_valido",
                    ),
                ],
            },
        ),
    ]
