# Generated by Django 6.0.1 on 2026-03-09 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exame",
            options={
                "ordering": ["nome", "criado_em"],
                "verbose_name": "Exame",
                "verbose_name_plural": "Exames",
            },
        ),
        migrations.AlterModelOptions(
            name="examecampo",
            options={
                "verbose_name": "parâmetro",
                "verbose_name_plural": "parâmetros do exame",
            },
        ),
        migrations.AlterModelOptions(
            name="requisicaoanalise",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Requisição de exame",
                "verbose_name_plural": "Requisições de exames",
            },
        ),
    ]
