# Generated by Django 6.0.1 on 2026-03-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0003_referenciaclinica"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultadoitem",
            name="cor_laudo",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
