# Generated by Django 6.0.1 on 2026-03-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0003_alter_exame_options_alter_examecampo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="data_nascimento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de nascimento"
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="genero",
            field=models.CharField(
                choices=[("Masculino", "Masculino"), ("Femenino", "Femenino")],
                db_index=True,
                default="Femenino",
                max_length=10,
                verbose_name="Gênero",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="idade_gestacional_semanas",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Preencher apenas se a paciente estiver gestante.",
                null=True,
                verbose_name="Idade gestacional (semanas)",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="morada",
            field=models.CharField(max_length=150, verbose_name="Morada"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="numero_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Número do documento",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="proveniencia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ambulatório", "Ambulatório"),
                    ("Clínica Externa", "Clínica Externa"),
                    ("Medicina Ocupacional", "Medicina Ocupacional"),
                    ("Maternidade", "Maternidade"),
                    ("Ginecologia", "Ginecologia"),
                    ("Pediatria", "Pediatria"),
                    ("Banco de Socorros", "Banco de Socorros"),
                    ("Consulta Externa", "Consulta Externa"),
                    ("Urologia", "Urologia"),
                    ("Cirurgia", "Cirurgia"),
                    ("Dentária", "Dentária"),
                    ("Oftalmologia", "Oftalmologia"),
                    ("Outro", "Outro"),
                ],
                default="Clínica Externa",
                max_length=50,
                verbose_name="Proveniência",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="raca_origem",
            field=models.CharField(
                choices=[
                    ("Branca", "Branca"),
                    ("Negra", "Negra"),
                    ("Parda", "Parda"),
                    ("Amarela", "Amarela"),
                    ("Indígena", "Indígena"),
                    ("Outro", "Outro"),
                ],
                default="Negra",
                max_length=20,
                verbose_name="Raça / Origem",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("BI", "Bilhete de Identidade"),
                    ("PASS", "Passaporte"),
                    ("DIRE", "Documento de Identificação de Residente Estrangeiro"),
                    ("CC", "Carta de Condução"),
                    ("NUIT", "Número Único de Identificação Tributária"),
                    ("CE", "Cartão de Eleitor"),
                    ("CN", "Certidão de Nascimento"),
                    ("OUT", "Outro"),
                ],
                default="BI",
                max_length=50,
                verbose_name="Tipo de documento",
            ),
        ),
    ]
