# Generated by Django 6.0.1 on 2026-03-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0003_alter_exame_options_alter_examecampo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examecampo",
            name="referencia",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Valor de Referência"
            ),
        ),
        migrations.AlterField(
            model_name="examecampo",
            name="unidade",
            field=models.CharField(
                choices=[
                    ("g/dl", "g/dl"),
                    ("mg/dl", "mg/dl"),
                    ("mmol/l", "mmol/l"),
                    ("µmol/l", "µmol/l"),
                    ("cel/mm3", "cel/mm3"),
                    ("x10³/µl", "x10³/µl"),
                    ("×10⁶/µL", "×10⁶/µL"),
                    ("%", "%"),
                    ("u/l", "u/l"),
                    ("p/µL", "p/µL"),
                    ("ph", "ph"),
                    ("fl", "fl"),
                ],
                default="p/µL",
                max_length=30,
                verbose_name="Unidade de medida",
            ),
        ),
    ]
