# Generated by Django 6.0.1 on 2026-03-01 22:56

import infrastrutura.orm.fields.unidade_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0003_alter_examecampo_unidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examecampo",
            name="unidade",
            field=infrastrutura.orm.fields.unidade_field.UnidadeField(
                blank=True,
                choices=[
                    ("g/dl", "g/dl"),
                    ("mg/dl", "mg/dl"),
                    ("mmol/l", "mmol/l"),
                    ("µmol/l", "µmol/l"),
                    ("cel/mm3", "cel/mm3"),
                    ("x10³/µl", "x10³/µl"),
                    ("×10⁶/µL", "×10⁶/µL"),
                    ("%", "%"),
                    ("u/l", "u/l"),
                    ("p/µL", "p/µL"),
                    ("ph", "ph"),
                ],
                default="p/µL",
                max_length=20,
                null=True,
                verbose_name="Unidade",
            ),
        ),
    ]
