# Generated by Django 4.2.16 on 2026-03-16 18:00

import json

from django.db import migrations, models


def _coerce_endereco(value):
    if value is None:
        return {}
    if isinstance(value, dict):
        return value
    if isinstance(value, str):
        txt = value.strip()
        if not txt:
            return {}
        # Tentativa: pode ser JSON serializado.
        try:
            j = json.loads(txt)
            return j if isinstance(j, dict) else {"rua": txt}
        except Exception:
            return {"rua": txt}
    return {}


def forwards_endereco(apps, schema_editor):
    Paciente = apps.get_model("clinico", "Paciente")
    db_alias = schema_editor.connection.alias

    qs = Paciente.objects.using(db_alias).all()
    for p in qs.iterator():
        src = getattr(p, "morada_json", None)
        d = _coerce_endereco(src)

        def g(key: str) -> str:
            v = d.get(key)
            return (v or "").strip() if isinstance(v, str) or v is None else str(v).strip()

        updates = {}

        rua = g("rua")
        numero = g("numero")
        bairro = g("bairro")
        cidade = g("cidade")
        provincia = g("provincia")
        codigo_postal = g("codigo_postal")
        pais = g("pais")
        complemento = g("complemento")

        if rua and not (getattr(p, "endereco_rua", "") or "").strip():
            updates["endereco_rua"] = rua
        if numero and not (getattr(p, "endereco_numero", "") or "").strip():
            updates["endereco_numero"] = numero
        if bairro and not (getattr(p, "endereco_bairro", "") or "").strip():
            updates["endereco_bairro"] = bairro
        if cidade and not (getattr(p, "endereco_cidade", "") or "").strip():
            updates["endereco_cidade"] = cidade
        if provincia and not (getattr(p, "endereco_provincia", "") or "").strip():
            updates["endereco_provincia"] = provincia
        if codigo_postal and not (getattr(p, "endereco_codigo_postal", "") or "").strip():
            updates["endereco_codigo_postal"] = codigo_postal
        if pais and not (getattr(p, "endereco_pais", "") or "").strip():
            updates["endereco_pais"] = pais
        if complemento and not (getattr(p, "endereco_complemento", "") or "").strip():
            updates["endereco_complemento"] = complemento

        # Morada (texto) vira um resumo consistente a partir do endereço.
        parts = []
        for field in (
            "endereco_rua",
            "endereco_numero",
            "endereco_bairro",
            "endereco_cidade",
            "endereco_provincia",
            "endereco_codigo_postal",
            "endereco_complemento",
        ):
            v = updates.get(field, getattr(p, field, "")) or ""
            v = str(v).strip()
            if v:
                parts.append(v)

        updates["morada"] = ", ".join(parts).strip()

        if updates:
            Paciente.objects.using(db_alias).filter(pk=p.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0003_alter_examecampo_unidade_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paciente",
            old_name="morada",
            new_name="morada_json",
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_rua",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="Rua"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_numero",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="Número"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_bairro",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="Bairro"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_cidade",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="Cidade"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_provincia",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="Província"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_codigo_postal",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="Código postal"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_pais",
            field=models.CharField(blank=True, default="Moçambique", max_length=120, verbose_name="País"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_complemento",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Complemento"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="morada",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Texto livre ou resumo (auto) da morada.",
                max_length=255,
                verbose_name="Morada",
            ),
        ),
        migrations.RunPython(forwards_endereco, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="paciente",
            name="morada_json",
        ),
    ]

