# Generated by Django 6.0.1 on 2026-03-08 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0004_alter_resultadoitem_cor_laudo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultadoitem",
            name="validado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resultados_validados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Resultado",
            ),
        ),
    ]
