# Generated by Django 6.0.1 on 2026-03-09 03:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clinico",
            "0004_alter_paciente_data_nascimento_alter_paciente_genero_and_more",
        ),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="paciente",
            index=models.Index(
                fields=["inquilino"], name="clinico_pac_inquili_f10385_idx"
            ),
        ),
    ]
