# Generated by Django 4.2.16 on 2026-03-16 20:12

import re
import unicodedata

from django.db import migrations
from django.utils.translation import override
from django_countries import countries
import django_countries.fields


def _normalize(value: str) -> str:
    value = (value or "").strip().lower()
    if not value:
        return ""
    value = unicodedata.normalize("NFD", value)
    value = "".join(ch for ch in value if unicodedata.category(ch) != "Mn")
    return value


def _build_country_name_to_code() -> dict[str, str]:
    """
    Best-effort reverse lookup from country name to ISO alpha-2 code.

    We build a map for a couple of languages because legacy data may have been
    stored using a translated name (ex.: "Moçambique") instead of the ISO code.
    """
    name_to_code: dict[str, str] = {}

    for lang in ("pt-br", "pt", "en"):
        try:
            with override(lang):
                for code, name in list(countries):
                    name_to_code[_normalize(str(name))] = code
        except Exception:
            continue

    # Hard guarantees for our main default, even if translations change.
    name_to_code[_normalize("Mozambique")] = "MZ"
    name_to_code[_normalize("Moçambique")] = "MZ"

    return name_to_code


def forwards_endereco_pais_countryfield(apps, schema_editor):
    Paciente = apps.get_model("clinico", "Paciente")
    db_alias = schema_editor.connection.alias

    name_to_code = _build_country_name_to_code()

    qs = Paciente.objects.using(db_alias).all()
    for p in qs.iterator():
        raw = (getattr(p, "endereco_pais", "") or "").strip()
        if not raw:
            continue

        code = countries.alpha2(raw)
        if not code:
            code = name_to_code.get(_normalize(raw))

        if not code:
            # Handle common "CODE - Name" / "Name, ..." patterns.
            for part in [x.strip() for x in re.split(r"[-,/;|]+", raw) if x.strip()]:
                code = countries.alpha2(part) or name_to_code.get(_normalize(part))
                if code:
                    break

        if code:
            if code != raw:
                Paciente.objects.using(db_alias).filter(pk=p.pk).update(endereco_pais=code)
        else:
            # If we can't map, blank it out so the upcoming max_length=2 won't
            # truncate invalid data on strict DBs.
            Paciente.objects.using(db_alias).filter(pk=p.pk).update(endereco_pais="")


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0004_paciente_endereco_campos_reais'),
    ]

    operations = [
        migrations.RunPython(forwards_endereco_pais_countryfield, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='paciente',
            name='endereco_pais',
            field=django_countries.fields.CountryField(blank=True, default='MZ', max_length=2, verbose_name='País'),
        ),
    ]
