# Generated by Django 6.0.1 on 2026-03-01 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0004_alter_examecampo_unidade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requisicaoitem",
            name="nome",
        ),
        migrations.AlterField(
            model_name="requisicaoitem",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="requisicaoitem",
            name="atualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado_por",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="requisicaoitem",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="requisicaoitem",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado_por",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
