# Generated by Django 6.0.1 on 2026-03-05 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0004_alter_examecampo_referencia_alter_examecampo_unidade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisicaoanalise",
            name="analista",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requisicoes_processadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="O Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="requisicaoanalise",
            name="status_clinico",
            field=models.CharField(
                choices=[
                    ("NAO_URGENTE", "Não urgente"),
                    ("NORMAL", "Normal"),
                    ("ROTINA", "Rotina"),
                    ("POUCO_URGENTE", "Pouco urgente"),
                    ("PRIORITARIO", "Prioritário"),
                    ("URGENTE", "Urgente"),
                    ("MUITO_URGENTE", "Muito urgente"),
                    ("URGENTISSIMO", "Urgentíssimo"),
                    ("EMERGENCIA", "Emergência"),
                ],
                db_index=True,
                default="NAO_URGENTE",
                max_length=50,
            ),
        ),
    ]
