# Generated by Django 4.2.16 on 2026-03-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0004_alter_requisicaoitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaoanalise',
            name='tipo',
            field=models.CharField(choices=[('LAB', 'Laboratório'), ('MED', 'Exame médico')], db_index=True, default='LAB', max_length=3),
        ),
    ]
