# Generated by Django 6.0.1 on 2026-03-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0005_alter_requisicaoanalise_analista_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultadoitem",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em_analise", "Em Análise"),
                    ("aguardando_validacao", "Aguardando Validação"),
                    ("validado", "Validado"),
                    ("rejeitado", "Rejeitado"),
                ],
                db_index=True,
                default="validado",
                max_length=30,
            ),
        ),
    ]
