# Generated by Django 6.0.1 on 2026-03-01 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0005_remove_requisicaoitem_nome_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultadoitem",
            name="nome",
        ),
    ]
