# Generated by Django 4.2.16 on 2026-03-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0005_paciente_endereco_pais_countryfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='aplica_iva_por_padrao',
            field=models.BooleanField(default=True, help_text='Desmarque se este exame normalmente não deve ter IVA.', verbose_name='Aplicar IVA por padrão'),
        ),
        migrations.AddField(
            model_name='examemedico',
            name='aplica_iva_por_padrao',
            field=models.BooleanField(default=True, help_text='Desmarque se este exame normalmente não deve ter IVA.', verbose_name='Aplicar IVA por padrão'),
        ),
    ]
