# Generated by Django 4.2.16 on 2026-03-14 21:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import infrastrutura.orm.fields.dinheiro_field
import infrastrutura.orm.fields.metodo_field
import infrastrutura.orm.fields.setor_field


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0006_paciente_empresa_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='iva_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Taxa de IVA aplicada ao exame (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)'),
        ),
        migrations.AddField(
            model_name='examemedico',
            name='iva_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Taxa de IVA aplicada ao exame médico (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='metodo',
            field=infrastrutura.orm.fields.metodo_field.MetodoField(choices=[('Enzimatico', 'Enzimático'), ('Colorimetrico', 'Colorimétrico'), ('Espectrofotometrico', 'Espectrofotométrico'), ('Turbidimetrico', 'Turbidimétrico'), ('Nefelometrico', 'Nefelométrico'), ('Potenciometrico', 'Potenciométrico'), ('Eletroquimico', 'Eletroquímico'), ('ELISA', 'ELISA'), ('Quimioluminescencia', 'Quimioluminescência'), ('Eletroquimioluminescencia', 'Eletroquimioluminescência'), ('Imunofluorescencia', 'Imunofluorescência'), ('Imunoturbidimetria', 'Imunoturbidimetria'), ('Aglutinacao', 'Aglutinação'), ('Cultura', 'Cultura'), ('Antibiograma', 'Antibiograma'), ('Microscopico', 'Microscópico'), ('ColoracaoGram', 'Coloração de Gram'), ('ColoracaoZiehl', 'Ziehl-Neelsen'), ('IsolamentoMicrobiano', 'Isolamento Microbiano'), ('CitometriaFluxo', 'Citometria de Fluxo'), ('HematologiaAutomatizada', 'Hematologia Automatizada'), ('MicroscopiaOptica', 'Microscopia Óptica'), ('PCR', 'PCR'), ('RT_PCR', 'RT-PCR'), ('PCRTempoReal', 'PCR em Tempo Real'), ('Sequenciamento', 'Sequenciamento Genético'), ('HibridizacaoMolecular', 'Hibridização Molecular'), ('Genotipagem', 'Genotipagem'), ('Cromatografia', 'Cromatografia'), ('CromatografiaGasosa', 'Cromatografia Gasosa'), ('CromatografiaLiquida', 'Cromatografia Líquida'), ('HPLC', 'Cromatografia Líquida de Alta Eficiência'), ('Eletroforese', 'Eletroforese'), ('Isoeletrofoque', 'Isoeletrofocalização'), ('Sedimentacao', 'Sedimentação'), ('Flutuacao', 'Flutuação'), ('KatoKatz', 'Kato-Katz'), ('TiraReagente', 'Tira Reagente'), ('AnaliseMicroscopica', 'Análise Microscópica'), ('EspectrometriaMassa', 'Espectrometria de Massa'), ('MALDI_TOF', 'MALDI-TOF'), ('RessonanciaMagneticaNuclear', 'Ressonância Magnética Nuclear')], db_index=True, max_length=50, verbose_name='Método do exame'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='preco',
            field=infrastrutura.orm.fields.dinheiro_field.DinheiroField(decimal_places=2, default=Decimal('0.00'), help_text='Preço do exame.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço do exame'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='setor',
            field=infrastrutura.orm.fields.setor_field.SetorField(blank=True, choices=[('Hematologia', 'Hematologia'), ('Bioquimica', 'Bioquímica'), ('Microbiologia', 'Microbiologia'), ('Imunologia', 'Imunologia'), ('Serologia', 'Serologia'), ('Parasitologia', 'Parasitologia'), ('BiologiaMolecular', 'Biologia Molecular'), ('Toxicologia', 'Toxicologia'), ('Hormonios', 'Hormônios e Endocrinologia'), ('MarcadoresTumorais', 'Marcadores Tumorais'), ('Coagulacao', 'Coagulação'), ('Urinalise', 'Urinálise'), ('LiquidosCorporais', 'Líquidos Corporais'), ('Gasometria', 'Gasometria'), ('NutricaoClinica', 'Nutrição Clínica'), ('Micologia', 'Micologia'), ('Virologia', 'Virologia'), ('Bacteriologia', 'Bacteriologia'), ('BancoSangue', 'Banco de Sangue'), ('ImunoHematologia', 'Imuno-hematologia'), ('Triagem', 'Triagem Laboratorial'), ('RecepcaoAmostras', 'Recepção de Amostras'), ('ControleQualidade', 'Controle de Qualidade'), ('Pesquisa', 'Pesquisa Laboratorial'), ('Outro', 'Outro')], db_index=True, max_length=40, null=True, verbose_name='Setor do exame'),
        ),
        migrations.AlterField(
            model_name='examemedico',
            name='metodo',
            field=infrastrutura.orm.fields.metodo_field.MetodoField(choices=[('Enzimatico', 'Enzimático'), ('Colorimetrico', 'Colorimétrico'), ('Espectrofotometrico', 'Espectrofotométrico'), ('Turbidimetrico', 'Turbidimétrico'), ('Nefelometrico', 'Nefelométrico'), ('Potenciometrico', 'Potenciométrico'), ('Eletroquimico', 'Eletroquímico'), ('ELISA', 'ELISA'), ('Quimioluminescencia', 'Quimioluminescência'), ('Eletroquimioluminescencia', 'Eletroquimioluminescência'), ('Imunofluorescencia', 'Imunofluorescência'), ('Imunoturbidimetria', 'Imunoturbidimetria'), ('Aglutinacao', 'Aglutinação'), ('Cultura', 'Cultura'), ('Antibiograma', 'Antibiograma'), ('Microscopico', 'Microscópico'), ('ColoracaoGram', 'Coloração de Gram'), ('ColoracaoZiehl', 'Ziehl-Neelsen'), ('IsolamentoMicrobiano', 'Isolamento Microbiano'), ('CitometriaFluxo', 'Citometria de Fluxo'), ('HematologiaAutomatizada', 'Hematologia Automatizada'), ('MicroscopiaOptica', 'Microscopia Óptica'), ('PCR', 'PCR'), ('RT_PCR', 'RT-PCR'), ('PCRTempoReal', 'PCR em Tempo Real'), ('Sequenciamento', 'Sequenciamento Genético'), ('HibridizacaoMolecular', 'Hibridização Molecular'), ('Genotipagem', 'Genotipagem'), ('Cromatografia', 'Cromatografia'), ('CromatografiaGasosa', 'Cromatografia Gasosa'), ('CromatografiaLiquida', 'Cromatografia Líquida'), ('HPLC', 'Cromatografia Líquida de Alta Eficiência'), ('Eletroforese', 'Eletroforese'), ('Isoeletrofoque', 'Isoeletrofocalização'), ('Sedimentacao', 'Sedimentação'), ('Flutuacao', 'Flutuação'), ('KatoKatz', 'Kato-Katz'), ('TiraReagente', 'Tira Reagente'), ('AnaliseMicroscopica', 'Análise Microscópica'), ('EspectrometriaMassa', 'Espectrometria de Massa'), ('MALDI_TOF', 'MALDI-TOF'), ('RessonanciaMagneticaNuclear', 'Ressonância Magnética Nuclear')], db_index=True, max_length=50, verbose_name='Método do exame'),
        ),
        migrations.AlterField(
            model_name='examemedico',
            name='preco',
            field=infrastrutura.orm.fields.dinheiro_field.DinheiroField(decimal_places=2, default=Decimal('0.00'), help_text='Preço do exame médico.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço do exame médico'),
        ),
        migrations.AlterField(
            model_name='examemedico',
            name='setor',
            field=infrastrutura.orm.fields.setor_field.SetorField(blank=True, choices=[('Hematologia', 'Hematologia'), ('Bioquimica', 'Bioquímica'), ('Microbiologia', 'Microbiologia'), ('Imunologia', 'Imunologia'), ('Serologia', 'Serologia'), ('Parasitologia', 'Parasitologia'), ('BiologiaMolecular', 'Biologia Molecular'), ('Toxicologia', 'Toxicologia'), ('Hormonios', 'Hormônios e Endocrinologia'), ('MarcadoresTumorais', 'Marcadores Tumorais'), ('Coagulacao', 'Coagulação'), ('Urinalise', 'Urinálise'), ('LiquidosCorporais', 'Líquidos Corporais'), ('Gasometria', 'Gasometria'), ('NutricaoClinica', 'Nutrição Clínica'), ('Micologia', 'Micologia'), ('Virologia', 'Virologia'), ('Bacteriologia', 'Bacteriologia'), ('BancoSangue', 'Banco de Sangue'), ('ImunoHematologia', 'Imuno-hematologia'), ('Triagem', 'Triagem Laboratorial'), ('RecepcaoAmostras', 'Recepção de Amostras'), ('ControleQualidade', 'Controle de Qualidade'), ('Pesquisa', 'Pesquisa Laboratorial'), ('Outro', 'Outro')], db_index=True, max_length=40, null=True, verbose_name='Setor do exame'),
        ),
    ]
