# Generated by Django 6.0.1 on 2026-03-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0007_remove_requisicaoanalise_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisicaoanalise",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em_analise", "Em Análise"),
                    ("aguardando_validacao", "Aguardando Validação"),
                    ("validado", "Validado"),
                    ("rejeitado", "Rejeitado"),
                ],
                db_index=True,
                default="pendente",
                max_length=30,
            ),
        ),
    ]
