# Generated by Django 6.0.1 on 2026-03-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0008_requisicaoanalise_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requisicaoanalise",
            name="estado",
        ),
    ]
