# Generated by Django 6.0.1 on 2026-03-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0009_remove_requisicaoanalise_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisicaoanalise",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em_analise", "Em Análise"),
                    ("aguardando_validacao", "Aguardando Validação"),
                    ("validado", "Validado"),
                    ("rejeitado", "Rejeitado"),
                ],
                db_index=True,
                default="pendente",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="exame",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="examecampo",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="referenciaclinica",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="requisicaoanalise",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="requisicaoitem",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="resultado",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="resultadoitem",
            name="id_custom",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
    ]
