# Generated by Django 6.0.1 on 2026-03-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0010_requisicaoanalise_estado_alter_exame_id_custom_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="referenciaclinica",
            name="clinico_ref_exame_c_4f26c7_idx",
        ),
        migrations.RemoveIndex(
            model_name="referenciaclinica",
            name="clinico_ref_sexo_5e6d41_idx",
        ),
        migrations.RemoveIndex(
            model_name="referenciaclinica",
            name="clinico_ref_idade_m_b6ce91_idx",
        ),
        migrations.RemoveConstraint(
            model_name="referenciaclinica",
            name="ref_idade_intervalo_valido",
        ),
        migrations.RemoveConstraint(
            model_name="referenciaclinica",
            name="ref_valor_intervalo_valido",
        ),
        migrations.RemoveConstraint(
            model_name="referenciaclinica",
            name="ref_critico_intervalo_valido",
        ),
        migrations.AlterModelOptions(
            name="examecampo",
            options={
                "verbose_name": "parâmetro de exame",
                "verbose_name_plural": "parâmetros de exame",
            },
        ),
        migrations.RemoveField(
            model_name="examecampo",
            name="referencia",
        ),
        migrations.AddField(
            model_name="examecampo",
            name="critico_max",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Valor crítico máximo",
            ),
        ),
        migrations.AddField(
            model_name="examecampo",
            name="critico_min",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Valor crítico mínimo",
            ),
        ),
        migrations.AddField(
            model_name="examecampo",
            name="delta_max",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Delta máximo permitido"
            ),
        ),
        migrations.AddField(
            model_name="examecampo",
            name="referencia_max",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Referência máxima"
            ),
        ),
        migrations.AddField(
            model_name="examecampo",
            name="referencia_min",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Referência mínima"
            ),
        ),
        migrations.AlterField(
            model_name="resultadoitem",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em_analise", "Em Análise"),
                    ("aguardando_validacao", "Aguardando Validação"),
                    ("validado", "Validado"),
                    ("rejeitado", "Rejeitado"),
                ],
                db_index=True,
                default="pendente",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="ReferenciaClinica",
        ),
    ]
