# Generated by Django 6.0.1 on 2026-03-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clinico",
            "0011_remove_referenciaclinica_clinico_ref_exame_c_4f26c7_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="examecampo",
            name="critico_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Valor crítico máximo",
            ),
        ),
        migrations.AlterField(
            model_name="examecampo",
            name="critico_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Valor crítico mínimo",
            ),
        ),
        migrations.AlterField(
            model_name="examecampo",
            name="delta_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Delta máximo permitido",
            ),
        ),
        migrations.AlterField(
            model_name="examecampo",
            name="referencia_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Referência máxima",
            ),
        ),
        migrations.AlterField(
            model_name="examecampo",
            name="referencia_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Referência mínima",
            ),
        ),
        migrations.AlterField(
            model_name="resultadoitem",
            name="resultado_valor",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
    ]
