# Generated by Django 6.0.1 on 2026-03-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinico", "0012_alter_examecampo_critico_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examecampo",
            name="critico_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor crítico máximo",
            ),
        ),
        migrations.AlterField(
            model_name="examecampo",
            name="critico_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor crítico mínimo",
            ),
        ),
        migrations.AlterField(
            model_name="examecampo",
            name="delta_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Delta máximo permitido",
            ),
        ),
        migrations.AlterField(
            model_name="examecampo",
            name="referencia_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Referência máxima",
            ),
        ),
        migrations.AlterField(
            model_name="examecampo",
            name="referencia_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Referência mínima",
            ),
        ),
    ]
