# Generated by Django 4.2.16 on 2026-03-28 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enfermagem', '0001_initial'),
        ('clinical', '0002_initial'),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardbed',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wardbed',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wardbed',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='wardbed',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wardbed',
            name='ward',
            field=models.ForeignKey(db_column='ward_id', on_delete=django.db.models.deletion.PROTECT, related_name='camas', to='enfermagem.ward', verbose_name='Enfermaria'),
        ),
        migrations.AddField(
            model_name='wardadmission',
            name='bed',
            field=models.ForeignKey(db_column='bed_id', on_delete=django.db.models.deletion.PROTECT, related_name='internamentos', to='enfermagem.wardbed', verbose_name='Cama'),
        ),
        migrations.AddField(
            model_name='wardadmission',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wardadmission',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wardadmission',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, related_name='internamentos_ward', to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='wardadmission',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='wardadmission',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ward',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ward',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ward',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='ward',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedurematerialvalue',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedurematerialvalue',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedurematerialvalue',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='value', to='enfermagem.procedurematerial'),
        ),
        migrations.AddField(
            model_name='procedurematerialvalue',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='procedurematerialvalue',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedurematerial',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedurematerial',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedurematerial',
            name='inventory_movement',
            field=models.OneToOneField(blank=True, db_column='inventory_movement_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumo_procedure', to='farmacia.inventorymovement'),
        ),
        migrations.AddField(
            model_name='procedurematerial',
            name='lot',
            field=models.ForeignKey(blank=True, db_column='lot_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumos_procedure', to='farmacia.lot'),
        ),
        migrations.AddField(
            model_name='procedurematerial',
            name='procedure',
            field=models.ForeignKey(db_column='procedure_id', on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='enfermagem.procedure'),
        ),
        migrations.AddField(
            model_name='procedurematerial',
            name='procedure_item',
            field=models.ForeignKey(blank=True, db_column='procedure_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_gerados', to='enfermagem.procedureitem'),
        ),
        migrations.AddField(
            model_name='procedurematerial',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='consumos_procedure', to='farmacia.product'),
        ),
        migrations.AddField(
            model_name='procedurematerial',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='procedurematerial',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedureitemvalue',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedureitemvalue',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedureitemvalue',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='value', to='enfermagem.procedureitem'),
        ),
        migrations.AddField(
            model_name='procedureitemvalue',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='procedureitemvalue',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedureitem',
            name='catalog',
            field=models.ForeignKey(blank=True, db_column='catalog_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_lancados', to='enfermagem.procedurecatalog'),
        ),
        migrations.AddField(
            model_name='procedureitem',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedureitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedureitem',
            name='procedure',
            field=models.ForeignKey(db_column='procedure_id', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='enfermagem.procedure'),
        ),
        migrations.AddField(
            model_name='procedureitem',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='procedureitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedurecatalogmaterial',
            name='catalog',
            field=models.ForeignKey(db_column='catalog_id', on_delete=django.db.models.deletion.CASCADE, related_name='materiais_padrao', to='enfermagem.procedurecatalog'),
        ),
        migrations.AddField(
            model_name='procedurecatalogmaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedurecatalogmaterial',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedurecatalogmaterial',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='materiais_padrao_procedure', to='farmacia.product'),
        ),
        migrations.AddField(
            model_name='procedurecatalogmaterial',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='procedurecatalogmaterial',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedurecatalog',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedurecatalog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedurecatalog',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='procedurecatalog',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedure',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedure',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedure',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, related_name='procedures_enfermagem', to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='professional',
            field=models.ForeignKey(blank=True, db_column='professional_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Profissional'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingvitalsign',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingvitalsign',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingvitalsign',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='nursingvitalsign',
            name='record',
            field=models.ForeignKey(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, related_name='signals_vitais', to='enfermagem.nursingrecord', verbose_name='Registro'),
        ),
        migrations.AddField(
            model_name='nursingvitalsign',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='nursingvitalsign',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingrecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingrecord',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='registros_enfermagem', to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='nursingrecord',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='nursingrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingprescription',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingprescription',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingprescription',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes_enfermagem', to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='nursingprescription',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='nursingprescription',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingevolution',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingevolution',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingevolution',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes_enfermagem', to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='nursingevolution',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='nursingevolution',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='wardbed',
            index=models.Index(fields=['tenant', 'ward', 'number'], name='enfermagem__tenant__d146ad_idx'),
        ),
        migrations.AddIndex(
            model_name='wardbed',
            index=models.Index(fields=['tenant', 'active', 'created_at'], name='enfermagem__tenant__cfe79e_idx'),
        ),
        migrations.AddConstraint(
            model_name='wardbed',
            constraint=models.UniqueConstraint(fields=('tenant', 'ward', 'number'), name='uniq_bed_ward_number_por_tenant'),
        ),
        migrations.AddIndex(
            model_name='wardadmission',
            index=models.Index(fields=['tenant', 'active', 'admission_date'], name='enfermagem__tenant__02a6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='wardadmission',
            index=models.Index(fields=['tenant', 'bed', 'active'], name='enfermagem__tenant__4f9176_idx'),
        ),
        migrations.AddIndex(
            model_name='wardadmission',
            index=models.Index(fields=['tenant', 'patient', 'admission_date'], name='enfermagem__tenant__d5083d_idx'),
        ),
        migrations.AddIndex(
            model_name='wardadmission',
            index=models.Index(fields=['tenant', 'next_medication_at'], name='enfermagem__tenant__8d01b2_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['tenant', 'active', 'name'], name='enfermagem__tenant__b9a3c7_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurematerial',
            index=models.Index(fields=['tenant', 'procedure'], name='enfermagem__tenant__49aec5_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurematerial',
            index=models.Index(fields=['procedure_item'], name='enfermagem__procedu_941de4_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurematerial',
            index=models.Index(fields=['product'], name='enfermagem__product_f99a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurematerial',
            index=models.Index(fields=['lot'], name='enfermagem__lot_id_f2c03c_idx'),
        ),
        migrations.AddIndex(
            model_name='procedureitem',
            index=models.Index(fields=['tenant', 'procedure'], name='enfermagem__tenant__5c4e18_idx'),
        ),
        migrations.AddIndex(
            model_name='procedureitem',
            index=models.Index(fields=['catalog'], name='enfermagem__catalog_aeb737_idx'),
        ),
        migrations.AddIndex(
            model_name='procedureitem',
            index=models.Index(fields=['description'], name='enfermagem__descrip_6125b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='procedurecatalogmaterial',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('catalog', 'product'), name='unique_material_padrao_por_catalog'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['tenant', 'patient'], name='enfermagem__tenant__613f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['performed_date'], name='enfermagem__perform_755e33_idx'),
        ),
    ]
