# Generated by Django 4.2.29 on 2026-03-18 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enfermagem', '0001_initial'),
        ('inquilinos', '0001_initial'),
        ('clinico', '0002_initial'),
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinalvitalenfermagem',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sinalvitalenfermagem',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sinalvitalenfermagem',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sinalvitalenfermagem',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='sinalvitalenfermagem',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals_vitais', to='enfermagem.registroenfermagem'),
        ),
        migrations.AddField(
            model_name='registroenfermagem',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroenfermagem',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroenfermagem',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroenfermagem',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='registroenfermagem',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_enfermagem', to='clinico.paciente'),
        ),
        migrations.AddField(
            model_name='procedimentomaterialvalor',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentomaterialvalor',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentomaterialvalor',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentomaterialvalor',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='procedimentomaterialvalor',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valor', to='enfermagem.procedimentomaterial'),
        ),
        migrations.AddField(
            model_name='procedimentomaterial',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentomaterial',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentomaterial',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentomaterial',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='procedimentomaterial',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumos_procedimento', to='farmacia.lote'),
        ),
        migrations.AddField(
            model_name='procedimentomaterial',
            name='movimento_estoque',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumo_procedimento', to='farmacia.movimentoestoque'),
        ),
        migrations.AddField(
            model_name='procedimentomaterial',
            name='procedimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='enfermagem.procedimento'),
        ),
        migrations.AddField(
            model_name='procedimentomaterial',
            name='procedimento_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_gerados', to='enfermagem.procedimentoitem'),
        ),
        migrations.AddField(
            model_name='procedimentomaterial',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_procedimento', to='farmacia.produto'),
        ),
        migrations.AddField(
            model_name='procedimentoitemvalor',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentoitemvalor',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentoitemvalor',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentoitemvalor',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='procedimentoitemvalor',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valor', to='enfermagem.procedimentoitem'),
        ),
        migrations.AddField(
            model_name='procedimentoitem',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentoitem',
            name='catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_lancados', to='enfermagem.procedimentocatalogo'),
        ),
        migrations.AddField(
            model_name='procedimentoitem',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentoitem',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentoitem',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='procedimentoitem',
            name='procedimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='enfermagem.procedimento'),
        ),
        migrations.AddField(
            model_name='procedimentocatalogomaterial',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentocatalogomaterial',
            name='catalogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_padrao', to='enfermagem.procedimentocatalogo'),
        ),
        migrations.AddField(
            model_name='procedimentocatalogomaterial',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentocatalogomaterial',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentocatalogomaterial',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='procedimentocatalogomaterial',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiais_padrao_procedimento', to='farmacia.produto'),
        ),
        migrations.AddField(
            model_name='procedimentocatalogo',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentocatalogo',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentocatalogo',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimentocatalogo',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimentos_enfermagem', to='clinico.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimentos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Profissional'),
        ),
        migrations.AddField(
            model_name='prescricaoenfermagem',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescricaoenfermagem',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescricaoenfermagem',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescricaoenfermagem',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='prescricaoenfermagem',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes_enfermagem', to='clinico.paciente'),
        ),
        migrations.AddField(
            model_name='internamentoenfermaria',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internamentoenfermaria',
            name='cama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internamentos', to='enfermagem.camaenfermaria', verbose_name='Cama'),
        ),
        migrations.AddField(
            model_name='internamentoenfermaria',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internamentoenfermaria',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internamentoenfermaria',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='internamentoenfermaria',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internamentos_enfermaria', to='clinico.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='evolucaoenfermagem',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evolucaoenfermagem',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evolucaoenfermagem',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evolucaoenfermagem',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='evolucaoenfermagem',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes_enfermagem', to='clinico.paciente'),
        ),
        migrations.AddField(
            model_name='enfermaria',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enfermaria',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enfermaria',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enfermaria',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='camaenfermaria',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='camaenfermaria',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='camaenfermaria',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='camaenfermaria',
            name='enfermaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camas', to='enfermagem.enfermaria', verbose_name='Enfermaria'),
        ),
        migrations.AddField(
            model_name='camaenfermaria',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddIndex(
            model_name='procedimentomaterial',
            index=models.Index(fields=['inquilino', 'procedimento'], name='enfermagem__inquili_b172e6_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimentomaterial',
            index=models.Index(fields=['procedimento_item'], name='enfermagem__procedi_fd692c_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimentomaterial',
            index=models.Index(fields=['produto'], name='enfermagem__produto_6c90ec_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimentomaterial',
            index=models.Index(fields=['lote'], name='enfermagem__lote_id_1019ee_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimentoitem',
            index=models.Index(fields=['inquilino', 'procedimento'], name='enfermagem__inquili_db8a55_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimentoitem',
            index=models.Index(fields=['catalogo'], name='enfermagem__catalog_4e19ce_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimentoitem',
            index=models.Index(fields=['descricao'], name='enfermagem__descric_73baec_idx'),
        ),
        migrations.AddConstraint(
            model_name='procedimentocatalogomaterial',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False)), fields=('catalogo', 'produto'), name='unique_material_padrao_por_catalogo'),
        ),
        migrations.AddIndex(
            model_name='procedimento',
            index=models.Index(fields=['inquilino', 'paciente'], name='enfermagem__inquili_1c9e86_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimento',
            index=models.Index(fields=['data_realizacao'], name='enfermagem__data_re_8b4dac_idx'),
        ),
        migrations.AddIndex(
            model_name='internamentoenfermaria',
            index=models.Index(fields=['inquilino', 'ativo', 'data_internamento'], name='enfermagem__inquili_9fdd4b_idx'),
        ),
        migrations.AddIndex(
            model_name='internamentoenfermaria',
            index=models.Index(fields=['inquilino', 'cama', 'ativo'], name='enfermagem__inquili_2e1334_idx'),
        ),
        migrations.AddIndex(
            model_name='internamentoenfermaria',
            index=models.Index(fields=['inquilino', 'paciente', 'data_internamento'], name='enfermagem__inquili_3ae888_idx'),
        ),
        migrations.AddIndex(
            model_name='internamentoenfermaria',
            index=models.Index(fields=['inquilino', 'proxima_medicacao_em'], name='enfermagem__inquili_7b2fad_idx'),
        ),
        migrations.AddIndex(
            model_name='enfermaria',
            index=models.Index(fields=['inquilino', 'ativa', 'nome'], name='enfermagem__inquili_c40cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='camaenfermaria',
            index=models.Index(fields=['inquilino', 'enfermaria', 'numero'], name='enfermagem__inquili_e30dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='camaenfermaria',
            index=models.Index(fields=['inquilino', 'ativa', 'criado_em'], name='enfermagem__inquili_6a0d81_idx'),
        ),
        migrations.AddConstraint(
            model_name='camaenfermaria',
            constraint=models.UniqueConstraint(fields=('inquilino', 'enfermaria', 'numero'), name='uniq_cama_enfermaria_numero_por_inquilino'),
        ),
    ]
