# Generated by Django 4.2.29 on 2026-05-25 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_alter_clinicalhistory_patient_and_more'),
        ('enfermagem', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursingevolution',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, related_name='evolucoes_enfermagem', to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='nursingprescription',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes_enfermagem', to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='nursingrecord',
            name='lab_request',
            field=models.OneToOneField(blank=True, db_column='lab_request_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nursing_intake_record', to='clinical.labrequest', verbose_name='Requisição laboratorial'),
        ),
        migrations.AlterField(
            model_name='nursingrecord',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, related_name='registros_enfermagem', to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='nursingvitalsign',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='nursingvitalsign',
            name='record',
            field=models.ForeignKey(db_column='record_id', on_delete=django.db.models.deletion.PROTECT, related_name='signals_vitais', to='enfermagem.nursingrecord', verbose_name='Registro'),
        ),
    ]
