# Generated by Django 4.2.29 on 2026-04-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_alter_lot_initial_quantity_and_more'),
        ('enfermagem', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='selected_materials',
            field=models.ManyToManyField(blank=True, related_name='procedures_selected', to='farmacia.product', verbose_name='Materiais selecionados'),
        ),
    ]
