# Generated by Django 5.1 on 2026-03-26 05:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0005_alter_clinicalevent_options_and_more"),
        ("enfermagem", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nursingevolution",
            name="patient",
            field=models.ForeignKey(
                db_column="patient_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evolucoes_enfermagem",
                to="clinical.patient",
                verbose_name="Paciente",
            ),
        ),
        migrations.AlterField(
            model_name="nursingprescription",
            name="patient",
            field=models.ForeignKey(
                db_column="patient_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescricoes_enfermagem",
                to="clinical.patient",
                verbose_name="Paciente",
            ),
        ),
        migrations.AlterField(
            model_name="nursingrecord",
            name="observation",
            field=models.TextField(
                blank=True,
                db_column="observation",
                default="",
                verbose_name="Observação",
            ),
        ),
        migrations.AlterField(
            model_name="nursingrecord",
            name="patient",
            field=models.ForeignKey(
                db_column="patient_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registros_enfermagem",
                to="clinical.patient",
                verbose_name="Paciente",
            ),
        ),
        migrations.AlterField(
            model_name="nursingrecord",
            name="priority",
            field=models.CharField(
                choices=[("URG", "Urgente"), ("NOR", "Normal"), ("BAI", "Baixa")],
                db_column="priority",
                db_index=True,
                default="NOR",
                max_length=3,
                verbose_name="Prioridade",
            ),
        ),
        migrations.AlterField(
            model_name="nursingvitalsign",
            name="blood_pressure",
            field=models.CharField(
                blank=True,
                db_column="blood_pressure",
                default="",
                max_length=20,
                verbose_name="Pressão arterial",
            ),
        ),
        migrations.AlterField(
            model_name="nursingvitalsign",
            name="collected_at",
            field=models.DateTimeField(
                db_column="collected_at",
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Coletado em",
            ),
        ),
        migrations.AlterField(
            model_name="nursingvitalsign",
            name="record",
            field=models.ForeignKey(
                db_column="record_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signals_vitais",
                to="enfermagem.nursingrecord",
                verbose_name="Registro",
            ),
        ),
    ]
