# Generated by Django 4.2.29 on 2026-05-26 05:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0003_alter_nursingevolution_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursingprescription',
            name='active',
            field=models.BooleanField(db_column='active', default=True, verbose_name='Prescrição ativa'),
        ),
        migrations.AlterField(
            model_name='nursingrecord',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True, db_column='record_date', verbose_name='Data do registo'),
        ),
        migrations.AlterField(
            model_name='procedurecatalog',
            name='applies_vat_by_default',
            field=models.BooleanField(db_column='applies_vat_by_default', default=True, help_text='Desmarque se este procedimento normalmente não deve ter IVA.', verbose_name='Aplicar IVA por padrão'),
        ),
        migrations.AlterField(
            model_name='procedurecatalog',
            name='vat_percentage',
            field=models.DecimalField(db_column='vat_percentage', decimal_places=2, default=Decimal('5.00'), help_text='Taxa de IVA aplicada ao procedimento (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)'),
        ),
        migrations.AlterField(
            model_name='wardadmission',
            name='estimated_observation_hours',
            field=models.PositiveSmallIntegerField(blank=True, db_column='estimated_observation_hours', help_text='Tempo estimado de observação em horas (quando aplicável).', null=True, verbose_name='Tempo estimado de observação (horas)'),
        ),
        migrations.AlterField(
            model_name='wardbed',
            name='number',
            field=models.CharField(db_column='number', db_index=True, max_length=20, verbose_name='Número da cama'),
        ),
    ]
