# Generated by Django 4.2.29 on 2026-04-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0003_procedure_selected_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardadmission',
            name='active',
            field=models.BooleanField(db_column='active', db_index=True, default=True, verbose_name='Internamento ativo'),
        ),
        migrations.AlterField(
            model_name='wardadmission',
            name='estimated_observation_hours',
            field=models.PositiveSmallIntegerField(blank=True, db_column='estimated_observation_hours', help_text='Tempo estimado de observação em hours (quando aplicável).', null=True, verbose_name='Tempo estimado de observação (horas)'),
        ),
    ]
