# Generated by Django 4.2.29 on 2026-06-01 18:39

from django.db import migrations, models
from django.db.models import OuterRef, Subquery
import django.db.models.deletion


def backfill_ward_context(apps, schema_editor):
    WardAdmission = apps.get_model('enfermagem', 'WardAdmission')
    WardBed = apps.get_model('enfermagem', 'WardBed')
    ProcedureCatalogMaterial = apps.get_model('enfermagem', 'ProcedureCatalogMaterial')
    ProcedureCatalog = apps.get_model('enfermagem', 'ProcedureCatalog')
    ProcedureItem = apps.get_model('enfermagem', 'ProcedureItem')
    Procedure = apps.get_model('enfermagem', 'Procedure')
    ProcedureMaterial = apps.get_model('enfermagem', 'ProcedureMaterial')
    ProcedureItemValue = apps.get_model('enfermagem', 'ProcedureItemValue')
    ProcedureMaterialValue = apps.get_model('enfermagem', 'ProcedureMaterialValue')
    NursingVitalSign = apps.get_model('enfermagem', 'NursingVitalSign')
    NursingRecord = apps.get_model('enfermagem', 'NursingRecord')

    WardAdmission.objects.filter(ward__isnull=True, bed__isnull=False).update(
        ward_id=Subquery(WardBed.objects.filter(pk=OuterRef('bed_id')).values('ward_id')[:1])
    )
    ProcedureCatalogMaterial.objects.filter(ward__isnull=True, catalog__isnull=False).update(
        ward_id=Subquery(ProcedureCatalog.objects.filter(pk=OuterRef('catalog_id')).values('ward_id')[:1])
    )
    ProcedureItem.objects.filter(ward__isnull=True, procedure__isnull=False).update(
        ward_id=Subquery(Procedure.objects.filter(pk=OuterRef('procedure_id')).values('ward_id')[:1])
    )
    ProcedureItem.objects.filter(ward__isnull=True, catalog__isnull=False).update(
        ward_id=Subquery(ProcedureCatalog.objects.filter(pk=OuterRef('catalog_id')).values('ward_id')[:1])
    )
    ProcedureMaterial.objects.filter(ward__isnull=True, procedure__isnull=False).update(
        ward_id=Subquery(Procedure.objects.filter(pk=OuterRef('procedure_id')).values('ward_id')[:1])
    )
    ProcedureMaterial.objects.filter(ward__isnull=True, procedure_item__isnull=False).update(
        ward_id=Subquery(ProcedureItem.objects.filter(pk=OuterRef('procedure_item_id')).values('ward_id')[:1])
    )
    ProcedureItemValue.objects.filter(ward__isnull=True, item__isnull=False).update(
        ward_id=Subquery(ProcedureItem.objects.filter(pk=OuterRef('item_id')).values('ward_id')[:1])
    )
    ProcedureMaterialValue.objects.filter(ward__isnull=True, material__isnull=False).update(
        ward_id=Subquery(ProcedureMaterial.objects.filter(pk=OuterRef('material_id')).values('ward_id')[:1])
    )
    NursingVitalSign.objects.filter(ward__isnull=True, record__isnull=False).update(
        ward_id=Subquery(NursingRecord.objects.filter(pk=OuterRef('record_id')).values('ward_id')[:1])
    )


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('enfermagem', '0004_alter_nursingprescription_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursingevolution',
            name='ward',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='enfermagem.ward', verbose_name='Enfermaria'),
        ),
        migrations.AddField(
            model_name='nursingprescription',
            name='ward',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='enfermagem.ward', verbose_name='Enfermaria'),
        ),
        migrations.AddField(
            model_name='nursingrecord',
            name='ward',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='enfermagem.ward', verbose_name='Enfermaria'),
        ),
        migrations.AddField(
            model_name='nursingvitalsign',
            name='ward',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='enfermagem.ward', verbose_name='Enfermaria'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='ward',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='enfermagem.ward', verbose_name='Enfermaria'),
        ),
        migrations.AddField(
            model_name='procedurecatalog',
            name='ward',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='enfermagem.ward', verbose_name='Enfermaria'),
        ),
        migrations.AddField(
            model_name='procedurecatalogmaterial',
            name='ward',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='enfermagem.ward', verbose_name='Enfermaria'),
        ),
        migrations.AddField(
            model_name='procedureitem',
            name='ward',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='enfermagem.ward', verbose_name='Enfermaria'),
        ),
        migrations.AddField(
            model_name='procedureitemvalue',
            name='ward',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='enfermagem.ward', verbose_name='Enfermaria'),
        ),
        migrations.AddField(
            model_name='procedurematerial',
            name='ward',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='enfermagem.ward', verbose_name='Enfermaria'),
        ),
        migrations.AddField(
            model_name='procedurematerialvalue',
            name='ward',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='enfermagem.ward', verbose_name='Enfermaria'),
        ),
        migrations.AddField(
            model_name='wardadmission',
            name='ward',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='enfermagem.ward', verbose_name='Enfermaria'),
        ),
        migrations.RunPython(backfill_ward_context, migrations.RunPython.noop),
    ]
