# Generated by Django 6.0.5 on 2026-07-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0006_repair_nursing_record_lab_intake_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardadmission',
            name='admission_date',
            field=models.DateTimeField(auto_now_add=True, db_column='admission_date', db_index=True, verbose_name='Data de internamento'),
        ),
    ]
