# Generated by Django 4.2.16 on 2026-04-20 06:00

from django.conf import settings
from django.db import migrations, models


def copy_professional_fk_to_m2m(apps, schema_editor):
    Procedure = apps.get_model("enfermagem", "Procedure")
    db_alias = schema_editor.connection.alias

    m2m_field = Procedure._meta.get_field("professional_m2m")
    through_model = m2m_field.remote_field.through
    procedure_fk_name = f"{m2m_field.m2m_field_name()}_id"
    professional_fk_name = f"{m2m_field.m2m_reverse_field_name()}_id"

    relations = []
    for procedure_id, professional_id in (
        Procedure.objects.using(db_alias)
        .exclude(professional_id__isnull=True)
        .values_list("id", "professional_id")
    ):
        relations.append(
            through_model(
                **{
                    procedure_fk_name: procedure_id,
                    professional_fk_name: professional_id,
                }
            )
        )

    if relations:
        through_model.objects.using(db_alias).bulk_create(relations, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("enfermagem", "0006_remove_procedurecatalogmaterial_unique_material_padrao_por_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedure",
            name="professional_m2m",
            field=models.ManyToManyField(
                blank=True,
                related_name="procedures_realizados_m2m_tmp",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Profissionais",
            ),
        ),
        migrations.RunPython(copy_professional_fk_to_m2m, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="procedure",
            name="professional",
        ),
        migrations.RenameField(
            model_name="procedure",
            old_name="professional_m2m",
            new_name="professional",
        ),
        migrations.AlterField(
            model_name="procedure",
            name="professional",
            field=models.ManyToManyField(
                blank=True,
                related_name="procedures_realizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Profissionais",
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="selected_catalogs",
            field=models.ManyToManyField(
                blank=True,
                related_name="procedures_selected",
                to="enfermagem.procedurecatalog",
                verbose_name="Procedimentos do catálogo",
            ),
        ),
    ]
