# Generated by Django 4.2.29 on 2026-04-28 21:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0007_procedure_professional_m2m_and_selected_catalogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedurecatalog',
            options={'ordering': ['name'], 'verbose_name': 'Catálogo de Procedimento', 'verbose_name_plural': 'Catálogos de Procedimentos'},
        ),
        migrations.AlterModelOptions(
            name='procedureitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Procedimento de Enfermagem - Item', 'verbose_name_plural': 'Procedimentos de Enfermagem - Itens'},
        ),
        migrations.AlterField(
            model_name='procedurecatalog',
            name='vat_percentage',
            field=models.DecimalField(db_column='vat_percentage', decimal_places=2, default=Decimal('5.00'), help_text='Taxa de IVA aplicada ao procedure (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)'),
        ),
        migrations.AlterField(
            model_name='procedureitem',
            name='billed',
            field=models.BooleanField(db_column='billed', db_index=True, default=False, verbose_name='Faturado'),
        ),
        migrations.AlterField(
            model_name='procedureitem',
            name='catalog',
            field=models.ForeignKey(blank=True, db_column='catalog_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_lancados', to='enfermagem.procedurecatalog', verbose_name='Catálogo do Procedimento'),
        ),
        migrations.AlterField(
            model_name='procedureitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_column='completed_at', null=True, verbose_name='Concluído em'),
        ),
        migrations.AlterField(
            model_name='procedureitem',
            name='executed_at',
            field=models.DateTimeField(blank=True, db_column='executed_at', null=True, verbose_name='Executado em'),
        ),
        migrations.AlterField(
            model_name='procedureitem',
            name='observation',
            field=models.TextField(blank=True, db_column='observation', default='', verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='procedureitem',
            name='performed',
            field=models.BooleanField(db_column='performed', db_index=True, default=True, verbose_name='Realizado'),
        ),
        migrations.AlterField(
            model_name='procedureitem',
            name='procedure',
            field=models.ForeignKey(db_column='procedure_id', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='enfermagem.procedure', verbose_name='Procedimento'),
        ),
        migrations.AlterField(
            model_name='procedureitem',
            name='quantity',
            field=models.PositiveIntegerField(db_column='quantity', default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='procedureitem',
            name='unit_price',
            field=models.DecimalField(db_column='unit_price', decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço Unitário'),
        ),
    ]
