# Generated by Django 4.2.29 on 2026-05-19 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0013_labexam_sample_options'),
        ('enfermagem', '0009_alter_procedureitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursingrecord',
            name='collection_guidance',
            field=models.JSONField(blank=True, db_column='collection_guidance', default=list, help_text='Estrutura operacional da coleta por exame, com opções de amostra, tipo de frasco/tubo e volume mínimo.', verbose_name='Guia de coleta'),
        ),
        migrations.AddField(
            model_name='nursingrecord',
            name='lab_request',
            field=models.OneToOneField(blank=True, db_column='lab_request_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nursing_intake_record', to='clinical.labrequest', verbose_name='Requisição laboratorial'),
        ),
        migrations.AddField(
            model_name='nursingrecord',
            name='origin_role',
            field=models.CharField(blank=True, db_column='origin_role', default='', max_length=60, verbose_name='Perfil de origem'),
        ),
        migrations.AddField(
            model_name='nursingrecord',
            name='record_kind',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('LAB_COLLECTION_REQUEST', 'Requisição laboratorial para coleta')], db_column='record_kind', db_index=True, default='MANUAL', max_length=40, verbose_name='Tipo de registro'),
        ),
        migrations.AddIndex(
            model_name='nursingrecord',
            index=models.Index(fields=['record_kind', 'record_date'], name='enfermagem__record__6707e9_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingrecord',
            index=models.Index(fields=['lab_request', 'deleted'], name='enfermagem__lab_req_4245f4_idx'),
        ),
    ]
