# Generated by Django 4.2.16 on 2026-03-14 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinico', '0005_requisicaoanalise_tipo'),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('data_ultima_menstruacao', models.DateField(blank=True, null=True)),
                ('data_prevista_parto', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACOMP', 'Em acompanhamento'), ('PARTO', 'Parto realizado'), ('ENCERR', 'Encerrada'), ('CANCEL', 'Cancelada')], db_index=True, default='ACOMP', max_length=10)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
                ('medico_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestacoes_responsavel', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestacoes', to='clinico.paciente')),
            ],
            options={
                'verbose_name': 'Gestação',
                'verbose_name_plural': 'Gestações',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['inquilino', 'paciente', 'criado_em'], name='maternidade_inquili_d42c57_idx'), models.Index(fields=['inquilino', 'estado', 'criado_em'], name='maternidade_inquili_78a2a3_idx')],
            },
        ),
    ]
