# Generated by Django 4.2.16 on 2026-03-18 23:14

from django.db import migrations, models
import django.db.models.deletion


def _map_usuario_para_funcionario(apps):
    PerfilProfissional = apps.get_model("identidade", "PerfilProfissional")
    return dict(
        PerfilProfissional.objects.exclude(funcionario_id__isnull=True).values_list("usuario_id", "funcionario_id")
    )


def forward_medico_responsavel_funcionario(apps, schema_editor):
    Gestacao = apps.get_model("maternidade", "Gestacao")
    mapping = _map_usuario_para_funcionario(apps)
    if not mapping:
        return

    qs = Gestacao.objects.exclude(medico_responsavel_id__isnull=True)
    for gestacao in qs.iterator():
        funcionario_id = mapping.get(gestacao.medico_responsavel_id)
        if funcionario_id and gestacao.medico_responsavel_funcionario_id != funcionario_id:
            gestacao.medico_responsavel_funcionario_id = funcionario_id
            gestacao.save(update_fields=["medico_responsavel_funcionario"])


def backward_medico_responsavel_funcionario(apps, schema_editor):
    Gestacao = apps.get_model("maternidade", "Gestacao")
    PerfilProfissional = apps.get_model("identidade", "PerfilProfissional")
    mapping = dict(
        PerfilProfissional.objects.exclude(usuario_id__isnull=True).values_list("funcionario_id", "usuario_id")
    )
    if not mapping:
        return

    qs = Gestacao.objects.exclude(medico_responsavel_funcionario_id__isnull=True)
    for gestacao in qs.iterator():
        usuario_id = mapping.get(gestacao.medico_responsavel_funcionario_id)
        if usuario_id and gestacao.medico_responsavel_id != usuario_id:
            gestacao.medico_responsavel_id = usuario_id
            gestacao.save(update_fields=["medico_responsavel"])


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_funcionario_profissao'),
        ('identidade', '0002_initial'),
        ('maternidade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name="gestacao",
            name="medico_responsavel_funcionario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gestacoes_responsavel",
                to="recursos_humanos.funcionario",
                verbose_name="Médico/Ginecologista responsável",
            ),
        ),
        migrations.RunPython(forward_medico_responsavel_funcionario, backward_medico_responsavel_funcionario),
        migrations.RemoveField(
            model_name="gestacao",
            name="medico_responsavel",
        ),
        migrations.RenameField(
            model_name="gestacao",
            old_name="medico_responsavel_funcionario",
            new_name="medico_responsavel",
        ),
    ]
