# Generated by Django 6.0.1 on 2026-03-09 02:48

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConciliacaoFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                (
                    "valor_contabil",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "valor_recebido",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("divergencia", models.DecimalField(decimal_places=2, max_digits=18)),
                ("conciliado", models.BooleanField(db_index=True, default=False)),
                (
                    "referencia_externa",
                    models.CharField(
                        blank=True, db_index=True, max_length=120, null=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Conta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ATI", "Ativo"),
                            ("PAS", "Passivo"),
                            ("REC", "Receita"),
                            ("DES", "Despesa"),
                            ("PAT", "Patrimônio"),
                        ],
                        db_index=True,
                        default="DES",
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lancamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                ("descricao", models.CharField(max_length=255)),
                (
                    "data",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "referencia_externa",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("confirmado", models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                ("referencia_externa", models.CharField(db_index=True, max_length=120)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("data_contabil", models.DateField(db_index=True)),
                ("descricao", models.CharField(max_length=255)),
                ("revertido", models.BooleanField(db_index=True, default=False)),
                ("motivo_reversao", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "hash_anterior",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "hash_atual",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LedgerLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "natureza",
                    models.CharField(
                        choices=[("D", "Débito"), ("C", "Crédito")], max_length=1
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_custom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                ("deletado", models.BooleanField(db_index=True, default=False)),
                ("deletado_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                (
                    "debito",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "credito",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaldoConta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saldo_atual",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "total_debitos",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "total_creditos",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
    ]
