# Generated by Django 6.0.1 on 2026-02-27 09:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_custom', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('ordem', models.PositiveIntegerField(db_index=True, default=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ATI', 'Ativo'), ('PAS', 'Passivo'), ('REC', 'Receita'), ('DES', 'Despesa'), ('PAT', 'Patrimônio')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_custom', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('ordem', models.PositiveIntegerField(db_index=True, default=1)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateField(db_index=True)),
                ('referencia_externa', models.CharField(blank=True, db_index=True, max_length=120)),
                ('confirmado', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_custom', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('ordem', models.PositiveIntegerField(db_index=True, default=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
            ],
        ),
    ]
