# Generated by Django 6.0.1 on 2026-02-27 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidade', '0001_initial'),
        ('inquilinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conta',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conta',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimento',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidade.conta'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimento',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='contabilidade.lancamento'),
        ),
        migrations.AddIndex(
            model_name='conta',
            index=models.Index(fields=['id_custom'], name='contabilida_id_cust_8cdc6d_idx'),
        ),
        migrations.AddIndex(
            model_name='conta',
            index=models.Index(fields=['tipo'], name='contabilida_tipo_46cc1a_idx'),
        ),
        migrations.AddIndex(
            model_name='conta',
            index=models.Index(fields=['inquilino', 'id_custom'], name='contabilida_inquili_f927db_idx'),
        ),
        migrations.AddConstraint(
            model_name='conta',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False)), fields=('inquilino', 'id_custom'), name='unique_codigo_conta_por_inquilino'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['data'], name='contabilida_data_8a89c0_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['confirmado'], name='contabilida_confirm_debfdd_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['lancamento'], name='contabilida_lancame_9ee3b3_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['conta'], name='contabilida_conta_i_0b07d8_idx'),
        ),
    ]
