# Generated by Django 4.2.13 on 2026-03-12 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faturamento', '0001_initial'),
        ('contabilidade', '0001_initial'),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimento',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='contabilidade.conta'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimento',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimento',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='contabilidade.lancamento'),
        ),
        migrations.AddField(
            model_name='ledgerline',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerline',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidade.conta'),
        ),
        migrations.AddField(
            model_name='ledgerline',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerline',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerline',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas', to='contabilidade.ledgerentry'),
        ),
        migrations.AddField(
            model_name='ledgerline',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reverso_de',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversao', to='contabilidade.ledgerentry'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='conta',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conta',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conta',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conta',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='conciliacaofinanceira',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conciliacaofinanceira',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conciliacaofinanceira',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conciliacaofinanceira',
            name='fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes', to='faturamento.fatura'),
        ),
        migrations.AddField(
            model_name='conciliacaofinanceira',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['inquilino', 'lancamento'], name='contabilida_inquili_86204e_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['inquilino', 'conta'], name='contabilida_inquili_f1e1d9_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerline',
            index=models.Index(fields=['entry'], name='contabilida_entry_i_abe270_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerline',
            index=models.Index(fields=['inquilino', 'conta', 'criado_em'], name='contabilida_inquili_28a9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerline',
            index=models.Index(fields=['inquilino', 'entry'], name='contabilida_inquili_6a009f_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerline',
            constraint=models.CheckConstraint(check=models.Q(('valor__gt', 0)), name='ledgerline_valor_positivo'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['inquilino', 'data_contabil'], name='contabilida_inquili_ee01c7_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['inquilino', 'criado_em'], name='contabilida_inquili_29e97c_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['referencia_externa'], name='contabilida_referen_25ddcf_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('inquilino', 'idempotency_key'), name='unique_ledger_idempotency'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['inquilino', 'data'], name='contabilida_inquili_9369a3_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['inquilino', 'confirmado'], name='contabilida_inquili_1c65ef_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['referencia_externa'], name='contabilida_referen_f08b53_idx'),
        ),
        migrations.AddIndex(
            model_name='conta',
            index=models.Index(fields=['inquilino', 'id_custom'], name='contabilida_inquili_f927db_idx'),
        ),
        migrations.AddIndex(
            model_name='conta',
            index=models.Index(fields=['inquilino', 'tipo'], name='contabilida_inquili_ded674_idx'),
        ),
        migrations.AddConstraint(
            model_name='conta',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado', False)), fields=('inquilino', 'id_custom'), name='unique_codigo_conta_por_inquilino'),
        ),
        migrations.AddIndex(
            model_name='conciliacaofinanceira',
            index=models.Index(fields=['fatura'], name='contabilida_fatura__286d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='conciliacaofinanceira',
            index=models.Index(fields=['conciliado'], name='contabilida_concili_346cde_idx'),
        ),
    ]
