# Generated by Django 6.0.1 on 2026-02-28 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidade", "0003_alter_conta_id_custom_alter_lancamento_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimento",
            name="conta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimentos",
                related_query_name="movimento",
                to="contabilidade.conta",
            ),
        ),
        migrations.AlterField(
            model_name="movimento",
            name="lancamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimentos",
                related_query_name="movimento",
                to="contabilidade.lancamento",
            ),
        ),
    ]
