# Generated by Django 4.2.16 on 2026-03-17 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('metodo', models.CharField(db_index=True, max_length=10, verbose_name='Método HTTP')),
                ('caminho', models.CharField(db_index=True, max_length=255, verbose_name='Rota curta')),
                ('path_completo', models.TextField(blank=True, default='', verbose_name='URL completa')),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, default=500, verbose_name='Status HTTP')),
                ('duracao_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (ms)')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User-Agent')),
                ('view_basename', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='View')),
                ('view_action', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Ação da view')),
                ('objeto_id', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Objeto (ID)')),
                ('exception_class', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Classe da exceção')),
                ('mensagem', models.CharField(blank=True, default='', max_length=500, verbose_name='Mensagem')),
                ('traceback', models.TextField(blank=True, default='', verbose_name='Traceback')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erros_sistema', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Erro do Sistema',
                'verbose_name_plural': 'Erros do Sistema',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['inquilino', 'criado_em'], name='monitoramen_inquili_963a13_idx'), models.Index(fields=['inquilino', 'status_code', 'criado_em'], name='monitoramen_inquili_9fcd0b_idx'), models.Index(fields=['inquilino', 'exception_class', 'criado_em'], name='monitoramen_inquili_ba1bcf_idx')],
            },
        ),
    ]
