# Generated by Django 5.1 on 2026-03-26 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "inquilinos",
            "0002_rename_inquilinos__tipo_856ce4_idx_inquilinos__type_fdb81e_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "method",
                    models.CharField(
                        db_column="method",
                        db_index=True,
                        max_length=10,
                        verbose_name="Método HTTP",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        db_column="path",
                        db_index=True,
                        max_length=255,
                        verbose_name="Rota curta",
                    ),
                ),
                (
                    "full_path",
                    models.TextField(
                        blank=True,
                        db_column="full_path",
                        default="",
                        verbose_name="URL completa",
                    ),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=500, verbose_name="Status HTTP"
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        db_column="duration_ms",
                        null=True,
                        verbose_name="Duração (ms)",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP de origin"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="User-Agent",
                    ),
                ),
                (
                    "view_basename",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=120,
                        verbose_name="View",
                    ),
                ),
                (
                    "view_action",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=120,
                        verbose_name="Ação da view",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        db_column="object_id",
                        db_index=True,
                        default="",
                        max_length=80,
                        verbose_name="Objeto (ID)",
                    ),
                ),
                (
                    "exception_class",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=120,
                        verbose_name="Classe da exceção",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        db_column="message",
                        default="",
                        max_length=500,
                        verbose_name="Mensagem",
                    ),
                ),
                (
                    "traceback",
                    models.TextField(blank=True, default="", verbose_name="Traceback"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadados"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erros_sistema",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilizador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Erro do Sistema",
                "verbose_name_plural": "Erros do Sistema",
                "db_table": "monitoramento_errosistema",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="monitoramen_tenant__20ebc3_idx",
                    ),
                    models.Index(
                        fields=["tenant", "status_code", "created_at"],
                        name="monitoramen_tenant__5e6a80_idx",
                    ),
                    models.Index(
                        fields=["tenant", "exception_class", "created_at"],
                        name="monitoramen_tenant__4a33a9_idx",
                    ),
                ],
            },
        ),
    ]
