# Generated by Django 4.2.29 on 2026-05-18 19:38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionalOutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='ID do evento')),
                ('event_type', models.CharField(db_index=True, max_length=180, verbose_name='Tipo de evento')),
                ('aggregate_id', models.CharField(blank=True, default='', max_length=120, verbose_name='ID do agregado')),
                ('aggregate_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='Versão do agregado')),
                ('tenant_identifier', models.CharField(blank=True, db_index=True, max_length=80, null=True, verbose_name='Tenant')),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Trace ID')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=140, verbose_name='Chave de idempotência')),
                ('source', models.CharField(default='django.event_bus', max_length=80, verbose_name='Origem')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('delivered', 'Entregue'), ('failed', 'Falhado'), ('dead_letter', 'Dead letter')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Disponível em')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ocorrido em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Último erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Evento de Outbox',
                'verbose_name_plural': 'Eventos de Outbox',
                'db_table': 'monitoramento_eventooutbox',
                'ordering': ['available_at', 'id'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='monitoramen_status_8778bc_idx'), models.Index(fields=['event_type', 'occurred_at'], name='monitoramen_event_t_1c0d53_idx'), models.Index(fields=['tenant_identifier', 'status', 'available_at'], name='monitoramen_tenant__71a3c9_idx')],
            },
        ),
    ]
