# Generated by Django 4.2.29 on 2026-05-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemerror',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem'),
        ),
        migrations.AlterField(
            model_name='transactionaloutboxevent',
            name='tenant_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, verbose_name='Cliente'),
        ),
    ]
