# Generated by Django 5.1 on 2026-03-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoramento", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="systemerror",
            new_name="monitoramen_tenant__20ebc3_idx",
            old_name="monitoramen_inquili_963a13_idx",
        ),
        migrations.RenameIndex(
            model_name="systemerror",
            new_name="monitoramen_tenant__5e6a80_idx",
            old_name="monitoramen_inquili_9fcd0b_idx",
        ),
        migrations.RenameIndex(
            model_name="systemerror",
            new_name="monitoramen_tenant__4a33a9_idx",
            old_name="monitoramen_inquili_ba1bcf_idx",
        ),
    ]
