# Generated by Django 4.2.29 on 2026-05-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0003_merge_20260519_0313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionaloutboxevent',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='transactionaloutboxevent',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=140, verbose_name='Chave de idempotência'),
        ),
        migrations.RemoveField(
            model_name='transactionaloutboxevent',
            name='last_error_at',
        ),
        migrations.RemoveField(
            model_name='transactionaloutboxevent',
            name='max_retries',
        ),
    ]
