# Generated by Django 5.2.12 on 2026-03-28 00:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Progression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Identificador do tenant",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Removido em"
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=60, verbose_name="Código"),
                ),
                ("cycle", models.IntegerField(verbose_name="Ciclo")),
                (
                    "academic_year",
                    models.CharField(max_length=10, verbose_name="Ano letivo"),
                ),
                ("decision_date", models.DateField(verbose_name="Data da decisão")),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approved", "Aprovado"),
                            ("retained", "Retido"),
                            ("transferred", "Transferido"),
                        ],
                        max_length=20,
                        verbose_name="Decisão",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comentário")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.student",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progressão",
                "verbose_name_plural": "Progressões",
                "ordering": ["-decision_date"],
            },
        ),
    ]
