# Generated by Django 5.2.12 on 2026-03-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0002_alter_progression_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progression",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Escola"),
        ),
    ]
