# Generated by Django 4.2.16 on 2026-03-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('nuit', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='NUIT')),
                ('endereco_sede', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local / Sede')),
                ('contactos', models.CharField(blank=True, help_text='Pessoa, departamento ou referência de contacto.', max_length=255, null=True, verbose_name='Contactos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone')),
                ('telefone2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone (alternativo)')),
                ('nib', models.CharField(blank=True, max_length=60, null=True, verbose_name='NIB / Conta bancária')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
    ]
