# Generated by Django 5.2.12 on 2026-03-28 03:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0005_alter_guardian_usuario_alter_student_usuario_and_more"),
        ("curriculum", "0004_competency_area_fk"),
        ("school", "0004_alter_teacher_specialty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Identificador do tenant",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Removido em"
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=60, verbose_name="Código"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("student", "Aluno"), ("teacher", "Professor")],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "move_teaching_assignments",
                    models.BooleanField(
                        default=False, verbose_name="Mover alocações docentes"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Motivo")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("applied", "Aplicada"),
                            ("failed", "Falhou"),
                            ("canceled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aplicada em"
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Erro")),
                (
                    "from_classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="school.classroom",
                        verbose_name="Turma de origem",
                    ),
                ),
                (
                    "from_school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="school.school",
                        verbose_name="Escola de origem",
                    ),
                ),
                (
                    "new_specialty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="curriculum.subjectspecialty",
                        verbose_name="Nova especialidade",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="academic.student",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="school.teacher",
                        verbose_name="Professor",
                    ),
                ),
                (
                    "to_classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="school.classroom",
                        verbose_name="Turma de destino",
                    ),
                ),
                (
                    "to_school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="school.school",
                        verbose_name="Escola de destino",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transferência",
                "verbose_name_plural": "Transferências",
                "ordering": ["-created_at"],
            },
        ),
    ]
