# Generated by Django 5.2.12 on 2026-03-28

from django.db import migrations


def forwards_copy_and_drop(apps, schema_editor):
    connection = schema_editor.connection
    tables = set(connection.introspection.table_names())

    old_table = "transferencia_transfer"
    new_table = "transfer_transfer"

    if old_table not in tables or new_table not in tables:
        return

    with connection.cursor() as cursor:
        cursor.execute(f"SELECT COUNT(*) FROM {new_table}")
        new_count = cursor.fetchone()[0] or 0
        if new_count == 0:
            cursor.execute(f"INSERT INTO {new_table} SELECT * FROM {old_table}")

        cursor.execute(f"DROP TABLE {old_table}")

        if connection.vendor == "postgresql":
            cursor.execute(f"SELECT COALESCE(MAX(id), 1) FROM {new_table}")
            max_id = cursor.fetchone()[0] or 1
            cursor.execute(
                "SELECT setval(pg_get_serial_sequence(%s, %s), %s, true)",
                [new_table, "id", max_id],
            )


class Migration(migrations.Migration):
    dependencies = [
        ("transfer", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards_copy_and_drop, migrations.RunPython.noop),
    ]
