# Generated by Django 5.1 on 2026-03-25 04:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Insurer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(db_column="nome", db_index=True, max_length=120),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=1)),
                (
                    "external_code",
                    models.CharField(
                        blank=True,
                        db_column="codigo_externo",
                        db_index=True,
                        max_length=60,
                        null=True,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_column="telefone", max_length=30, null=True
                    ),
                ),
                (
                    "active",
                    models.BooleanField(db_column="ativo", db_index=True, default=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="criado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deletado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="inquilino_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="atualizado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguradora",
                "verbose_name_plural": "Seguradoras",
                "db_table": "seguradora_seguradora",
            },
        ),
        migrations.CreateModel(
            name="CoveragePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(db_column="nome", db_index=True, max_length=120),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=1)),
                (
                    "coverage_percentage",
                    models.DecimalField(
                        db_column="percentual_cobertura",
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentual de cobertura (0-100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "requires_authorization",
                    models.BooleanField(
                        db_column="exige_autorizacao", db_index=True, default=False
                    ),
                ),
                (
                    "active",
                    models.BooleanField(db_column="ativo", db_index=True, default=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="criado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deletado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="inquilino_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="atualizado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "insurer",
                    models.ForeignKey(
                        db_column="seguradora_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planos",
                        to="seguradora.insurer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de Cobertura",
                "verbose_name_plural": "Planos de Cobertura",
                "db_table": "seguradora_planocobertura",
            },
        ),
        migrations.CreateModel(
            name="ProcedureAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=1)),
                (
                    "request_id",
                    models.CharField(
                        db_column="requisicao_id", db_index=True, max_length=60
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("APROVADA", "Aprovada"),
                            ("NEGADA", "Negada"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                (
                    "authorization_code",
                    models.CharField(
                        blank=True,
                        db_column="codigo_autorizacao",
                        db_index=True,
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "response_date",
                    models.DateTimeField(
                        blank=True, db_column="data_resposta", null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_column="nome",
                        db_index=True,
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(db_column="ativo", db_index=True, default=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="criado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deletado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        db_column="plano_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="autorizacoes",
                        to="seguradora.coverageplan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="inquilino_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="atualizado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Autorização de Procedimento",
                "verbose_name_plural": "Autorizações de Procedimento",
                "db_table": "seguradora_autorizacaoprocedimento",
            },
        ),
        migrations.CreateModel(
            name="TenantCoveragePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(db_column="nome", db_index=True, max_length=120),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=1)),
                (
                    "override_percentage",
                    models.DecimalField(
                        blank=True,
                        db_column="percentual_override",
                        decimal_places=2,
                        help_text="Se vazio, usa o percentual do plan global.",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "active",
                    models.BooleanField(db_column="ativo", db_index=True, default=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="criado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deletado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "global_plan",
                    models.ForeignKey(
                        db_column="plano_global_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides_por_tenant",
                        to="seguradora.coverageplan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="inquilino_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="atualizado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano por Tenant",
                "verbose_name_plural": "Planos por Tenant",
                "db_table": "seguradora_tenantplanocobertura",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "global_plan"), name="uniq_tenant_global_plan"
                    )
                ],
            },
        ),
    ]
