# Generated by Django 4.2.29 on 2026-05-22 18:50

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquilinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoveragePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('order', models.PositiveIntegerField(db_index=True, default=1)),
                ('coverage_percentage', models.DecimalField(db_column='coverage_percentage', decimal_places=2, default=Decimal('0.00'), help_text='Percentual de cobertura (0-100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Percentual de cobertura')),
                ('requires_authorization', models.BooleanField(db_column='requires_authorization', db_index=True, default=False, verbose_name='Requer autorização')),
                ('active', models.BooleanField(db_column='active', db_index=True, default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de Cobertura',
                'verbose_name_plural': 'Planos de Cobertura',
                'db_table': 'seguradora_planocobertura',
            },
        ),
        migrations.CreateModel(
            name='TenantCoveragePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('order', models.PositiveIntegerField(db_index=True, default=1)),
                ('override_percentage', models.DecimalField(blank=True, db_column='override_percentage', decimal_places=2, help_text='Se vazio, usa o percentual do plan global.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Percentual sobrescrito')),
                ('active', models.BooleanField(db_column='active', db_index=True, default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('global_plan', models.ForeignKey(db_column='global_plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='overrides_por_tenant', to='seguradora.coverageplan', verbose_name='Plano global')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano por Tenant',
                'verbose_name_plural': 'Planos por Tenant',
                'db_table': 'seguradora_tenantplanocobertura',
            },
        ),
        migrations.CreateModel(
            name='ProcedureAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=1)),
                ('request_id', models.CharField(db_column='request_id', db_index=True, max_length=60, verbose_name='ID da requisição')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('NEGADA', 'Negada')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Situação')),
                ('authorization_code', models.CharField(blank=True, db_column='authorization_code', db_index=True, max_length=80, null=True, verbose_name='Código de autorização')),
                ('response_date', models.DateTimeField(blank=True, db_column='response_date', null=True, verbose_name='Data da resposta')),
                ('name', models.CharField(blank=True, db_column='name', db_index=True, max_length=120, null=True, verbose_name='Nome')),
                ('active', models.BooleanField(db_column='active', db_index=True, default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes', to='seguradora.coverageplan', verbose_name='Plano')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autorização de Procedimento',
                'verbose_name_plural': 'Autorizações de Procedimento',
                'db_table': 'seguradora_autorizacaoprocedimento',
            },
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('order', models.PositiveIntegerField(db_index=True, default=1)),
                ('external_code', models.CharField(blank=True, db_column='external_code', db_index=True, max_length=60, null=True, verbose_name='Código externo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=30, null=True, verbose_name='Telefone')),
                ('active', models.BooleanField(db_column='active', db_index=True, default=True, verbose_name='Ativa')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguradora',
                'verbose_name_plural': 'Seguradoras',
                'db_table': 'seguradora_seguradora',
            },
        ),
        migrations.AddField(
            model_name='coverageplan',
            name='insurer',
            field=models.ForeignKey(db_column='insurer_id', on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='seguradora.insurer', verbose_name='Seguradora'),
        ),
        migrations.AddField(
            model_name='coverageplan',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='coverageplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='tenantcoverageplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'global_plan'), name='uniq_tenant_global_plan'),
        ),
    ]
