# Generated by Django 4.2.29 on 2026-05-26 05:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguradora', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantcoverageplan',
            options={'verbose_name': 'Plano por Cliente', 'verbose_name_plural': 'Planos por Cliente'},
        ),
        migrations.AlterField(
            model_name='tenantcoverageplan',
            name='override_percentage',
            field=models.DecimalField(blank=True, db_column='override_percentage', decimal_places=2, help_text='Se vazio, usa o percentual do plano global.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Percentual sobrescrito'),
        ),
    ]
