# Generated by Django 4.2.29 on 2026-05-22 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquilinos', '0001_initial'),
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='education_teacher_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='education_student_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='education.course'),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='randomtest',
            name='classroom',
            field=models.ForeignKey(db_column='classroom_id', on_delete=django.db.models.deletion.PROTECT, related_name='random_tests', to='education.classroom'),
        ),
        migrations.AddField(
            model_name='randomtest',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='random_tests', to='education.course'),
        ),
        migrations.AddField(
            model_name='randomtest',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='randomtest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='randomtest',
            name='enrollment',
            field=models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.PROTECT, related_name='random_tests', to='education.enrollment'),
        ),
        migrations.AddField(
            model_name='randomtest',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, related_name='random_tests', to='education.studentprofile'),
        ),
        migrations.AddField(
            model_name='randomtest',
            name='teacher',
            field=models.ForeignKey(blank=True, db_column='teacher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='random_tests', to='education.teacherprofile'),
        ),
        migrations.AddField(
            model_name='randomtest',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='randomtest',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='author',
            field=models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents_authored', to='education.teacherprofile'),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='education.course'),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='assignment_submission',
            field=models.ForeignKey(blank=True, db_column='assignment_submission_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_records', to='education.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='enrollment',
            field=models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='education.enrollment'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='examination_attempt',
            field=models.ForeignKey(blank=True, db_column='examination_attempt_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_records', to='education.examinationattempt'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='teacher',
            field=models.ForeignKey(blank=True, db_column='teacher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_given', to='education.teacherprofile'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='enrollment',
            field=models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.PROTECT, related_name='examination_attempts', to='education.enrollment'),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='examination',
            field=models.ForeignKey(db_column='examination_id', on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='education.examination'),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='graded_by',
            field=models.ForeignKey(blank=True, db_column='graded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_attempts_graded', to='education.teacherprofile'),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, related_name='examination_attempts', to='education.studentprofile'),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examination',
            name='classroom',
            field=models.ForeignKey(blank=True, db_column='classroom_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to='education.classroom'),
        ),
        migrations.AddField(
            model_name='examination',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='education.course'),
        ),
        migrations.AddField(
            model_name='examination',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examination',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examination',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='examination',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='classroom',
            field=models.ForeignKey(db_column='classroom_id', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='education.classroom'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='education.studentprofile'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplineschedulestudentstatus',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplineschedulestudentstatus',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplineschedulestudentstatus',
            name='enrollment',
            field=models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.PROTECT, related_name='discipline_schedule_progress', to='education.enrollment'),
        ),
        migrations.AddField(
            model_name='disciplineschedulestudentstatus',
            name='schedule_item',
            field=models.ForeignKey(db_column='schedule_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='education.disciplinescheduleitem'),
        ),
        migrations.AddField(
            model_name='disciplineschedulestudentstatus',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='disciplineschedulestudentstatus',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinescheduleitem',
            name='classroom',
            field=models.ForeignKey(db_column='classroom_id', on_delete=django.db.models.deletion.PROTECT, related_name='discipline_schedule_items', to='education.classroom'),
        ),
        migrations.AddField(
            model_name='disciplinescheduleitem',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='discipline_schedule_items', to='education.course'),
        ),
        migrations.AddField(
            model_name='disciplinescheduleitem',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinescheduleitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinescheduleitem',
            name='linked_assignment',
            field=models.ForeignKey(blank=True, db_column='linked_assignment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_schedule_items', to='education.assignment'),
        ),
        migrations.AddField(
            model_name='disciplinescheduleitem',
            name='linked_content',
            field=models.ForeignKey(blank=True, db_column='linked_content_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_schedule_items', to='education.learningcontent'),
        ),
        migrations.AddField(
            model_name='disciplinescheduleitem',
            name='linked_examination',
            field=models.ForeignKey(blank=True, db_column='linked_examination_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_schedule_items', to='education.examination'),
        ),
        migrations.AddField(
            model_name='disciplinescheduleitem',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='disciplinescheduleitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='education.course'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, db_column='homeroom_teacher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classrooms', to='education.teacherprofile'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='enrollment',
            field=models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='education.enrollment'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='education.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='enrollment',
            field=models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.PROTECT, related_name='assignment_submissions', to='education.enrollment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, db_column='graded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions_graded', to='education.teacherprofile'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, related_name='assignment_submissions', to='education.studentprofile'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(blank=True, db_column='classroom_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='education.classroom'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='education.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(blank=True, db_column='teacher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to='education.teacherprofile'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['tenant', 'status'], name='education_t_tenant__8740b9_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['tenant', 'teacher_code'], name='education_t_tenant__32ce33_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='education_teacher_tenant_user_uniq'),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'teacher_code'), name='education_teacher_tenant_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['tenant', 'status'], name='education_s_tenant__d787b4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['tenant', 'student_code'], name='education_s_tenant__f7d572_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='education_student_tenant_user_uniq'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'student_code'), name='education_student_tenant_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['tenant', 'status'], name='education_s_tenant__99c388_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['tenant', 'course'], name='education_s_tenant__10f15f_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['tenant', 'code'], name='education_s_tenant__51233c_idx'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('tenant', 'course', 'code'), name='education_skill_tenant_course_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('tenant', 'course', 'name'), name='education_skill_tenant_course_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='randomtest',
            index=models.Index(fields=['tenant', 'status'], name='education_r_tenant__48a4dd_idx'),
        ),
        migrations.AddIndex(
            model_name='randomtest',
            index=models.Index(fields=['tenant', 'classroom'], name='education_r_tenant__c3ae26_idx'),
        ),
        migrations.AddIndex(
            model_name='randomtest',
            index=models.Index(fields=['tenant', 'student'], name='education_r_tenant__6269e5_idx'),
        ),
        migrations.AddIndex(
            model_name='randomtest',
            index=models.Index(fields=['tenant', 'teacher'], name='education_r_tenant__31bdbe_idx'),
        ),
        migrations.AddIndex(
            model_name='randomtest',
            index=models.Index(fields=['tenant', 'scheduled_for'], name='education_r_tenant__2e3b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='randomtest',
            index=models.Index(fields=['tenant', 'opens_at'], name='education_r_tenant__82b7dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='randomtest',
            constraint=models.UniqueConstraint(fields=('tenant', 'enrollment', 'opens_at'), name='education_random_test_tenant_enrollment_open_uniq'),
        ),
        migrations.AddIndex(
            model_name='learningcontent',
            index=models.Index(fields=['tenant', 'content_type'], name='education_l_tenant__079fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='learningcontent',
            index=models.Index(fields=['tenant', 'published'], name='education_l_tenant__799074_idx'),
        ),
        migrations.AddIndex(
            model_name='graderecord',
            index=models.Index(fields=['tenant', 'published_at'], name='education_g_tenant__c503d2_idx'),
        ),
        migrations.AddIndex(
            model_name='graderecord',
            index=models.Index(fields=['tenant', 'component'], name='education_g_tenant__1b7804_idx'),
        ),
        migrations.AddConstraint(
            model_name='graderecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'enrollment', 'component'), name='education_grade_unique_component_per_enrollment'),
        ),
        migrations.AddIndex(
            model_name='examinationattempt',
            index=models.Index(fields=['tenant', 'status'], name='education_e_tenant__b31ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationattempt',
            index=models.Index(fields=['tenant', 'started_at'], name='education_e_tenant__e193f0_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationattempt',
            index=models.Index(fields=['tenant', 'expires_at'], name='education_e_tenant__7fab04_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationattempt',
            index=models.Index(fields=['tenant', 'examination'], name='education_e_tenant__354b20_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationattempt',
            index=models.Index(fields=['tenant', 'student'], name='education_e_tenant__f335da_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationattempt',
            index=models.Index(fields=['tenant', 'attempt_number'], name='education_e_tenant__6d5850_idx'),
        ),
        migrations.AddConstraint(
            model_name='examinationattempt',
            constraint=models.UniqueConstraint(fields=('tenant', 'examination', 'student', 'attempt_number'), name='education_exam_attempt_tenant_exam_student_attempt_uniq'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['tenant', 'scheduled_for'], name='education_e_tenant__e4f8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['tenant', 'opens_at'], name='education_e_tenant__8cf11e_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['tenant', 'closes_at'], name='education_e_tenant__b1b760_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['tenant', 'status'], name='education_e_tenant__29597e_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['tenant', 'course'], name='education_e_tenant__01de2a_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['tenant', 'exam_type'], name='education_e_tenant__3f2206_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['tenant', 'status'], name='education_e_tenant__a10fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['tenant', 'enrolled_on'], name='education_e_tenant__4627a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('tenant', 'student', 'classroom'), name='education_enrollment_tenant_student_classroom_uniq'),
        ),
        migrations.AddIndex(
            model_name='disciplineschedulestudentstatus',
            index=models.Index(fields=['tenant', 'status'], name='education_d_tenant__4d43ae_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplineschedulestudentstatus',
            index=models.Index(fields=['tenant', 'schedule_item'], name='education_d_tenant__3c890b_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplineschedulestudentstatus',
            index=models.Index(fields=['tenant', 'enrollment'], name='education_d_tenant__a12585_idx'),
        ),
        migrations.AddConstraint(
            model_name='disciplineschedulestudentstatus',
            constraint=models.UniqueConstraint(fields=('tenant', 'schedule_item', 'enrollment'), name='education_schedule_student_status_tenant_item_enrollment_uniq'),
        ),
        migrations.AddIndex(
            model_name='disciplinescheduleitem',
            index=models.Index(fields=['tenant', 'status'], name='education_d_tenant__8584bf_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinescheduleitem',
            index=models.Index(fields=['tenant', 'scheduled_date'], name='education_d_tenant__4ac611_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinescheduleitem',
            index=models.Index(fields=['tenant', 'course'], name='education_d_tenant__8a61a6_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinescheduleitem',
            index=models.Index(fields=['tenant', 'classroom'], name='education_d_tenant__28ed4b_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinescheduleitem',
            index=models.Index(fields=['tenant', 'item_type'], name='education_d_tenant__0aaa8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='disciplinescheduleitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'classroom', 'item_type', 'title', 'scheduled_date'), name='education_schedule_item_tenant_classroom_type_title_date_uniq'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['tenant', 'status'], name='education_c_tenant__f27e33_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['tenant', 'code'], name='education_c_tenant__5713ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='education_course_tenant_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='education_course_tenant_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['tenant', 'academic_year'], name='education_c_tenant__8666ff_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['tenant', 'course'], name='education_c_tenant__142ea9_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('tenant', 'course', 'name', 'academic_year'), name='education_classroom_unique_name_per_year'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['tenant', 'attendance_date'], name='education_a_tenant__db595c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['tenant', 'status'], name='education_a_tenant__d82777_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'enrollment', 'attendance_date'), name='education_attendance_unique_day_per_enrollment'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['tenant', 'status'], name='education_a_tenant__f54fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['tenant', 'submitted_at'], name='education_a_tenant__d1b9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['tenant', 'assignment'], name='education_a_tenant__b853e9_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['tenant', 'student'], name='education_a_tenant__7725e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('tenant', 'assignment', 'student', 'attempt_number'), name='education_assignment_submission_tenant_assignment_student_attempt_uniq'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'status'], name='education_a_tenant__ea5d36_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'due_at'], name='education_a_tenant__53bb09_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'work_category'], name='education_a_tenant__8b0700_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'course'], name='education_a_tenant__89e7d3_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'classroom'], name='education_a_tenant__a0af57_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'classroom', 'title', 'due_at'), name='education_assignment_tenant_classroom_title_due_uniq'),
        ),
    ]
