# Generated by Django 4.2.29 on 2026-05-21 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('code', models.CharField(db_column='code', max_length=32)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical'), ('COGNITIVE', 'Cognitive'), ('SOCIOEMOTIONAL', 'Socioemotional'), ('LANGUAGE', 'Language')], db_column='category', default='TECHNICAL', max_length=24)),
                ('level', models.CharField(choices=[('FOUNDATION', 'Foundation'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], db_column='level', default='FOUNDATION', max_length=24)),
                ('description', models.TextField(blank=True, db_column='description', default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_column='status', default='ACTIVE', max_length=16)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='education.course')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'education_skill',
                'ordering': ['name', 'created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='education_s_tenant__99c388_idx'), models.Index(fields=['tenant', 'course'], name='education_s_tenant__10f15f_idx'), models.Index(fields=['tenant', 'code'], name='education_s_tenant__51233c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('tenant', 'course', 'code'), name='education_skill_tenant_course_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('tenant', 'course', 'name'), name='education_skill_tenant_course_name_uniq'),
        ),
    ]
