# Generated by Django 4.2.29 on 2026-05-22 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0001_initial'),
        ('education', '0002_skill_skill_education_skill_tenant_course_code_uniq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('title', models.CharField(db_column='title', max_length=180)),
                ('instructions', models.TextField(blank=True, db_column='instructions', default='')),
                ('opens_at', models.DateTimeField(blank=True, db_column='opens_at', null=True)),
                ('due_at', models.DateTimeField(db_column='due_at')),
                ('max_score', models.DecimalField(db_column='max_score', decimal_places=2, default=20, max_digits=6)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], db_column='status', default='DRAFT', max_length=16)),
                ('allow_late_submission', models.BooleanField(db_column='allow_late_submission', default=False)),
                ('allow_multiple_submissions', models.BooleanField(db_column='allow_multiple_submissions', default=False)),
                ('max_submissions', models.PositiveIntegerField(db_column='max_submissions', default=1)),
                ('published_at', models.DateTimeField(blank=True, db_column='published_at', null=True)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'education_assignment',
                'ordering': ['due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('attempt_number', models.PositiveIntegerField(db_column='attempt_number', default=1)),
                ('submitted_at', models.DateTimeField(db_column='submitted_at', default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('LATE', 'Late'), ('GRADED', 'Graded')], db_column='status', default='SUBMITTED', max_length=16)),
                ('content_text', models.TextField(blank=True, db_column='content_text', default='')),
                ('attachment_url', models.URLField(blank=True, db_column='attachment_url', default='')),
                ('max_score_snapshot', models.DecimalField(db_column='max_score_snapshot', decimal_places=2, default=20, max_digits=6)),
                ('score', models.DecimalField(blank=True, db_column='score', decimal_places=2, max_digits=6, null=True)),
                ('teacher_feedback', models.TextField(blank=True, db_column='teacher_feedback', default='')),
                ('graded_at', models.DateTimeField(blank=True, db_column='graded_at', null=True)),
            ],
            options={
                'verbose_name': 'Assignment submission',
                'verbose_name_plural': 'Assignment submissions',
                'db_table': 'education_assignment_submission',
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('status', models.CharField(choices=[('OPENED', 'Opened'), ('SUBMITTED', 'Submitted'), ('EXPIRED', 'Expired')], db_column='status', default='OPENED', max_length=16)),
                ('started_at', models.DateTimeField(db_column='started_at', default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_column='expires_at')),
                ('submitted_at', models.DateTimeField(blank=True, db_column='submitted_at', null=True)),
                ('time_limit_minutes_snapshot', models.PositiveIntegerField(db_column='time_limit_minutes_snapshot', default=90)),
                ('max_score_snapshot', models.DecimalField(db_column='max_score_snapshot', decimal_places=2, default=20, max_digits=6)),
                ('submission_payload', models.TextField(blank=True, db_column='submission_payload', default='')),
                ('score', models.DecimalField(blank=True, db_column='score', decimal_places=2, max_digits=6, null=True)),
                ('teacher_feedback', models.TextField(blank=True, db_column='teacher_feedback', default='')),
                ('graded_at', models.DateTimeField(blank=True, db_column='graded_at', null=True)),
            ],
            options={
                'verbose_name': 'Examination attempt',
                'verbose_name_plural': 'Examination attempts',
                'db_table': 'education_examination_attempt',
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='examination',
            options={'ordering': ['-opens_at', '-scheduled_for', '-created_at'], 'verbose_name': 'Examination', 'verbose_name_plural': 'Examinations'},
        ),
        migrations.AddField(
            model_name='examination',
            name='closes_at',
            field=models.DateTimeField(blank=True, db_column='closes_at', null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='duration_minutes',
            field=models.PositiveIntegerField(db_column='duration_minutes', default=90),
        ),
        migrations.AddField(
            model_name='examination',
            name='max_attempts',
            field=models.PositiveIntegerField(db_column='max_attempts', default=1),
        ),
        migrations.AddField(
            model_name='examination',
            name='opens_at',
            field=models.DateTimeField(blank=True, db_column='opens_at', null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='published_at',
            field=models.DateTimeField(blank=True, db_column='published_at', null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], db_column='status', default='DRAFT', max_length=16),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['tenant', 'opens_at'], name='education_e_tenant__8cf11e_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['tenant', 'closes_at'], name='education_e_tenant__b1b760_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['tenant', 'status'], name='education_e_tenant__29597e_idx'),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='enrollment',
            field=models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.PROTECT, related_name='examination_attempts', to='education.enrollment'),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='examination',
            field=models.ForeignKey(db_column='examination_id', on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='education.examination'),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='graded_by',
            field=models.ForeignKey(blank=True, db_column='graded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_attempts_graded', to='education.teacherprofile'),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, related_name='examination_attempts', to='education.studentprofile'),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='education.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='enrollment',
            field=models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.PROTECT, related_name='assignment_submissions', to='education.enrollment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, db_column='graded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions_graded', to='education.teacherprofile'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, related_name='assignment_submissions', to='education.studentprofile'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(blank=True, db_column='classroom_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='education.classroom'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='education.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(blank=True, db_column='teacher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to='education.teacherprofile'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='assignment_submission',
            field=models.ForeignKey(blank=True, db_column='assignment_submission_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_records', to='education.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='examination_attempt',
            field=models.ForeignKey(blank=True, db_column='examination_attempt_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_records', to='education.examinationattempt'),
        ),
        migrations.AddIndex(
            model_name='examinationattempt',
            index=models.Index(fields=['tenant', 'status'], name='education_e_tenant__b31ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationattempt',
            index=models.Index(fields=['tenant', 'started_at'], name='education_e_tenant__e193f0_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationattempt',
            index=models.Index(fields=['tenant', 'expires_at'], name='education_e_tenant__7fab04_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationattempt',
            index=models.Index(fields=['tenant', 'examination'], name='education_e_tenant__354b20_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationattempt',
            index=models.Index(fields=['tenant', 'student'], name='education_e_tenant__f335da_idx'),
        ),
        migrations.AddConstraint(
            model_name='examinationattempt',
            constraint=models.UniqueConstraint(fields=('tenant', 'examination', 'student'), name='education_exam_attempt_tenant_exam_student_uniq'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['tenant', 'status'], name='education_a_tenant__f54fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['tenant', 'submitted_at'], name='education_a_tenant__d1b9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['tenant', 'assignment'], name='education_a_tenant__b853e9_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['tenant', 'student'], name='education_a_tenant__7725e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('tenant', 'assignment', 'student', 'attempt_number'), name='education_assignment_submission_tenant_assignment_student_attempt_uniq'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'status'], name='education_a_tenant__ea5d36_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'due_at'], name='education_a_tenant__53bb09_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'course'], name='education_a_tenant__89e7d3_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'classroom'], name='education_a_tenant__a0af57_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'classroom', 'title', 'due_at'), name='education_assignment_tenant_classroom_title_due_uniq'),
        ),
    ]
