# Generated by Django 4.2.29 on 2026-05-25 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['due_at', '-created_at'], 'verbose_name': 'Trabalho', 'verbose_name_plural': 'Trabalhos'},
        ),
        migrations.AlterModelOptions(
            name='assignmentsubmission',
            options={'ordering': ['-submitted_at', '-created_at'], 'verbose_name': 'Submissão de Trabalho', 'verbose_name_plural': 'Submissões de Trabalho'},
        ),
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-attendance_date', '-created_at'], 'verbose_name': 'Presença', 'verbose_name_plural': 'Presenças'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['academic_year', 'name'], 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name', 'created_at'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='disciplinescheduleitem',
            options={'ordering': ['scheduled_date', 'item_type', 'created_at'], 'verbose_name': 'Item do Cronograma da Disciplina', 'verbose_name_plural': 'Itens do Cronograma da Disciplina'},
        ),
        migrations.AlterModelOptions(
            name='disciplineschedulestudentstatus',
            options={'ordering': ['schedule_item__scheduled_date', 'enrollment_id', 'created_at'], 'verbose_name': 'Estado do Estudante no Cronograma', 'verbose_name_plural': 'Estados dos Estudantes no Cronograma'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_on', '-created_at'], 'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='examination',
            options={'ordering': ['-opens_at', '-scheduled_for', '-created_at'], 'verbose_name': 'Exame', 'verbose_name_plural': 'Exames'},
        ),
        migrations.AlterModelOptions(
            name='examinationattempt',
            options={'ordering': ['-started_at', '-created_at'], 'verbose_name': 'Tentativa de Exame', 'verbose_name_plural': 'Tentativas de Exame'},
        ),
        migrations.AlterModelOptions(
            name='graderecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterModelOptions(
            name='learningcontent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Conteúdo de Aprendizagem', 'verbose_name_plural': 'Conteúdos de Aprendizagem'},
        ),
        migrations.AlterModelOptions(
            name='randomtest',
            options={'ordering': ['-opens_at', '-scheduled_for', '-created_at'], 'verbose_name': 'Teste Aleatório', 'verbose_name_plural': 'Testes Aleatórios'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name', 'created_at'], 'verbose_name': 'Competência', 'verbose_name_plural': 'Competências'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['student_code', 'created_at'], 'verbose_name': 'Estudante', 'verbose_name_plural': 'Estudantes'},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'ordering': ['teacher_code', 'created_at'], 'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
    ]
