# Generated by Django 4.2.29 on 2026-05-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_assignment_assignmentsubmission_examinationattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='work_category',
            field=models.CharField(choices=[('MANDATORY', 'Mandatory'), ('HYGIENIC', 'Hygienic'), ('OPTIONAL', 'Optional')], db_column='work_category', default='MANDATORY', max_length=16),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'work_category'], name='education_a_tenant__8b0700_idx'),
        ),
    ]
