# Generated by Django 4.2.29 on 2026-05-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_learningcontent_content_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examinationattempt',
            name='education_exam_attempt_tenant_exam_student_uniq',
        ),
        migrations.AddField(
            model_name='examination',
            name='discipline_final_stage',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('RECORRENCIA', 'Recorrencia'), ('ESPECIAL', 'Especial')], db_column='discipline_final_stage', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='exam_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('TEST', 'Test'), ('DISCIPLINE_FINAL', 'Discipline final'), ('COURSE_FINAL', 'Course final')], db_column='exam_type', default='REGULAR', max_length=24),
        ),
        migrations.AddField(
            model_name='examination',
            name='pass_mark',
            field=models.DecimalField(db_column='pass_mark', decimal_places=2, default=10, max_digits=6),
        ),
        migrations.AddField(
            model_name='examination',
            name='test_slot',
            field=models.PositiveSmallIntegerField(blank=True, db_column='test_slot', null=True),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(db_column='attempt_number', default=1),
        ),
        migrations.AddField(
            model_name='examinationattempt',
            name='requires_year_repeat',
            field=models.BooleanField(db_column='requires_year_repeat', default=False),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['tenant', 'exam_type'], name='education_e_tenant__3f2206_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationattempt',
            index=models.Index(fields=['tenant', 'attempt_number'], name='education_e_tenant__6d5850_idx'),
        ),
        migrations.AddConstraint(
            model_name='examinationattempt',
            constraint=models.UniqueConstraint(fields=('tenant', 'examination', 'student', 'attempt_number'), name='education_exam_attempt_tenant_exam_student_attempt_uniq'),
        ),
    ]
