# Generated by Django 4.2.29 on 2026-05-22 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0001_initial'),
        ('education', '0007_remove_examinationattempt_education_exam_attempt_tenant_exam_student_uniq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('item_type', models.CharField(choices=[('TEST', 'Test'), ('ASSIGNMENT', 'Assignment'), ('THEME', 'Theme'), ('EXERCISE', 'Exercise')], db_column='item_type', default='THEME', max_length=16)),
                ('title', models.CharField(db_column='title', max_length=180)),
                ('description', models.TextField(blank=True, db_column='description', default='')),
                ('scheduled_date', models.DateField(db_column='scheduled_date')),
                ('requires_attendance', models.BooleanField(db_column='requires_attendance', default=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], db_column='status', default='PLANNED', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, db_column='completed_at', null=True)),
                ('notes', models.CharField(blank=True, db_column='notes', default='', max_length=255)),
                ('classroom', models.ForeignKey(db_column='classroom_id', on_delete=django.db.models.deletion.PROTECT, related_name='discipline_schedule_items', to='education.classroom')),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='discipline_schedule_items', to='education.course')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('linked_assignment', models.ForeignKey(blank=True, db_column='linked_assignment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_schedule_items', to='education.assignment')),
                ('linked_content', models.ForeignKey(blank=True, db_column='linked_content_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_schedule_items', to='education.learningcontent')),
                ('linked_examination', models.ForeignKey(blank=True, db_column='linked_examination_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_schedule_items', to='education.examination')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discipline schedule item',
                'verbose_name_plural': 'Discipline schedule items',
                'db_table': 'education_discipline_schedule_item',
                'ordering': ['scheduled_date', 'item_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineScheduleStudentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('OVERDUE', 'Overdue')], db_column='status', default='PENDING', max_length=16)),
                ('completion_marked', models.BooleanField(db_column='completion_marked', default=False)),
                ('completed_at', models.DateTimeField(blank=True, db_column='completed_at', null=True)),
                ('attendance_status_snapshot', models.CharField(blank=True, db_column='attendance_status_snapshot', default='', max_length=16)),
                ('notes', models.CharField(blank=True, db_column='notes', default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.PROTECT, related_name='discipline_schedule_progress', to='education.enrollment')),
                ('schedule_item', models.ForeignKey(db_column='schedule_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='education.disciplinescheduleitem')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discipline schedule student status',
                'verbose_name_plural': 'Discipline schedule student statuses',
                'db_table': 'education_discipline_schedule_student_status',
                'ordering': ['schedule_item__scheduled_date', 'enrollment_id', 'created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='education_d_tenant__4d43ae_idx'), models.Index(fields=['tenant', 'schedule_item'], name='education_d_tenant__3c890b_idx'), models.Index(fields=['tenant', 'enrollment'], name='education_d_tenant__a12585_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='disciplineschedulestudentstatus',
            constraint=models.UniqueConstraint(fields=('tenant', 'schedule_item', 'enrollment'), name='education_schedule_student_status_tenant_item_enrollment_uniq'),
        ),
        migrations.AddIndex(
            model_name='disciplinescheduleitem',
            index=models.Index(fields=['tenant', 'status'], name='education_d_tenant__8584bf_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinescheduleitem',
            index=models.Index(fields=['tenant', 'scheduled_date'], name='education_d_tenant__4ac611_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinescheduleitem',
            index=models.Index(fields=['tenant', 'course'], name='education_d_tenant__8a61a6_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinescheduleitem',
            index=models.Index(fields=['tenant', 'classroom'], name='education_d_tenant__28ed4b_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinescheduleitem',
            index=models.Index(fields=['tenant', 'item_type'], name='education_d_tenant__0aaa8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='disciplinescheduleitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'classroom', 'item_type', 'title', 'scheduled_date'), name='education_schedule_item_tenant_classroom_type_title_date_uniq'),
        ),
    ]
