# Generated by Django 4.2.29 on 2026-05-22 18:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('type', models.CharField(choices=[('ENT', 'Entrada'), ('SAI', 'Saída'), ('AJU', 'Ajuste')], db_column='type', db_index=True, max_length=3, verbose_name='Tipo')),
                ('origin', models.CharField(choices=[('VEND', 'Venda'), ('PROC', 'Procedimento'), ('AJUS', 'Ajuste'), ('REQ', 'Requisição')], db_column='origin', db_index=True, default='AJUS', max_length=4, verbose_name='Origem')),
                ('quantity', models.PositiveIntegerField(db_column='quantity', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Movimento de estoque',
                'verbose_name_plural': 'Movimentos de estoque',
                'db_table': 'farmacia_movimentoestoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('lot_number', models.CharField(db_column='lot_number', db_index=True, max_length=100, verbose_name='Número do lote')),
                ('expiration_date', models.DateField(db_column='expiration_date', db_index=True, verbose_name='Validade')),
                ('initial_quantity', models.PositiveIntegerField(db_column='initial_quantity', help_text='Quantidade inicial do lote.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade inicial')),
                ('sale_price', models.DecimalField(db_column='sale_price', decimal_places=2, default=Decimal('0.00'), help_text='Preço de venda para itens deste lote.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço unitário')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'farmacia_lote',
                'ordering': ['expiration_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('sector', models.CharField(choices=[('LAB', 'Laboratório'), ('ENF', 'Enfermagem'), ('REC', 'Recepção'), ('MED', 'Medicina'), ('MOC', 'Medicina Ocupacional'), ('OUT', 'Outros setores')], db_column='sector', db_index=True, max_length=3, verbose_name='Setor solicitante')),
                ('requested_by_department', models.CharField(blank=True, db_column='requested_by_department', default='', help_text='Departamento do utilizador no momento da requisição.', max_length=120, verbose_name='Departamento (snapshot)')),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('PAR', 'Parcialmente aviada'), ('FUL', 'Aviada'), ('HLD', 'Arquivada (aguarda estoque)')], db_column='status', db_index=True, default='PEN', max_length=3, verbose_name='Estado')),
                ('hold_reason', models.TextField(blank=True, db_column='hold_reason', default=None, null=True, verbose_name='Motivo do arquivamento')),
                ('fulfilled_at', models.DateTimeField(blank=True, db_column='fulfilled_at', db_index=True, default=None, null=True, verbose_name='Aviada em')),
                ('on_hold_at', models.DateTimeField(blank=True, db_column='on_hold_at', db_index=True, default=None, null=True, verbose_name='Arquivada em')),
            ],
            options={
                'verbose_name': 'Requisição de material',
                'verbose_name_plural': 'Requisições de material',
                'db_table': 'farmacia_requisicaomaterial',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('requested_quantity', models.PositiveIntegerField(db_column='requested_quantity', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade solicitada')),
                ('supplied_quantity', models.PositiveIntegerField(db_column='supplied_quantity', default=0, verbose_name='Quantidade aviada')),
                ('notes', models.TextField(blank=True, db_column='notes', default=None, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Item da requisição de material',
                'verbose_name_plural': 'Itens de requisição de material',
                'db_table': 'farmacia_requisicaomaterialitem',
                'ordering': ['requisition', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('description', models.TextField(blank=True, db_column='description', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria Pai',
                'verbose_name_plural': 'Categorias Pai',
                'db_table': 'farmacia_categoriapai',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('type', models.CharField(choices=[('MED', 'Medicamento'), ('MAT', 'Material'), ('OUT', 'Outro')], db_column='type', db_index=True, default='OUT', max_length=3, verbose_name='Tipo')),
                ('sale_price', models.DecimalField(db_column='sale_price', decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço de Venda')),
                ('vat_percentage', models.DecimalField(db_column='vat_percentage', decimal_places=2, default=Decimal('16.00'), help_text='Taxa de IVA aplicada ao produto (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)')),
                ('applies_vat_by_default', models.BooleanField(db_column='applies_vat_by_default', default=True, help_text='Desmarque se este produto normalmente não deve ter IVA.', verbose_name='Aplicar IVA por padrão')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'farmacia_produto',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('description', models.TextField(blank=True, db_column='description', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produto',
                'db_table': 'farmacia_categoriaproduto',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('number', models.CharField(db_column='number', db_index=True, max_length=40, verbose_name='Número')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'db_table': 'farmacia_venda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('quantity', models.PositiveIntegerField(db_column='quantity', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(blank=True, db_column='unit_price', decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço unitário')),
            ],
            options={
                'verbose_name': 'Item de Venda',
                'verbose_name_plural': 'Itens de Venda',
                'db_table': 'farmacia_itemvenda',
                'ordering': ['sale', 'position', 'id'],
            },
        ),
    ]
