# Generated by Django 4.2.16 on 2026-03-28 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmacia', '0001_initial'),
        ('clinical', '0002_initial'),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='farmacia.product', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(db_column='sale_id', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='farmacia.sale', verbose_name='Venda'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='patient',
            field=models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_farmacia', to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, db_column='parent_category_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='farmacia.parentcategory', verbose_name='Categoria pai'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='farmacia.productcategory', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lot',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lot',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lot',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='farmacia.product', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='lot',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='lot',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='lot',
            field=models.ForeignKey(db_column='lot_id', on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='farmacia.lot', verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='sale_item',
            field=models.ForeignKey(blank=True, db_column='sale_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='farmacia.saleitem', verbose_name='Item de aquisição'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale'], name='farmacia_it_sale_id_dbc721_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product'], name='farmacia_it_product_e81dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product'], name='farmacia_it_sale_id_0d0d42_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('sale', 'product'), name='unique_product_por_sale'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'number'], name='farmacia_ve_tenant__556dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'patient'], name='farmacia_ve_tenant__aebd3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('tenant', 'number'), name='unique_number_sale_por_tenant'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['tenant', 'name'], name='farmacia_ca_tenant__bcc9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['parent_category'], name='farmacia_ca_parent__9bd30a_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('tenant', 'name'), name='unique_category_product_por_tenant'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'name'], name='farmacia_pr_tenant__2aaec9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='farmacia_pr_categor_b20c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['type'], name='farmacia_pr_type_98638a_idx'),
        ),
        migrations.AddIndex(
            model_name='parentcategory',
            index=models.Index(fields=['deleted'], name='farmacia_ca_deleted_f9118c_idx'),
        ),
        migrations.AddIndex(
            model_name='parentcategory',
            index=models.Index(fields=['version'], name='farmacia_ca_version_1fbd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='parentcategory',
            index=models.Index(fields=['tenant', 'name'], name='farmacia_ca_tenant__b288fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='parentcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('tenant', 'name'), name='unique_parent_category_por_tenant'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['product', 'expiration_date'], name='farmacia_lo_product_3bbff3_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['expiration_date'], name='farmacia_lo_expirat_e593be_idx'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('product', 'lot_number'), name='unique_lot_product'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['lot', 'created_at'], name='farmacia_mo_lot_id_03def7_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['type'], name='farmacia_mo_type_45aa5e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['origin'], name='farmacia_mo_origin_ddff1d_idx'),
        ),
    ]
