# Generated by Django 5.1 on 2026-03-26 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0002_initial"),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "name",
                    models.CharField(db_column="name", db_index=True, max_length=120),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_column="description", verbose_name="Descrição"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria Pai",
                "verbose_name_plural": "Categorias Pai",
                "db_table": "farmacia_categoriapai",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_category_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcategorias",
                to="farmacia.parentcategory",
                verbose_name="Categoria pai",
            ),
        ),
        migrations.AddIndex(
            model_name="parentcategory",
            index=models.Index(
                fields=["deleted"], name="farmacia_ca_deleted_f9118c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parentcategory",
            index=models.Index(
                fields=["version"], name="farmacia_ca_version_1fbd4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parentcategory",
            index=models.Index(
                fields=["tenant", "name"], name="farmacia_ca_tenant__b288fb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="parentcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("tenant", "name"),
                name="unique_parent_category_por_tenant",
            ),
        ),
    ]
