# Generated by Django 5.1 on 2026-03-26 05:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventorymovement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Movimento de estoque",
                "verbose_name_plural": "Movimentos de estoque",
            },
        ),
        migrations.AlterModelOptions(
            name="lot",
            options={
                "ordering": ["expiration_date"],
                "verbose_name": "Lote",
                "verbose_name_plural": "Lotes",
            },
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Categoria de Produto",
                "verbose_name_plural": "Categorias de Produto",
            },
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="lot",
            field=models.ForeignKey(
                db_column="lot_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimentos",
                to="farmacia.lot",
                verbose_name="Lote",
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="origin",
            field=models.CharField(
                choices=[
                    ("VEND", "Venda"),
                    ("PROC", "Procedimento"),
                    ("AJUS", "Ajuste"),
                ],
                db_column="origin",
                db_index=True,
                default="AJUS",
                max_length=4,
                verbose_name="Origem",
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="quantity",
            field=models.PositiveIntegerField(
                db_column="quantity",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Quantidade",
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="sale_item",
            field=models.ForeignKey(
                blank=True,
                db_column="sale_item_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentos",
                to="farmacia.saleitem",
                verbose_name="Item de venda",
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="type",
            field=models.CharField(
                choices=[("ENT", "Entrada"), ("SAI", "Saída"), ("AJU", "Ajuste")],
                db_column="type",
                db_index=True,
                max_length=3,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="expiration_date",
            field=models.DateField(
                db_column="expiration_date", db_index=True, verbose_name="Validade"
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="initial_quantity",
            field=models.PositiveIntegerField(
                db_column="initial_quantity",
                help_text="Quantidade inicial do lot.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Quantidade inicial",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="lot_number",
            field=models.CharField(
                db_column="lot_number",
                db_index=True,
                max_length=100,
                verbose_name="Número do lote",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="product",
            field=models.ForeignKey(
                db_column="product_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lotes",
                to="farmacia.product",
                verbose_name="Produto",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="description",
            field=models.TextField(
                blank=True, db_column="description", verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_category_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcategorias",
                to="farmacia.productcategory",
                verbose_name="Categoria pai",
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="product",
            field=models.ForeignKey(
                db_column="product_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="farmacia.product",
                verbose_name="Produto",
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="quantity",
            field=models.PositiveIntegerField(
                db_column="quantity",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Quantidade",
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="sale",
            field=models.ForeignKey(
                db_column="sale_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="farmacia.sale",
                verbose_name="Venda",
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                db_column="unit_price",
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Preço unitário",
            ),
        ),
    ]
