# Generated by Django 5.1 on 2026-03-26 21:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmacia",
            "0003_parentcategory_alter_productcategory_parent_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="saleitem",
            options={
                "verbose_name": "Item de Venda",
                "verbose_name_plural": "Itens de Venda",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(
                db_column="sale_price",
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Preço de Venda",
            ),
        ),
    ]
