# Generated by Django 5.1 on 2026-03-26 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0004_alter_saleitem_options_alter_product_sale_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymovement",
            name="sale_item",
            field=models.ForeignKey(
                blank=True,
                db_column="sale_item_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentos",
                to="farmacia.saleitem",
                verbose_name="Item de aquisição",
            ),
        ),
    ]
