# Generated by Django 6.0.5 on 2026-07-18 08:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def forwards_update_existing_vat(apps, schema_editor):
    model = apps.get_model("farmacia", "Product")
    model.objects.filter(vat_percentage=Decimal("16.00")).update(vat_percentage=Decimal("5.00"))


def reverse_update_existing_vat(apps, schema_editor):
    model = apps.get_model("farmacia", "Product")
    model.objects.filter(vat_percentage=Decimal("5.00")).update(vat_percentage=Decimal("16.00"))


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0005_lot_status_lot_status_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat_percentage',
            field=models.DecimalField(db_column='vat_percentage', decimal_places=2, default=Decimal('5.00'), help_text='Taxa de IVA aplicada ao produto (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)'),
        ),
        migrations.RunPython(forwards_update_existing_vat, reverse_update_existing_vat),
    ]
