# Generated by Django 4.2.29 on 2026-04-13 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_alter_lot_initial_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, db_column='parent_category_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='farmacia.parentcategory', verbose_name='Categoria Base'),
        ),
    ]
