# Generated by Django 5.2.12 on 2026-04-20 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0008_alter_productcategory_parent_category"),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="parentcategory",
            name="unique_parent_category_por_tenant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("tenant", "name"),
                name="unique_parent_category_por_tenant",
                violation_error_message="Ja existe uma Categoria Pai com este nome neste tenant.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="productcategory",
            name="unique_category_product_por_tenant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("tenant", "name"),
                name="unique_category_product_por_tenant",
                violation_error_message="Ja existe uma Categoria de Produto com este nome neste tenant.",
            ),
        ),
    ]
