# Generated by Django 5.2.12 on 2026-04-21 23:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmacia",
            "0009_alter_parentcategory_unique_parent_category_por_tenant_and_more",
        ),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymovement",
            name="origin",
            field=models.CharField(
                choices=[
                    ("VEND", "Venda"),
                    ("PROC", "Procedimento"),
                    ("AJUS", "Ajuste"),
                    ("REQ", "Requisição"),
                ],
                db_column="origin",
                db_index=True,
                default="AJUS",
                max_length=4,
                verbose_name="Origem",
            ),
        ),
        migrations.CreateModel(
            name="MaterialRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("LAB", "Laboratório"),
                            ("ENF", "Enfermagem"),
                            ("REC", "Recepção"),
                        ],
                        db_column="sector",
                        db_index=True,
                        max_length=3,
                        verbose_name="Setor solicitante",
                    ),
                ),
                (
                    "requested_by_department",
                    models.CharField(
                        blank=True,
                        db_column="requested_by_department",
                        default="",
                        help_text="Departamento do utilizador no momento da requisição.",
                        max_length=120,
                        verbose_name="Departamento (snapshot)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendente"),
                            ("PAR", "Parcialmente aviada"),
                            ("FUL", "Aviada"),
                            ("HLD", "Arquivada (aguarda estoque)"),
                        ],
                        db_column="status",
                        db_index=True,
                        default="PEN",
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "hold_reason",
                    models.TextField(
                        blank=True,
                        db_column="hold_reason",
                        default=None,
                        null=True,
                        verbose_name="Motivo do arquivamento",
                    ),
                ),
                (
                    "fulfilled_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="fulfilled_at",
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Aviada em",
                    ),
                ),
                (
                    "on_hold_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="on_hold_at",
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Arquivada em",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fulfilled_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="fulfilled_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materialrequisicao_aviada",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aviada por",
                    ),
                ),
                (
                    "on_hold_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="on_hold_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materialrequisicao_arquivada",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Arquivada por",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisição de material",
                "verbose_name_plural": "Requisições de material",
                "db_table": "farmacia_requisicaomaterial",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialRequisitionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "requested_quantity",
                    models.PositiveIntegerField(
                        db_column="requested_quantity",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantidade solicitada",
                    ),
                ),
                (
                    "supplied_quantity",
                    models.PositiveIntegerField(
                        db_column="supplied_quantity",
                        default=0,
                        verbose_name="Quantidade aviada",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        db_column="notes",
                        default=None,
                        null=True,
                        verbose_name="Observações",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        db_column="lot_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_request_items",
                        to="farmacia.lot",
                        verbose_name="Lote",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        db_column="requisition_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="farmacia.materialrequisition",
                        verbose_name="Requisição",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da requisição de material",
                "verbose_name_plural": "Itens de requisição de material",
                "db_table": "farmacia_requisicaomaterialitem",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="material_request_item",
            field=models.ForeignKey(
                blank=True,
                db_column="material_request_item_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentos",
                to="farmacia.materialrequisitionitem",
                verbose_name="Item de requisição",
            ),
        ),
        migrations.AddIndex(
            model_name="materialrequisition",
            index=models.Index(
                fields=["tenant", "status", "created_at"],
                name="farmacia_re_tenant__ef6dd4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialrequisition",
            index=models.Index(
                fields=["tenant", "sector", "created_at"],
                name="farmacia_re_tenant__a0ca5d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialrequisitionitem",
            index=models.Index(
                fields=["tenant", "requisition"], name="farmacia_re_tenant__f47832_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialrequisitionitem",
            index=models.Index(
                fields=["tenant", "lot"], name="farmacia_re_tenant__765638_idx"
            ),
        ),
    ]
