# Generated by Django 4.2.16 on 2026-04-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0010_alter_inventorymovement_origin_materialrequisition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequisition',
            name='sector',
            field=models.CharField(choices=[('LAB', 'Laboratório'), ('ENF', 'Enfermagem'), ('REC', 'Recepção'), ('MED', 'Medicina'), ('MOC', 'Medicina Ocupacional'), ('OUT', 'Outros setores')], db_column='sector', db_index=True, max_length=3, verbose_name='Setor solicitante'),
        ),
    ]
