# Generated by Django 4.2.29 on 2026-04-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0011_alter_materialrequisition_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialrequisitionitem',
            options={'ordering': ['requisition', 'position', 'id'], 'verbose_name': 'Item da requisição de material', 'verbose_name_plural': 'Itens de requisição de material'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['sale', 'position', 'id'], 'verbose_name': 'Item de Venda', 'verbose_name_plural': 'Itens de Venda'},
        ),
        migrations.AddField(
            model_name='materialrequisitionitem',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
