# Generated by Django 5.1 on 2026-03-25 04:18

import apps.equipment_integrations.models.message
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinico", "0001_initial"),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "name",
                    models.CharField(db_column="nome", db_index=True, max_length=120),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("ECG", "Eletrocardiograma"),
                            ("HEM", "Hemograma (Hematologia)"),
                            ("BIO", "Bioquímica"),
                            ("US", "Ecografia (Ultrassom)"),
                            ("XR", "Raios-X"),
                            ("OUT", "Outro"),
                        ],
                        db_column="modalidade",
                        db_index=True,
                        default="OUT",
                        max_length=20,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("HTTP_JSON", "HTTP (JSON)"),
                            ("HL7_MLLP", "HL7 v2 (MLLP)"),
                            ("ASTM_TCP", "ASTM (TCP)"),
                            ("DICOM", "DICOM"),
                            ("FILE_DROP", "File drop (pasta)"),
                        ],
                        db_column="protocolo",
                        db_index=True,
                        default="HTTP_JSON",
                        max_length=20,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, db_column="fabricante", default="", max_length=120
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, db_column="modelo", default="", max_length=120
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        db_column="numero_serie",
                        db_index=True,
                        default="",
                        max_length=120,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(db_column="ativo", db_index=True, default=True),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="criado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deletado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="inquilino_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="atualizado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipamento (Integração)",
                "verbose_name_plural": "Equipamentos (Integração)",
                "db_table": "integracoes_equipamentos_integracaoequipamento",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "label",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=12
                    ),
                ),
                ("key_last4", models.CharField(blank=True, default="", max_length=4)),
                (
                    "key_hash",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("scopes", models.JSONField(blank=True, default=list)),
                (
                    "active",
                    models.BooleanField(db_column="ativo", db_index=True, default=True),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, db_column="revogada_em", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="criado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deletado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="inquilino_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="atualizado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        db_column="equipamento_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credenciais",
                        to="integracoes_equipamentos.integrationequipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credencial (Equipamento)",
                "verbose_name_plural": "Credenciais (Equipamentos)",
                "db_table": "integracoes_equipamentos_integracaocredencial",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationAnalyteMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "name",
                    models.CharField(db_column="nome", db_index=True, max_length=120),
                ),
                (
                    "code",
                    models.CharField(db_column="codigo", db_index=True, max_length=80),
                ),
                (
                    "unit_override",
                    models.CharField(
                        blank=True,
                        db_column="unidade_override",
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(db_column="ativo", db_index=True, default=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="criado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deletado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam_field",
                    models.ForeignKey(
                        db_column="exame_campo_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mapeamentos_integracao",
                        to="clinico.labexamfield",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="inquilino_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="atualizado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        db_column="equipamento_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapeamentos_analitos",
                        to="integracoes_equipamentos.integrationequipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapeamento de analito",
                "verbose_name_plural": "Mapeamentos de analitos",
                "db_table": "integracoes_equipamentos_integracaomapeamentoanalito",
                "ordering": ["equipment", "code"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEND", "Pendente"),
                            ("SEND", "Enviada"),
                            ("EXEC", "Em execução"),
                            ("DONE", "Concluída"),
                            ("ERRO", "Erro"),
                            ("CANC", "Cancelada"),
                        ],
                        db_column="estado",
                        db_index=True,
                        default="PEND",
                        max_length=4,
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, db_column="observacao", default=""),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="criado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deletado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        db_column="equipamento_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens",
                        to="integracoes_equipamentos.integrationequipment",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        db_column="requisicao_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens_integracao",
                        to="clinico.labrequest",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="inquilino_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="atualizado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem (Integração)",
                "verbose_name_plural": "Ordens (Integração)",
                "db_table": "integracoes_equipamentos_integracaoordem",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "Entrada"), ("OUT", "Saída")],
                        db_column="direcao",
                        db_index=True,
                        default="IN",
                        max_length=3,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        blank=True,
                        db_column="protocolo",
                        db_index=True,
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("payload_raw", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECV", "Recebida"),
                            ("PROC", "Processada"),
                            ("ERRO", "Erro"),
                        ],
                        db_column="estado",
                        db_index=True,
                        default="RECV",
                        max_length=4,
                    ),
                ),
                ("error", models.TextField(blank=True, db_column="erro", default="")),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, db_column="processado_em", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="criado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deletado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        db_column="equipamento_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mensagens",
                        to="integracoes_equipamentos.integrationequipment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="inquilino_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="atualizado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_column="ordem_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mensagens",
                        to="integracoes_equipamentos.integrationorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem (Integração)",
                "verbose_name_plural": "Mensagens (Integração)",
                "db_table": "integracoes_equipamentos_integracaomensagem",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEND", "Pendente"),
                            ("EXEC", "Em execução"),
                            ("DONE", "Concluído"),
                            ("ERRO", "Erro"),
                            ("CANC", "Cancelado"),
                        ],
                        db_column="estado",
                        db_index=True,
                        default="PEND",
                        max_length=4,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="criado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deletado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="ordem_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="integracoes_equipamentos.integrationorder",
                    ),
                ),
                (
                    "request_item",
                    models.ForeignKey(
                        db_column="requisicao_item_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens_integracao_itens",
                        to="clinico.labrequestitem",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="inquilino_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="atualizado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de order (Integração)",
                "verbose_name_plural": "Itens de order (Integração)",
                "db_table": "integracoes_equipamentos_integracaoordemitem",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "file",
                    models.FileField(
                        db_column="arquivo",
                        upload_to=apps.equipment_integrations.models.message._upload_path,
                    ),
                ),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="criado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deletado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="inquilino_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="atualizado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        db_column="mensagem_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="integracoes_equipamentos.integrationmessage",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        db_column="ordem_item_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos",
                        to="integracoes_equipamentos.integrationorderitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento (Integração)",
                "verbose_name_plural": "Documentos (Integração)",
                "db_table": "integracoes_equipamentos_integracaodocumento",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationRouting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("LAB", "Exame laboratorial"),
                            ("MED", "Exame médico (imagem/diagnóstico)"),
                        ],
                        db_column="tipo_exame",
                        db_index=True,
                        default="LAB",
                        max_length=3,
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("Hematologia", "Hematologia"),
                            ("Bioquimica", "Bioquímica"),
                            ("Microbiologia", "Microbiologia"),
                            ("Imunologia", "Imunologia"),
                            ("Serologia", "Serologia"),
                            ("Parasitologia", "Parasitologia"),
                            ("BiologiaMolecular", "Biologia Molecular"),
                            ("Toxicologia", "Toxicologia"),
                            ("Hormonios", "Hormônios e Endocrinologia"),
                            ("MarcadoresTumorais", "Marcadores Tumorais"),
                            ("Coagulacao", "Coagulação"),
                            ("Urinalise", "Urinálise"),
                            ("LiquidosCorporais", "Líquidos Corporais"),
                            ("Gasometria", "Gasometria"),
                            ("NutricaoClinica", "Nutrição Clínica"),
                            ("Micologia", "Micologia"),
                            ("Virologia", "Virologia"),
                            ("Bacteriologia", "Bacteriologia"),
                            ("BancoSangue", "Banco de Sangue"),
                            ("ImunoHematologia", "Imuno-hematologia"),
                            ("Triagem", "Triagem Laboratorial"),
                            ("RecepcaoAmostras", "Recepção de Amostras"),
                            ("ControleQualidade", "Controle de Qualidade"),
                            ("Pesquisa", "Pesquisa Laboratorial"),
                            ("Outro", "Outro"),
                        ],
                        db_column="setor",
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(db_column="ativo", db_index=True, default=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="criado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deletado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        db_column="equipamento_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roteamentos",
                        to="integracoes_equipamentos.integrationequipment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="inquilino_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="atualizado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Roteamento (Integração)",
                "verbose_name_plural": "Roteamentos (Integração)",
                "db_table": "integracoes_equipamentos_integracaoroteamento",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="integrationequipment",
            index=models.Index(
                fields=["tenant", "modality"], name="integracoes_inquili_e2b01b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationequipment",
            index=models.Index(
                fields=["tenant", "protocol"], name="integracoes_inquili_c94006_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationequipment",
            index=models.Index(
                fields=["tenant", "active"], name="integracoes_inquili_b4f35e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationcredential",
            index=models.Index(
                fields=["tenant", "equipment"], name="integracoes_inquili_a6a53f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationcredential",
            index=models.Index(
                fields=["equipment", "active"], name="integracoes_equipam_5432b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationanalytemapping",
            index=models.Index(
                fields=["tenant", "equipment", "active"],
                name="integracoes_inquili_85dff0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationanalytemapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("equipment", "code"),
                name="unique_code_por_equipment",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationorder",
            index=models.Index(
                fields=["tenant", "equipment", "status"],
                name="integracoes_inquili_7c9f99_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationorder",
            index=models.Index(
                fields=["request"], name="integracoes_requisi_420c7d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationorder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("equipment", "request"),
                name="unique_order_por_equipment_request",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationmessage",
            index=models.Index(
                fields=["tenant", "equipment", "status"],
                name="integracoes_inquili_cc354d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationmessage",
            index=models.Index(
                fields=["equipment", "direction", "created_at"],
                name="integracoes_equipam_e6a50c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationorderitem",
            index=models.Index(
                fields=["tenant", "order", "status"],
                name="integracoes_inquili_d08885_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationorderitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("order", "request_item"),
                name="unique_item_por_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationrouting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("equipment", "exam_type", "sector"),
                name="unique_roteamento_por_equipment_type_sector",
            ),
        ),
    ]
