# Generated by Django 5.1 on 2026-03-26 04:14

import apps.equipment_integrations.models.message
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinical", "0004_clinicalhistory_clinicalevent"),
        (
            "inquilinos",
            "0002_rename_inquilinos__tipo_856ce4_idx_inquilinos__type_fdb81e_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "name",
                    models.CharField(db_column="name", db_index=True, max_length=120),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("ECG", "Eletrocardiograma"),
                            ("HEM", "Hemograma (Hematologia)"),
                            ("BIO", "Bioquímica"),
                            ("US", "Ecografia (Ultrassom)"),
                            ("XR", "Raios-X"),
                            ("OUT", "Outro"),
                        ],
                        db_column="modality",
                        db_index=True,
                        default="OUT",
                        max_length=20,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("HTTP_JSON", "HTTP (JSON)"),
                            ("HL7_MLLP", "HL7 v2 (MLLP)"),
                            ("ASTM_TCP", "ASTM (TCP)"),
                            ("DICOM", "DICOM"),
                            ("FILE_DROP", "File drop (pasta)"),
                        ],
                        db_column="protocol",
                        db_index=True,
                        default="HTTP_JSON",
                        max_length=20,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, db_column="manufacturer", default="", max_length=120
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, db_column="model", default="", max_length=120
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        db_column="serial_number",
                        db_index=True,
                        default="",
                        max_length=120,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_column="active", db_index=True, default=True
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipamento (Integração)",
                "verbose_name_plural": "Equipamentos (Integração)",
                "db_table": "integracoes_equipamentos_integracaoequipamento",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=12
                    ),
                ),
                ("key_last4", models.CharField(blank=True, default="", max_length=4)),
                (
                    "key_hash",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("scopes", models.JSONField(blank=True, default=list)),
                (
                    "active",
                    models.BooleanField(
                        db_column="active", db_index=True, default=True
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, db_column="revoked_at", null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        db_column="equipment_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credenciais",
                        to="integracoes_equipamentos.integrationequipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credencial (Equipamento)",
                "verbose_name_plural": "Credenciais (Equipamentos)",
                "db_table": "integracoes_equipamentos_integracaocredencial",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationAnalyteMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "name",
                    models.CharField(db_column="name", db_index=True, max_length=120),
                ),
                (
                    "code",
                    models.CharField(db_column="code", db_index=True, max_length=80),
                ),
                (
                    "unit_override",
                    models.CharField(
                        blank=True, db_column="unit_override", default="", max_length=30
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_column="active", db_index=True, default=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam_field",
                    models.ForeignKey(
                        db_column="exam_field_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mapeamentos_integracao",
                        to="clinical.labexamfield",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        db_column="equipment_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapeamentos_analitos",
                        to="integracoes_equipamentos.integrationequipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapeamento de analito",
                "verbose_name_plural": "Mapeamentos de analitos",
                "db_table": "integracoes_equipamentos_integracaomapeamentoanalito",
                "ordering": ["equipment", "code"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEND", "Pendente"),
                            ("SEND", "Enviada"),
                            ("EXEC", "Em execução"),
                            ("DONE", "Concluída"),
                            ("ERRO", "Erro"),
                            ("CANC", "Cancelada"),
                        ],
                        db_column="status",
                        db_index=True,
                        default="PEND",
                        max_length=4,
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, db_column="observation", default=""),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        db_column="equipment_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="integracoes_equipamentos.integrationequipment",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        db_column="request_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integration_orders",
                        to="clinical.labrequest",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem (Integração)",
                "verbose_name_plural": "Ordens (Integração)",
                "db_table": "integracoes_equipamentos_integracaoordem",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "Entrada"), ("OUT", "Saída")],
                        db_column="direction",
                        db_index=True,
                        default="IN",
                        max_length=3,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        blank=True,
                        db_column="protocol",
                        db_index=True,
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("payload_raw", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECV", "Recebida"),
                            ("PROC", "Processada"),
                            ("ERRO", "Erro"),
                        ],
                        db_column="status",
                        db_index=True,
                        default="RECV",
                        max_length=4,
                    ),
                ),
                ("error", models.TextField(blank=True, db_column="error", default="")),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, db_column="processed_at", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        db_column="equipment_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mensagens",
                        to="integracoes_equipamentos.integrationequipment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_column="order_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mensagens",
                        to="integracoes_equipamentos.integrationorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem (Integração)",
                "verbose_name_plural": "Mensagens (Integração)",
                "db_table": "integracoes_equipamentos_integracaomensagem",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEND", "Pendente"),
                            ("EXEC", "Em execução"),
                            ("DONE", "Concluído"),
                            ("ERRO", "Erro"),
                            ("CANC", "Cancelado"),
                        ],
                        db_column="status",
                        db_index=True,
                        default="PEND",
                        max_length=4,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="integracoes_equipamentos.integrationorder",
                    ),
                ),
                (
                    "request_item",
                    models.ForeignKey(
                        db_column="request_item_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integration_order_items",
                        to="clinical.labrequestitem",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de order (Integração)",
                "verbose_name_plural": "Itens de order (Integração)",
                "db_table": "integracoes_equipamentos_integracaoordemitem",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "file",
                    models.FileField(
                        db_column="file",
                        upload_to=apps.equipment_integrations.models.message._upload_path,
                    ),
                ),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        db_column="message_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="integracoes_equipamentos.integrationmessage",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        db_column="order_item_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos",
                        to="integracoes_equipamentos.integrationorderitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento (Integração)",
                "verbose_name_plural": "Documentos (Integração)",
                "db_table": "integracoes_equipamentos_integracaodocumento",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationRouting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("LAB", "Exame laboratorial"),
                            ("MED", "Exame médico (imagem/diagnóstico)"),
                        ],
                        db_column="exam_type",
                        db_index=True,
                        default="LAB",
                        max_length=3,
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("Hematologia", "Hematologia"),
                            ("Bioquimica", "Bioquímica"),
                            ("Microbiologia", "Microbiologia"),
                            ("Imunologia", "Imunologia"),
                            ("Serologia", "Serologia"),
                            ("Parasitologia", "Parasitologia"),
                            ("BiologiaMolecular", "Biologia Molecular"),
                            ("Toxicologia", "Toxicologia"),
                            ("Hormonios", "Hormônios e Endocrinologia"),
                            ("MarcadoresTumorais", "Marcadores Tumorais"),
                            ("Coagulacao", "Coagulação"),
                            ("Urinalise", "Urinálise"),
                            ("LiquidosCorporais", "Líquidos Corporais"),
                            ("Gasometria", "Gasometria"),
                            ("NutricaoClinica", "Nutrição Clínica"),
                            ("Micologia", "Micologia"),
                            ("Virologia", "Virologia"),
                            ("Bacteriologia", "Bacteriologia"),
                            ("BancoSangue", "Banco de Sangue"),
                            ("ImunoHematologia", "Imuno-hematologia"),
                            ("Triagem", "Triagem Laboratorial"),
                            ("RecepcaoAmostras", "Recepção de Amostras"),
                            ("ControleQualidade", "Controle de Qualidade"),
                            ("Pesquisa", "Pesquisa Laboratorial"),
                            ("Outro", "Outro"),
                        ],
                        db_column="sector",
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_column="active", db_index=True, default=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        db_column="equipment_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roteamentos",
                        to="integracoes_equipamentos.integrationequipment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Roteamento (Integração)",
                "verbose_name_plural": "Roteamentos (Integração)",
                "db_table": "integracoes_equipamentos_integracaoroteamento",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="integrationequipment",
            index=models.Index(
                fields=["tenant", "modality"], name="integracoes_tenant__9756d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationequipment",
            index=models.Index(
                fields=["tenant", "protocol"], name="integracoes_tenant__a34a16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationequipment",
            index=models.Index(
                fields=["tenant", "active"], name="integracoes_tenant__6f9f09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationcredential",
            index=models.Index(
                fields=["tenant", "equipment"], name="integracoes_tenant__e13e17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationcredential",
            index=models.Index(
                fields=["equipment", "active"], name="integracoes_equipme_0adb1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationanalytemapping",
            index=models.Index(
                fields=["tenant", "equipment", "active"],
                name="integracoes_tenant__9869ff_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationanalytemapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("equipment", "code"),
                name="unique_code_por_equipment",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationorder",
            index=models.Index(
                fields=["tenant", "equipment", "status"],
                name="integracoes_tenant__826e87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationorder",
            index=models.Index(
                fields=["request"], name="integracoes_request_4faec9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationorder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("equipment", "request"),
                name="unique_order_por_equipment_request",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationmessage",
            index=models.Index(
                fields=["tenant", "equipment", "status"],
                name="integracoes_tenant__785a35_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationmessage",
            index=models.Index(
                fields=["equipment", "direction", "created_at"],
                name="integracoes_equipme_1a88ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationorderitem",
            index=models.Index(
                fields=["tenant", "order", "status"],
                name="integracoes_tenant__8011b8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationorderitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("order", "request_item"),
                name="unique_item_por_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationrouting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("equipment", "exam_type", "sector"),
                name="unique_roteamento_por_equipment_type_sector",
            ),
        ),
    ]
