# Generated by Django 5.1 on 2026-03-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integracoes_equipamentos", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="integrationanalytemapping",
            new_name="integracoes_tenant__9869ff_idx",
            old_name="integracoes_inquili_85dff0_idx",
        ),
        migrations.RenameIndex(
            model_name="integrationcredential",
            new_name="integracoes_tenant__e13e17_idx",
            old_name="integracoes_inquili_a6a53f_idx",
        ),
        migrations.RenameIndex(
            model_name="integrationcredential",
            new_name="integracoes_equipme_0adb1d_idx",
            old_name="integracoes_equipam_5432b2_idx",
        ),
        migrations.RenameIndex(
            model_name="integrationequipment",
            new_name="integracoes_tenant__9756d2_idx",
            old_name="integracoes_inquili_e2b01b_idx",
        ),
        migrations.RenameIndex(
            model_name="integrationequipment",
            new_name="integracoes_tenant__a34a16_idx",
            old_name="integracoes_inquili_c94006_idx",
        ),
        migrations.RenameIndex(
            model_name="integrationequipment",
            new_name="integracoes_tenant__6f9f09_idx",
            old_name="integracoes_inquili_b4f35e_idx",
        ),
        migrations.RenameIndex(
            model_name="integrationmessage",
            new_name="integracoes_tenant__785a35_idx",
            old_name="integracoes_inquili_cc354d_idx",
        ),
        migrations.RenameIndex(
            model_name="integrationmessage",
            new_name="integracoes_equipme_1a88ec_idx",
            old_name="integracoes_equipam_e6a50c_idx",
        ),
        migrations.RenameIndex(
            model_name="integrationorder",
            new_name="integracoes_tenant__826e87_idx",
            old_name="integracoes_inquili_7c9f99_idx",
        ),
        migrations.RenameIndex(
            model_name="integrationorder",
            new_name="integracoes_request_4faec9_idx",
            old_name="integracoes_requisi_420c7d_idx",
        ),
        migrations.RenameIndex(
            model_name="integrationorderitem",
            new_name="integracoes_tenant__8011b8_idx",
            old_name="integracoes_inquili_d08885_idx",
        ),
    ]
