# Generated by Django 4.2.29 on 2026-04-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes_equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationorderitem',
            options={'ordering': ['order', 'position', 'id'], 'verbose_name': 'Item de order (Integração)', 'verbose_name_plural': 'Itens de order (Integração)'},
        ),
        migrations.AddField(
            model_name='integrationorderitem',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
