# Generated by Django 5.1 on 2026-03-26 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0005_alter_clinicalevent_options_and_more"),
        ("integracoes_equipamentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationanalytemapping",
            name="active",
            field=models.BooleanField(
                db_column="active", db_index=True, default=True, verbose_name="Ativo"
            ),
        ),
        migrations.AlterField(
            model_name="integrationanalytemapping",
            name="code",
            field=models.CharField(
                db_column="code", db_index=True, max_length=80, verbose_name="Código"
            ),
        ),
        migrations.AlterField(
            model_name="integrationanalytemapping",
            name="equipment",
            field=models.ForeignKey(
                db_column="equipment_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mapeamentos_analitos",
                to="integracoes_equipamentos.integrationequipment",
                verbose_name="Equipamento",
            ),
        ),
        migrations.AlterField(
            model_name="integrationanalytemapping",
            name="exam_field",
            field=models.ForeignKey(
                db_column="exam_field_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mapeamentos_integracao",
                to="clinical.labexamfield",
                verbose_name="Campo de exame",
            ),
        ),
        migrations.AlterField(
            model_name="integrationanalytemapping",
            name="unit_override",
            field=models.CharField(
                blank=True,
                db_column="unit_override",
                default="",
                max_length=30,
                verbose_name="Unidade (override)",
            ),
        ),
        migrations.AlterField(
            model_name="integrationequipment",
            name="active",
            field=models.BooleanField(
                db_column="active", db_index=True, default=True, verbose_name="Ativo"
            ),
        ),
        migrations.AlterField(
            model_name="integrationequipment",
            name="config",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Configuração"
            ),
        ),
        migrations.AlterField(
            model_name="integrationequipment",
            name="manufacturer",
            field=models.CharField(
                blank=True,
                db_column="manufacturer",
                default="",
                max_length=120,
                verbose_name="Fabricante",
            ),
        ),
        migrations.AlterField(
            model_name="integrationequipment",
            name="modality",
            field=models.CharField(
                choices=[
                    ("ECG", "Eletrocardiograma"),
                    ("HEM", "Hemograma (Hematologia)"),
                    ("BIO", "Bioquímica"),
                    ("US", "Ecografia (Ultrassom)"),
                    ("XR", "Raios-X"),
                    ("OUT", "Outro"),
                ],
                db_column="modality",
                db_index=True,
                default="OUT",
                max_length=20,
                verbose_name="Modalidade",
            ),
        ),
        migrations.AlterField(
            model_name="integrationequipment",
            name="model",
            field=models.CharField(
                blank=True,
                db_column="model",
                default="",
                max_length=120,
                verbose_name="Modelo",
            ),
        ),
        migrations.AlterField(
            model_name="integrationequipment",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("HTTP_JSON", "HTTP (JSON)"),
                    ("HL7_MLLP", "HL7 v2 (MLLP)"),
                    ("ASTM_TCP", "ASTM (TCP)"),
                    ("DICOM", "DICOM"),
                    ("FILE_DROP", "File drop (pasta)"),
                ],
                db_column="protocol",
                db_index=True,
                default="HTTP_JSON",
                max_length=20,
                verbose_name="Protocolo",
            ),
        ),
        migrations.AlterField(
            model_name="integrationequipment",
            name="serial_number",
            field=models.CharField(
                blank=True,
                db_column="serial_number",
                db_index=True,
                default="",
                max_length=120,
                verbose_name="Número de série",
            ),
        ),
    ]
