# Generated by Django 4.2.29 on 2026-03-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_custom', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deletado', models.BooleanField(db_index=True, default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('metodo', models.CharField(db_index=True, max_length=10, verbose_name='Método HTTP')),
                ('caminho', models.CharField(db_index=True, max_length=255, verbose_name='Rota curta')),
                ('path_completo', models.TextField(blank=True, default='', verbose_name='URL completa')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Status HTTP')),
                ('duracao_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (ms)')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User-Agent')),
                ('view_basename', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='View')),
                ('view_action', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Ação da view')),
                ('objeto_id', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Objeto (ID)')),
                ('mensagem', models.CharField(blank=True, default='', max_length=255, verbose_name='Mensagem')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
            ],
            options={
                'verbose_name': 'Actividade do Utilizador',
                'verbose_name_plural': 'Actividades do Utilizador',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
