# Generated by Django 4.2.16 on 2026-03-17 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0001_initial'),
        ('auditoria_atividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeusuario',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atividadeusuario',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atividadeusuario',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atividadeusuario',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='atividadeusuario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditoria_atividades', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador'),
        ),
        migrations.AddIndex(
            model_name='atividadeusuario',
            index=models.Index(fields=['inquilino', 'criado_em'], name='auditoria_a_inquili_efc74c_idx'),
        ),
        migrations.AddIndex(
            model_name='atividadeusuario',
            index=models.Index(fields=['inquilino', 'usuario', 'criado_em'], name='auditoria_a_inquili_0aaacc_idx'),
        ),
        migrations.AddIndex(
            model_name='atividadeusuario',
            index=models.Index(fields=['inquilino', 'status_code'], name='auditoria_a_inquili_2a1772_idx'),
        ),
        migrations.AddIndex(
            model_name='atividadeusuario',
            index=models.Index(fields=['inquilino', 'view_basename', 'criado_em'], name='auditoria_a_inquili_dc3d1a_idx'),
        ),
    ]
