"""Facade module for education viewsets."""

from .viewsets_impl import (
    VIEWSET_MAP,
    AssignmentSubmissionViewSet,
    AssignmentViewSet,
    AttendanceRecordViewSet,
    BibliographyContentViewSet,
    ClassroomViewSet,
    CourseViewSet,
    EnrollmentViewSet,
    ExaminationViewSet,
    ExaminationAttemptViewSet,
    GradeRecordViewSet,
    LearningContentViewSet,
    RandomTestViewSet,
    SkillViewSet,
    StudentProfileViewSet,
    TeacherProfileViewSet,
    ThematicMapContentViewSet,
)

__all__ = [
    "VIEWSET_MAP",
    "AssignmentViewSet",
    "AssignmentSubmissionViewSet",
    "AttendanceRecordViewSet",
    "BibliographyContentViewSet",
    "ClassroomViewSet",
    "CourseViewSet",
    "EnrollmentViewSet",
    "ExaminationViewSet",
    "ExaminationAttemptViewSet",
    "GradeRecordViewSet",
    "LearningContentViewSet",
    "RandomTestViewSet",
    "SkillViewSet",
    "StudentProfileViewSet",
    "TeacherProfileViewSet",
    "ThematicMapContentViewSet",
]
