# Generated by Django 4.2.29 on 2026-05-30 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical', '0004_alter_labexam_turnaround_hours_and_more'),
        ('recursos_humanos', '0001_initial'),
        ('inquilinos', '0002_alter_tenant_options_and_more'),
        ('odontologia', '0003_dentalodontogramentry_tooth_number_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalPatientTreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('assigned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Atribuído em')),
                ('valid_from', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Início da vigência')),
                ('valid_until', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fim da vigência')),
                ('status', models.CharField(choices=[('ACTIVE', 'Válido'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Paciente com Plano Dentário',
                'verbose_name_plural': 'Pacientes com Plano Dentário',
                'db_table': 'odontologia_plano_tratamento_paciente',
                'ordering': ['-valid_from', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='dentaltreatmentplan',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dental_treatment_plans', to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AddIndex(
            model_name='dentaltreatmentplan',
            index=models.Index(fields=['tenant', 'status'], name='odontologia_tenant__3af23c_idx'),
        ),
        migrations.AddField(
            model_name='dentalpatienttreatmentplan',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dentalpatienttreatmentplan',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dentalpatienttreatmentplan',
            name='dentist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dental_patient_treatment_plans', to='recursos_humanos.employee', verbose_name='Dentista responsável'),
        ),
        migrations.AddField(
            model_name='dentalpatienttreatmentplan',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dental_plan_assignments', to='clinical.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='dentalpatienttreatmentplan',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_treatment_plans', to='odontologia.dentalrecord', verbose_name='Prontuário dentário'),
        ),
        migrations.AddField(
            model_name='dentalpatienttreatmentplan',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='dentalpatienttreatmentplan',
            name='treatment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_assignments', to='odontologia.dentaltreatmentplan', verbose_name='Plano dentário'),
        ),
        migrations.AddField(
            model_name='dentalpatienttreatmentplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dentalpatienttreatmentplan',
            index=models.Index(fields=['tenant', 'patient', 'status'], name='odontologia_tenant__947241_idx'),
        ),
        migrations.AddIndex(
            model_name='dentalpatienttreatmentplan',
            index=models.Index(fields=['tenant', 'treatment_plan', 'status'], name='odontologia_tenant__73fafc_idx'),
        ),
        migrations.AddIndex(
            model_name='dentalpatienttreatmentplan',
            index=models.Index(fields=['tenant', 'valid_until'], name='odontologia_tenant__6398a6_idx'),
        ),
    ]
