# Generated by Django 5.2.12 on 2026-04-20 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinical", "0005_alter_labexam_applies_vat_by_default_and_more"),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "bag_identifier",
                    models.CharField(
                        db_column="bag_identifier",
                        db_index=True,
                        max_length=40,
                        verbose_name="Identificador da bolsa",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("O-", "O negativo"),
                            ("O+", "O positivo"),
                            ("A-", "A negativo"),
                            ("A+", "A positivo"),
                            ("B-", "B negativo"),
                            ("B+", "B positivo"),
                            ("AB-", "AB negativo"),
                            ("AB+", "AB positivo"),
                            ("UNK", "Nao informado"),
                        ],
                        db_column="blood_type",
                        db_index=True,
                        default="UNK",
                        max_length=3,
                        verbose_name="Tipo sanguineo",
                    ),
                ),
                (
                    "donation_type",
                    models.CharField(
                        choices=[("WBL", "Sangue total"), ("APH", "Aferese")],
                        db_column="donation_type",
                        db_index=True,
                        default="WBL",
                        max_length=3,
                        verbose_name="Tipo de doacao",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REG", "Registrada"),
                            ("SCR", "Em triagem"),
                            ("COM", "Concluida"),
                            ("CAN", "Cancelada"),
                        ],
                        db_column="status",
                        db_index=True,
                        default="REG",
                        max_length=3,
                        verbose_name="Estado da doacao",
                    ),
                ),
                (
                    "screening_status",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendente"),
                            ("APR", "Aprovada"),
                            ("REJ", "Rejeitada"),
                        ],
                        db_column="screening_status",
                        db_index=True,
                        default="PEN",
                        max_length=3,
                        verbose_name="Estado da triagem",
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        db_column="collected_at",
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Data/hora da coleta",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="processed_at",
                        db_index=True,
                        null=True,
                        verbose_name="Data/hora do processamento",
                    ),
                ),
                (
                    "volume_ml",
                    models.PositiveIntegerField(
                        db_column="volume_ml",
                        default=450,
                        verbose_name="Volume coletado (ml)",
                    ),
                ),
                (
                    "donor_weight_kg",
                    models.DecimalField(
                        blank=True,
                        db_column="donor_weight_kg",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Peso do doador (kg)",
                    ),
                ),
                (
                    "hemoglobin_g_dl",
                    models.DecimalField(
                        blank=True,
                        db_column="hemoglobin_g_dl",
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Hemoglobina (g/dL)",
                    ),
                ),
                (
                    "donor_height_cm",
                    models.PositiveIntegerField(
                        blank=True,
                        db_column="donor_height_cm",
                        null=True,
                        verbose_name="Altura do doador (cm)",
                    ),
                ),
                (
                    "blood_pressure_systolic",
                    models.PositiveIntegerField(
                        blank=True,
                        db_column="blood_pressure_systolic",
                        null=True,
                        verbose_name="Pressao arterial sistolica (mmHg)",
                    ),
                ),
                (
                    "blood_pressure_diastolic",
                    models.PositiveIntegerField(
                        blank=True,
                        db_column="blood_pressure_diastolic",
                        null=True,
                        verbose_name="Pressao arterial diastolica (mmHg)",
                    ),
                ),
                (
                    "pulse_bpm",
                    models.PositiveIntegerField(
                        blank=True,
                        db_column="pulse_bpm",
                        null=True,
                        verbose_name="Pulso (bpm)",
                    ),
                ),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True,
                        db_column="temperature_c",
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Temperatura (C)",
                    ),
                ),
                (
                    "hiv_test",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendente"),
                            ("NEG", "Negativo"),
                            ("POS", "Positivo"),
                            ("INC", "Inconclusivo"),
                            ("NDO", "Nao realizado"),
                        ],
                        db_column="hiv_test",
                        db_index=True,
                        default="PEN",
                        max_length=3,
                        verbose_name="HIV",
                    ),
                ),
                (
                    "syphilis_rpr_test",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendente"),
                            ("NEG", "Negativo"),
                            ("POS", "Positivo"),
                            ("INC", "Inconclusivo"),
                            ("NDO", "Nao realizado"),
                        ],
                        db_column="syphilis_rpr_test",
                        db_index=True,
                        default="PEN",
                        max_length=3,
                        verbose_name="Sifilis/RPR",
                    ),
                ),
                (
                    "hepatitis_b_hbsag_test",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendente"),
                            ("NEG", "Negativo"),
                            ("POS", "Positivo"),
                            ("INC", "Inconclusivo"),
                            ("NDO", "Nao realizado"),
                        ],
                        db_column="hepatitis_b_hbsag_test",
                        db_index=True,
                        default="PEN",
                        max_length=3,
                        verbose_name="Hepatite B (HBsAg)",
                    ),
                ),
                (
                    "hepatitis_c_anti_hcv_test",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendente"),
                            ("NEG", "Negativo"),
                            ("POS", "Positivo"),
                            ("INC", "Inconclusivo"),
                            ("NDO", "Nao realizado"),
                        ],
                        db_column="hepatitis_c_anti_hcv_test",
                        db_index=True,
                        default="PEN",
                        max_length=3,
                        verbose_name="Hepatite C (anti-HCV)",
                    ),
                ),
                (
                    "malaria_test",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendente"),
                            ("NEG", "Negativo"),
                            ("POS", "Positivo"),
                            ("INC", "Inconclusivo"),
                            ("NDO", "Nao realizado"),
                        ],
                        db_column="malaria_test",
                        db_index=True,
                        default="PEN",
                        max_length=3,
                        verbose_name="Malaria",
                    ),
                ),
                (
                    "test_notes",
                    models.TextField(
                        blank=True,
                        db_column="test_notes",
                        default="",
                        verbose_name="Observacoes dos exames",
                    ),
                ),
                (
                    "contraindications",
                    models.TextField(
                        blank=True,
                        db_column="contraindications",
                        default="",
                        verbose_name="Contraindicacoes",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        db_column="notes",
                        default="",
                        verbose_name="Observacoes",
                    ),
                ),
                (
                    "collected_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="collected_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blood_donations_collected",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Profissional da coleta",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        db_column="donor_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blood_donations",
                        to="clinical.patient",
                        verbose_name="Doador",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doacao de Sangue",
                "verbose_name_plural": "Doacoes de Sangue",
                "db_table": "bloodbank_blood_donation",
                "ordering": ["-collected_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BloodStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="name",
                        db_index=True,
                        max_length=120,
                        verbose_name="Nome do armazenamento",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        db_column="location",
                        default="",
                        max_length=255,
                        verbose_name="Localizacao",
                    ),
                ),
                (
                    "capacity_units",
                    models.PositiveIntegerField(
                        db_column="capacity_units",
                        default=100,
                        verbose_name="Capacidade (unidades)",
                    ),
                ),
                (
                    "temperature_min_c",
                    models.DecimalField(
                        db_column="temperature_min_c",
                        decimal_places=1,
                        default=2.0,
                        max_digits=4,
                        verbose_name="Temperatura minima (C)",
                    ),
                ),
                (
                    "temperature_max_c",
                    models.DecimalField(
                        db_column="temperature_max_c",
                        decimal_places=1,
                        default=6.0,
                        max_digits=4,
                        verbose_name="Temperatura maxima (C)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_column="is_active",
                        db_index=True,
                        default=True,
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "last_validation_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="last_validation_at",
                        null=True,
                        verbose_name="Ultima validacao",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        db_column="notes",
                        default="",
                        verbose_name="Observacoes",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Armazenamento de Sangue",
                "verbose_name_plural": "Armazenamentos de Sangue",
                "db_table": "bloodbank_blood_storage",
                "ordering": ["name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="BloodStorageMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("PRV", "Preventiva"),
                            ("COR", "Corretiva"),
                            ("CAL", "Calibracao"),
                            ("SAN", "Higienizacao"),
                            ("TMP", "Validacao de temperatura"),
                        ],
                        db_column="maintenance_type",
                        db_index=True,
                        default="PRV",
                        max_length=3,
                        verbose_name="Tipo de manutencao",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCH", "Agendada"),
                            ("INP", "Em andamento"),
                            ("COM", "Concluida"),
                            ("CAN", "Cancelada"),
                        ],
                        db_column="status",
                        db_index=True,
                        default="SCH",
                        max_length=3,
                        verbose_name="Estado da manutencao",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        db_column="scheduled_at",
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Data/hora agendada",
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="performed_at",
                        null=True,
                        verbose_name="Data/hora executada",
                    ),
                ),
                (
                    "next_due_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="next_due_at",
                        null=True,
                        verbose_name="Proxima manutencao prevista",
                    ),
                ),
                (
                    "technician_name",
                    models.CharField(
                        blank=True,
                        db_column="technician_name",
                        default="",
                        max_length=120,
                        verbose_name="Tecnico responsavel",
                    ),
                ),
                (
                    "findings",
                    models.TextField(
                        blank=True,
                        db_column="findings",
                        default="",
                        verbose_name="Achados",
                    ),
                ),
                (
                    "actions_taken",
                    models.TextField(
                        blank=True,
                        db_column="actions_taken",
                        default="",
                        verbose_name="Acoes executadas",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        db_column="notes",
                        default="",
                        verbose_name="Observacoes",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        db_column="storage_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenances",
                        to="bloodbank.bloodstorage",
                        verbose_name="Armazenamento",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Manutencao de Banco de Sangue",
                "verbose_name_plural": "Manutencoes de Banco de Sangue",
                "db_table": "bloodbank_blood_storage_maintenance",
                "ordering": ["-scheduled_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BloodUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "unit_number",
                    models.CharField(
                        db_column="unit_number",
                        db_index=True,
                        max_length=40,
                        verbose_name="Numero da unidade",
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("WB", "Sangue total"),
                            ("RBC", "Concentrado de hemacias"),
                            ("PLS", "Plasma fresco"),
                            ("PLT", "Concentrado de plaquetas"),
                            ("CRY", "Crioprecipitado"),
                        ],
                        db_column="component_type",
                        db_index=True,
                        default="WB",
                        max_length=3,
                        verbose_name="Tipo de componente",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("O-", "O negativo"),
                            ("O+", "O positivo"),
                            ("A-", "A negativo"),
                            ("A+", "A positivo"),
                            ("B-", "B negativo"),
                            ("B+", "B positivo"),
                            ("AB-", "AB negativo"),
                            ("AB+", "AB positivo"),
                            ("UNK", "Nao informado"),
                        ],
                        db_column="blood_type",
                        db_index=True,
                        default="UNK",
                        max_length=3,
                        verbose_name="Tipo sanguineo",
                    ),
                ),
                (
                    "volume_ml",
                    models.PositiveIntegerField(
                        db_column="volume_ml",
                        default=0,
                        verbose_name="Volume da unidade (ml)",
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        db_column="collected_at",
                        db_index=True,
                        verbose_name="Data/hora da coleta",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_column="expires_at",
                        db_index=True,
                        verbose_name="Data/hora de validade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUA", "Quarentena"),
                            ("AVL", "Disponivel"),
                            ("RES", "Reservada"),
                            ("TRN", "Transfundida"),
                            ("EXP", "Expirada"),
                            ("DSC", "Descartada"),
                        ],
                        db_column="status",
                        db_index=True,
                        default="QUA",
                        max_length=3,
                        verbose_name="Estado da unidade",
                    ),
                ),
                (
                    "is_irradiated",
                    models.BooleanField(
                        db_column="is_irradiated",
                        default=False,
                        verbose_name="Irradiada",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        db_column="notes",
                        default="",
                        verbose_name="Observacoes",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        db_column="donation_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blood_units",
                        to="bloodbank.blooddonation",
                        verbose_name="Doacao de origem",
                    ),
                ),
                (
                    "reserved_for",
                    models.ForeignKey(
                        blank=True,
                        db_column="reserved_for_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reserved_blood_units",
                        to="clinical.patient",
                        verbose_name="Paciente reservado",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        blank=True,
                        db_column="storage_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blood_units",
                        to="bloodbank.bloodstorage",
                        verbose_name="Armazenamento atual",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade de Sangue",
                "verbose_name_plural": "Unidades de Sangue",
                "db_table": "bloodbank_blood_unit",
                "ordering": ["-collected_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BloodTransfusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQ", "Solicitada"),
                            ("APR", "Aprovada"),
                            ("INP", "Em andamento"),
                            ("COM", "Concluida"),
                            ("CAN", "Cancelada"),
                            ("REA", "Reacao adversa"),
                        ],
                        db_column="status",
                        db_index=True,
                        default="REQ",
                        max_length=3,
                        verbose_name="Estado da transfusao",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        db_column="requested_at",
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Data/hora da solicitacao",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="started_at",
                        db_index=True,
                        null=True,
                        verbose_name="Data/hora de inicio",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="finished_at",
                        db_index=True,
                        null=True,
                        verbose_name="Data/hora de termino",
                    ),
                ),
                (
                    "indication",
                    models.TextField(
                        blank=True,
                        db_column="indication",
                        default="",
                        verbose_name="Indicacao clinica",
                    ),
                ),
                (
                    "reaction_notes",
                    models.TextField(
                        blank=True,
                        db_column="reaction_notes",
                        default="",
                        verbose_name="Registro de reacao",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        db_column="notes",
                        default="",
                        verbose_name="Observacoes",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="performed_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blood_transfusions_performed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Executado por",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        db_column="recipient_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blood_transfusions",
                        to="clinical.patient",
                        verbose_name="Paciente receptor",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="requested_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blood_transfusions_requested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitado por",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blood_unit",
                    models.ForeignKey(
                        db_column="blood_unit_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfusions",
                        to="bloodbank.bloodunit",
                        verbose_name="Unidade transfundida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfusao de Sangue",
                "verbose_name_plural": "Transfusoes de Sangue",
                "db_table": "bloodbank_blood_transfusion",
                "ordering": ["-requested_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BloodStockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="custom_id",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deleted", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                (
                    "version",
                    models.PositiveIntegerField(db_column="version", default=1),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("INB", "Entrada"),
                            ("OUT", "Saida"),
                            ("TRF", "Transferencia"),
                            ("RSV", "Reserva"),
                            ("RLS", "Liberacao"),
                            ("DSC", "Descarte"),
                            ("EXP", "Baixa por validade"),
                            ("ADJ", "Ajuste manual"),
                        ],
                        db_column="movement_type",
                        db_index=True,
                        max_length=3,
                        verbose_name="Tipo de movimentacao",
                    ),
                ),
                (
                    "moved_at",
                    models.DateTimeField(
                        db_column="moved_at",
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Data/hora da movimentacao",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        db_column="reason",
                        default="",
                        max_length=200,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        db_column="notes",
                        default="",
                        verbose_name="Observacoes",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="performed_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blood_stock_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Executado por",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_storage",
                    models.ForeignKey(
                        blank=True,
                        db_column="destination_storage_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements_in",
                        to="bloodbank.bloodstorage",
                        verbose_name="Armazenamento de destino",
                    ),
                ),
                (
                    "source_storage",
                    models.ForeignKey(
                        blank=True,
                        db_column="source_storage_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements_out",
                        to="bloodbank.bloodstorage",
                        verbose_name="Armazenamento de origem",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="bloodbank.bloodunit",
                        verbose_name="Unidade movimentada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentacao de Estoque de Sangue",
                "verbose_name_plural": "Movimentacoes de Estoque de Sangue",
                "db_table": "bloodbank_blood_stock_movement",
                "ordering": ["-moved_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="blooddonation",
            index=models.Index(
                fields=["tenant", "status", "collected_at"],
                name="bloodbank_b_tenant__41a1cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blooddonation",
            index=models.Index(
                fields=["tenant", "screening_status", "collected_at"],
                name="bloodbank_b_tenant__8247ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blooddonation",
            index=models.Index(
                fields=["tenant", "blood_type", "collected_at"],
                name="bloodbank_b_tenant__1ea063_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="blooddonation",
            constraint=models.UniqueConstraint(
                fields=("tenant", "bag_identifier"),
                name="uq_blood_donation_bag_identifier_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="bloodstorage",
            index=models.Index(
                fields=["tenant", "is_active", "name"],
                name="bloodbank_b_tenant__680e30_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bloodstorage",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uq_blood_storage_name_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="bloodstoragemaintenance",
            index=models.Index(
                fields=["tenant", "status", "scheduled_at"],
                name="bloodbank_b_tenant__a942c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bloodstoragemaintenance",
            index=models.Index(
                fields=["tenant", "maintenance_type", "scheduled_at"],
                name="bloodbank_b_tenant__06a839_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bloodstoragemaintenance",
            index=models.Index(
                fields=["tenant", "storage", "status"],
                name="bloodbank_b_tenant__a48d55_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bloodunit",
            index=models.Index(
                fields=["tenant", "status", "expires_at"],
                name="bloodbank_b_tenant__366f36_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bloodunit",
            index=models.Index(
                fields=["tenant", "blood_type", "status"],
                name="bloodbank_b_tenant__37243e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bloodunit",
            index=models.Index(
                fields=["tenant", "storage", "status"],
                name="bloodbank_b_tenant__2e3966_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bloodunit",
            constraint=models.UniqueConstraint(
                fields=("tenant", "unit_number"), name="uq_blood_unit_number_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="bloodtransfusion",
            index=models.Index(
                fields=["tenant", "status", "requested_at"],
                name="bloodbank_b_tenant__d48d33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bloodtransfusion",
            index=models.Index(
                fields=["tenant", "recipient", "status"],
                name="bloodbank_b_tenant__cd9022_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bloodtransfusion",
            index=models.Index(
                fields=["tenant", "blood_unit", "status"],
                name="bloodbank_b_tenant__4f5da3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bloodstockmovement",
            index=models.Index(
                fields=["tenant", "movement_type", "moved_at"],
                name="bloodbank_b_tenant__afa7b1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bloodstockmovement",
            index=models.Index(
                fields=["tenant", "unit", "moved_at"],
                name="bloodbank_b_tenant__383aa3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bloodstockmovement",
            index=models.Index(
                fields=["tenant", "source_storage", "destination_storage"],
                name="bloodbank_b_tenant__cb2e38_idx",
            ),
        ),
    ]
