# Generated by Django 5.2.12 on 2026-04-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbank", "0001_initial"),
        ("clinical", "0007_patient_is_replacement_donor_inapt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blooddonation",
            name="donor_role",
            field=models.CharField(
                choices=[("VOL", "Voluntario"), ("REP", "Repositor")],
                db_column="donor_role",
                db_index=True,
                default="VOL",
                max_length=3,
                verbose_name="Tipo de doador",
            ),
        ),
        migrations.AddField(
            model_name="blooddonation",
            name="replacement_for",
            field=models.ForeignKey(
                blank=True,
                db_column="replacement_for_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replacement_blood_donations",
                to="clinical.patient",
                verbose_name="Reposicao para (paciente)",
            ),
        ),
    ]
