# Generated by Django 4.2.29 on 2026-05-22 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('inquilinos', '0001_initial'),
        ('bloodbank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodunit',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='dispatch_outcome_by',
            field=models.ForeignKey(blank=True, db_column='dispatch_outcome_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_units_dispatch_outcomes', to=settings.AUTH_USER_MODEL, verbose_name='Desfecho registado por'),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='donation',
            field=models.ForeignKey(db_column='donation_id', on_delete=django.db.models.deletion.PROTECT, related_name='blood_units', to='bloodbank.blooddonation', verbose_name='Doação de origem'),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='forwarded_by',
            field=models.ForeignKey(blank=True, db_column='forwarded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_units_forwarded', to=settings.AUTH_USER_MODEL, verbose_name='Aviada por'),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='reserved_for',
            field=models.ForeignKey(blank=True, db_column='reserved_for_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_blood_units', to='clinical.patient', verbose_name='Paciente reservado'),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='storage',
            field=models.ForeignKey(blank=True, db_column='storage_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_units', to='bloodbank.bloodstorage', verbose_name='Armazenamento atual'),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodtransfusion',
            name='blood_unit',
            field=models.ForeignKey(db_column='blood_unit_id', on_delete=django.db.models.deletion.PROTECT, related_name='transfusions', to='bloodbank.bloodunit', verbose_name='Unidade transfundida'),
        ),
        migrations.AddField(
            model_name='bloodtransfusion',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodtransfusion',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodtransfusion',
            name='performed_by',
            field=models.ForeignKey(blank=True, db_column='performed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_transfusions_performed', to=settings.AUTH_USER_MODEL, verbose_name='Executado por'),
        ),
        migrations.AddField(
            model_name='bloodtransfusion',
            name='recipient',
            field=models.ForeignKey(db_column='recipient_id', on_delete=django.db.models.deletion.PROTECT, related_name='blood_transfusions', to='clinical.patient', verbose_name='Paciente receptor'),
        ),
        migrations.AddField(
            model_name='bloodtransfusion',
            name='requested_by',
            field=models.ForeignKey(blank=True, db_column='requested_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_transfusions_requested', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AddField(
            model_name='bloodtransfusion',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='bloodtransfusion',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodstoragemaintenance',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodstoragemaintenance',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodstoragemaintenance',
            name='storage',
            field=models.ForeignKey(db_column='storage_id', on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='bloodbank.bloodstorage', verbose_name='Armazenamento'),
        ),
        migrations.AddField(
            model_name='bloodstoragemaintenance',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='bloodstoragemaintenance',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodstorage',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodstorage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodstorage',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='bloodstorage',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodstockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodstockmovement',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodstockmovement',
            name='destination_storage',
            field=models.ForeignKey(blank=True, db_column='destination_storage_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_in', to='bloodbank.bloodstorage', verbose_name='Armazenamento de destino'),
        ),
        migrations.AddField(
            model_name='bloodstockmovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, db_column='performed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Executado por'),
        ),
        migrations.AddField(
            model_name='bloodstockmovement',
            name='source_storage',
            field=models.ForeignKey(blank=True, db_column='source_storage_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_out', to='bloodbank.bloodstorage', verbose_name='Armazenamento de origem'),
        ),
        migrations.AddField(
            model_name='bloodstockmovement',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='bloodstockmovement',
            name='unit',
            field=models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='bloodbank.bloodunit', verbose_name='Unidade movimentada'),
        ),
        migrations.AddField(
            model_name='bloodstockmovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='collected_by',
            field=models.ForeignKey(blank=True, db_column='collected_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_donations_collected', to=settings.AUTH_USER_MODEL, verbose_name='Profissional da coleta'),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='donor',
            field=models.ForeignKey(db_column='donor_id', on_delete=django.db.models.deletion.PROTECT, related_name='blood_donations', to='clinical.patient', verbose_name='Doador'),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='replacement_for',
            field=models.ForeignKey(blank=True, db_column='replacement_for_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_blood_donations', to='clinical.patient', verbose_name='Reposição para (paciente)'),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bloodunit',
            index=models.Index(fields=['tenant', 'status', 'expires_at'], name='bloodbank_b_tenant__366f36_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodunit',
            index=models.Index(fields=['tenant', 'blood_type', 'status'], name='bloodbank_b_tenant__37243e_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodunit',
            index=models.Index(fields=['tenant', 'storage', 'status'], name='bloodbank_b_tenant__2e3966_idx'),
        ),
        migrations.AddConstraint(
            model_name='bloodunit',
            constraint=models.UniqueConstraint(fields=('tenant', 'unit_number'), name='uq_blood_unit_number_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='bloodtransfusion',
            index=models.Index(fields=['tenant', 'status', 'requested_at'], name='bloodbank_b_tenant__d48d33_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodtransfusion',
            index=models.Index(fields=['tenant', 'recipient', 'status'], name='bloodbank_b_tenant__cd9022_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodtransfusion',
            index=models.Index(fields=['tenant', 'blood_unit', 'status'], name='bloodbank_b_tenant__4f5da3_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodstoragemaintenance',
            index=models.Index(fields=['tenant', 'status', 'scheduled_at'], name='bloodbank_b_tenant__a942c4_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodstoragemaintenance',
            index=models.Index(fields=['tenant', 'maintenance_type', 'scheduled_at'], name='bloodbank_b_tenant__06a839_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodstoragemaintenance',
            index=models.Index(fields=['tenant', 'storage', 'status'], name='bloodbank_b_tenant__a48d55_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodstorage',
            index=models.Index(fields=['tenant', 'is_active', 'name'], name='bloodbank_b_tenant__680e30_idx'),
        ),
        migrations.AddConstraint(
            model_name='bloodstorage',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_blood_storage_name_per_tenant', violation_error_message='Já existe um armazenamento com este nome neste tenant.'),
        ),
        migrations.AddIndex(
            model_name='bloodstockmovement',
            index=models.Index(fields=['tenant', 'movement_type', 'moved_at'], name='bloodbank_b_tenant__afa7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodstockmovement',
            index=models.Index(fields=['tenant', 'unit', 'moved_at'], name='bloodbank_b_tenant__383aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodstockmovement',
            index=models.Index(fields=['tenant', 'source_storage', 'destination_storage'], name='bloodbank_b_tenant__cb2e38_idx'),
        ),
        migrations.AddIndex(
            model_name='blooddonation',
            index=models.Index(fields=['tenant', 'status', 'collected_at'], name='bloodbank_b_tenant__41a1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='blooddonation',
            index=models.Index(fields=['tenant', 'screening_status', 'collected_at'], name='bloodbank_b_tenant__8247ed_idx'),
        ),
        migrations.AddIndex(
            model_name='blooddonation',
            index=models.Index(fields=['tenant', 'blood_type', 'collected_at'], name='bloodbank_b_tenant__1ea063_idx'),
        ),
        migrations.AddConstraint(
            model_name='blooddonation',
            constraint=models.UniqueConstraint(fields=('tenant', 'bag_identifier'), name='uq_blood_donation_bag_identifier_per_tenant'),
        ),
    ]
