# Generated by Django 4.2.29 on 2026-06-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='bag_identifier',
            field=models.CharField(blank=True, db_column='bag_identifier', db_index=True, default='', help_text='Gerado automaticamente a partir do custom_id quando não informado.', max_length=40, verbose_name='Identificador da bolsa'),
        ),
    ]
