# Generated by Django 4.2.29 on 2026-04-30 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0011_alter_labexamfield_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloodbank', '0003_alter_bloodstorage_uq_blood_storage_name_per_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blooddonation',
            options={'ordering': ['-collected_at', '-created_at'], 'verbose_name': 'Doação de sangue', 'verbose_name_plural': 'Doações de sangue'},
        ),
        migrations.AlterModelOptions(
            name='bloodstockmovement',
            options={'ordering': ['-moved_at', '-created_at'], 'verbose_name': 'Movimentação de stock de sangue', 'verbose_name_plural': 'Movimentações de stock de sangue'},
        ),
        migrations.AlterModelOptions(
            name='bloodstorage',
            options={'ordering': ['name', 'created_at'], 'verbose_name': 'Armazenamento de sangue', 'verbose_name_plural': 'Armazenamentos de sangue'},
        ),
        migrations.AlterModelOptions(
            name='bloodstoragemaintenance',
            options={'ordering': ['-scheduled_at', '-created_at'], 'verbose_name': 'Manutenção de banco de sangue', 'verbose_name_plural': 'Manutenções de banco de sangue'},
        ),
        migrations.AlterModelOptions(
            name='bloodtransfusion',
            options={'ordering': ['-requested_at', '-created_at'], 'verbose_name': 'Transfusão de sangue', 'verbose_name_plural': 'Transfusões de sangue'},
        ),
        migrations.AlterModelOptions(
            name='bloodunit',
            options={'ordering': ['-collected_at', '-created_at'], 'verbose_name': 'Unidade de sangue', 'verbose_name_plural': 'Unidades de sangue'},
        ),
        migrations.RemoveConstraint(
            model_name='bloodstorage',
            name='uq_blood_storage_name_per_tenant',
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='dispatch_outcome',
            field=models.CharField(choices=[('PEN', 'Pendente'), ('TRN', 'Transfundida'), ('RET', 'Devolvida'), ('DSC', 'Descartada')], db_column='dispatch_outcome', db_index=True, default='PEN', max_length=3, verbose_name='Desfecho da aviação'),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='dispatch_outcome_at',
            field=models.DateTimeField(blank=True, db_column='dispatch_outcome_at', db_index=True, null=True, verbose_name='Data/hora do desfecho da aviação'),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='dispatch_outcome_by',
            field=models.ForeignKey(blank=True, db_column='dispatch_outcome_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_units_dispatch_outcomes', to=settings.AUTH_USER_MODEL, verbose_name='Desfecho registado por'),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='dispatch_outcome_notes',
            field=models.TextField(blank=True, db_column='dispatch_outcome_notes', default='', verbose_name='Observações do desfecho da aviação'),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, db_column='forwarded_at', db_index=True, null=True, verbose_name='Data/hora da aviação'),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='forwarded_by',
            field=models.ForeignKey(blank=True, db_column='forwarded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_units_forwarded', to=settings.AUTH_USER_MODEL, verbose_name='Aviada por'),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='forwarded_to_sector',
            field=models.CharField(blank=True, db_column='forwarded_to_sector', db_index=True, default='', max_length=80, verbose_name='Setor de aviação'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='blood_pressure_diastolic',
            field=models.PositiveIntegerField(blank=True, db_column='blood_pressure_diastolic', null=True, verbose_name='Pressão arterial diastólica (mmHg)'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='blood_pressure_systolic',
            field=models.PositiveIntegerField(blank=True, db_column='blood_pressure_systolic', null=True, verbose_name='Pressão arterial sistólica (mmHg)'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='blood_type',
            field=models.CharField(choices=[('O-', 'O negativo'), ('O+', 'O positivo'), ('A-', 'A negativo'), ('A+', 'A positivo'), ('B-', 'B negativo'), ('B+', 'B positivo'), ('AB-', 'AB negativo'), ('AB+', 'AB positivo'), ('UNK', 'Não informado')], db_column='blood_type', db_index=True, default='UNK', max_length=3, verbose_name='Tipo sanguíneo'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='contraindications',
            field=models.TextField(blank=True, db_column='contraindications', default='', verbose_name='Contraindicações'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='donation_type',
            field=models.CharField(choices=[('WBL', 'Sangue total'), ('APH', 'Aferese')], db_column='donation_type', db_index=True, default='WBL', max_length=3, verbose_name='Tipo de doação'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='hepatitis_b_hbsag_test',
            field=models.CharField(choices=[('PEN', 'Pendente'), ('NEG', 'Negativo'), ('POS', 'Positivo'), ('INC', 'Inconclusivo'), ('NDO', 'Não realizado')], db_column='hepatitis_b_hbsag_test', db_index=True, default='PEN', max_length=3, verbose_name='Hepatite B (HBsAg)'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='hepatitis_c_anti_hcv_test',
            field=models.CharField(choices=[('PEN', 'Pendente'), ('NEG', 'Negativo'), ('POS', 'Positivo'), ('INC', 'Inconclusivo'), ('NDO', 'Não realizado')], db_column='hepatitis_c_anti_hcv_test', db_index=True, default='PEN', max_length=3, verbose_name='Hepatite C (anti-HCV)'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='hiv_test',
            field=models.CharField(choices=[('PEN', 'Pendente'), ('NEG', 'Negativo'), ('POS', 'Positivo'), ('INC', 'Inconclusivo'), ('NDO', 'Não realizado')], db_column='hiv_test', db_index=True, default='PEN', max_length=3, verbose_name='Teste HIV'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='malaria_test',
            field=models.CharField(choices=[('PEN', 'Pendente'), ('NEG', 'Negativo'), ('POS', 'Positivo'), ('INC', 'Inconclusivo'), ('NDO', 'Não realizado')], db_column='malaria_test', db_index=True, default='PEN', max_length=3, verbose_name='Malaria'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='notes',
            field=models.TextField(blank=True, db_column='notes', default='', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='replacement_for',
            field=models.ForeignKey(blank=True, db_column='replacement_for_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_blood_donations', to='clinical.patient', verbose_name='Reposição para (paciente)'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='status',
            field=models.CharField(choices=[('REG', 'Registrada'), ('SCR', 'Em triagem'), ('COM', 'Concluida'), ('CAN', 'Cancelada')], db_column='status', db_index=True, default='REG', max_length=3, verbose_name='Estado da doação'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='syphilis_rpr_test',
            field=models.CharField(choices=[('PEN', 'Pendente'), ('NEG', 'Negativo'), ('POS', 'Positivo'), ('INC', 'Inconclusivo'), ('NDO', 'Não realizado')], db_column='syphilis_rpr_test', db_index=True, default='PEN', max_length=3, verbose_name='Sífilis/RPR'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='test_notes',
            field=models.TextField(blank=True, db_column='test_notes', default='', verbose_name='Observações dos exames'),
        ),
        migrations.AlterField(
            model_name='bloodstockmovement',
            name='moved_at',
            field=models.DateTimeField(db_column='moved_at', db_index=True, default=django.utils.timezone.now, verbose_name='Data/hora da movimentação'),
        ),
        migrations.AlterField(
            model_name='bloodstockmovement',
            name='movement_type',
            field=models.CharField(choices=[('INB', 'Entrada'), ('OUT', 'Saída'), ('TRF', 'Transferência'), ('RSV', 'Reserva'), ('RLS', 'Liberação'), ('FWD', 'Aviação para setor'), ('RTN', 'Devolução ao banco de sangue'), ('DSC', 'Descarte'), ('EXP', 'Baixa por validade'), ('ADJ', 'Ajuste manual')], db_column='movement_type', db_index=True, max_length=3, verbose_name='Tipo de movimentação'),
        ),
        migrations.AlterField(
            model_name='bloodstockmovement',
            name='notes',
            field=models.TextField(blank=True, db_column='notes', default='', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='bloodstorage',
            name='last_validation_at',
            field=models.DateTimeField(blank=True, db_column='last_validation_at', null=True, verbose_name='Última validação'),
        ),
        migrations.AlterField(
            model_name='bloodstorage',
            name='location',
            field=models.CharField(blank=True, db_column='location', default='', max_length=255, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='bloodstorage',
            name='notes',
            field=models.TextField(blank=True, db_column='notes', default='', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='bloodstorage',
            name='temperature_max_c',
            field=models.DecimalField(db_column='temperature_max_c', decimal_places=1, default=6.0, max_digits=4, verbose_name='Temperatura máxima (°C)'),
        ),
        migrations.AlterField(
            model_name='bloodstorage',
            name='temperature_min_c',
            field=models.DecimalField(db_column='temperature_min_c', decimal_places=1, default=2.0, max_digits=4, verbose_name='Temperatura mínima (°C)'),
        ),
        migrations.AlterField(
            model_name='bloodstoragemaintenance',
            name='actions_taken',
            field=models.TextField(blank=True, db_column='actions_taken', default='', verbose_name='Ações executadas'),
        ),
        migrations.AlterField(
            model_name='bloodstoragemaintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('PRV', 'Preventiva'), ('COR', 'Corretiva'), ('CAL', 'Calibração'), ('SAN', 'Higienização'), ('TMP', 'Validação de temperatura')], db_column='maintenance_type', db_index=True, default='PRV', max_length=3, verbose_name='Tipo de manutenção'),
        ),
        migrations.AlterField(
            model_name='bloodstoragemaintenance',
            name='next_due_at',
            field=models.DateTimeField(blank=True, db_column='next_due_at', null=True, verbose_name='Próxima manutenção prevista'),
        ),
        migrations.AlterField(
            model_name='bloodstoragemaintenance',
            name='notes',
            field=models.TextField(blank=True, db_column='notes', default='', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='bloodstoragemaintenance',
            name='status',
            field=models.CharField(choices=[('SCH', 'Agendada'), ('INP', 'Em andamento'), ('COM', 'Concluída'), ('CAN', 'Cancelada')], db_column='status', db_index=True, default='SCH', max_length=3, verbose_name='Estado da manutenção'),
        ),
        migrations.AlterField(
            model_name='bloodstoragemaintenance',
            name='technician_name',
            field=models.CharField(blank=True, db_column='technician_name', default='', max_length=120, verbose_name='Técnico responsável'),
        ),
        migrations.AlterField(
            model_name='bloodtransfusion',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_column='finished_at', db_index=True, null=True, verbose_name='Data/hora de término'),
        ),
        migrations.AlterField(
            model_name='bloodtransfusion',
            name='indication',
            field=models.TextField(blank=True, db_column='indication', default='', verbose_name='Indicação clínica'),
        ),
        migrations.AlterField(
            model_name='bloodtransfusion',
            name='notes',
            field=models.TextField(blank=True, db_column='notes', default='', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='bloodtransfusion',
            name='reaction_notes',
            field=models.TextField(blank=True, db_column='reaction_notes', default='', verbose_name='Registo de reação'),
        ),
        migrations.AlterField(
            model_name='bloodtransfusion',
            name='requested_at',
            field=models.DateTimeField(db_column='requested_at', db_index=True, default=django.utils.timezone.now, verbose_name='Data/hora da solicitação'),
        ),
        migrations.AlterField(
            model_name='bloodtransfusion',
            name='started_at',
            field=models.DateTimeField(blank=True, db_column='started_at', db_index=True, null=True, verbose_name='Data/hora de início'),
        ),
        migrations.AlterField(
            model_name='bloodtransfusion',
            name='status',
            field=models.CharField(choices=[('REQ', 'Solicitada'), ('APR', 'Aprovada'), ('INP', 'Em andamento'), ('COM', 'Concluída'), ('CAN', 'Cancelada'), ('REA', 'Reação adversa')], db_column='status', db_index=True, default='REQ', max_length=3, verbose_name='Estado da transfusão'),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='blood_type',
            field=models.CharField(choices=[('O-', 'O negativo'), ('O+', 'O positivo'), ('A-', 'A negativo'), ('A+', 'A positivo'), ('B-', 'B negativo'), ('B+', 'B positivo'), ('AB-', 'AB negativo'), ('AB+', 'AB positivo'), ('UNK', 'Não informado')], db_column='blood_type', db_index=True, default='UNK', max_length=3, verbose_name='Tipo sanguíneo'),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='donation',
            field=models.ForeignKey(db_column='donation_id', on_delete=django.db.models.deletion.PROTECT, related_name='blood_units', to='bloodbank.blooddonation', verbose_name='Doação de origem'),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='notes',
            field=models.TextField(blank=True, db_column='notes', default='', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='status',
            field=models.CharField(choices=[('QUA', 'Quarentena'), ('AVL', 'Disponível'), ('RES', 'Reservada'), ('FWD', 'Aviada para setor'), ('TRN', 'Transfundida'), ('EXP', 'Expirada'), ('DSC', 'Descartada')], db_column='status', db_index=True, default='QUA', max_length=3, verbose_name='Estado da unidade'),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='unit_number',
            field=models.CharField(db_column='unit_number', db_index=True, max_length=40, verbose_name='Número da unidade'),
        ),
        migrations.AddConstraint(
            model_name='bloodstorage',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_blood_storage_name_per_tenant', violation_error_message='Já existe um armazenamento com este nome neste tenant.'),
        ),
    ]
