# Generated by Django 4.2.29 on 2026-05-20 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiOperationalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('assigned_group', models.CharField(db_index=True, max_length=120, verbose_name='Grupo responsável')),
                ('module_key', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Módulo')),
                ('title', models.CharField(max_length=180, verbose_name='Título')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('critical', 'Crítica')], db_index=True, default='normal', max_length=20, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em execução'), ('done', 'Concluída'), ('cancelled', 'Cancelada')], db_index=True, default='open', max_length=20, verbose_name='Estado')),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Prazo')),
                ('source_type', models.CharField(blank=True, default='', max_length=120, verbose_name='Tipo de origem')),
                ('source_reference', models.CharField(blank=True, default='', max_length=180, verbose_name='Referência de origem')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('action', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_task', to='ai_assistant.aisuggestedaction', verbose_name='Acção de origem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_operational_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_tasks', to='ai_assistant.aisession', verbose_name='Sessão')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa Operacional da IA',
                'verbose_name_plural': 'Tarefas Operacionais da IA',
                'db_table': 'ai_assistant_operational_task',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='ai_assistan_tenant__97de69_idx'), models.Index(fields=['tenant', 'assigned_group', 'status'], name='ai_assistan_tenant__ef1743_idx'), models.Index(fields=['tenant', 'module_key', 'status'], name='ai_assistan_tenant__d7abf0_idx'), models.Index(fields=['session', 'status', 'created_at'], name='ai_assistan_session_d65e39_idx')],
            },
        ),
    ]
