# Generated by Django 4.2.29 on 2026-05-22 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('inquilinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aitoolcall',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aitoolcall',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aitoolcall',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_calls', to='ai_assistant.aimessage', verbose_name='Mensagem'),
        ),
        migrations.AddField(
            model_name='aitoolcall',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='ai_assistant.aisession', verbose_name='Sessão'),
        ),
        migrations.AddField(
            model_name='aitoolcall',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='aitoolcall',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aisuggestedaction',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_confirmed_actions', to=settings.AUTH_USER_MODEL, verbose_name='Confirmada por'),
        ),
        migrations.AddField(
            model_name='aisuggestedaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggested_actions', to=settings.AUTH_USER_MODEL, verbose_name='Criada por'),
        ),
        migrations.AddField(
            model_name='aisuggestedaction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aisuggestedaction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_actions', to='ai_assistant.aisession', verbose_name='Sessão'),
        ),
        migrations.AddField(
            model_name='aisuggestedaction',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='aisuggestedaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aisession',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aisession',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aisession',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='aisession',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aisession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador'),
        ),
        migrations.AddField(
            model_name='aipolicyevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aipolicyevent',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aipolicyevent',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_events', to='ai_assistant.aisession', verbose_name='Sessão'),
        ),
        migrations.AddField(
            model_name='aipolicyevent',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='aipolicyevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aipolicyevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_policy_events', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador'),
        ),
        migrations.AddField(
            model_name='aioperationaltask',
            name='action',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_task', to='ai_assistant.aisuggestedaction', verbose_name='Acção de origem'),
        ),
        migrations.AddField(
            model_name='aioperationaltask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_operational_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Criada por'),
        ),
        migrations.AddField(
            model_name='aioperationaltask',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aioperationaltask',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_tasks', to='ai_assistant.aisession', verbose_name='Sessão'),
        ),
        migrations.AddField(
            model_name='aioperationaltask',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='aioperationaltask',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aisession', verbose_name='Sessão'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_messages', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador'),
        ),
        migrations.AddField(
            model_name='aiknowledgeentry',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiknowledgeentry',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiknowledgeentry',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='aiknowledgeentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiinvestigation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_investigations', to=settings.AUTH_USER_MODEL, verbose_name='Criada por'),
        ),
        migrations.AddField(
            model_name='aiinvestigation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiinvestigation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='ai_assistant.aisession', verbose_name='Sessão'),
        ),
        migrations.AddField(
            model_name='aiinvestigation',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant'),
        ),
        migrations.AddField(
            model_name='aiinvestigation',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aitoolcall',
            index=models.Index(fields=['session', 'tool_name', 'created_at'], name='ai_assistan_session_b01ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='aitoolcall',
            index=models.Index(fields=['status', 'created_at'], name='ai_assistan_status_87312c_idx'),
        ),
        migrations.AddIndex(
            model_name='aitoolcall',
            index=models.Index(fields=['tenant', 'tool_name', 'created_at'], name='ai_assistan_tenant__170c51_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestedaction',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='ai_assistan_tenant__c15b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestedaction',
            index=models.Index(fields=['session', 'status', 'created_at'], name='ai_assistan_session_49d540_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestedaction',
            index=models.Index(fields=['tenant', 'action_type', 'created_at'], name='ai_assistan_tenant__55d3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['tenant', 'user', 'updated_at'], name='ai_assistan_tenant__0aae7b_idx'),
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['tenant', 'status', 'updated_at'], name='ai_assistan_tenant__b84b93_idx'),
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['tenant', 'active_module', 'updated_at'], name='ai_assistan_tenant__347929_idx'),
        ),
        migrations.AddIndex(
            model_name='aipolicyevent',
            index=models.Index(fields=['tenant', 'severity', 'created_at'], name='ai_assistan_tenant__c903d5_idx'),
        ),
        migrations.AddIndex(
            model_name='aipolicyevent',
            index=models.Index(fields=['tenant', 'policy_key', 'created_at'], name='ai_assistan_tenant__7a3c41_idx'),
        ),
        migrations.AddIndex(
            model_name='aipolicyevent',
            index=models.Index(fields=['tenant', 'blocked', 'created_at'], name='ai_assistan_tenant__7ddd02_idx'),
        ),
        migrations.AddIndex(
            model_name='aioperationaltask',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='ai_assistan_tenant__97de69_idx'),
        ),
        migrations.AddIndex(
            model_name='aioperationaltask',
            index=models.Index(fields=['tenant', 'assigned_group', 'status'], name='ai_assistan_tenant__ef1743_idx'),
        ),
        migrations.AddIndex(
            model_name='aioperationaltask',
            index=models.Index(fields=['tenant', 'module_key', 'status'], name='ai_assistan_tenant__d7abf0_idx'),
        ),
        migrations.AddIndex(
            model_name='aioperationaltask',
            index=models.Index(fields=['session', 'status', 'created_at'], name='ai_assistan_session_d65e39_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['session', 'created_at'], name='ai_assistan_session_3851e5_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['session', 'role', 'created_at'], name='ai_assistan_session_b292b5_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['tenant', 'created_at'], name='ai_assistan_tenant__dcc378_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgeentry',
            index=models.Index(fields=['tenant', 'status', 'priority'], name='ai_assistan_tenant__a99b47_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgeentry',
            index=models.Index(fields=['tenant', 'category', 'status'], name='ai_assistan_tenant__a0ee8e_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgeentry',
            index=models.Index(fields=['tenant', 'module_key', 'status'], name='ai_assistan_tenant__08676f_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgeentry',
            index=models.Index(fields=['tenant', 'source', 'status'], name='ai_assistan_tenant__039397_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiknowledgeentry',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_ai_knowledge_entry_tenant_slug'),
        ),
        migrations.AddIndex(
            model_name='aiinvestigation',
            index=models.Index(fields=['tenant', 'session', 'created_at'], name='ai_assistan_tenant__93317d_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinvestigation',
            index=models.Index(fields=['tenant', 'created_by', 'created_at'], name='ai_assistan_tenant__bac57d_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinvestigation',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='ai_assistan_tenant__ced763_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinvestigation',
            index=models.Index(fields=['tenant', 'intent', 'created_at'], name='ai_assistan_tenant__044c19_idx'),
        ),
    ]
