# Generated by Django 4.2.29 on 2026-05-20 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0001_initial'),
        ('ai_assistant', '0002_aioperationaltask'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('title', models.CharField(max_length=180, verbose_name='Título')),
                ('question', models.TextField(blank=True, default='', verbose_name='Pergunta')),
                ('intent', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Intenção')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('ready', 'Pronta'), ('blocked', 'Bloqueada'), ('archived', 'Arquivada')], db_index=True, default='ready', max_length=20, verbose_name='Estado')),
                ('confidence_score', models.PositiveSmallIntegerField(default=60, verbose_name='Confiança (%)')),
                ('scope', models.JSONField(blank=True, default=dict, verbose_name='Escopo')),
                ('findings', models.JSONField(blank=True, default=list, verbose_name='Achados')),
                ('next_steps', models.JSONField(blank=True, default=list, verbose_name='Próximos passos')),
                ('recommended_questions', models.JSONField(blank=True, default=list, verbose_name='Perguntas recomendadas')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='Fontes')),
                ('tool_names', models.JSONField(blank=True, default=list, verbose_name='Ferramentas')),
                ('result_summary', models.TextField(blank=True, default='', verbose_name='Resumo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_investigations', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='ai_assistant.aisession', verbose_name='Sessão')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investigação da IA',
                'verbose_name_plural': 'Investigações da IA',
                'db_table': 'ai_assistant_investigation',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'session', 'created_at'], name='ai_assistan_tenant__93317d_idx'), models.Index(fields=['tenant', 'created_by', 'created_at'], name='ai_assistan_tenant__bac57d_idx'), models.Index(fields=['tenant', 'status', 'created_at'], name='ai_assistan_tenant__ced763_idx'), models.Index(fields=['tenant', 'intent', 'created_at'], name='ai_assistan_tenant__044c19_idx')],
            },
        ),
    ]
