# Generated by Django 4.2.29 on 2026-05-21 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0001_initial'),
        ('ai_assistant', '0003_aiinvestigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiKnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('slug', models.SlugField(max_length=140, verbose_name='Chave')),
                ('title', models.CharField(max_length=180, verbose_name='Título')),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Categoria')),
                ('module_key', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Módulo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Activa'), ('archived', 'Arquivada')], db_index=True, default='active', max_length=20, verbose_name='Estado')),
                ('source', models.CharField(choices=[('custom', 'Personalizada'), ('system_override', 'Substitui entrada do sistema'), ('imported', 'Importada')], db_index=True, default='custom', max_length=30, verbose_name='Origem')),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=50, verbose_name='Prioridade')),
                ('questions_pt', models.JSONField(blank=True, default=list, verbose_name='Perguntas em português')),
                ('questions_en', models.JSONField(blank=True, default=list, verbose_name='Perguntas em inglês')),
                ('aliases_pt', models.JSONField(blank=True, default=list, verbose_name='Aliases em português')),
                ('aliases_en', models.JSONField(blank=True, default=list, verbose_name='Aliases em inglês')),
                ('semantic_terms', models.JSONField(blank=True, default=list, verbose_name='Termos semânticos')),
                ('answer_pt', models.TextField(verbose_name='Resposta em português')),
                ('answer_en', models.TextField(blank=True, default='', verbose_name='Resposta em inglês')),
                ('follow_ups_pt', models.JSONField(blank=True, default=list, verbose_name='Perguntas seguintes em português')),
                ('follow_ups_en', models.JSONField(blank=True, default=list, verbose_name='Perguntas seguintes em inglês')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Etiquetas')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Conhecimento da IA',
                'verbose_name_plural': 'Entradas de Conhecimento da IA',
                'db_table': 'ai_assistant_knowledge_entry',
                'ordering': ['-priority', 'category', 'title', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status', 'priority'], name='ai_assistan_tenant__a99b47_idx'), models.Index(fields=['tenant', 'category', 'status'], name='ai_assistan_tenant__a0ee8e_idx'), models.Index(fields=['tenant', 'module_key', 'status'], name='ai_assistan_tenant__08676f_idx'), models.Index(fields=['tenant', 'source', 'status'], name='ai_assistan_tenant__039397_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='aiknowledgeentry',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_ai_knowledge_entry_tenant_slug'),
        ),
    ]
