# Generated by Django 5.1 on 2026-03-25 04:18

import core.mixins.tenant_propagation
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipamentos", "0001_initial"),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="atualizado_em"),
                ),
                (
                    "custom_id",
                    models.CharField(
                        blank=True,
                        db_column="id_custom",
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_column="deletado", db_index=True, default=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_column="deletado_em", null=True
                    ),
                ),
                ("version", models.PositiveIntegerField(db_column="versao", default=1)),
                (
                    "date",
                    models.DateTimeField(
                        db_column="data",
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("AVARIA", "Avaria"),
                            ("INCIDENTE", "Incidente"),
                            ("OUTRO", "Outro"),
                        ],
                        db_column="tipo",
                        db_index=True,
                        default="AVARIA",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(db_column="descricao")),
                (
                    "support_contact",
                    models.CharField(
                        blank=True,
                        db_column="contacto_assistencia",
                        default="",
                        max_length=120,
                        verbose_name="Contacto de assistência",
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        db_column="resolvido", db_index=True, default=False
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="criado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deletado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        db_column="equipamento_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias",
                        to="equipamentos.equipment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="inquilino_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="inquilinos.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="atualizado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrência",
                "verbose_name_plural": "Ocorrências",
                "db_table": "ocorrencias_ocorrencia",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "equipment", "date"],
                        name="ocorrencias_inquili_c6bb38_idx",
                    ),
                    models.Index(
                        fields=["tenant", "type", "date"],
                        name="ocorrencias_inquili_009e3e_idx",
                    ),
                    models.Index(
                        fields=["tenant", "resolved"],
                        name="ocorrencias_inquili_c25886_idx",
                    ),
                ],
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
    ]
