# Generated by Django 4.2.16 on 2026-03-26 05:22

import core.mixins.tenant_propagation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('date', models.DateTimeField(db_column='date', db_index=True, default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('AVARIA', 'Avaria'), ('INCIDENTE', 'Incidente'), ('OUTRO', 'Outro')], db_column='type', db_index=True, default='AVARIA', max_length=20)),
                ('description', models.TextField(db_column='description')),
                ('support_contact', models.CharField(blank=True, db_column='support_contact', default='', max_length=120, verbose_name='Contacto de assistência')),
                ('resolved', models.BooleanField(db_column='resolved', db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='equipamentos.equipment')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='inquilinos.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'db_table': 'ocorrencias_ocorrencia',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'equipment', 'date'], name='ocorrencias_tenant__580f87_idx'), models.Index(fields=['tenant', 'type', 'date'], name='ocorrencias_tenant__1bd35c_idx'), models.Index(fields=['tenant', 'resolved'], name='ocorrencias_tenant__bad751_idx')],
            },
            bases=(core.mixins.tenant_propagation.TenantPropagationMixin, models.Model),
        ),
    ]
