# Generated by Django 5.1 on 2026-03-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocorrencias", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="incident",
            new_name="ocorrencias_tenant__580f87_idx",
            old_name="ocorrencias_inquili_c6bb38_idx",
        ),
        migrations.RenameIndex(
            model_name="incident",
            new_name="ocorrencias_tenant__1bd35c_idx",
            old_name="ocorrencias_inquili_009e3e_idx",
        ),
        migrations.RenameIndex(
            model_name="incident",
            new_name="ocorrencias_tenant__bad751_idx",
            old_name="ocorrencias_inquili_c25886_idx",
        ),
    ]
