# Generated by Django 4.2.29 on 2026-05-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='maintenance_completed_at',
            field=models.DateTimeField(blank=True, db_column='maintenance_completed_at', db_index=True, null=True, verbose_name='Manutenção concluída em'),
        ),
        migrations.AddField(
            model_name='incident',
            name='maintenance_requested_at',
            field=models.DateTimeField(blank=True, db_column='maintenance_requested_at', db_index=True, null=True, verbose_name='Pedido de manutenção em'),
        ),
        migrations.AddField(
            model_name='incident',
            name='post_incident_actions',
            field=models.TextField(blank=True, db_column='post_incident_actions', default='', verbose_name='Ações após ocorrência'),
        ),
        migrations.AddField(
            model_name='incident',
            name='requires_maintenance',
            field=models.BooleanField(db_column='requires_maintenance', db_index=True, default=False, verbose_name='Requer manutenção'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['tenant', 'requires_maintenance'], name='ocorrencias_tenant__0b233c_idx'),
        ),
    ]
