# Generated by Django 4.2.29 on 2026-05-25 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_equipment_maintenance_required_since_and_more'),
        ('ocorrencias', '0002_incident_maintenance_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='equipment',
            field=models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='equipamentos.equipment'),
        ),
    ]
