# Generated by Django 4.2.16 on 2026-03-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('custom_id', models.CharField(blank=True, db_column='custom_id', db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('deleted', models.BooleanField(db_column='deleted', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120)),
                ('nuit', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='NUIT')),
                ('headquarters_address', models.CharField(blank=True, db_column='headquarters_address', max_length=255, null=True, verbose_name='Local / Sede')),
                ('contacts', models.CharField(blank=True, db_column='contacts', help_text='Pessoa, department ou referência de contact.', max_length=255, null=True, verbose_name='Contactos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone1', models.CharField(blank=True, db_column='phone1', max_length=30, null=True, verbose_name='Telefone')),
                ('phone2', models.CharField(blank=True, db_column='phone2', max_length=30, null=True, verbose_name='Telefone (alternativo)')),
                ('nib', models.CharField(blank=True, max_length=60, null=True, verbose_name='NIB / Conta bancária')),
                ('active', models.BooleanField(db_column='active', db_index=True, default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, db_column='notes', null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'entidades_empresa',
                'ordering': ['name'],
            },
        ),
    ]
