# Generated by Django 5.1 on 2026-03-25 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entidades", "0001_initial"),
        ("inquilinos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="criado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                db_column="deletado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="tenant",
            field=models.ForeignKey(
                db_column="inquilino_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.tenant",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="atualizado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["tenant"], name="entidades_e_inquili_6b17c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["name"], name="entidades_e_nome_1e0560_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["nuit"], name="entidades_e_nuit_6fa4bd_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["active"], name="entidades_e_ativo_67ecc6_idx"),
        ),
    ]
