# Generated by Django 5.1 on 2026-03-25 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entidades", "0002_initial"),
        (
            "inquilinos",
            "0002_rename_inquilinos__tipo_856ce4_idx_inquilinos__type_fdb81e_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="company",
            new_name="entidades_e_tenant__9031cf_idx",
            old_name="entidades_e_inquili_6b17c5_idx",
        ),
        migrations.RenameIndex(
            model_name="company",
            new_name="entidades_e_name_4f23d6_idx",
            old_name="entidades_e_nome_1e0560_idx",
        ),
        migrations.RenameIndex(
            model_name="company",
            new_name="entidades_e_active_92625f_idx",
            old_name="entidades_e_ativo_67ecc6_idx",
        ),
        migrations.AlterField(
            model_name="company",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="created_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                db_column="deleted_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="inquilinos.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
