# Generated by Django 5.1 on 2026-03-25 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinico", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="nome", db_index=True, max_length=120, unique=True
                    ),
                ),
                ("content", models.TextField(db_column="conteudo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de Notificação",
                "verbose_name_plural": "Templates de Notificação",
                "db_table": "notificacoes_templatenotificacao",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient",
                    models.CharField(db_column="destinatario", max_length=255),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "E-mail"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        db_column="canal",
                        max_length=50,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, db_column="assunto", default="", max_length=160
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("GERAL", "Geral"),
                            ("RESET_SENHA", "Reposição de palavra-passe"),
                            ("RESULTADO", "Resultado disponível"),
                            ("FATURA", "Fatura emitida"),
                            ("RECIBO", "Recibo gerado"),
                        ],
                        db_column="tipo_evento",
                        default="GERAL",
                        max_length=40,
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True, db_column="referencia_externa", max_length=120
                    ),
                ),
                ("message", models.TextField(db_column="mensagem")),
                ("sent", models.BooleanField(db_column="enviada", default=False)),
                (
                    "send_error",
                    models.TextField(blank=True, db_column="erro_envio", default=""),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, db_column="enviado_em", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="criado_em"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        db_column="paciente_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to="clinico.patient",
                    ),
                ),
            ],
            options={
                "db_table": "notificacoes_notificacao",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(db_index=True, max_length=40)),
                (
                    "response",
                    models.TextField(blank=True, db_column="resposta", default=""),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="criado_em", db_index=True
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        db_column="notificacao_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_envio",
                        to="notificacoes.notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Envio",
                "verbose_name_plural": "Logs de Envio",
                "db_table": "notificacoes_logenvio",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["channel"], name="notificacoe_canal_a5c8e0_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["event_type"], name="notificacoe_tipo_ev_42172b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["sent"], name="notificacoe_enviada_f32028_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["external_reference"], name="notificacoe_referen_09c562_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverylog",
            index=models.Index(
                fields=["notification", "created_at"],
                name="notificacoe_notific_9108da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverylog",
            index=models.Index(fields=["status"], name="notificacoe_status_8fbd4f_idx"),
        ),
    ]
