# Generated by Django 4.2.16 on 2026-03-28 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', db_index=True, max_length=120, unique=True, verbose_name='Nome')),
                ('content', models.TextField(db_column='content', verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Template de Notificação',
                'verbose_name_plural': 'Templates de Notificação',
                'db_table': 'notificacoes_templatenotificacao',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(db_column='recipient', max_length=255, verbose_name='Destinatário')),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], db_column='channel', max_length=50, verbose_name='Canal')),
                ('subject', models.CharField(blank=True, db_column='subject', default='', max_length=160, verbose_name='Assunto')),
                ('event_type', models.CharField(choices=[('GERAL', 'Geral'), ('RESET_SENHA', 'Reposição de palavra-passe'), ('RESULTADO', 'Resultado disponível'), ('FATURA', 'Fatura emitida'), ('RECIBO', 'Recibo gerado')], db_column='event_type', default='GERAL', max_length=40, verbose_name='Tipo de evento')),
                ('external_reference', models.CharField(blank=True, db_column='external_reference', max_length=120, verbose_name='Referência externa')),
                ('message', models.TextField(db_column='message', verbose_name='Mensagem')),
                ('sent', models.BooleanField(db_column='sent', default=False, verbose_name='Enviada')),
                ('send_error', models.TextField(blank=True, db_column='send_error', default='', verbose_name='Erro de envio')),
                ('sent_at', models.DateTimeField(blank=True, db_column='sent_at', null=True, verbose_name='Enviado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Criado em')),
                ('patient', models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='clinical.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'notificacoes_notificacao',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, max_length=40, verbose_name='Status')),
                ('response', models.TextField(blank=True, db_column='response', default='', verbose_name='Resposta')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='Criado em')),
                ('notification', models.ForeignKey(db_column='notification_id', on_delete=django.db.models.deletion.CASCADE, related_name='logs_envio', to='notificacoes.notification', verbose_name='Notificação')),
            ],
            options={
                'verbose_name': 'Log de Envio',
                'verbose_name_plural': 'Logs de Envio',
                'db_table': 'notificacoes_logenvio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel'], name='notificacoe_channel_6ad7bd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event_type'], name='notificacoe_event_t_cbdea4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sent'], name='notificacoe_sent_43e7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['external_reference'], name='notificacoe_externa_4095d1_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['notification', 'created_at'], name='notificacoe_notific_3afc20_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['status'], name='notificacoe_status_8fbd4f_idx'),
        ),
    ]
