# Generated by Django 5.1 on 2026-03-26 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinical", "0004_clinicalhistory_clinicalevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="name", db_index=True, max_length=120, unique=True
                    ),
                ),
                ("content", models.TextField(db_column="content")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de Notificação",
                "verbose_name_plural": "Templates de Notificação",
                "db_table": "notificacoes_templatenotificacao",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.CharField(db_column="recipient", max_length=255)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "E-mail"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        db_column="channel",
                        max_length=50,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, db_column="subject", default="", max_length=160
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("GERAL", "Geral"),
                            ("RESET_SENHA", "Reposição de palavra-passe"),
                            ("RESULTADO", "Resultado disponível"),
                            ("FATURA", "Fatura emitida"),
                            ("RECIBO", "Recibo gerado"),
                        ],
                        db_column="event_type",
                        default="GERAL",
                        max_length=40,
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True, db_column="external_reference", max_length=120
                    ),
                ),
                ("message", models.TextField(db_column="message")),
                ("sent", models.BooleanField(db_column="sent", default=False)),
                (
                    "send_error",
                    models.TextField(blank=True, db_column="send_error", default=""),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, db_column="sent_at", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        db_column="patient_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to="clinical.patient",
                    ),
                ),
            ],
            options={
                "db_table": "notificacoes_notificacao",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(db_index=True, max_length=40)),
                (
                    "response",
                    models.TextField(blank=True, db_column="response", default=""),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", db_index=True
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        db_column="notification_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_envio",
                        to="notificacoes.notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Envio",
                "verbose_name_plural": "Logs de Envio",
                "db_table": "notificacoes_logenvio",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["channel"], name="notificacoe_channel_6ad7bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["event_type"], name="notificacoe_event_t_cbdea4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["sent"], name="notificacoe_sent_43e7ca_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["external_reference"], name="notificacoe_externa_4095d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverylog",
            index=models.Index(
                fields=["notification", "created_at"],
                name="notificacoe_notific_3afc20_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverylog",
            index=models.Index(fields=["status"], name="notificacoe_status_8fbd4f_idx"),
        ),
    ]
