# Generated by Django 5.1 on 2026-03-26 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0005_alter_clinicalevent_options_and_more"),
        ("notificacoes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
            },
        ),
        migrations.AlterField(
            model_name="deliverylog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="created_at",
                db_index=True,
                verbose_name="Criado em",
            ),
        ),
        migrations.AlterField(
            model_name="deliverylog",
            name="notification",
            field=models.ForeignKey(
                db_column="notification_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs_envio",
                to="notificacoes.notification",
                verbose_name="Notificação",
            ),
        ),
        migrations.AlterField(
            model_name="deliverylog",
            name="response",
            field=models.TextField(
                blank=True, db_column="response", default="", verbose_name="Resposta"
            ),
        ),
        migrations.AlterField(
            model_name="deliverylog",
            name="status",
            field=models.CharField(db_index=True, max_length=40, verbose_name="Status"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[("email", "E-mail"), ("sms", "SMS"), ("whatsapp", "WhatsApp")],
                db_column="channel",
                max_length=50,
                verbose_name="Canal",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_column="created_at", verbose_name="Criado em"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("GERAL", "Geral"),
                    ("RESET_SENHA", "Reposição de palavra-passe"),
                    ("RESULTADO", "Resultado disponível"),
                    ("FATURA", "Fatura emitida"),
                    ("RECIBO", "Recibo gerado"),
                ],
                db_column="event_type",
                default="GERAL",
                max_length=40,
                verbose_name="Tipo de evento",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="external_reference",
            field=models.CharField(
                blank=True,
                db_column="external_reference",
                max_length=120,
                verbose_name="Referência externa",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(db_column="message", verbose_name="Mensagem"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_column="patient_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notificacoes",
                to="clinical.patient",
                verbose_name="Paciente",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.CharField(
                db_column="recipient", max_length=255, verbose_name="Destinatário"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="send_error",
            field=models.TextField(
                blank=True,
                db_column="send_error",
                default="",
                verbose_name="Erro de envio",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="sent",
            field=models.BooleanField(
                db_column="sent", default=False, verbose_name="Enviada"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, db_column="sent_at", null=True, verbose_name="Enviado em"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="subject",
            field=models.CharField(
                blank=True,
                db_column="subject",
                default="",
                max_length=160,
                verbose_name="Assunto",
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="content",
            field=models.TextField(db_column="content", verbose_name="Conteúdo"),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="created_at",
                db_index=True,
                verbose_name="Criado em",
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="name",
            field=models.CharField(
                db_column="name",
                db_index=True,
                max_length=120,
                unique=True,
                verbose_name="Nome",
            ),
        ),
    ]
