# Generated by Django 5.1 on 2026-03-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="deliverylog",
            new_name="notificacoe_notific_3afc20_idx",
            old_name="notificacoe_notific_9108da_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificacoe_channel_6ad7bd_idx",
            old_name="notificacoe_canal_a5c8e0_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificacoe_event_t_cbdea4_idx",
            old_name="notificacoe_tipo_ev_42172b_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificacoe_sent_43e7ca_idx",
            old_name="notificacoe_enviada_f32028_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificacoe_externa_4095d1_idx",
            old_name="notificacoe_referen_09c562_idx",
        ),
    ]
