from django.db import models


class DefaultUnit(models.TextChoices):
    G_DL = "g/dl", "g/dl"
    G_L = "g/L", "g/L"
    MG_DL = "mg/dl", "mg/dl"
    MG_L = "mg/L", "mg/L"
    MG_24H = "mg/24h", "mg/24h"
    UG_DL = "µg/dL", "µg/dL"
    UG_L = "µg/L", "µg/L"
    UG_ML = "µg/mL", "µg/mL"
    NG_ML = "ng/mL", "ng/mL"
    NG_DL = "ng/dL", "ng/dL"
    PG_ML = "pg/mL", "pg/mL"
    MMOL_L = "mmol/l", "mmol/l"
    MMOL_MOL = "mmol/mol", "mmol/mol"
    UMOL_L = "µmol/l", "µmol/l"
    NMOL_L = "nmol/L", "nmol/L"
    PMOL_L = "pmol/L", "pmol/L"
    MEQ_L = "mEq/L", "mEq/L"
    CEL_MM3 = "cel/mm3", "cel/mm3"
    X10_3_UL = "x10³/µl", "x10³/µl"
    X10_6_UL = "x10⁶/µL", "x10⁶/µL"
    PERCENT = "%", "%"
    U_L = "u/l", "u/l"
    U_ML = "U/mL", "U/mL"
    UI_L = "UI/L", "UI/L"
    UI_ML = "UI/mL", "UI/mL"
    MUI_L = "mUI/L", "mUI/L"
    KU_L = "kU/L", "kU/L"
    P_UL = "p/µL", "p/µL"
    PH = "ph", "ph"
    FL = "fl", "fl"
    MM_H = "mm/h", "mm/h"
    MMHG = "mmHg", "mmHg"
    MOSM_KG = "mOsm/kg", "mOsm/kg"
    SECONDS = "s", "s"
    INR = "INR", "INR"
    RATIO_INDEX = "razão/índice", "razão/índice"
    NO_UNIT = "sem unidade", "sem unidade"


__all__ = ["DefaultUnit"]
