from django.db import models


class DefaultUnit(models.TextChoices):
    G_DL = "g/dl", "g/dl"
    G_L = "g/L", "g/L"
    MG_DL = "mg/dl", "mg/dl"
    MG_L = "mg/L", "mg/L"
    MG_24H = "mg/24h", "mg/24h"
    UG_DL = "µg/dL", "µg/dL"
    UG_L = "µg/L", "µg/L"
    UG_ML = "µg/mL", "µg/mL"
    NG_ML = "ng/mL", "ng/mL"
    NG_DL = "ng/dL", "ng/dL"
    PG_ML = "pg/mL", "pg/mL"
    MMOL_L = "mmol/l", "mmol/l"
    MMOL_MOL = "mmol/mol", "mmol/mol"
    UMOL_L = "µmol/l", "µmol/l"
    NMOL_L = "nmol/L", "nmol/L"
    PMOL_L = "pmol/L", "pmol/L"
    MEQ_L = "mEq/L", "mEq/L"
    CEL_MM3 = "cel/mm3", "cel/mm3"
    X10_3_UL = "x10³/µl", "x10³/µl"
    X10_6_UL = "x10⁶/µL", "x10⁶/µL"
    PERCENT = "%", "%"
    U_L = "u/l", "u/l"
    U_ML = "U/mL", "U/mL"
    UI_L = "UI/L", "UI/L"
    UI_ML = "UI/mL", "UI/mL"
    MUI_L = "mUI/L", "mUI/L"
    KU_L = "kU/L", "kU/L"
    P_UL = "p/µL", "p/µL"
    PH = "ph", "ph"
    FL = "fl", "fl"
    MM_H = "mm/h", "mm/h"
    # Parasitologia
    OVOS_G = "ovos/g", "ovos/g"
    OVOS_10ML = "ovos/10mL", "ovos/10mL"
    PARASITAS_UL = "parasitas/µL", "parasitas/µL"
    PARASITAS_CAMPO = "parasitas/campo", "parasitas/campo"
    CISTOS_CAMPO = "cistos/campo", "cistos/campo"
    LARVAS_CAMPO = "larvas/campo", "larvas/campo"
    # Biologia molecular (UI/mL já definido acima)
    CT = "Ct", "Ct"
    COPIAS_ML = "cópias/mL", "cópias/mL"
    COPIAS_REACAO = "cópias/reação", "cópias/reação"
    LOG10 = "log10", "log10"
    PCT_ALELO = "% alelo", "% alelo"
    PCT_IS = "% IS", "% IS"
    GENOTIPO = "genótipo", "genótipo"
    TRACOS_DETECTADO = "traços/detectado", "traços/detectado"
    # Serologia e imunologia (UI/mL e U/mL já definidos acima)
    S_CO = "S/CO", "S/CO"
    MUI_ML = "mUI/mL", "mUI/mL"
    TITULO = "título", "título"
    INDEX = "index", "index"
    # Microbiologia (µg/mL já definido acima)
    UFC_ML = "UFC/mL", "UFC/mL"
    UFC_G = "UFC/g", "UFC/g"
    UFC_PLACA = "UFC/placa", "UFC/placa"
    HORAS = "horas", "horas"
    S_I_R = "S/I/R", "S/I/R"
    MM = "mm", "mm"
    CRUZES = "cruzes", "cruzes"
    CAMPO = "campo", "campo"
    # Uroanálise / urinálise
    CELULAS_CAMPO = "células/campo", "células/campo"
    ML_24H = "mL/24h", "mL/24h"
    ML_MIN = "mL/min", "mL/min"
    MG_G_CREATININA = "mg/g creatinina", "mg/g creatinina"
    DENSIDADE = "densidade", "densidade"
    # Endocrinologia / hormônios (ng/dL, ng/mL, pg/mL, µg/dL, pmol/L, nmol/L,
    # mUI/mL, U/mL já definidos acima)
    MICRO_UI_ML = "µUI/mL", "µUI/mL"
    # Marcadores tumorais (ng/mL, U/mL, pmol/L, mUI/mL, µg/L, mg/L, index já definidos)
    PCT_RISCO = "% risco", "% risco"
    # Coagulação e hemostasia (mg/L, µg/mL e INR já definidos acima)
    SEGUNDOS = "segundos", "segundos"
    MINUTOS = "minutos", "minutos"
    RATIO = "ratio", "ratio"
    NG_ML_FEU = "ng/mL FEU", "ng/mL FEU"
    UG_ML_FEU = "µg/mL FEU", "µg/mL FEU"
    MG_L_FEU = "mg/L FEU", "mg/L FEU"
    MMHG = "mmHg", "mmHg"
    MOSM_KG = "mOsm/kg", "mOsm/kg"
    SECONDS = "s", "s"
    INR = "INR", "INR"
    RATIO_INDEX = "razão/índice", "razão/índice"
    NO_UNIT = "sem unidade", "sem unidade"


__all__ = ["DefaultUnit"]
